### ISSUE TITLE
Inject DAPR_PORT env var for Kubernetes mode

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#102]

**Comment by bign8** [comment]
Are you suggesting adding an extra environment variable to the sidecar or an environment variable to the dapr client container.

```yaml
annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "nodeapp"
        dapr.io/port: "3000"
```
Source: https://github.com/dapr/docs/blob/24781faf9050ead710877c6f779ac6a0ff3886b6/best-practices/troubleshooting/common_issues.md#i-dont-see-the-dapr-sidecar-injected-to-my-pod

Asking because if it's the client application, it would be nice for the Dapr SDKs to be able to read that value from an environment variable instead of hard coding a specific port to connect to.

If this doesn't belong on this ticket, please let me know and I'll create a different issue to encompass this effort.  Thanks!
