### ISSUE TITLE
Create traces monitoring toolset

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1050]
## In what area(s)?

/area observability

## Related issue

#969

## Describe the feature

When we improve traces (#969), it is good to provide monitoring images or helm charts with monitoring configuration, which allows users to enable monitoring system easily

- traces: zipkin, opentelemetry-collector (for app insight)

**Comment by youngbupark** [comment]
Local fowarder is being deprecated. Switching to opentelemetry agent makes sense for appinsight traces.

https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by youngbupark** [comment]
https://github.com/open-telemetry/opentelemetry-collector/tree/master/examples/demo
demo is working with the below config.yaml
```
receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  zipkin:
    url: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger_grpc:
    endpoint: jaeger-all-in-one:14250
  
  azuremonitor:
  azuremonitor/2:
    # endpoint is the uri used to communicate with Azure Monitor
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    # instrumentation_key is the unique identifer for your Application Insights resource
    instrumentation_key: "3d50fb98-92a8-43d5-98fe-c6158551848b"
    # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
    maxbatchinterval: 10s

# Alternatively, use jaeger_thrift_http with the settings below. In this case
# update the list of exporters on the traces pipeline.
#
#  jaeger_thrift_http:
#    url: http://jaeger-all-in-one:14268/api/traces

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging, zipkin, jaeger_grpc, azuremonitor/2]
      processors: [batch, queued_retry]
    metrics:
      receivers: [opencensus]
      exporters: [logging,prometheus, azuremonitor/2]
```
