### ISSUE TITLE
Secret handling during local development

### ISSUE THREAD

**Issue by subesokun** [dapr/dapr#1075]
## In what area(s)?

> /area runtime
> /area docs

## Ask your question here

Hi, I'd like do know what the recommended strategy is for handling secrets during local development. I've defined in the `components` folder a `servicebusqueue-binding.yaml` which currently looks like

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myqueue
spec:
  type: bindings.azure.servicebusqueues
  metadata:
  - name: storageAccessKey
    value: my-secret-as-clear-text
  - name: queue
    value: myqueue
  - name: storageAccount
    value: mystorageaccountname
```

According to the [docu for component secrets](https://github.com/dapr/docs/blob/master/concepts/components/secrets.md), I can use a K8s secret and reference it in the component YAML in case my app is running in the K8s cluster. But how can I remove the cleartext password from that file in case I'm using `dapr run`? I want to avoid adding the secret into the component file as this file is under version control.
