### ISSUE TITLE
Switch Local Forwarder to OpenTelemetry Collector

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1080]
## In what area(s)?

/area observability

## Describe the feature

Local Forwarder is being deprecated. Switching to OpenTelemetry agent makes sense for AppInsights traces. 

- https://github.com/open-telemetry/opentelemetry-collector
- https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by youngbupark** [comment]
@Haishi2016 any objection for this ^

**Comment by youngbupark** [comment]
Dupe #1050

**Comment by youngbupark** [comment]
@yaron2 @shalabhms I contributed to opentelemetry collector contrib repo to fix the existing problem such as ai.cloud.role and ai.cloud.roleinstance:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/218

**Comment by youngbupark** [comment]
@shalabhms @yaron2 @amanbha 

JFYI - Peter who is original author of appinsights exporter approved my [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/218) But I am not sure when it is merged.

**Comment by amanbha** [comment]
Very nice to see this come togather.

**Comment by youngbupark** [comment]
PR is merged!

**Comment by youngbupark** [comment]
testable image -

docker pull otel/opentelemetry-collector-contrib-dev:2b5b51cf55542e8e8a09ef2bf6813dbb356345a0

**Comment by youngbupark** [comment]
@shalabhms @amanbha @yaron2 @orizohar @msfussell / @pcwiese has worked on azure monitor exporter to support the latest opentelemetry spec. so once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/380 pr is merged, we can migrate from local forwarder to opentelemetry collector.

**Comment by youngbupark** [comment]
PR is merged. :) we can start validating trace with otel collector :)

otel collector deployment yaml example

```yaml
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: default
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "otel-collector.default.svc.cluster.local:55678"
---
```

otel-collector.yml

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
    processors:
      queued_retry:
      batch:
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    exporters:
      azuremonitor:
      azuremonitor/2:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: "<ikey>"
        # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
        maxbatchinterval: 10s
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [opencensus]
          exporters: [azuremonitor/2]
          processors: [batch, queued_retry]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opencesus
    component: otel-collector
spec:
  ports:
  - name: opencensus # Default endpoint for Opencensus receiver.
    port: 55678
    protocol: TCP
    targetPort: 55678
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  replicas: 1  # scale out based on your usage
  selector:
    matchLabels:
      app: opentelemetry
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: docker pull otel/opentelemetry-collector-contrib-dev:latest
        command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
          - containerPort: 55678 # Default endpoint for Opencensus receiver.
        volumeMounts:
          - name: otel-collector-config-vol
            mountPath: /conf
          #- name: otel-collector-secrets
          #  mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
#       - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem

```
