### ISSUE TITLE
Sidecar-injector TLS handshake error when using Istio mTLS

### ISSUE THREAD

**Issue by maminio** [dapr/dapr#1096]
## In what area(s)?

/area sidecar-injector

## What version of Dapr?

0.4

## Description 
I'm trying to use `Dapr` alongside Istio service mesh, but I'm having problem with `Dapr's` sidecar injector as it doesn't work as expected. When my isito `mTLS` is enabled I get the error below as I apply a new deployment with `dapr.io/enabled: "true"`. Although it works fine with istio's `mTLS` disabled. 
```
time="2020-02-24T21:43:43Z" level=info msg="log level set to: info"
time="2020-02-24T21:43:43Z" level=info msg="starting Dapr Sidecar Injector -- version 0.4.0 -- commit v0.3.0-rc.0-73-ga1e270f-dirty"
time="2020-02-24T21:43:44Z" level=info msg="Sidecar injector is listening on :4000, patching Dapr-enabled pods"
2020/02/24 21:44:02 http: TLS handshake error from 127.0.0.1:43092: EOF
```

**Any suggestions on what I'm missing or if I have configuration conflicts between Istio service mesh and Dapr ?**

## Steps to Reproduce the Problem

* Initialize isito with mTLS enabled on istio-system namesapce
* Install dapr with helm on dapr-system namesapce
* Create a new Deployment with dapr.io enabled
* Check out dapr-sidecar-injector logs

**Comment by yaron2** [comment]
Hey @maminio, if using Istio and Dapr, you should disable mTLS on either Istio or Dapr.

You also need to make sure Istio is not enabled on the `dapr-system` namespace.

In order to disable mTLS on Dapr, edit the default Dapr configuration and set mTLS to false.

```
kubectl edit configurations default -n dapr-system
```

Next, restart your pods for the change to take effect.
More info [here](https://github.com/dapr/docs/tree/master/howto/configure-mtls#sentry-configuration).

Please keep us updated, and glad to hear it works when Istio's mTLS is turned off - this is the way to go. (have either Istio or Dapr do mTLS).

**Comment by maminio** [comment]
Thank you @yaron2, 
Yes disabling mTLS in `dapr-system` worked and now sidecar injector works fine. 
Although as I use mTLS for all of my connections it still has problem connecting to `redis` as `Envoy` blocks its connection. 

For a way around:
* I used `mode: PERMISSIVE` in my istio `meshpolicy` 
* Labelled `dapr-system` with `istio-injection=enabled`
* Disabled dapr mTLS

I know using `PERMISSIVE` is not secure as it enables services to take both HTTP and mutual TLS traffic , that's why I'm looking to find a better way.

**Comment by yaron2** [comment]
Great to hear it's working now @maminio, thanks for updating.

So to be clear, the issue now is how to get Istio to authenticate with Redis?
I'm not an Istio guru by any means, but I think you can use Istio authentication policies to achieve that.

More info here:
https://istio.io/faq/security/#auth-mix-and-match

**Comment by yaron2** [comment]
Actually, more accurate:
https://istio.io/faq/security/#accessing-non-istio-services

**Comment by maminio** [comment]
Great!
Thanks, I configured istio `DestinationRule` to enable Dapr apis to pass through and it works fine now.

**Comment by yaron2** [comment]
That's awesome. Can you paste the Istio Destination Rule here for general visibility? I'm going to put a lot of this conversation into Dapr/Istio docs.

**Comment by maminio** [comment]
You can create these Destination rules as follow for dapr services. 
I'm not sure that it is required for all of them by certainly you need it for `dapr-sidecar-injector` and `dapr-api`. 

```
# For Dapr sidecar injector
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "dapr-sidecar-injector"
spec:
 host: "dapr-sidecar-injector.dapr-system.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE
```

```
# For Dapr-Api 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "dapr-api"
spec:
 host: "dapr-api.dapr-system.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE
```
If you installed dapr in a different namespace other than `dapr-system`, make sure to change the host value.

**Comment by jellebens** [comment]
I am using Actors with Redis as a actor state store
then you need to disable mtls for redius as well
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "redis-disable-mtls"
spec:
 host: "*.redis.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE
```
