### ISSUE TITLE
enable tracing crashes daprd (master branch)

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1177]
## In what area(s)?

/area observabiltiy

## What version of Dapr?

master

## Expected Behavior

dapr runtime sidecar should not be panic.

## Actual Behavior

dapr runtime sidecar is panic.

```
panic: The stream server interceptor was already set and may not be reset.

goroutine 1 [running]:
google.golang.org/grpc.StreamInterceptor.func1(0xc0005420f0)
        /Users/youngp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:319 +0x6b
google.golang.org/grpc.(*funcServerOption).apply(0xc0000b4a38, 0xc0005420f0)
        /Users/youngp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:164 +0x33
google.golang.org/grpc.NewServer(0xc000780400, 0x5, 0x8, 0x4)
        /Users/youngp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:396 +0xc9
github.com/dapr/dapr/pkg/grpc.(*server).getGRPCServer(0xc00056a0f0, 0x3, 0xc0004968a0, 0x6)
        /Users/youngp/go/src/github.com/dapr/dapr/pkg/grpc/server.go:140 +0x71
github.com/dapr/dapr/pkg/grpc.(*server).StartNonBlocking(0xc00056a0f0, 0xc000496890, 0x0)
        /Users/youngp/go/src/github.com/dapr/dapr/pkg/grpc/server.go:70 +0xfd
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).startGRPCServer(0xc00038cc40, 0xc351, 0x21, 0xc0002e5ce0)
        /Users/youngp/go/src/github.com/dapr/dapr/pkg/runtime/runtime.go:510 +0x3b6
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc00038cc40, 0xc00035e180, 0xb, 0xc00009f820)
        /Users/youngp/go/src/github.com/dapr/dapr/pkg/runtime/runtime.go:217 +0x99f
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc00038cc40, 0xc000403f10, 0x8, 0x8, 0xc0000a21e0, 0x2f31c41)
        /Users/youngp/go/src/github.com/dapr/dapr/pkg/runtime/runtime.go:127 +0x24e
main.main()
        /Users/youngp/go/src/github.com/dapr/dapr/cmd/daprd/main.go:103 +0xd8c
```

## Steps to Reproduce the Problem

1. Deploy dapr from master
2. Enable tracing
```
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "otel-collector.monitoring.svc.cluster.local:55678"
---
```
3. deploy app with tracing configuration
