### ISSUE TITLE
[Proposal] Logger Component

### ISSUE THREAD

**Issue by stather** [dapr/dapr#1246]
## In what area(s)?

> /area runtime

## Logging Component

A new component type Logger to support enterprise logging systems such as graylog. 

As with other components this would remove the need for a microservice to know about the functionality of the actually logging system.

The service would post a log message to the configured logger by posting a message to

http://localhost:3500/v1.0/logger/{level}
The content to be logged would be the body of the message.

The dapr sidecar would process an extra annotation indicating the logger component to forward the log message on to. This prevents the need for the actual service to know a different URI to identify the logger.
`dapr.io/logger: "mylogger"`

The logger instance would be configured in a similar way similar to output bindings:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mylogger
spec:
  type: logger.graylog
  metadata:
  - name: host
    value: somedns.com:9000
  - name: input
    value: 12202
```

The logger component would need to expose 2 methods:

- Init(metadatafromyaml)
- Log(string logmessage)
