### ISSUE TITLE
Consolidate secrets schema for secret stores that support keyed secrets

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/dapr#1283]
## What version of Dapr?

0.4

## Expected Behavior

Components that utilize a SecretStore should continue to load after upgrading to Dapr 0.5

## Actual Behavior

Dapr 0.5 introduced a breaking change in which Dapr components may not properly initialize if they utilized a SecretStore and didn't set a SecretKeyRef key in addition to the name.

## Steps to Reproduce the Problem

Create a component that uses a SecretStore but don't set a secretKeyRef.key (which was perfectly valid in 0.4). You'll see that Dapr fails to initialize the component. Here is a sample pubsub manifest for reference:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
      name: sb-root-connectionstring
auth:
    secretStore: azurekeyvault
```

Currently, in 0.5 you must also set a secretKeyRef.key in order to get the component to load correctly.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
      name: sb-root-connectionstring
      key: sb-root-connectionstring
auth:
    secretStore: azurekeyvault
```
