### ISSUE TITLE
gRPC calls fails for Secret API requests if mTLS is enabled

### ISSUE THREAD

**Issue by cmendible** [dapr/dapr#1292]
## In what area(s)?

/area runtime

## What version of Dapr?

> 0.5.0

## Expected Behavior

gRPC calls from application to Dapr side car should work with mTLS enabled.

## Actual Behavior

gRPC calls to get secrets fail when Dapr mTLS is enabled.

## Steps to Reproduce the Problem

Deploy the following yaml to K8s:

```yaml
---
# Create a Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: super-secret
  namespace: default
type: Opaque
data:
  super-secret: eW91ciBzdXBlciBzZWNyZXQK

---
# If RBAC is enabled in K8s, give the default SA access to secrets in the default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dapr-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```

Create and deploy an ASP.NET Core application which implements the following call:

```chshap
var secrets = await client.GetSecretAsync("kubernetes", "super-secret", new Dictionary<string, string>() { { "namespace", "default" } });
```

The call will fail with mTLS enabled.

Note: the the .NET SDK calls gRPC over http.

Related issue: https://github.com/dapr/dotnet-sdk/issues/261
