### ISSUE TITLE
Proposal: scoping for Pub/Sub topics

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1294]
## Use Case

Users may want to apply specific policies as to which app can publish and/or subscribe to a topic.
For example, given two apps, App A and App B deployed to the cluster, an operator may want to define that App A can publish to Topic A, and App B can subscribe to Topic B but not publish to it.

## Design Proposal

Two new `metadata` properties will be added to a component of type `pubsub`:

`spec.metadata.subscriptionScopes`<br>
`spec.metadata.publishingScopes `

An example of allowing an application called `app1` to subscribe to `topic1` and publish to `topic2` and `topic3`:

```yaml
spec:
  type: pubsub.nats
  metadata:
  - name: subscriptionScopes
    value: "app1=topic1"
  - name: publishingScopes
    value: "app1=topic2,topic3"
```

An example of multiple scopes:

```yaml
spec:
  type: pubsub.nats
  metadata:
  - name: subscriptionScopes
    value: "app1=topic1;app2=topic1,topic2"
  - name: publishingScopes
    value: "app1=topic2,topic3;app2=topic4"
```

The example above shows `app1` allowed to subscribe for `topic1`, and `app2` allowed to subscribe for `topic1` and topic2`.

On the producer scopes, `app1` is allowed to publish to `topic2` and `topic3`, and `app2` is allowed to publish to `topic4`.

If an app is NOT specified in `subscriptionScopes`, its allowed to subscribe to all topics.
If an app is NOT specified in `publishingScopes `, its allowed to publish to all topics.

This feature does not break backwards compatibility.

Namespacing/application scoping of components takes prioritization over scoping of topics.

**Comment by yaron2** [comment]
cc @RicardoNiepel

**Comment by AaronCrawfis** [comment]
Should we be consistent with terms? Seems like it should be
`spec.metadata.subscriptionScopes` and `spec.metadata.productionScopes` 
or 
`spec.metadata.subscriberScopes` and `spec.metadata.producerScopes`

And should it be producer or publisher?

To me `spec.metadata.subscriptionScopes` and `spec.metadata.publishingScopes` seems the most natural

Also from a security pov would it be possible to ever spoof an appId such that I can start publishing from an app that I control? (or listen)

**Comment by yaron2** [comment]
> To me spec.metadata.subscriptionScopes and spec.metadata.publishingScopes seems the most natural

Yep, I like that. I'll change to `publishingScopes`.

> Also from a security pov would it be possible to ever spoof an appId such that I can start publishing from an app that I control? (or listen)

No, you can't spoof it from the Dapr runtime.

**Comment by RicardoNiepel** [comment]
For making this concept also useful from a security view, I would suggest having https://github.com/dapr/dapr/issues/1030.

With dapr <> app authentication and transport encryption this topic scoping cannot only be used from a functional standpoint, but also for security related requirements for publishing / subscribing to specific topics.

**Comment by yaron2** [comment]
> For making this concept also useful from a security view, I would suggest having #1030.
> 
> With dapr <> app authentication and transport encryption this topic scoping cannot only be used from a functional standpoint, but also for security related requirements for publishing / subscribing to specific topics.

You mean if there's a rogue code **inside** the Pod, it might intercept traffic between the application and Dapr and figure out the topic published to, correct?

#1030 is a separate discussion, as it has a wider scope of network interception in general, not related specifically to pub/sub.

**Comment by RicardoNiepel** [comment]
Yes, could be inside the app container or in any other container inside this pod.

I agree with you on the wider scope of #1030 and just want to ensure that I think we can focus on the functional aspect in the proposal and rely on the app id and #1030 would ensure the security aspects.

**Comment by artursouza** [comment]
LGTM

**Comment by amanbha** [comment]
LGTM, thanks!

**Comment by yaron2** [comment]
Thanks everyone for the quick turnaround!

**Comment by RicardoNiepel** [comment]
The current design proposal only fulfills two of three initial feature requests #1035:

- [X] It should be possible to configure, which Dapr applications are allowed to publish messages to which topic
- [X] It should be possible to configure, which Dapr applications are allowed to subscribe to which topic
- [ ] PubSub components should become a property for indicating, if it should auto-create topics or only use already existing topics

The idea is that - especially small and mid-size - teams can have a single source of truth which topics are exist and can published / subscribed to.

# Design Proposal Extension:

```yaml
spec:
  type: pubsub.nats
  metadata:
  - name: subscriptionScopes
    value: "app1=topic1"
  - name: publishingScopes
    value: "app1=topic2,topic3"
  - name: topicAutoCreation
    value: "enabled"
  - name: allowedTopics
    value: "topic1,topic2,topic3"
```

With ```topicAutoCreation``` it is possible to enable/disable the auto creation of topics. If disabled an error is thrown if any non-existing topic is used.

If ```allowedTopics``` is set, only the topics named in the list can be used. All other topic usage will throw an error. If it is not set, any topic can be used.
