### ISSUE TITLE
Azure Monitor Tracing doesn't work

### ISSUE THREAD

**Issue by MohsenMahdieh** [dapr/dapr#1369]
## In what area(s)?

> /area tracing

## What version of Dapr?

0.6.0

## Expected Behavior

By following the steps in [this documentation](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md) I  should have trace information in App Insight

## Actual Behavior

By following the steps in [this documentation](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md) I  don't have trace information in App Insight

## Steps to Reproduce the Problem

- Create an application deployed in Kubernetes in separate namespace - the application should use pub-sub for communication
- Create App Insight account and grab instrumentation key and API key
- Deploy  local forwarder using the following 
```
kind: Service
apiVersion: v1
metadata:
  name: dapr-localforwarder
  namespace: cw
  labels:
    app: dapr-localforwarder
spec:
  selector:
    app: dapr-localforwarder
  ports:
  - protocol: TCP
    port: 55678
    targetPort: 55678
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-localforwarder
  namespace: cw
  labels:
    app: dapr-localforwarder
spec:
  replicas: 3 # Adjust replica # based on your telemetry volume
  selector:
    matchLabels:
      app: dapr-localforwarder
  template:
    metadata:
      labels:
        app: dapr-localforwarder
    spec:
      containers:
      - name: dapr-localforwarder
        image: daprio/dapr-localforwarder:0.1-beta1
        ports:
        - containerPort: 55678
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "20m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"        
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value:  #{app-insight-key} # Replace with your ikey
          - name: APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY
            value:  #{app-insight-apikey} # Replace with your generated api key
```

- Deploy Tracing and Exporter using the following
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: cw
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: cw
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "http://dapr-localforwarder.{app namespace}.svc.cluster.local:55678"
```

**Comment by yaron2** [comment]
Is cloudwatcher the namespace you deployed your app to?

**Comment by lynn-orrell** [comment]
Can you post your app deployment manifest as well?

**Comment by youngbupark** [comment]
@MohsenMahdieh configuration is working without specific namespace

```apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: cloudwatcher
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true```

Please remove `namespace` to enable tracing globally.

**Comment by yaron2** [comment]
@MohsenMahdieh, we have @youngbupark looking into this now with configuration similar to what you described. we will update today.

**Comment by youngbupark** [comment]
@MohsenMahdieh  Please review this configs https://github.com/youngbupark/samples/tree/youngp/tracing-test/2.hello-kubernetes/deploy

I created three namespaces for this test

* dapr-system : deployed dapr via helm
* dapr-monitoring : deployed localfowarder using [yaml](https://github.com/youngbupark/samples/blob/youngp/tracing-test/2.hello-kubernetes/deploy/localforwarder-deploy.yaml)
* samples : deployed hello kubernetes samples

From your example, tracing and native exporter component yaml must be deployed to your app's namespace and also agentEndpoint should not include protocol part. Please check [this yaml](https://github.com/youngbupark/samples/blob/youngp/tracing-test/2.hello-kubernetes/deploy/tracing-config.yaml) in my sample.

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: cloudwatcher
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: cloudwatcher  
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "http://dapr-localforwarder.{app namespace}.svc.cluster.local:55678"
```
