### ISSUE TITLE
Component Contrib middleware not registered with dapr runtime

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1376]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

v0.6.0-5-gbff71a5a

## Expected Behavior
Middleware from [component-contrib](https://github.com/dapr/components-contrib) is available to use as a component in the dapr runtime. including:
- [Rate Limit](https://github.com/dapr/components-contrib/tree/master/middleware/http/ratelimit)
- [Bearer](https://github.com/dapr/components-contrib/tree/master/middleware/http/bearer)

## Actual Behavior
It looks like the component contrib middleware is not being registered with the dapr runtime. Unless I've missed something the only middleware being registered with the runtime is the default `uppercase` and `oauth2`. This is leading people to try using other middleware receiving the following error:
```
level=warning msg="failed to build HTTP pipeline: couldn't find HTTP middleware middleware.http.ratelimit"
```

## Steps to Reproduce the Problem
Deploy a middleware component
```
 apiVersion: dapr.io/v1alpha1
 kind: Component
 metadata:
   name: ratelimit
 spec:
   type: middleware.http.ratelimit
   metadata:
   - name: maxRequestsPerSecond
     value: "10"
```
Deploy a middleware config
```
apiVersion: dapr.io/v1alpha1
 kind: Configuration
 metadata:
   name: pipeline
 spec:
   httpPipeline:
     handlers:
     - name: ratelimit
       type: middleware.http.ratelimit
```
Launch dapr and watch the logs for an error.

cc: @benc-uk @cmendible
