### ISSUE TITLE
Uppercase middleware has empty body

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#1389]
/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
v0.6.0

## Expected Behavior
Can run the [hello world kubernetes sample](https://github.com/dapr/samples/tree/master/2.hello-kubernetes) with the `uppercase` middleware enabled.

In theory, the `pythonapp` is posting a json payload to the `nodeapp` and this will go through the `uppercase` middleware and the body should arrive at the `nodeapp` with uppercase json properties.

such as is demonstrated here: https://play.golang.org/p/MFRrM86j3BA

## Actual Behavior
When running the [hello world kubernetes sample](https://github.com/dapr/samples/tree/master/2.hello-kubernetes) with _just_ the `uppercase` middleware enabled I get the following behaviour.

```
k logs nodeapp-554d49c67c-pwt8q node

TypeError: Cannot read property 'orderId' of undefined
    at app.post (/app/app.js:36:26)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
...
```
I assume this is because the request body received in the `nodeapp` is undefined instead of an uppercase string.

I updated the middleware to print the body that's passed in to it and the body post transformation to uppercase and I get the following logs.
```
k logs nodeapp-554d49c67c-pwt8q daprd

time="2020-04-08T15:43:11.231456713Z" level=info msg="uppercase middeware: body = " app_id=nodeapp instance=nodeapp-554d49c67c-pwt8q scope=dapr.runtime type=log ver=edge
time="2020-04-08T15:43:11.231492913Z" level=info msg="uppercase middeware: upper = " app_id=nodeapp instance=nodeapp-554d49c67c-pwt8q scope=dapr.runtime type=log ver=edge
```
This seems to indicate that the context body is empty when passed into the uppercase middleware.

The pipeline configuration I'm using is:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
spec:
  httpPipeline:
    handlers:
    - name: uppercase
      type: middleware.http.uppercase
```
The uppercase component I'm using is:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: uppercase
spec:
  type: middleware.http.uppercase
```
This is the only middleware I'm using in this pipeline. 

If I remove the uppercase config, the sample starts to work again.

I'll continue to investigate it but just wanted to see if this repro'd for others too.
