### ISSUE TITLE
support for single handler to process multiple input bindings 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#1528]
Today the name of the input binding is tightly coupled to the name of the handler which will process its events 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
```

```go
route.POST("/tweets", tweetHandler)
```
As a developer I may want the same type of input binding with different metadata (e.g diff credentials in case of Twitter or totally different server in case of Kafka for example) to be handled by the same service... to enable fan-in like pattern.

**Proposal**
Support a `hint` in metadata to override the component name. For example: 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets-search1
spec:
  type: bindings.twitter
  metadata:
  - name: route
    value: "/tweets"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets-search2
spec:
  type: bindings.twitter
  metadata:
  - name: route
    value: "/tweets"
```

For backward compatibility, if the `route` key is not present the component `name` would be used as it is today
