### ISSUE TITLE
Add ability to disable metrics through configuration

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1643]
## In what area(s)?

/area runtime

## Describe the feature

Add metrics disable annotation for perf test

**Comment by youngbupark** [comment]
@yaron2 can you work on this ?

**Comment by yaron2** [comment]
> @yaron2 can you work on this ?

Yes

**Comment by youngbupark** [comment]
@yaron2 as we discussed a little bit, we may need to use the similar config options like trace. 

so by default, we turned off metrics. only when user turns on metrics in config, dapr will generate the metrics.

for example,
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: true
```
