### ISSUE TITLE
telemetry forwarded to Application Insights is incomplete

### ISSUE THREAD

**Issue by KaiWalter** [dapr/dapr#1698]
## Expected Behavior

When using the native trace exporter and the Application Insights forwarder I would expect, that all requests, traces and dependencies telemetry is rendered to Application Insights.

## Actual Behavior

For a sample case - actor is instantiated by a service invocation (or messagebus binding), pub/subs 2 others services and is updated by these - only this is recorded in Application Insights:

| type | count | content |
| ---- | ---- | ---- |
| traces | 1 | AI: Local storage access has resulted in an error (User: ) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped |
| customEvents | 2 | /opencensus.proto.agent.trace.v1.TraceService/Export.node<br/>/opencensus.proto.agent.trace.v1.TraceService/Config.node |
| dependencies | 2 | target/name: PublishEvent: xxxx |

Forwarder is picking up batches with this message:

```
2020/05/16 05:59:21.823|INFO|OpenCensus input: [ConnectionCount: 0, BatchesReceiv
ed: 1, BatchesFailed: 0, ConfigsReceived: 2, ConfigsFailed: 0]
```

## Steps to Reproduce the Problem

followed [these instructions](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md)

### started forwarer locally

```
docker run -e APPINSIGHTS_INSTRUMENTATIONKEY={instrumentationKey} -e APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY={apiKey} -d -p 55678:55678 daprio/dapr-localforwarder:latest
```

### added component native.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: default
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "localhost:55678"
```

### created tracing.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
```

### referenced tracing.yaml when starting Daprd

```
daprd --app-id "magic-app" `
    --app-port "5000" `
    --placement-address 50005 `
    --log-level debug `
    --components-path ./components/ `
    --config ./tracing.yaml `
    --dapr-http-port 3500 `
    --dapr-grpc-port 50001
```

## dapr --version

CLI version: 0.7.0
Runtime version: 0.7.0
