### ISSUE TITLE
oauth middleware not obtaining token

### ISSUE THREAD

**Issue by tejaswini11** [dapr/dapr#1699]
## **Expected Behavior**
[https://github.com/dapr/docs/tree/master/howto/authorization-with-oauth](url)
[https://tools.ietf.org/html/rfc6749#section-4.1](url)

accessing dapr endpoint --> redirect to Google sign in --> Sign in and consent -->(obtain state and auth code --> redirect to tokenURL --> obtain token) --> redirect to redirectUri, token saved under mentioned authHeaderName

## **Actual Behavior**
accessing dapr endpoint --> redirect to Google sign in --> Sign in and consent  --> (obtain state and auth code ) -->redirect to redirectUri with state and auth code, no token acquired

## Steps to Reproduce the Problem

**1. Add oauth2.yaml file under components**

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
  namespace: default
spec:
  type: middleware.http.oauth2
  metadata:
  - name: clientId
    value: "<client id>"
  - name: clientSecret
    value: "<client secret>"
  - name: scopes
    value: "https://mail.google.com/"
  - name: authURL
    value: "https://accounts.google.com/o/oauth2/v2/auth"
  - name: tokenURL
    value: "https://accounts.google.com/o/oauth2/token"
  - name: redirectURL
    value: "http://localhost:3504/v1.0/invoke/serviceA/method/display"
  - name: authHeaderName
    value: "Authorization"
```
**2. Add pipeline.yaml**

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
  namespace: default
spec:
  httpPipeline:
    handlers:
    - name: oauth2
      type: middleware.http.oauth2
```

**3. Controller file of dotnet application**

```
namespace BankServiceMvc.Controllers
{
    [ApiController]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet]
        [Route("/display")]
        public string display()
        {
            string headers = Response.Headers["Authorization"].ToString();
            Console.WriteLine("working");
            Console.WriteLine(headers);
            return "Hello World";
        }
    }
}
```

**4. Creating ClientID**
Created a Client ID and client secret for a web application. Set redirect Uri to http://localhost:3504/v1.0/invoke/serviceA/method/display

**5. Run dapr**
`sudo dapr run --app-id serviceA --app-port 5000 --port 3504 --components-path ./components --config pipeline.yaml dotnet serviceA.dll`

**6. Accessing dapr endpoint**
[http://localhost:3504/v1.0/invoke/serviceA/method/display](url)
