### ISSUE TITLE
Allowlist for secrets

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1782]
Dapr has a Secrets API that allows developers to fetch secrets from different secret stores.
While this is a highly used feature, it can also lead an attacker knowing a secret name and/or key to target the Dapr secrets API in case of a malicious code in the cluster.

Suggested solutions:

1. Enable API auth for Dapr by default
2. Create scoping for secrets, the same way topics are scoped for Pub/Sub (Cure53 suggestion)

**Comment by mukundansundar** [comment]
For solution 1, we could generate a random Key when the Dapr sidecar starts and inject it to the application as the DAPR_API_TOKEN env. 

For solution 2, we can modify the Configuration yaml to include as a secrets spec with secret store name and an allow list of secrets accessible from that secret store. 

**The default behavior would what we have now, no scoping all secrets can be accessed from a configured secret store.** 
Once the secrets configuration spec is added to the Configuration yaml and applied, then only the secrets listed as allowed can be accessed from that particular secret store. 

Configuration Spec: 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  secrets:
    stores:
      - name: <STORE_NAME_1>
         allowedSecrets: "secret1,secret2"
      - name: <STORE_NAME_2>
         allowedSecrets: "secret3, secret4"
```

Concrete yaml: 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: secrets-list
  namespace: default
spec:
  secrets:
    stores:
      - name: kubernetes
         allowedSecrets: "redisPassword"
      - name: myVaultStore
         allowedSecrets: "sqlserverPassword"
```
This also protects the Secrets API that is available. 
Similar to how tracing and middleware configs are enabled for each sidecar, the secrets config can also be enabled on a per sidecar basis for Kubernetes bound deployments. The Configuration CRD can be applied via the `dapr.io/config' annotation for Kubernetes deployments and can be overridden via the `--config` parameter in `dapr run` for self-hosted deployments.

@yaron2

**Comment by yaron2** [comment]
LGTM on adding secret scopes to configurations.

This is a global per app setting and not per component, and this is exactly what the `Configuration` CRD is for.

**Comment by youngbupark** [comment]
@mukundansundar can we use single-line array for allowed list key ? 

[ "key1", "key2" ]


yaml will automatically deserialize it to array without additional CSV parsing.

**Comment by msfussell** [comment]
LGTM. And I agree with @youngbupark  on the use of [ ] brackets. 
Also raise the configuration section concepts doc update issue that needs to update this topic https://github.com/dapr/docs/tree/master/concepts/configuration

**Comment by vinayada1** [comment]
Looks okay. Just one clarification: What would be the behavior if the secrets config spec is added but a secret store is not specified. For example, Secret Store 3 in the sample spec above?

**Comment by rynowak** [comment]
> The default behavior would what we have now, no scoping all secrets can be accessed from a configured secret store.
Once the secrets configuration spec is added to the Configuration yaml and applied, then only the secrets listed as allowed can be accessed from that particular secret store.

So what would it look like to specify that a component can't access anything? Empty list? or do we want something explicit?

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: secrets-list
  namespace: default
spec:
  secrets:
    scopes:
```

**Comment by rynowak** [comment]
> For solution 1, we could generate a random Key when the Dapr sidecar starts and inject it to the application as the DAPR_API_TOKEN env.

Thinking a little bit more about this.... 

If this is an env-var that means it's accessible to any code running the cluster that has read access to the PodSpec or a backing k8s secret right? In k8s Dapr is not the one starting your container, so it has to be represented in the k8s apis. I'm not sure how we think about these concepts in the overall threat model...

Another approach might be to generate a token on startup and store it on disk in a well-known location, so that an attacker has to have to file-system access to the pod to read the token. This is much more complicated of course.

**Comment by yaron2** [comment]
> > The default behavior would what we have now, no scoping all secrets can be accessed from a configured secret store.
> > Once the secrets configuration spec is added to the Configuration yaml and applied, then only the secrets listed as allowed can be accessed from that particular secret store.
> 
> So what would it look like to specify that an app can't access anything? Empty list? or do we want something explicit?
> 
> ```yaml
> apiVersion: dapr.io/v1alpha1
> kind: Configuration
> metadata:
>   name: secrets-list
>   namespace: default
> spec:
>   secrets:
>     scopes:
> ```
> 
> --
> 
> As a practical matter - one of the challenges in building .NET SDK support for secrets is that the application code has to list the secrets that it's _interested in_ so they can be fetched eagerly. So in effect, .NET applications using dapr and the `IConfiguration` apis for secrets effectively already have this feature - though moving this to external configuration seems better.
> 
> I would be interested in knowing if other SDKs have similar integrations points and whether we can do something to remove duplication for users that are doing this _the right way_.
> 
> At first it seems appealing to have the sidecar expose an endpoint that tells the app the names of secrets it has access to ... but that's problematic for the default case where you didn't configure anything.

+1 on the need to come up with a way to deny access to all secrets. It might be a dedicated property.

**Comment by yaron2** [comment]
> > For solution 1, we could generate a random Key when the Dapr sidecar starts and inject it to the application as the DAPR_API_TOKEN env.
> 
> Thinking a little bit more about this....
> 
> If this is an env-var that means it's accessible to any code running the cluster that has read access to the PodSpec or a backing k8s secret right? In k8s Dapr is not the one starting your container, so it has to be represented in the k8s apis. I'm not sure how we think about these concepts in the overall threat model...
> 
> Another approach might be to generate a token on startup and store it on disk in a well-known location, so that an attacker has to have to file-system access to the pod to read the token. This is much more complicated of course.

Just to clarify, the proposal being discussed here is about solution 2 and thus the token is currently irelevant unless we tackle solution 1 instead.

**Comment by wcs1only** [comment]
A few things:

I'm not sure I like the behavior of defaulting to open to all, and only closing once an ACL is added. Imagine the scenario of a production Dapr cluster which contains many microservices using many different secrets. Now imagine retroactively trying to add valid ACLs. If a maintainer misses some secrets in their ACL when applying it for the first time, they may break their running application.

I also am nervous that this violates the "secure by default" security principle. A user is who new to dapr who is unaware of this attack vector is likely to write up their application, have it run fine and be completely unaware of this security pitfall until they get breached. At this point they will have to retroactively figure out how to add these allow lists.

I guess what I'm asking is, why can't we go ahead and build solution 1? Seems like it would deliver the security we need out of the box without the user having to do anything? Do I understand the problem we're trying to solve correctly?

**Comment by yaron2** [comment]
> A few things:
> 
> I'm not sure I like the behavior of defaulting to open to all, and only closing once an ACL is added. Imagine the scenario of a production Dapr cluster which contains many microservices using many different secrets. Now imagine retroactively trying to add valid ACLs. If a maintainer misses some secrets in their ACL when applying it for the first time, they may break their running application.
> 
> I also am nervous that this violates the "secure by default" security principle. A user is who new to dapr who is unaware of this attack vector is likely to write up their application, have it run fine and be completely unaware of this security pitfall until they get breached. At this point they will have to retroactively figure out how to add these allow lists.
> 
> I guess what I'm asking is, why can't we go ahead and build solution 1? Seems like it would deliver the security we need out of the box without the user having to do anything? Do I understand the problem we're trying to solve correctly?

We already have solution 1 in place today. Users can set up tokens in a secret and then have Dapr only authenticate requests with that token.

This issue came up during the security audit Dapr went through, the recommendation from the team was to add the ability for users to deny access to secrets.

**Comment by rynowak** [comment]
> We already have solution 1 in place today.

If that's the case, I'm not sure what what the change is that's being discussed here (re: auth) is the idea that a token would be *required* for access to secrets?

In either case solution 2 is very useful as a defense in depth mechanism for cases of accidental disclosure. In particular I'm thinking of vulnerabilities where application code uses user-input to determine which secret to use. Having an allow-list of secrets that the app can access limits the blast radius.

**Comment by yaron2** [comment]
> If that's the case, I'm not sure what what the change is that's being discussed here (re: auth) is the idea that a token would be required for access to secrets?

correct, which means that we'd mandate creating a token and then injecting it into a user's pod or process. (that's doable on both k8s natively through the sidecar injector and self-hosted).

**Comment by rynowak** [comment]
> correct, which means that we'd mandate creating a token and then injecting it into a user's pod or process. (that's doable on both k8s natively through the sidecar injector and self-hosted).

Without auth, what's stopping *any* code running in the cluster from pinging a random dapr sidecar and asking for all of the secrets?

**Comment by yaron2** [comment]
Without auth enabled, nothing. However you can't ask Dapr for all the secrets as it intentionally doesn't have a List operation for secrets, you can Get a secret by providing the name for it.

In general, Kubernetes allows by default any Pod to access any other Pod over the network, whether in the same namespace or even across namespaces. Only fairly recently did Network Policies come into play, and those can be used by cluster admins in general to restrict access from specific workloads to others.

It was recommended (to us and later on by us) that Dapr provides finer security mechanisms (mTLS, auth tokens, scopes, etc) but to only make mTLS enabled by default because it does not mandate any special user involvement (transparent), and have the others opt-in, as users may choose their own security mechanisms (service mesh, network policies, etc.) as part of their cluster deployments.

**Comment by mukundansundar** [comment]
@rynowak @yaron2  I think only Kubernetes secret store does not need any setup and that would be the only secret store which would need a deny all mechanism. All other secret stores need components setup and combined with the allowlist can have a flow similar to deny all. But at the same time, we can also have a property specifically to deny access to any secrets in that secretstore. 
The configuration template might look something like this. 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  secrets:
    scopes:
      - storeName: <STORE_NAME_1>
        denyAccess: false     # default value
        allowedSecrets: ["key1","key2"]
      - storeName: <STORE_NAME_2>
        denyAccess: true
```

By default the value fore denyAccess will be false following the current behavior we have now and be explicitly set to true. 

@youngbupark  modified the spec to be a single-line array. 

@vinayada1 If the store is not configured via the components yaml then the configuration yaml should have no effect on the store. 

If we want to go for a secure by default principle then this will be a breaking change where the existing users would need to apply a new configuration to allow access first.

**Comment by artursouza** [comment]
I am in favor of forcing the user to provide the allowlist and have an empty list to mean "no access". To have a denylist scenario covered, I think it is better to have an attribute such as `defaultAccess: allow` or `defaultAccess: deny` and have `alowedSecrets` and `deniedSecrets` too.

**Comment by yaron2** [comment]
I support having `defaultAccess` to specify the default behavior of the scope, but not forcing users to specify scopes. That'd also be a breaking change, regardless.

**Comment by mukundansundar** [comment]
The design becomes: 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  secrets:
    scopes:
      - storeName: <STORE_NAME_1>
        defaultAccess: deny     
        allowedSecrets: ["key1","key2"]
      - storeName: <STORE_NAME_2>
        denyAccess: allow # default value
        deniedSecrets: ["key3"]
        allowedSecrets: ["key4", "key5"]
    - storeName: <STORE_NAME_3>
        denyAccess: allow # default value
        deniedSecrets: ["key6"]
```
defaultAccess is still allow, to allow all secrets to be read. 
If the defaultAccess is set as deny, then only the list of secrets in the allowedSecrets will be granted access to.
If the default Access is set as allow, then 
 - if allowedSecrets is present, only those secrets will be accessible eg: STORE_NAME_2, only "key4" and "key5" are allowed
 - if allowedSecrets is not preset, all secrets are allowed access to except for the ones in the deniedAccess list eg: for STORE_NAME_3 only "key6" is denied, rest of the secrets are accessible. 
In this scenario
