### ISSUE TITLE
Label control plane pods in the Helm Chart

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1805]
To make it easier for tooling to interact with the Dapr control plane (examples include our own CLI, Dashboard) it's recommended we use labels to identify the control plane pods.

Kubernetes has the concept of recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

The following suggestion is based on the above:

Suggested labels:

```yaml
app.kubernetes.io/name: {{ Release.Name}}
app.kubernetes.io/version: {{ Values.global.tag }}
app.kubernetes.io/component: sentry/operator/sidecar-injector/dashboard/placement
app.kubernetes.io/part-of: "dapr"
app.kubernetes.io/managed-by: "helm"
```
