### ISSUE TITLE
Secret key ref in component doesn't work after first Dapr deployment

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1807]
After deploying Dapr (control plane) for the first time, creating a component YAML that has a `secretKeyRef` to take the value from a Kubernetes secret will have Dapr fail to get the secret only the first time the Pod is started. A restart resolves this.

Steps to reproduce:

0. Remove any prior installation of Dapr you have
1. Install Dapr: `helm install dapr dapr/dapr --namespace dapr-system`
2. Install Redis: `helm install redis stable/redis --set cluster.slaveCount=0`
3. Apply the following YAML with `kubectl apply -f`:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      key: redis-password
      name: redis
```

4. Deploy the 2. hello kubernetes sample apps:

```
kubectl apply -f https://raw.githubusercontent.com/dapr/samples/release-0.9/2.hello-kubernetes/deploy/python.yaml

kubectl apply -f https://raw.githubusercontent.com/dapr/samples/release-0.9/2.hello-kubernetes/deploy/node.yaml
```

5. Wait until both pods are Running with 2/2 containers. Look at the logs of the node app with: `kubectl logs <pod-name> node -f` and see that you get an error message persisting state.

6. Look at the logs of daprd with: `kubectl logs <pod-name> daprd` and see the following error: `level=warning msg="error initializing state store state.redis: redis store: error connecting to redis at redis-master:6379: NOAUTH Authentication required." app_id=nodeapp instance=nodeapp-74bd485bcf-2vwpc scope=dapr.runtime type=log ver=0.9.0`

7. Restart the node pod. look at the node container logs again: everything's working fine.
