### ISSUE TITLE
Retry Pattern in Dapr runtime

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1820]
## In what area(s)?

> /area runtime

## Describe the proposal

Currently, there are two kinds of retries supported by Dapr:-
	1.	User application level retries for stateful write operations which is configurable by the user on a per-call basis. The retry logic has been consistently implemented by all the state components in the components-contrib repo.
	2.	Internal retries by Dapr during service invocation i.e. Dapr tries to reach the callee side Dapr sidecar and sees some error and attempts a retry
 
For the user application level retries, the proposal is to offer a retry pattern which is consistent across all component types. Below are some of the options:-
	1.	Do not support retries in Dapr runtime and let the user application handle the retry logic. In this case, we will remove the retry logic currently supported by stateful operations
	2.	Move the retry logic to middleware which will provide a consistent experience across all components
	3.	Implement the retry logic as a separate building block which can hooked in as needed.
 
For the internal retries, the proposal is to offer a consistent retry logic across all building blocks and not just service invocation. For example, if Dapr sees a timeout while accessing a DB, Dapr will retry the same way as it does now for the service invocation case.  For this, some of the options are:-
	1.	The retry logic could be fixed and not configurable per-component/per-call basis
	2.	The retry logic could be configurable on a per-component basis
	3.	The retry logic could offer some knobs to make it configurable per-component and per-call basis.

**Comment by vinayada1** [comment]
As discussed in the community meeting, Dapr runtime will implement a retry mechanism. We will keep this retry logic very simple and optional. Below is an initial design proposal.

Design Proposal:-
1. A retry spec will be added to the global config
2. The retries could be configured as follows in the config.yaml:-

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
  retries:
    backoffMechanism: Linear/BinaryExponentialBackoff
    retryCount: 3
    initialBackoffIntervalInMilliSeconds = 1000
    buildingBlocks: ['state', 'pubsub', 'secrets', 'bindings', 'actors']
 ```

3. The building blocks can be opted-in or out from the retry logic by including or excluding them from the buildingBlocks property in the config.
4. The retry config will be fixed across all calls and cannot be configured on a per-call basis or customized for a particular building block.
