### ISSUE TITLE
Add a version to component resource definition

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#1841]
Currently component yaml doesn't have a version, proposal is to add a version which would allow Dapr to handle breaking changes in future for components.

Proposed schema:
```
apiVersion: dapr.io/v1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v2
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"  
```
