### ISSUE TITLE
Dapr Operator not issuing Cluster IP on Kubernetes

### ISSUE THREAD

**Issue by skmaingi** [dapr/dapr#1860]
## In what area(s)?

 /area placement

## What version of Dapr?

 0.9.0

## Expected Behavior

Dapr Sidecar Services to have Cluster IP address

## Actual Behavior

None Cluster IP address

## Steps to Reproduce the Problem

1. Install Dapr to Kubernetes environment using Helm 3

```
helm repo add dapr https://daprio.azurecr.io/helm/v1/repo
helm repo update
helm install dapr dapr/dapr --namespace my-namespace
```

2. Deploy application to Kubernetes: `kubectl apply -f app.yaml`

app.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
  namespace: my-namespace
  labels:
    app: appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "appname"
        dapr.io/port: "3000"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: appname
        image: appnameapp:latest
        ports:
        - containerPort: 8080
```
