### ISSUE TITLE
old annotation does not work

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1877]
## In what area(s)?

/area runtime

## What version of Dapr?

edge

## Steps to Reproduce the Problem

1. helm install dapr dapr/dapr --set-string global.tag=edge
2. deploy the app with old annotation.
```
annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "actoropenai"
        dapr.io/port: "3000"
```

## Expected Behavior

dapr side car service is created.

## Actual Behavior

dapr side car service is not created.
