### ISSUE TITLE
Component yaml can not be loaded in k8s if one value is integer and not string

### ISSUE THREAD

**Issue by h2floh** [dapr/dapr#1893]
## In what area(s)?

/area operator

## What version of Dapr?
v0.8.0-rc

## Expected Behavior

A component yaml with integer values can be loaded in standalone mode but not if running in kubernetes mode.

Behavior should be same for standalone and kubernetes mode. Either allowing integers or failing with integers.

## Actual Behavior

Standalone is working
Kubernetes throws an error within Operator Service:
```
E0812 06:11:42.076047       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha1.Component: v1alpha1.ComponentList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.Component: v1alpha1.Component.Spec: v1alpha1.ComponentSpec.Type: Metadata: []v1alpha1.MetadataItem: v1alpha1.MetadataItem.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":1}],"type":|..., bigger context ...|msQuery","value":""},{"name":"authStyle","value":1}],"type":"middleware.http.oauth2clientcredentials|...
```

## Steps to Reproduce the Problem

Deploy this Component to a dapr k8s
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test
spec:
  type: somecomponent
  metadata:
  - name: integer
    value: 1
```
check the logs of the Operator service/pod
