### ISSUE TITLE
Declarative mechanism to create Topic Subscription 

### ISSUE THREAD

**Issue by anishj0shi** [dapr/dapr#1895]
## In what area(s)?

/area operator

## Describe the feature
The Current Mechanism a workload needs to ensure for subscribing to a topic is pretty microservice biased, where the workload defines an http handler to define the topic it's interested in and a callback route for dispatching the message. This mechanism might not be the best way to define a topic subscription for a serverless function, where these additional endpoint ,what the dapr sidecar would invoke, would probably not be the part of the serverless code. Hence, I propose a more declarative approach to define subscription to a topic. This API can be either defined as a Custom Resource Definition or any other API in conformance to Open Service Broker API specification, which any user can invoke to create subscription to a topic. I'd expect this API to have 2 mandatory parameters: 1) Topic of interest 2) Subscriber reference (url, k8s object reference, etc).

**Comment by yaron2** [comment]
This makes sense, I'd like to flush out a design for this.

Would you mind drafting a CRD definition for how you'd like to see this?

**Comment by anishj0shi** [comment]
Given the existing user simplicity offered by dapr, I could think of the following CRD.

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  group: dapr.io
  names:
    kind: Subscription
    plural: subscriptions
    singular: subscription
  scope: Namespaced
  versions:
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              topic:
                description: corresponds to an event topic on which a published message should trigger a callback
                type: string
              subscriberURI:
                description: the destination URI that should receive the message.
                type: string
```

**Comment by yaron2** [comment]
> Given the existing user simplicity offered by dapr, I could think of the following CRD.
> 
> ```yaml
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> spec:
>   group: dapr.io
>   names:
>     kind: Subscription
>     plural: subscriptions
>     singular: subscription
>   scope: Namespaced
>   versions:
>     name: v1alpha1
>     schema:
>       openAPIV3Schema:
>         properties:
>           spec:
>             properties:
>               topic:
>                 description: corresponds to an event topic on which a published message should trigger a callback
>                 type: string
>               subscriberURI:
>                 description: the destination URI that should receive the message.
>                 type: string
> ```

This looks good. Now we need to be able to come up with a way to attach this to a specific app. We cannot use k8s selectors as this would violate the multi-platform principal, but given how Dapr already supports scoping components to specific apps, I think we can use that mechanism here and have it be explicitly required.

Here's an example based on the CRD above using scopes:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: newOrder
  subscriberURI: /api.v1/order
scopes:
- app1
- app2
```
