### ISSUE TITLE
redundent metadata in dapr_service_injector_service.yaml

### ISSUE THREAD

**Issue by beiwei30** [dapr/dapr#2136]
## In what area(s)?

> /area operator

## What version of Dapr?

> Output of git describe --dirty
v0.11.0-rc.2-12-gb84096b8

## Expected Behavior

a redundant 'metadata' is defined under 'metadata' in charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  metadata:
  name: dapr-sidecar-injector
```
## Actual Behavior

I believe it should be 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dapr-sidecar-injector
```
