### ISSUE TITLE
Metrics disable not working

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2163]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

0.11.0-rc.4

## Expected Behavior

Metrics to be disabled if the configuration is added to disable it. 

## Actual Behavior

Metrics still visible.

## Steps to Reproduce the Problem

Add configuration in either self hosted or kubernetes mode. 

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: nodeconfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: false
```

Run any of the quick starts with this configuration enabled `dapr.io/config` annotation for kubernetes or `--config` flag for self hosted. 

For self hosted --- see logs for metrics server port and visit that port. 

For kubernetes --- port-forward <pod> 9090 and visit localhost:9090.
