### ISSUE TITLE
Invalid component category does not raise error

### ISSUE THREAD

**Issue by amolenk** [dapr/dapr#2178]
## In what area(s)?

/area runtime

## What version of Dapr?

0.11.0

## Expected Behavior

When I specify an incorrect type in a component configuration, the log will show me an error as expected. In the example below, I’m using `secretstores.foo` as the component type which clearly doesn’t exist:

``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
  namespace: default
spec:
  type: secretstores.foo
  metadata:
```

This results in the following error in the log as expected:

```
== DAPR == time="2020-10-02T14:01:02.982503+02:00" level=warning msg="failed creating secret store secretstores.foo: couldn't find secret store secretstores.foo" app_id=trafficcontrolservice instance=Luna scope=dapr.runtime type=log ver=0.11.0

== DAPR == time="2020-10-02T14:01:02.98259+02:00" level=error msg="process component envvar-secret-store error, couldn't find secret store secretstores.foo" app_id=trafficcontrolservice instance=Luna scope=dapr.runtime type=log ver=0.11.0
```

However, when I make a mistake in the category part of the spec type, such as spelling ‘secretstores.’ as ‘se**cc**retstores.’ no error is displayed in the log. Example:

``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
  namespace: default
spec:
  type: seccretstores.local.env
  metadata:
```

The only line in the log about the component appears to indicate succes:

```
== DAPR == time="2020-10-02T14:07:54.123874+02:00" level=info msg="component loaded. name: my-secret-store, type: seccretstores.local.env" app_id=trafficcontrolservice instance=Luna scope=dapr.runtime type=log ver=0.11.0
```

I think we’d want an error to show up in this scenario. I’ll link a PR that adds the error to the log.
