### ISSUE TITLE
How to use declarative subscriptions consume topics

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2281]
> /area runtime
> /area docs

## Ask your question here
in components file have two config yaml:
custom.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: newOrder
  route: /orders
  pubsubname: rabbitmq
scopes:
- app
```

rabbitmq.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
spec:
  type: pubsub.rabbitmq
  metadata:
  - name: host
    value: amqp://localhost:5672
```

subscribe
```go
func main() {
	http.HandleFunc("/orders", func(w http.ResponseWriter, r *http.Request) {
		respBytes, _ := ioutil.ReadAll(r.Body)
		fmt.Println("Recieved Message from rabbitmq - " + string(respBytes))
	})

	fmt.Println("starting HTTP server....")
	http.ListenAndServe(":3011", nil)
}
```

run subscribe
```sh
dapr run --app-id app --app-port 3011 --dapr-http-port 3511 --components-path ./components -- go run main.go 
```

publisher
```go
const topic = "newOrder"
const daprPort = 3511
const publishName = "rabbitmq"

func main() {

	contentType := "application/json"
	publishURL := fmt.Sprintf("http://localhost:%d/v1.0/publish/%s/%s", daprPort, publishName, topic)

	data := `{"name": %s, "age":%s}`
        body := fmt.Sprintf(data, "li", "20")
	resp, err := http.Post(publishURL, contentType, strings.NewReader(string(body)))
	if err != nil {
		fmt.Println("err", err)
	}
	fmt.Println("sent message", string(data))
	fmt.Println("response", resp.Status)
}
```

run publisher
```sh
dapr run --app-id publisher --app-port 3005 go run main.go  
```
result:
i got `{"errorCode":"ERR_PUBSUB_NOT_FOUND","message":""}`
