### ISSUE TITLE
Require KeyCloak oauth  example

### ISSUE THREAD

**Issue by pzou19741** [dapr/dapr#2328]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Release Note

RELEASE NOTE:

**Comment by pzou19741** [comment]
any update?

**Comment by pzou19741** [comment]
I'm not able to make keycloak integration works.
I modified  https://github.com/dapr/quickstarts/tree/master/middleware  echoapp.

**Here is component yaml:**
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
  namespace: default
spec:
  type: middleware.http.oauth2
  metadata:
  - name: clientId
    value: "test"
  - name: clientSecret
    value: "[keycloak client secret]"
  - name: scopes
    value: "openid"
  - name: authURL
    value: "https://[keycloak endpoint]/auth/realms/demo/protocol/openid-connect/auth"
  - name: tokenURL
    value: "https://[keycloak endpoint]/auth/realms/demo/protocol/openid-connect/token"
  - name: redirectURL
    value: "http://localhost:3500/v1.0/invoke/echoapp.default/"
  - name: authHeaderName
    value: "authorization" 
```
**configuration yaml**

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
  namespace: default
spec:
  httpPipeline:
    handlers:
    - type: middleware.http.oauth2
      name: oauth2  
```

deployment yaml 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoapp
  namespace: default
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "echoapp"
        dapr.io/app-port: "3000"
        dapr.io/config: "pipeline"
    spec:
      containers:
      - name: echo
        image: archdevopsdevacr.azurecr.io/dapriosamples/middleware-echoapp:0.0.2
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: acrcred
```
I added console.log for debug   echoapp/app.js 

```

const express = require('express');
const bodyParser = require('body-parser');
const app = express();
app.use(bodyParser.json());

const daprPort = process.env.DAPR_HTTP_PORT || 3500;
const port = 3000;

app.get('/echo', (req, res) => {
    var text = req.query.text;
    console.log("Echoing: " + text);
    console.log("now let's print headers");
    for(var item in res.headers) {
	    console.log(item + ": " + res.headers[item]);
    }
    console.log("finished print   ");
    console.log("print headers: "+ res.headers);
    res.send("Access token: " + req.headers["authorization"] + " Text: " + text);


});

app.listen(port, () => console.log(`Node App listening on port ${port}!`));
```
