### ISSUE TITLE
Support Virtual Kubelet integration

### ISSUE THREAD

**Issue by cbellee** [dapr/dapr#2348]
## In what area(s)?
/area operator

## What version of Dapr?
0.11.x

## Expected Behavior
Dapr sidecar container is successfully created when running on AKS Virtual Nodes.

## Actual Behavior
An error is received when trying to run Dapr on AKS Virtual Nodes (virtual kubelet). The virtual kubelet container returns the error `"failed to sync pod \"<namespace>/<pod-name>\" in the provider: unsupported fieldPath: status.podIP"`. 

If Dapr annotations are removed from the Deployment manifest, the virtual kubelet is able to successfully create the pod. I discussed this issue with Yaron via the GItter community site who said it was due to AKS VK not supporting the downward API needed to get the host IP it's running on and offered two possible solutions. 

1. AKS VK is extended to support the downward API
2. Dapr is modified to allow end users to bypass the `status.PodIp` value, which is only required when running Dapr Actors.

## Steps to Reproduce the Problem

1. Create an AKS cluster with the virtual nodes feature enabled. https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-portal

2. Install Dapr into the cluster. https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster

3. If your container image is stored in a private registry, you will also need to create a Kubernetes secret to store the registry credentials as Azure Container Instances (ACI) doesn't yet support private registry credentials via Managed Identity.

```
kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson
```

3. Create a Kubernetes Deployment manifest that includes the Dapr annotations & virtual kubelet node selector & toleration.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: myapp
        image: myregistry/myapp:tag
        ports:
          - containerPort: 8003
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      imagePullSecrets:
      - name: regcred
```

4. Deploy manifest to AKS VK enabled cluster. 
`kubectl apply -f ./testdeploy.yml`

## Release Note
RELEASE NOTE: **FIX** Bug in runtime.

**Comment by WhoAteDaCake** [comment]
I'm not sure this issue is fixed yet? I've tried deploying:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/log-level: "debug"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: aci-helloworld
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
```

The dapr sidecard keeps shutting itself down: https://pastebin.com/kDNaXb9d
