### ISSUE TITLE
Potential tracing docs inconsistency 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#2359]
Our app config docs/examples indicate that the way you turn tracing sample rate is using `samplingRate`

```yaml
spec:
  tracing:
    samplingRate: "1"
```

But our tracing docs/samples show more verbose config which does not include the `samplingRate`

```yaml
spec:
  tracing:
    enabled: true
    exporterType: zipkin
    exporterAddress: "http://localhost:9411/api/v2/spans"
    expandParams: true
    includeBody: true
```

Few questions after reviewing the tracing docs: 

* Is the union of these two what's required? 
* Is `enabled` to turn it on and `samplingRate` to set the rate? 
* What are the defaults `expandParams` and `includeBody`?
* Can `exporterAddress` point to zipkin service in a different namespace?

**Comment by youngbupark** [comment]
The sample doc must be updated. the config in samples is out-dated.

Also we will migrate trace config to opentelemetry collector config. please look at https://github.com/dapr/dapr/issues/2337 

cc/ @tcnghia

**Comment by yaron2** [comment]
There is no union, this spec is wrong and should be removed from docs:

```
spec:
  tracing:
    enabled: true
    exporterType: zipkin
    exporterAddress: "http://localhost:9411/api/v2/spans"
    expandParams: true
    includeBody: true
```
