### ISSUE TITLE
Better support for non-default namespace deployments on Kubernetes 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#2371]
Today, during Helm installation, Dapr applies the necessary role and RBAC for reading secrets to the default namespace. This makes deploy Dapr apps to that namespace easy (`dapr.io/enabled: true` and good to go). 

However, if the user wants to deploy into any other namespace, additional secret related configuration is required:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```

> This configuration is documented but still, it represents a friction for users. 

It would be great if Dapr implemented namespace watcher so that users could label any namespace to have this configuration (and any other necessary for Dapr) automatically applied. 

```shell
kubectl label namespace demo dapr=enabled
```
