### ISSUE TITLE
 how to create(register)  actors?

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2393]
> /area runtime
> /area placement
> /area docs

## Ask your question here

 how to create(register)  actors?

**Comment by yaron2** [comment]
See here: https://docs.dapr.io/reference/api/actors_api/#invoke-actor-method

**Comment by dybxin** [comment]
oh,I noticed it,thank a lot !

**Comment by dybxin** [comment]
@yaron2 I'm sorry, maybe I didn't describe it clearly.I have reviewed the relevant documentation.I still don't clear how to create actors.i noticed in default statestore.yaml likely flowing:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
```
contains: actorStateStore attribute. and dapr run find logs :

```
== DAPR == time="2020-11-16T17:34:07.261774912+08:00" level=info msg="placement order received: lock" app_id=addapp instance=yabing scope=dapr.runtime.actor type=log ver=0.11.2

== DAPR == time="2020-11-16T17:34:07.261834797+08:00" level=info msg="placement order received: update" app_id=addapp instance=yabing scope=dapr.runtime.actor type=log ver=0.11.2

== DAPR == time="2020-11-16T17:34:07.261853708+08:00" level=info msg="placement tables updated, version: 0" app_id=addapp instance=yabing scope=dapr.runtime.actor type=log ver=0.11.2

== DAPR == time="2020-11-16T17:34:07.26187218+08:00" level=info msg="placement order received: unlock" app_id=addapp instance=yabing scope=dapr.runtime.actor type=log ver=0.11.2
```
the actors created already, but where the actortype and actorId.
