### ISSUE TITLE
questions about service invocation and access control list configuration 

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2473]
> /area runtime
> /area operator
> /area placement

## Ask your question here
-  about service_invocation_api:

serviceA:
 ```sh
dapr run --app-id goapp --app-port 3001 --dapr-http-port 3501 go run main.go
```
serviceB:
 ```sh
dapr run --app-id nodeapp --app-port 3000 --dapr-http-port 3500 node app.js
```
serviceA invoke serviceB's method. the call link should be `http://localhost:3500/v1.0/invoke/nodeapp/method/<method-name> `. but `http://localhost:3501/v1.0/invoke/nodeapp/method/<method-name>` and  `http://localhost:3500/v1.0/invoke/nodeapp/method/<method-name>` all can called.  
in `POST/GET/PUT/DELETE http://localhost:<daprPort>/v1.0/invoke/<appId>/method/<method-name>`, the daprPort  representative the calling(serviceA) port or the called(serviceB) port?

- about  apply access control list configuration for service invocation
i apply access control to the [hello world](https://docs.dapr.io/operations/configuration/invoke-allowlist/), but not effective. (i run in Local env.)

run pythonapp:
``` sh
dapr run --app-id pythonapp python3 app.py --config ./pythonappconfig.yaml
```

run nodeapp
```sh
dapr run --app-id nodeapp node app.js --app-port 3000 --dapr-http-port 3500 --config ./nodeappconfig.yaml
```

pythonappconfig.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: nodeappconfig
spec:
  tracing:
    samplingRate: "1"
  accessControl:
    defaultAction: allow
    trustDomain: "public"
    policies:
    - appId: pythonapp
      defaultAction: allow
      trustDomain: 'myDomain'
      namespace: "default"
      operations:
      - name: /neworder
        httpVerb: ['POST']
        action: deny
```

pythonappconfig.yaml

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pythonappconfig
spec:
  tracing:
    samplingRate: "1"
  accessControl:
    defaultAction: allow
    trustDomain: "myDomain"
```
