### ISSUE TITLE
access control list configuration for service invocation invalid

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2502]
> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

The dapr i using version 1.0.0-rc.1.

The scenario show how to deny access to the add method from the nodeapp2, where the nodeapp2 is in the myDomain trust domain and default namespace. The nodeapp1 is in the public trust domain.

desired result: the nodeapp2 can not access nodeapp1's add method.

actual results: the nodeapp2 can access nodeapp1's add method.

The fllowing is nodeapp1 and nodeapp2's core code.
## In app2 application:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: nodeapp2config
spec:
  tracing:
    samplingRate: "1"
  accessControl:
    defaultAction: allow
    trustDomain: "myDomain"
```
app.js
```js
const express = require('express');
const bodyParser = require('body-parser');
require('isomorphic-fetch');
const app = express();
app.use(bodyParser.json());
const cors = require('cors');

const port = 3002;

app.use(cors());

const daprPort = process.env.DAPR_HTTP_PORT || 3501;
const appID = `nodeapp1`;
const stateUrl = `http://localhost:${daprPort}/v1.0/invoke/${appID}/method`;

app.post('/app2/add', (req, res) => {
    let args = req.body;

    fetch(`${stateUrl}/add`, {
        method: "POST",
        body: JSON.stringify(args),
        headers: {
            "Content-Type": "application/json"
        }
    }).then((response) => {
        if (!response.ok) {
            throw "invoke failed.";
        }

        console.log("Successfully invoke.");
        res.status(200).send();
    }).catch((error) => {
        console.log(error);
        res.status(500).send({message: error});
    });
});

app.post('/app2/subtract', (req, res) => {
    let args = req.body;

    fetch(`${stateUrl}/subtract`, {
        method: "POST",
        body: JSON.stringify(args),
        headers: {
            "Content-Type": "application/json"
        }
    }).then((response) => {
        if (!response.ok) {
            throw "invoke failed.";
        }

        console.log("Successfully invoke.");
        res.status(200).send();
    }).catch((error) => {
        console.log(error);
        res.status(500).send({message: error});
    });
  });

app.listen(port, () => console.log(`Listening on port ${port}!`));
```

```shell
dapr run --app-id nodeapp2 --app-port 3002 --dapr-http-port 3502 node app.js --config ./config.yaml
```

## In app1 application:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: nodeapp1config
spec:
  tracing:
    samplingRate: "1"
  accessControl:
    defaultAction: allow
    trustDomain: "public"
    policies:
    - appId: nodeapp2
      defaultAction: allow
      trustDomain: 'myDomain'
      namespace: "default"
      operations:
      - name: /add
        httpVerb: ['POST']
        action: deny
```

```js
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
app.use(bodyParser.json());
const cors = require('cors');

const port = 3001;

app.use(cors());

app.post('/add', (req, res) => {
  let args = req.body;
  const [operandOne, operandTwo] = [Number(args['operandOne']), Number(args['operandTwo'])];
  
  console.log(`Adding ${operandOne} to ${operandTwo}`);
  
  let result = operandOne + operandTwo;
  res.send(result.toString());
});

app.post('/subtract', (req, res) => {
    let args = req.body;
    const [operandOne, operandTwo] = [Number(args['operandOne']), Number(args['operandTwo'])];
    
    console.log(`Subtracting ${operandOne} to ${operandTwo}`);
    
    let result = operandOne - operandTwo;
    res.send(result.toString());
  });

app.listen(port, () => console.log(`Listening on port ${port}!`));
```

```shell
dapr run --app-id nodeapp1 --app-port 3001 --dapr-http-port 3501 node app.js --config ./config.yaml
```
