### ISSUE TITLE
Migrate metrics config to Dapr Configuration

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2515]
Right now, Dapr enables metrics via helm chart config, injecting "prometheus.io/" annotations in the control plane deployments. Sidecar injector, then propagates the config as parameters to daprd container.

Instead, could this we have a "metrics" configuration in the Configuration CRD instead? This would be similar to how we enable tracing and mTLS.

**Comment by youngbupark** [comment]
`prometheus.io/*` is the annotation defined by prometheus itself, not by Dapr. prometheus discovers metrics port/url by looking at this annotation. Azure monitor also refers this annotation to scrape the metrics - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-prometheus-integration

**Comment by youngbupark** [comment]
> Instead, could this we have a "metrics" configuration in the Configuration CRD instead? This would be similar to how we enable tracing and mTLS.

We already have metrics configuration in CRD. https://github.com/dapr/docs/blob/a234e10fa34ea86192d0f2f455892f6d004186de/daprdocs/content/en/developing-applications/building-blocks/observability/metrics.md#configuration

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: false
```

if users set `metrics.enabled` to false, then Dapr sidecar will not emit the metrics.
