### ISSUE TITLE
Access control configuration invalid w/o at least 1 policy 

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#2526]
The following config doesn't seem to be currently supported in Dapr due to lack of at least one policy:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: my-app-config
spec:
  accessControl:
    defaultAction: allow
    trustDomain: "my-trust-domain"
```

In case where user wants this app to be wide open but all the downstream apps in this trust domain to be accessed only by this application (common microservice pattern), it would be good to enable this config to work so they make this app a part of the `my-trust-domain` trust domain.
