### ISSUE TITLE
prometheus--targets--state--down

### ISSUE THREAD

**Issue by dybxin** [dapr/dapr#2567]
> /area configuration

## Ask your question here

- prometheus.yml

```yaml
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'dapr'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090'] # Replace with Dapr metrics port if not default

```

- docker ps
![Screenshot from 2020-12-11 17-10-14](https://user-images.githubusercontent.com/14888437/101884522-cb4ea800-3bd3-11eb-89f9-45be85799b63.png)

- Run as Container

```sh
docker run \
    --net=host \
    -v /tmp/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus --config.file=/etc/prometheus/prometheus.yml --web.listen-address=:8081
```
- prometheus
![Screenshot from 2020-12-11 17-09-27](https://user-images.githubusercontent.com/14888437/101884445-a9edbc00-3bd3-11eb-88e1-bcc1d23aa8e3.png)
