### ISSUE TITLE
[Proposal] Enable Pub/Sub CloudEvent filtering for subscribers

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2582]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Subscribers should be able to filter based on the CloudEvent subject and other properties. See https://github.com/cloudevents/spec

## Release Note

RELEASE NOTE: **ADD** Support for CloudEvent filtering in PubSub's subscriber

**Comment by skyao** [comment]
Any more information about this proposal? What the plan?

**Comment by artursouza** [comment]
We will start the design for this in March to implement in v1.2. The proposal will be presented here for community commenting.

**Comment by jigargandhi** [comment]
I would like to work on this if unassigned

**Comment by artursouza** [comment]
I think it is a good issue to work on. PubSub payload is json cloud events, which makes me think that JsonPath matching is a good fit as the query language to filter. This should probably be defined as a response to the subscribe callback. The SDKs need a corresponding issue too to add this support.

I will assign this to you, @jigargandhi 

WDYT?

**Comment by jigargandhi** [comment]
I agree that 

> The filter should probably be defined as a response from the app to the subscribe callback. The SDKs need a corresponding issue too to add this support.

When you mentioned JsonPath filtering are you thinking of looking into the data of the message and then filter based on whether the JsonPath is satisfied or not.

I have a different opinion though:
We should not look into data rather use the following fields
- Type, a mandatory field this includes type of the message and apps might want to subscribe to certain types of messages which they can handle
- Source, this is a mandatory attribute in cloud events spec and is a URI, Apps might subscribe certain prefix paths of producers.
- Subject this is an optional field and can be used to do string matching.

Makes sense?

**Comment by pkedy** [comment]
@jigargandhi I like your thoughts above because decoding `data` could be expensive. However, I believe that developers will likely want to filter based on the contents of `data`. As an optimization, the filtering code can "lazy decode" `data` (as determined by `datacontenttype`) only if it is used in the filter expression (possibly determined by strings.Contains(`.data.`) or RegEx during initialization).

I think JsonPath is a good option as a filtering mechanism but I also wanted to point out [CEL](https://opensource.google/projects/cel). It would feel more like programming a predicate statement in a familiar programming language vs. writing a potentially unfamiliar expression syntax. It's used in a few projects like Istio and Firebase for this purpose. Also, I'm confident this will come up, but as much as I like WebAssembly, it is overkill for this use case. Message transformation would be a different story though ;)

As @artursouza mentioned, another consideration is where this filtering mechanism lives and where the filter expressions are configured. I think the filtering code would live in `dapr/dapr` (not `dapr/components-contrib`). Maybe that part is obvious. :) Where expressions live is more ambiguous. Having them returned by the subscribe call would work but what if that should be a responsibility of the operator or be configuration driven? My sense is that expressions are configuration in disguise. Unfortunately, it is probably not a good idea to use the component's metadata for configuration because they can be shared by multiple applications. A component would have to be created for each application if they had different filter rules. This would work but is not an ideal (or scalable?) solution.

In the [6 month plan](https://github.com/dapr/dapr/issues/2882) (no issue for this yet), there is mention of a configuration component that would apply at the application scope. This would be the ideal place for the developer to configure filtering rules but also subscriptions as well (since that is really configuration also). I propose waiting to implement this until after the configuration component exists. Maybe this is rationale for prioritizing it sooner than 6 months ;) I'd hate to see a short term solution implemented only to have it deprecated shortly after.

If we want to proceed with this now, there are two approaches above that could work. @jigargandhi can you think of any others?

Lastly, I was curious if others share the following opinion. I believe developers should prefer filtering based on `type` and other cloud event fields and **avoid** filtering based on specific topic names (I can elaborate on why if needed). This thinking could influence the design as the configuration of topics and filters _may not_ be directly coupled. For Dapr, this might be over engineering the solution, but curious if others think about this the same way.

Overall, my feeling is that this feature needs to be simple both in implementation and usage. Unless users really want more stream processing-like features, anything "complex" should be handled by the application.

**Comment by artursouza** [comment]
I agree to consider CEL instead of JsonPath.

Regarding the 'data' attribute. In CloudEvent spec, data attribute is a JsonObject, so filtering based on `data` is the same as filtering by any other field in the cloud  event - we might be able to lazy load this (like @pkedy  mentioned) but not 100% sure at this point.

In general terms, I agree to almost everything @pkedy mentioned, except the "waiting" part. This feature should not wait for the app config feature (MO) because we have enough people waiting for this filter feature. Second, I don't think the `/dapr/subscribe` callback will go away anytime soon. Some developers might prefer it over the app config.

**Comment by pkedy** [comment]
Having looked at this a bit more I think the easiest solution is to add an optional `Filter` field to the `Subscription` struct. Decoupling the concept of topic and filtering/processing get very complicated very fast ;)

**Comment by rynowak** [comment]
> Lastly, I was curious if others share the following opinion. I believe developers should prefer filtering based on type and other cloud event fields and avoid filtering based on specific topic names (I can elaborate on why if needed). This thinking could influence the design as the configuration of topics and filters may not be directly coupled. For Dapr, this might be over engineering the solution, but curious if others think about this the same way.

Personally I've seen this kind of topic come up over and over again during my work in the web framework space. Typical places where this would come up with be things like versioning, or A/B testing - basically anywhere you want to apply routing rules based on policy.

Like a cloud event, HTTP requests are also separated into **envelope** and **payload**. It's always better for everyone if you can do your filtering based on the envelope (headers or URL in HTTP) or other fields of the cloud event besides `data` in cloud events. 

It's typically better for the app developer to make metadata part of the metadata rather than a business object.

It's better for the runtime because it's more efficient, metadata is optimized for this kind of thing.

It's typically just overall simpler if you avoid building a rule engine that can avoid inspecting arbitrary content (consider non-JSON data payloads).

**Comment by pkedy** [comment]
In the case with pubsub you might think of it as three layers:

1) topic / broker
2) envelope (cloud event wrapper)
3) payload (cloud event `data` field)

What I was trying suggest was that you should try to leverage envelope/cloud event fields primarily, the payload only if needed, but **don't** use topic/broker level information **for filtering** if possible. I think @rynowak and I are aligned on that. :)

**Comment by daixiang0** [comment]
@artursouza please help add label to remove stale.

**Comment by pkedy** [comment]
Here is a proposal to satisfy filtering using a routing approach. It extends the existing Subscription CRD by adding the ability to specify multiple routing rules.

For context, the current CRD is structured like this and allows for a single topic subscription. `scopes` are the list of Dapr application IDs that use this subscription. The fields of importance are `pubsubname`, `topic`, and `route`. Also worth noting that #3380 adds `metadata`.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  route: /dsstatus # To become optional
scopes:
  - app1
  - app2
```

The enhancement to the CRD involves making `route` optional and adding a `routes` list (one of the two is required at runtime). Each route specifies a `match` that leverages a [CEL](https://opensource.google/projects/cel) expression to determine if the cloud event matches an expected condition the `route` is expecting. The large majority of use cases will route based only on `event.type`, but CEL allows for other cloud event fields (possibly including the data payload).

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  routes: # New field listing simple routing rules
    - match: event.type == "rebels.attacking.v2"
      route: /dsstatus.v2
    - match: event.type == "rebels.attacking.v3"
      route: /dsstatus.v3
scopes:
  - app1
  - app2
```

This would be added as an experimental feature, so parts like CEL could be replaced if needed. **However, it is important to call out that changes to the CRD are more permanent**. An enhancement for Dead Letter Queue support would extend this CRD even further. If we reverse or make breaking changes to the structure in the future, the schema will need to be versioned. Dapr does not handle multiple versions of CRDs so the YAML structure is important to consider now so we can avoid versioning the CRD.

**Comment by artursouza** [comment]
@pkedy LGTM.

**Comment by yaron2** [comment]
Preliminary thoughts:

I like the usage of CEL, it also has parity with the Knative Cloud Event filtering mechanism and other components.

I have concerns regarding the following:

1. Versioning - making a field in a CRD optional in order to support backward compatibility isn't a good practice. It's also confusing for users as the schema will be open to interpretation without reading a matching description that explains the usage. If we do go down this path, we should probably introduce `dapr.io/v2alpha1` for the `Subscription` CRD.
2. Subscribers can use either Subscription CRDs or do it programatically. We need a solution for programmatic subscriptions that will idealy be in schema parity with the CRD's `.spec` section (as it is today).
3. The crux of the issue here is really the addition of the `match` field. It's not clear to me why we need a collection of routes to support this change?

**Comment by pkedy** [comment]
1. I wouldn't think that having a field go from "required" to "optional" is a breaking change... Seems legit in JSON schema, Right?
2. The above would works with programmatic solution as well and has party with the `.spec` (already have that coded).
3. The reason for a collection of routes is avoid being "stuck" with a single filter. In practice, on Day 1 you might only handle 1 event type/filter, but on Day 10 that may expand into several event types/conditions.

The above CRD is my preferred option but here is an alternative CRD using the same scenario.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscriptionV2
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  route: /dsstatus.v2
  filter: event.type == "rebels.attacking.v2"
  routingname: rebelsAttackingV2 # Sent to gRPC
scopes:
  - app1
  - app2
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscriptionV3
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  route: /dsstatus.v3
  filter: event.type == "rebels.attacking.v3"
  routingname: rebelsAttackingV3 # Sent to gRPC
scopes:
  - app1
  - app2
```

The change to the `runtime` package is mainly to tweak the de-duping logic so that multiple pubsub/topic with unique filters can exist. Having the `routingname` specifically to support gRPC still feel icky to me...  all this to avoid having to filter in code :)

**Comment by msfussell** [comment]
@pkedy - Can you also provide programmatic example of the above proposal?

Also for my understanding, given a cloud event like this https://github.com/cloudevents/spec/blob/master/spec.md#example can you do filter on both the CloudEvent envelop as well as the data? It would be useful to see more examples (especially for data) so that we are clear on the scope. In the example above is "event.type" equivalent to the "type" field in the CloudEvent envelope?

**Comment by artursouza** [comment]
@pkedy @pkedy Looking into `routes.name`, it would cause confusion to have the gRPC differentiation in the schema. We can reuse the route itself into the gRPC implementation as we do today. Regarding versioning, I am a little bit iffy to reuse the current version for this change. So, what if we leave the current version for the Subscription CRD untouched and introduce a new version here:

```yaml
apiVersion: dapr.io/v1alpha1 # the current version remains supported
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  route: /dsstatus # remains as-is, mandatory.
scopes:
  - app1
  - app2
 ---
apiVersion: dapr.io/v1alpha2 # new version
kind: Subscription
metadata:
  name: myevent-subscription2
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  routes: # New field listing simple routing rules
    - route:  /dsstatus.v2 # Sent to gRPC and HTTP
      match: event.type == "rebels.attacking.v2"
   - route:  /dsstatus.v3
      match: event.type == "rebels.attacking.v3"
scopes:
  - app1
  - app2
```

**Comment by yaron2** [comment]
> I wouldn't think that having a field go from "required" to "optional" is a breaking change... Seems legit in JSON schema, Right?

Right, but that's not what I wrote. As you wrote on the original proposal, the field was made optional to avoid a breaking change when introducing the `routes` collection, which it will do. However, a more accepted way to do it would be to utilize the versioning scheme of the CRD and create a new `dapr.io/v2alpha1`. That makes the scheme clearer to both developers and operators and will require no changes to existing CRDs for people wanting to try the new version.

I agree a collection of routes might make sense in some scenarios and is more flexible than a single one.
As @artursouza pointed out, the use of `routes[0].name` can be removed.

As @msfussell said, it would be beneficial to see the programmatic experience for this.

**Comment by artursouza** [comment]
OK, the new version would be v2alpha1 instead of v1alpha2 since the spec change is somewhat "significant".

**Comment by pkedy** [comment]
> In the example above is "event.type" equivalent to the "type" field in the CloudEvent envelope?

Correct.

> Also for my understanding, given a cloud event like this https://github.com/cloudevents/spec/blob/master/spec.md#example can you do filter on both the CloudEvent envelop as well as the data? It would be useful to see more examples (especially for data) so that we are clear on the scope.

Yes, this is absolutely possible and could be very powerful. That said, since the data would need to be decoded based on `datacontenttype`, I was leaning toward not supporting filtering on the contents of data initially. I'm on the fence because XML, JSON, MsgPack could all be supported easily since they are schema-less. However, it opens the door to building proper Codec support in Dapr, which would be nice in the future, but not essential right now. I sense that is your feeling as well, @msfussell, but I would like to know yours thoughts.

> Can you also provide programmatic examples of the above proposal?

Below are two options in Go using raw structs without the Go-SDK. @yaron2, my sense is that Option B is what you would consider to have schema parity what what we have today.

**Option A: Aligned with the v2alpha1**

```golang
type subscription struct {
    PubsubName string            `json:"pubsubname"`
    Topic      string            `json:"topic"`
    Route      string            `json:"route,omitempty"`
    Metadata   map[string]string `json:"metadata"`
    Routes     []routingRule     `json:"routes,omitempty"`
}

type routingRule struct {
    Match string `json:"match"`
    Route string `json:"route"`
}

// this handles /dapr/subscribe, which is called from dapr into this app.
// this returns the list of topics the app is subscribed to.
func configureSubscribeHandler(w http.ResponseWriter, _ *http.Request) {
    t := []subscription{
        // What we have today
        {
            PubsubName: "pubsub",
            Topic:      "deathStarStatusA",
            Route:      "/dsstatus",
            Metadata: map[string]string{
                "rawPayload": "true",
            },
        },
        // With routes
        {
            PubsubName: pubsubName,
            Topic:      pubsubB,
            Routes: []routingRule{
                {
                    Match: `event.type == "rebels.attacking.v2"`,
                    Route: "/dsstatus.v2",
                },
                {
                    Match: `event.type == "rebels.attacking.v3"`,
                    Route: "/dsstatus.v3",
                },
            },
        },
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(t)
}
```

**Option B: Aligned with the v1alpha1**

```golang
type subscription struct {
    PubsubName string            `json:"pubsubname"`
    Topic      string            `json:"topic"`
    Match      string            `json:"match,omitempty"`
    Route      string            `json:"route"`
    Metadata   map[string]string `json:"metadata"`
}

// this handles /dapr/subscribe, which is called from dapr into this app.
// this returns the list of topics the app is subscribed to.
func configureSubscribeHandler(w http.ResponseWriter, _ *http.Request) {
    t := []subscription{
        // What we have today
        {
            PubsubName: "pubsub",
            Topic:      "deathStarStatusA",
            Route:      "/dsstatus",
            Metadata: map[string]string{
                "rawPayload": "true",
            },
        },
        // With routes, two entries with the same pubsub/topic but different matches and routes
        {
            PubsubName: "pubsub",
            Topic:      "deathStarStatusB",
            Match:      `event.type == "rebels.attacking.v2"`,
            Route:      "/dsstatus.v2",
        },
        {
            PubsubName: "pubsub",
            Topic:      "deathStarStatusB",
            Match:      `event.type == "rebels.attacking.v3"`,
            Route:      "/dsstatus.v3",
        },
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(t)
}
```

/cc @artursouza

**Comment by artursouza** [comment]
For the programmatic API, I actually prefer Option B.

**Comment by msfussell** [comment]
The second programmatic option is easier to read IMO.

**Comment by yaron2** [comment]
> The second programmatic option is easier to read IMO.

+1.

**Comment by pkedy** [comment]
Just circling back on GitHub info from a verbal discussion. For now, we are using Option A because when `metadata` is involved, it is unclear how to normalize the subscriptions. Option B assumed only keying off `pubsubname` and `topic`. We will get more feedback on this.

**Comment by pkedy** [comment]
Here is the latest iteration on the CRD/YAML and `dapr/subscribe` structures based on feedback received.

`rules` are now nested under `routes` along with an optional `default` for path.

```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  pubsubname: pubsub
  topic: deathStarStatus
  routes:
    rules:
      - match: event.type == "rebels.attacking.v3"
        path: /dsstatus.v3
      - match: event.type == "rebels.attacking.v2"
        path: /dsstatus.v2
    default: /dsstatus
scopes:
  - app1
  - app2
```

`routes` encapsulation structure was added.

```golang
type subscription struct {
    PubsubName string            `json:"pubsubname"`
    Topic      string            `json:"topic"`
    Metadata   map[string]string `json:"metadata,omitempty"`
    Routes     routes            `json:"routes"`
}

type routes struct {
    Rules   []rule `json:"rules,omitempty"`
    Default string `json:"default,omitempty"`
}

type rule struct {
    Match string `json:"match"`
    Path  string `json:"path"`
}

// This handles /dapr/subscribe
func configureSubscribeHandler(w http.ResponseWriter, _ *http.Request) {
    t := []subscription{
        {
            PubsubName: "pubsub",
            Topic:      "deathStarStatus",
            Routes: routes{
                Rules: []rule{
                    {
                        Match: `event.type == "rebels.attacking.v3"`,
                        Path:  "/dsstatus.v3",
                    },
                    {
                        Match: `event.type == "rebels.attacking.v2"`,
                        Path:  "/dsstatus.v2",
                    },
                },
                Default: "/dsstatus",
            },
        },
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(t)
}
```
