### ISSUE TITLE
dapr-sidecar-injector fails to make requests to tunnelfront service on AKS

### ISSUE THREAD

**Issue by onatm** [dapr/dapr#2595]
## In what area(s)?

/area runtime

## What version of Dapr?

1.0.0-rc.1

## Expected Behavior

dapr-sidecar-injector should not make any requests to tunnelfront on AKS.

## Actual Behavior

This is a really interesting problem we faced last week. AKS support has a theory that this issue happened because something wasn't ready in the system but they are not sure.

dapr-sidecar-injector makes requests to tunnelfront service and gets 'TLS handshake error from xxx.xxx.xxx.xxx:XXXXX: remote error: tls: bad certificate' error.

AFAIK, tunnelfront is used to enable `kubectl logs` and `kubectl exec` and I cannot see any reason why would dapr-sidecar-injector make any requests to it.

## Steps to Reproduce the Problem

We use `terraform` to provision a new AKS cluster and use `fluxcd` to deploy 3rd party helm charts (e.g. dapr, linkerd) and our own applications. `linkerd` is used for mTLS and `dapr` is only used for service discovery and message bus purposes. There are no networking policies in the system. You can find our dapr `helmrelease` config below:

```yaml
# snip
  values:
    global:
      mtls:
        # use only linkerd for mTLS
        enabled: false
    dapr_placement:
      replicaCount: 0
    dapr_sentry:
      replicaCount: 0
    dapr_dashboard:
      replicaCount: 0
```

## Release Note

RELEASE NOTE: **FIX** Do not make requests to tunnelfront on AKS
