### ISSUE TITLE
Uppercase middleware is not loaded

### ISSUE THREAD

**Issue by RadoslavGatev** [dapr/dapr#2602]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.11.3, Standalone mode

## Expected Behavior

As per the [middleware documentation](https://docs.dapr.io/concepts/middleware-concept/) state, the component of middleware.http.uppercase is pre-registered. When included in a middleware pipeline it should convert the request body to upper case. 

## Actual Behavior

The request body is not converted to upper case unless I define the component myself.
Logs:
time="2020-12-20T22:54:58.2383957+02:00" level=warning msg="failed to build HTTP pipeline: couldn't find middleware component with name uppercase and type middleware.http.uppercase" app_id=testapp instance=RGATEV-PC scope=dapr.runtime type=log ver=0.11.3

## Steps to Reproduce the Problem

1. Define a Dapr configuration the references the uppercase middleware:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipelineconfig
  namespace: default
spec:
  httpPipeline:
    handlers:
    - name: uppercase
      type: middleware.http.uppercase
```
2. Make sure to reference the config file when calling dapr run
dapr run --app-id testapp --app-port 5000 --dapr-http-port 3500 --components-path ..\components\ --config .\pipelineconfig.yaml dotnet run
3. Validate the casing of the incoming HTTP Body.

## Release Note

RELEASE NOTE: **FIX** The middleware.http.uppercase middleware comes pre-registered in Standalone mode.

**Comment by yaron2** [comment]
@RadoslavGatev did you also put this file in your components?

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: uppercase
spec:
  ignoreErrors: true
  type: middleware.http.uppercase
  metadata:
    - name: scopes
      value: "*"
```
