### ISSUE TITLE
Secret API "bulk" http endpoint does not work 

### ISSUE THREAD

**Issue by cmendible** [dapr/dapr#2649]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

v0.11.0-292-g8b9103b8

## Expected Behavior

Making a request to /v1.0/secrets/{secretStoreName}/bulk enpoint should work

## Actual Behavior

Making a request to /v1.0/secrets/{secretStoreName}/bulk enpoint results in:

 `{"errorCode":"ERR_STATE_GET","message":"secret bulk not found"}`

## Steps to Reproduce the Problem

Create a secrets.json file with the following components:

``` json
{
    "mysecret": "abcd",
    "connectionStrings": {
        "sql": "your sql connection string",
        "mysql": "your mysql connection string"
    }
}
```

Create a secretstore component (i.e. secrets.yaml):

``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
  namespace: default
spec:
  type: secretstores.local.file
  metadata:
  - name: secretsFile
    value: ./components/secrets.json
  - name: nestedSeparator
    value: ":"
```

Run:

``` shell
dapr run -d ./components/ -H 3500
curl localhost:3500/v1.0/secrets/localsecretstore/bulk
```

## Release Note

RELEASE NOTE:
