### ISSUE TITLE
Helm charts rendered output contains invalid YAML, with values ignored by Kubernetes

### ISSUE THREAD

**Issue by cuongvo** [dapr/dapr#2752]
## In what area(s)?
 /area helm chart
## What version of Dapr?
master branch

## Expected Behavior

The rendered output of the Helm chart is valid YAML and its values used by Kubernetes as intended. The YAML can also be used for post-renderer processing with Helm v3 if patching is required as outlined [here](https://helm.sh/docs/topics/advanced/).

## Actual Behavior

The YAML produced by the Dapr Helm chart contains duplicated keys based on the template's conditional logic. This is processed by Kubernetes successfully, but the duplicated keys are merged where the last defined key's value wins.

Due to this invalid YAML, YAML parsers used by tools like Kustomize are unable to parse the rendered output.

## Steps to Reproduce the Problem

- `helm install dapr dapr/dapr --namespace dapr-system --version 1.0.0-rc.3 --set global.ha.enabled=true --dry-run --debug > output.yaml`
- In `output.yaml` Notice the duplicate keys for `affinity`:

```yaml
...

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dapr-operator
            topologyKey: "kubernetes.io/hostname"
...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
```

This connects directly to the logic defined in the chart templates [here](https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_operator/templates/dapr_operator_deployment.yaml#L32-L43), for example. In that case, when HA is enabled, an additional `affinity` key is added. The `affinity` key is then defined again [here](https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_operator/templates/dapr_operator_deployment.yaml#L108-L121). With HA enabled, the first `affinity` value is overwritten and that conditional logic ignored.

In our cluster we can see this:
`kubectl get pod dapr-operator-... -o yaml -n dapr-system`:

```
...
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  containers:
  - args:
    - --log-level
    - info
    - --log-as-json
    - --enable-metrics
    - --metrics-port
    - "9090"
    command:
    - /operator
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: docker.io/daprio/dapr:1.0.0-rc.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: dapr-operator
    ports:
    - containerPort: 6500
      protocol: TCP
    - containerPort: 9090
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/dapr/credentials
      name: credentials
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: dapr-operator-token-fljhr
      readOnly: true
  dnsPolicy: ClusterFirst
...
```

Only the value last defined in the file is included, not the merged value as expected.

The same occurs in the `dapr_sidecar_injector_deployment` template [here](https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_sidecar_injector/templates/dapr_sidecar_injector_deployment.yaml#L65-L82):

```yaml
{{- if eq .Values.global.daprControlPlaneOs "linux" }}
        securityContext:
          runAsUser: 1000
{{- end }}
        command:
        - "/injector"
        args:
        - "--log-level"
        - {{ .Values.logLevel }}
{{- if eq .Values.global.logAsJson true }}
        - "--log-as-json"
{{- end }}
        - "--metrics-port"
        - "{{ .Values.global.prometheus.port }}"
{{- if eq .Values.global.daprControlPlaneOs "linux" }}
        securityContext:
          runAsNonRoot: {{ .Values.runAsNonRoot }}
{{- end }}
```

This time the same conditional is used to define the same key twice for `securityContext`. The first value of `runAsUser: 1000` is ignored:

Checking our cluster, we see it's true:

```
    resources: {}
    securityContext:
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
```

## Release Note

RELEASE NOTE:
