### ISSUE TITLE
Sidecar injector TLS handshake error

### ISSUE THREAD

**Issue by veselfil** [dapr/dapr#2783]
## In what area(s)?

/area runtime

## What version of Dapr?

1.0.0-rc1

## Expected Behavior

The DAPR runtime should refresh any TLS certificates it needs to function.

## Actual Behavior

DAPR Sidecar Injector stopped working (stopped injecting sidecars, 0 restarts on the pod) after ~9 days of running. All 3 replicas failed simultaneously. We have mTLS disabled on the deployment.

Restarting the dapr-sidecar-injector deployment has resolved the issue, but presumably only temporarily.

## Steps to Reproduce the Problem

I unfortunately do not have any reproduction steps other than install DAPR and wait. The last time that this has happened our deployment has been running for roughly 8-9 days.

Here's our HelmRelease file with the configuration we use.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  releaseName: dapr
  interval: 5m
  chart:
    # Chart: https://github.com/dapr/dapr/tree/master/charts/dapr
    spec:
      sourceRef:
        kind: HelmRepository
        name: acr
        namespace: gotk-system
      chart: dapr
      version: 1.0.0-rc.1
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    global:
      registry: # our container registry
      logAsJson: true
      mtls:
        enabled: false
      ha:
        enabled: true
    dapr_placement:
      logLevel: 'debug'
    dapr_sidecar_injector:
      logLevel: 'debug'
    dapr_operator:
      logLevel: 'debug'
    dapr_dashboard:
      replicaCount: 1
      logLevel: info
      image:
        registry: # our container registry
        image: dashboard
        tag: '0.3.0'
      ports:
        protocol: TCP
        port: 80
        targetPort: 8080
```

## Release Note

RELEASE NOTE: **FIX**: TLS handshake bug
