### ISSUE TITLE
Daprd fails to initialize when a serviceAccountName is set on the pod

### ISSUE THREAD

**Issue by SahajR** [dapr/dapr#2858]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What roles and permissions must be set on the serviceAccount for daprd to initialize?

I have a service account with permissions to read `secrets` named `quoti-app`, with the following role and binding set.
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: readSecrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readSecretsBinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: quoti-app
    namespace: default
roleRef:
  kind: Role
  name: readSecrets
  apiGroup: rbac.authorization.k8s.io
```

When I deploy a pod with the `serviceAccountName` set to `quot-app`, 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-trigger
  namespace: default
  labels:
    app: email-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-trigger
  template:
    metadata:
      labels:
        app: email-trigger
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "trigger"
        dapr.io/app-port: "8081"
    spec:
      serviceAccountName: quoti-app
      containers:
      - name: app
        image: xxx/xxx
        imagePullPolicy: Always

```

I get the following output, and the container is errored out:

```
kubectl logs mailer-7f7b6cbd95-48v2l --container daprd
time="2021-02-27T14:37:38.032261018Z" level=info msg="starting Dapr Runtime -- version 1.0.0 -- commit 6314733" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.03229517Z" level=info msg="log level set to: debug" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.03259333Z" level=info msg="metrics server started on :9090/" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.metrics type=log ver=1.0.0
time="2021-02-27T14:37:38.032615022Z" level=info msg="loading default configuration" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.032645331Z" level=info msg="kubernetes mode configured" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.032653921Z" level=info msg="app id: email" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.032821199Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.033047967Z" level=info msg="Initialized name resolution to kubernetes" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.033508489Z" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0
time="2021-02-27T14:37:38.034559062Z" level=fatal msg="process component kubernetes error: stat /home/nonroot/.kube/config: no such file or directory" app_id=email instance=mailer-7f7b6cbd95-48v2l scope=dapr.runtime type=log ver=1.0.0

```

I'm trying to set the service account on a mailer pod that has access to SES permissions. The service account is setup correctly on IAM. When I remove the `serviceAccountName` from the pod definition, the pod goes into the `RUNNING` state. I'm guessing the service account is affecting daprd in bootstrapping, so I'm curious about the required roles to be set.
