### ISSUE TITLE
Multiple race conditions when deploying any dapr application to Kubernetes

### ISSUE THREAD

**Issue by yoDon** [dapr/dapr#2861]
## In what area(s)?

/area runtime
/area operator
/area docs
/area test-and-release

## What version of Dapr?

1.0

## Expected Behavior

Scripted dapr kubernetes deployments should just work without hacky sleep statements

## Actual Behavior

Scripted dapr kubernetes deployments fail without multiple hacky sleep statements

## Steps to Reproduce the Problem

First, create this yaml file which condenses the [Hello-Kubernetes Quickstart](https://github.com/dapr/quickstarts/tree/master/hello-kubernetes) into a single yaml file format (just carrying over the echo server, not bothering with the python caller)

- Filename: `./hello-kubernetes.yaml`
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  # These settings will work out of the box if you use `helm install
  # bitnami/redis`.  If you have your own setup, replace
  # `redis-master:6379` with your own Redis master address, and the
  # Redis password with your own Secret's name. For more information,
  # see https://docs.dapr.io/operations/components/component-secrets .
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes
---
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
```

Next paste all the following commands into a terminal window to execute them as a single operation while being able to monitor the output. With the sleeps present, the script succeeds. If you comment out any of the sleeps, it will hit a race condition and commonly fail. The first sleep, after the `dapr init -k`, is followed by a slow enough process here that in this script it rarely triggers a crash but I believe there's still a potential for a race condition there too (happy to be proven wrong on that one, the others I've been able to watch crash due to race conditions on my machine).

Note that I'm running on a Windows PC and Windows doesn't have a `/bin/sleep` command so I'm using the standard Windows hack of `ping -n 6 127.0.0.1 > NUL` as my sleep command. `ping -n 6` delays for 5 seconds because `ping` waits for 1 second between attempts. `ping -n 11` waits for 10 seconds, etc. If you're running on Linux or WSL 2 you'll obviously want to swap the pings for sleep.

```bash
# NOTE: We need to wait for dapr containers to start running after dapr init -k.
# If we dapr status -k immediately after dapr init -k, status will panic with
# panic: runtime error: index out of range [0] with length 0
# If we wait a bit longer (but still not long enough) dapr status -k will report
# containers are Waiting (ContainerCreating). We want to wait until 
# status -k reports the containers are running before continuing the install.

dapr init -k
ping -n 6 127.0.0.1 > NUL
dapr status -k

# NOTE: We need to wait for helm to finish installing redis before deploying
# our pods to dapr. If we try to deploy our dapr pods before the 
# redis state pod is running, our dapr pods will launch into an error state.

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install redis bitnami/redis
ping -n 11 127.0.0.1 > NUL
kubectl get pods 

# NOTE: We need to wait after our yaml deployment to give the new dapr pods 
# time to start running before trying to check that curl localhost/ports
# returns valid data and before trying to access dapr services (which will 
# not have received the DAPR_HTTP_PORT and DAPR_GRPC_PORT if we hit them
# too soon and hence will crash when called)

kubectl apply -f ./hello-kubernetes.yaml
ping -n 11 127.0.0.1 > NUL
kubectl get pods
kubectl get svc
curl localhost/ports
curl --request POST --data "{\"data\": { \"orderId\": \"42\" } }" --header "Content-Type:application/json" http://localhost:80/neworder
kubectl logs --selector=app=node -c node
curl http://localhost:80/order

# NOTE: Always cleanup after running tests. Normally we don't need
# to wait for all the pods and services to be be fully removed but
# when doing repeated runs of this script to look for race conditions
# it's important to make sure we're always starting from a know clean state.

kubectl delete -f ./hello-kubernetes.yaml
helm uninstall redis
dapr uninstall -k
kubectl get all -A
ping -n 31 127.0.0.1 > NUL
kubectl get all -A

```

At a minimum, I recommend calling out the potential for race conditions in the dapr docs. If possible, I recommend adding a general purpose `dapr wait -k` command that waits for operations to complete so the dapr.

I'll also add a few additional error messages here that get triggered by these race conditions in case they help anyone find this issue via search terms:

``
{ FetchError: request to http://localhost:undefined/v1.0/state/statestore failed, reason: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'FetchError',
  message: 'request to http://localhost:undefined/v1.0/state/statestore failed, reason: connect ECONNREFUSED 127.0.0.1:80',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
``
