### ISSUE TITLE
Zipkin tracing not working in docker-compose

### ISSUE THREAD

**Issue by the-virt** [dapr/dapr#2939]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

Traces that should have been sent by dapr runtime to zipkin server somehow fails to reach it. What am I doing wrong?

The situation is the following:

I'm using Docker Desktop on my Windows PC. I have downloaded the sample from dapr repository (https://github.com/dapr/samples/tree/master/hello-docker-compose) which runs perfectly out of the box with docker-compose up.

Then I've added Zipkin support as per dapr documentation:

added this service in the bottom of docker-compose.yml
```
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - hello-dapr 
```
added config.yaml in components folder
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprsystem
spec:
  mtls:
    enabled: false
  tracing:
    enabled: true
    exporterType: zipkin
    samplingRate: "1"
    expandParams: true
    includeBody: true
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"    
```

When application runs, it should send traces to the zipkin server, but nothing is found in server UI.

Strange thing start to appear in the logs from nodeapp-dapr_1 service when I added tracing config: **error while reading spiffe id from client cert**

```
pythonapp-dapr_1  | time="2021-03-15T19:14:17.9654602Z" level=debug msg="found mDNS IPv4 address in cache: 172.19.0.7:34549" app_id=pythonapp instance=ce32220407e2 scope=dapr.contrib type=log ver=edge
nodeapp-dapr_1    | time="2021-03-15T19:14:17.9661792Z" level=debug msg="error while reading spiffe id from client cert: unable to retrieve peer auth info. applying default global policy action" app_id=nodeapp instance=773c486b5aac scope=dapr.runtime.grpc.api type=log ver=edge
nodeapp_1         | Got a new order! Order ID: 947
nodeapp_1         | Successfully persisted state.
```
Additional info - current dapr version used is 1.0.1. I made sure that security (mtls) is disabled in config file.
