### ISSUE TITLE
Add Opt-in for Preview Features

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#3048]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature
Going forward, features in dapr may first be released as a preview feature. The runtime needs a method to opt-in to these features for both standalone and kubernetes. 

The first feature that will be previewed is Actor Reentrancy #2901 

## Release Note

RELEASE NOTE: **ADD** Opt-in for preview features

## High Level Overview

- Enabled features are specified via the standard dapr configuration
- Features can be enabled/disabled individually
- Applications can specify which features are enabled individually or reference a common configuration

## Sample Configuration
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  features:
  - name: Actor.Reentrancy
    enabled: true
  - name: Feature2
    enabled: false
```

### Local
For local dapr, the configuration can be specified when running an application. 

```
dapr run --app-id nodeapp --dapr-http-port 3500 --app-port 3000 --config ./feature_config.yaml node app.js
```

### Kubernetes
For kubernetes, the configuration can be referenced once it is created as a component and then referenced in the application's configuration. Multiple applications can reference the same configuration or they can each deploy with their own.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: featureconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  features:
    - name: Actor.Reentrancy
      enabled: true
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/config: "featureconfig"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
```

## Additional Work
While this provides the basis for how we can declare which features are/are not enabled, there should also be a function that allows users to query which features are enabled. Ideally this would exist in the CLI and just output what the configuration has specified.

**Comment by halspang** [comment]
@yaron2 can you assign this to me and add it to the 1.2 milestone?

**Comment by halspang** [comment]
## High Level Overview

- Enabled features are specified via the standard dapr configuration
- Features can be enabled/disabled individually
- Applications can specify which features are enabled individually or reference a common configuration

## Sample Configuration
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  features:
  - name: Actor.Reentrancy
    enabled: true
  - name: Feature2
    enabled: false
```

## Applying the Configuration
### Local
For local dapr, the configuration can be specified when running an application. 

```
dapr run --app-id nodeapp --dapr-http-port 3500 --app-port 3000 --config ./feature_config.yaml node app.js
```

### Kubernetes
For kubernetes, the configuration can be referenced once it is created as a component and then referenced in the application's configuration. Multiple applications can reference the same configuration or they can each deploy with their own.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: featureconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  features:
    - name: Actor.Reentrancy
      enabled: true
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/config: "featureconfig"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
```

## Additional Work
While this provides the basis for how we can declare which features are/are not enabled, there should also be a function that allows users to query which features are enabled. Ideally this would exist in the CLI and just output what the configuration has specified.
