### ISSUE TITLE
Allow choosing which APIs are available on a sidecar

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3054]
In certain cases, users may want to choose which Dapr APIs are allowed access.
This might be used in low/no-trust environments and reduce an attack surface on a specific API.
In addition, this would allow operators and/or infosec teams to pursue an "enable what you use" philosophy, and comes handy in scenarios where an Ingress might expose the Dapr APIs to external consumers.

### Design proposal

To make this available on a per-sidecar basis, I propose to add a list of configurable APIs to the `Configuration` CRD, which can be referenced from one or more Dapr enabled apps.

Since the `Configuration` object is platform agnostic, this feature would naturally be supported on all hosting platforms. (today, Kubernetes and Self-Hosted).

#### New schema

Since the APIs are always known in advance, a list that explicitly sets which APIs are allowed is recommended and makes it clear to an observer holding any role (developer, operator etc.) to understand which APIs are available in this configuration.

The example below illustrates a configuration where  only`v1` of the State API is allowed:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myconfig
spec:
  api:
    allowed:
    - name: state
      version: v1.0
```

This example shows the equivalent for a gRPC service:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myconfig
spec:
  api:
    allowed:
    - name: state
      version: v1
```
