### ISSUE TITLE
openshift deployment

### ISSUE THREAD

**Issue by GeneralFox** [dapr/dapr#3069]
## In what area(s)?

> /area runtime
/area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
Hello to all,
I'm trying to install dapr for our development team under OpenShfit 4.7 with the helm chart.
Out of the box the chart doesn't work for OCP security enforcement however with some tuning on the permission ( oc adm policy add-scc-to-user nonroot -z dapr-operator -n dapr-system ) I was able to deploy the chart but I have failure on dapr-placement server:

_create Pod dapr-placement-server-0 in StatefulSet dapr-placement-server failed error: pods "dapr-placement-server-0" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000700000, 1000709999] spec.containers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]_

The simpler  way could be grant anyuid to dapr-operator service account but I've test that on a small test environment and this cause cluster failure ( control plane failure, operator redeploy, instability etc etc. )  that I'm currently investigating, but looking at the helm chart I've found in dapr_placement_deployment.yaml those line:

{{- if eq .Values.cluster.forceInMemoryLog true }}
          runAsNonRoot: {{ .Values.runAsNonRoot }}
{{- else }}
          runAsUser: 0

and I'm wondering if this is wanted.

Anyone else has tryed a deploy on OCP and can share some experience ?

**Comment by artursouza** [comment]
Creating a How To in dapr/docs repo for deploying to OpenShift would be a good outcome of this issue.

**Comment by HectorMeneses333** [comment]
Has anyone been able to deploy in openshift? 
I would like to give it a shot myself, but want to know if anyone has been successful already.

**Comment by sedat-eyuboglu** [comment]
This is an old issue but i want share our experiences:
#4051 pls. check this one. We saw an error while installing it on OKD and OCP. 
In our case open shift's olm manager service account was not in the list of allowed service accounts of dapr.
We deployed it in openshift accepting this result. And didn't see any critical result. But dapr injector continues to produce error messages.
We are not OCP expert but dapr behaves different in OCP.
If OCP is in the target platforms for dapr, there should be an openshift documentation and seperate tests for dapr on OCP.  Before OCP, we were using dapr in Rancher and didn't see such results.
Now, i am not sure which permissions we granted for dapr in OCP. We can query this and give feedback in this isue.

**Comment by Admiralkheir** [comment]
We gave some permission for sidecar injection and dapr components working
- gave system:openshift:scc:anyuid role to default service account in dapr-system
- gave cluster-admin cluster role to dapr-operator service account in dapr-system

**Comment by anobleperson** [comment]
A couple of other notes for OpenShift for the documentation
- DeploymentConfig workloads (OpenShift specific) don't work with dapr, it must be Deployment workloads. If DeploymentConfig is used, the sidecar won't be injected
- In order to give the permissions given by @Admiralkheir above, the following commands can be called
`oc policy add-role-to-user system:openshift:scc:anyuid -z default`
`oc policy add-role-to-user cluster-admin -z dapr-operator`

**Comment by cmoulliard** [comment]
I did a new end to end test and apparently we only need (till we better define it) to add this roleBinding 
```
oc policy add-role-to-user system:openshift:scc:anyuid -z dapr-operator
```

We have also to figure out how to fix such WARNINGS reported during the creation of some pods
```
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "node" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "node" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "node" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "node" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by cmoulliard** [comment]
> ```yaml
> dapr_sidecar_injector:
>   runAsNonRoot: true
> ```

I did what you proposed but then the daprd sidecar is not injected part by example of the nodeapp and dapr sidecar injector reports
```
2023/02/06 18:15:44 http: TLS handshake error from 172.17.33.19:38080: remote error: tls: bad certificate
2023/02/06 18:15:48 http: TLS handshake error from 172.17.33.19:38218: remote error: tls: bad certificate
```

**Comment by cmoulliard** [comment]
Not sure that all the pods can be launched as non root as the sidecar container is no injected within by example the nodeapp pod and sidecar_injector reports `2023/02/06 18:45:00 http: TLS handshake error from 172.17.33.19:38358: remote error: tls: bad certificate` @berndverst

**Comment by berndverst** [comment]
You'll have to play around with these settings - I am not familiar with the nuances of running as nonRoot and with pod security policies.

**Comment by cmoulliard** [comment]
We cannot use the `debug enabled` param of the `dapr sidecar injector` as deployment resource is reporting such an error
```
pods "dapr-sidecar-injector-6bf4997c8-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.capabilities.add: Invalid value: "SYS_PTRACE": capability may not be added, spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000900000, 1000909999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "ibm-restricted-scc": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "ibm-anyuid-scc": Forbidden: not usable by user or
```

**Comment by yaron2** [comment]
@cmoulliard can you uninstall Dapr and delete the namespace you installed it into? Then try to install again. It looks like there's a bad/missing TLS cert in the control plane namespace.

After you reinstall, if the same error repeats, can you paste the output of "kubectl get secrets -n dapr-system"? (If you installed in a different namespace, replace accordingly)

**Comment by cmoulliard** [comment]
> After you reinstall, if the same error repeats,

I cannot reproduce it this morning. So the only issue that we still have to fix is to setup a ocp scc able to run the pod in debug mode

**Comment by berndverst** [comment]
> Not sure that all the pods can be launched as non root as the sidecar container is no injected within by example the nodeapp pod and sidecar_injector reports `2023/02/06 18:45:00 http: TLS handshake error from 172.17.33.19:38358: remote error: tls: bad certificate` @berndverst  

FYI I ran into this issue today also - but in k3s (k3d) with the default helm chart settings.

This seems unrelated.

**Comment by cmoulliard** [comment]
> sidecar_injector reports `2023/02/06 18:45:00 http: TLS handshake error from 172.17.33.19:38358: remote error: tls: bad certificate`

I suggest to open a ticket to investigate separately (from this ticket) the TLS handshake issue as this is really painful and should be fixed as the error is blocking. WDYT ? @berndverst

**Comment by davidkarlsen** [comment]
> dapr_dashboard:
>   runAsNonRoot: true
> dapr_placement:
>   runAsNonRoot: true
> dapr_operator:
>   runAsNonRoot: true
> dapr_sentry:
>   runAsNonRoot: true
> dapr_sidecar_injector:
>   runAsNonRoot: true
> global:
>   logAsJson: true

Then I get:
time="2025-11-29T15:01:15.961835882Z" level=fatal msg="error creating operator: current user UID/GID (1001460000:0) does not match the required UID/GID (65532:65532). Dapr must be run as a non-root user 65532:65532 in Kubernetes environments. To override this check, set the environment variable 'DAPR_UNSAFE_SKIP_CONTAINER_UID_GID_CHECK=true'" instance=dapr-operator-f44778c5c-jxf2v scope=dapr.operator type=log ver=1.16.1

is it possible to run dapr with un-privileged user?

**Comment by yaron2** [comment]
@davidkarlsen  Can you try applying this?

```yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dapr-scc
runAsUser:
  type: MustRunAs
  uid: 65532
fsGroup:
  type: MustRunAs
  ranges:
  - min: 65532
    max: 65532
users:
  - system:serviceaccount:dapr-system:dapr-operator
```

```bash
oc apply -f dapr-scc.yaml

oc adm policy add-scc-to-user dapr-scc \
  -z dapr-operator \
  -n dapr-system
```

**Comment by davidkarlsen** [comment]
@yaron2 
Yeah, but we avoid special SCCs and prefer the built-in restricted default ones, this magic mix works :):
```yaml 
kind: DaprInstance
apiVersion: operator.dapr.io/v1alpha1
metadata:
  name: dapr-instance
  namespace: dapr-system
spec:
  chart:
    version: "1.16.3"
  values:
    global:
      logAsJson: true
      #seccompProfile: RuntimeDefault
      extraEnvVars:
        DAPR_UNSAFE_SKIP_CONTAINER_UID_GID_CHECK: "true"
    dapr_sidecar_injector:
      extraEnvVars:
        DAPR_UNSAFE_SKIP_CONTAINER_UID_GID_CHECK: "true"
    dapr_operator:
      extraEnvVars:
        DAPR_UNSAFE_SKIP_CONTAINER_UID_GID_CHECK: "true"
    dapr_sentry:
      extraEnvVars:
        DAPR_UNSAFE_SKIP_CONTAINER_UID_GID_CHECK: "true"

```

and also to avoid crashloop on OOM on operator:
```yaml
cat dapr-kubernetes-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dapr-kubernetes-operator
  namespace: dapr-system
spec:
  channel: alpha
  installPlanApproval: Manual
  name: dapr-kubernetes-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: dapr-kubernetes-operator.v0.0.12
  config:
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        cpu: 500m
        memory: 1Gi%
```

edit - forgot I had actually done something similar:
```yaml
cat rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-anyuid
  namespace: dapr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: Group
  name: system:serviceaccounts:dapr-system
```

Can't these pods run with a random uid? Seems to only affect the stateful sets:

```shell
k get sts
NAME                    READY   AGE
dapr-placement-server   0/1     4d20h
dapr-scheduler-server   0/3     4d20h
 dapr-system  k get deployment
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
dapr-control-plane      1/1     1            1           4d20h
dapr-operator           1/1     1            1           4d20h
dapr-sentry             1/1     1            1           4d20h
dapr-sidecar-injector   1/1     1            1           4d20h
```
