### ISSUE TITLE
read items from Azure Event Hub with Dapr Binding

### ISSUE THREAD

**Issue by jthin** [dapr/dapr#3086]
## In what area(s)?
/area docs
/area runtime

## What version of Dapr?
- Actual Dapr Runtime: 1.1.2

## Description
For test purpose, I am using Dapr binding with Azure Event Hub to read items. (I don't want to use pub/sub because a service will push item in Event Hub).
According to documentation, *partitionID* is optional in Dapr component manifest. But when I run `dapr run` command, I have the following error: 
```
time="2021-04-21T19:43:25.8626279+02:00" level=error msg="error reading from input binding demo-binding: illegal base64 data at input byte 24" app_id=demo instance=xxx scope=dapr.runtime type=log ver=1.1.2
Updating metadata for app command: node app.js
You're up and running! Both Dapr and your app logs will appear here.
```
and nothing happens after.

With *partitionID* declared, I run my app without problem and I can read items in Azure Event Hub:
```
time="2021-04-21T19:47:01.3262842+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=demo instance=MYMACHINE scope=dapr.runtime.actor type=log ver=1.1.2
time="2021-04-21T19:47:01.3268428+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 40.567899999999995ms" app_id=demo instance=MYMACHINE scope=dapr.runtime type=log ver=1.1.2
time="2021-04-21T19:47:01.3471984+02:00" level=info msg="placement tables updated, version: 0" app_id=demo instance=MYMACHINE scope=dapr.runtime.actor.internal.placement type=log ver=1.1.2
Updating metadata for app command: node app.js
You're up and running! Both Dapr and your app logs will appear here.

time="2021-04-21T19:47:01.6520667+02:00" level=info msg="eventhubs: using consumer group demo" app_id=demo instance=MYMACHINE scope=dapr.contrib type=log ver=1.1.2
time="2021-04-21T19:47:01.6520667+02:00" level=info msg="eventhubs: using partition id 0" app_id=demo instance=MYMACHINE scope=dapr.contrib type=log ver=1.1.2
== APP == /demo-binding invoked
== APP == OK
== APP == /demo-binding invoked
== APP == OK
```

Here is my component manifest:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demo-binding
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://***.servicebus.windows.net/;SharedAccessKeyName=***;SharedAccessKey=***;EntityPath=***"
  - name: consumerGroup
    value: "demo"
  - name: storageAccountName
    value: "***"   
  - name: storageAccountKey
    value: "DefaultEndpointsProtocol=https;AccountName=***;AccountKey=***;EndpointSuffix=core.windows.net"                
  - name: storageContainerName
    value: "***"    
  - name: partitionID # (Optional) PartitionID to send and receive events
    value: 0
```

- Is it a typo in the doc? 
- When shall we specify the partitionID?

## Steps to Reproduce the Problem
- Create an application that read items from Azure Event Hub with Dapr component
- Test with `Dapr run` command or deploy on K8s
