### ISSUE TITLE
Prometheus is not colleting the Dapr Metrics

### ISSUE THREAD

**Issue by frvasquezjaquez** [dapr/dapr#3119]
## In what area(s)?

 /area runtime

## Ask your question here
I just deployed Dapr with the prometheus stack, but prometheus is not getting the Dapr apps metrics. i think that the darp service monitor is missing. should i create it? those steps are not described in the Dapr doc.

**Comment by yaron2** [comment]
@wcs1only can you assist here kindly?

**Comment by frvasquezjaquez** [comment]
> @wcs1only can you assist here kindly?

@wcs1only any doc that you can share?

**Comment by frvasquezjaquez** [comment]
I was able to solve the issue, i had to create a service monitor to scrape the dapr metrics.

When using the prometheus operator or prometheus stack helm charts, you have to follow the following steps:

1. Apply the `prometheus operator` with the following `values.yaml`.
  ```
  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    prometheus:
      serviceMonitorSelector:
        matchExpressions:
        - key: serviceapp
          operator: Exists
  ```

2. Create a service monitor to scrape the sidecars metrics.
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: dapr-servicemonitor
    release: prometheus
  name: dapr-sidecar-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: dapr-metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      dapr.io/enabled: "true"
```
