### ISSUE TITLE
Http opa middleware crash

### ISSUE THREAD

**Issue by Amenocy** [dapr/dapr#3216]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

applying opa middleware should work

## Actual Behavior
app crashes 

with this error

![image](https://user-images.githubusercontent.com/2260390/119342743-2f56bb80-bc9e-11eb-9c8d-dd1a0ab044fb.png)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16bde9a]

goroutine 1 [running]:
github.com/dapr/dapr/pkg/middleware/http.Pipeline.Apply(0xc00000f0a0, 0x1, 0x1, 0xc0005a7720, 0x1)
        /home/runner/work/dapr/dapr/pkg/middleware/http/http_pipeline.go:26 +0x3a
github.com/dapr/dapr/pkg/http.(*server).useComponents(...)
        /home/runner/work/dapr/dapr/pkg/http/server.go:106
github.com/dapr/dapr/pkg/http.(*server).StartNonBlocking(0xc00069aa50)
        /home/runner/work/dapr/dapr/pkg/http/server.go:60 +0x67
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).startHTTPServer(0xc0000b4fc0, 0xdac, 0x1e61, 0x3b4d100, 0x1, 0xc00000f0a0, 0x1, 0x1)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:720 +0x4bc
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc0000b4fc0, 0xc00069a840, 0xa, 0xc00020fb10)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:324 +0x626
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc0000b4fc0, 0xc0008f3f40, 0x7, 0x7, 0x5f, 0xc000100000)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:204 +0x25e
main.main()
        /home/runner/work/dapr/dapr/cmd/daprd/main.go:134 +0xf9f
```

## Steps to Reproduce the Problem

adding OPA middleware on 1.1.2 

this is my config.yaml 
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  httpPipeline:
    handlers:
    - name: my-policy
      type: middleware.http.opa
```

and this is my component : 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-policy
  namespace: default
spec:
  type: middleware.http.opa
  version: v1
  metadata:
    - name: includedHeaders
      value: "x-my-custom-header, x-jwt-header, auth, auth-header"
    - name: defaultStatus
      value: 403
    - name: rego
      value: |
        package http
        default allow = true
```
## Release Note

RELEASE NOTE:
