### ISSUE TITLE
Add support for metadata in pub/sub subscription CRD

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3225]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

1.2

## Expected Behavior

Subscription CRD does not contain metadata map, like in the programmatic subscription payload.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  route: /dsstatus
  pubsubname: pubsub
  # metadata does not exist in the CRD.
scopes:
- app1
- app2
```

```Python
@app.route('/dapr/subscribe', methods=['GET'])
def subscribe():
    subscriptions = [{'pubsubname': 'pubsub',
                      'topic': 'deathStarStatus',
                      'route': 'dsstatus',
                      'metadata': {
                          'rawPayload': 'true',
                      } }]
    return jsonify(subscriptions)
```

## Actual Behavior

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  route: /dsstatus
  pubsubname: pubsub
  # metadata DOES exist in the CRD.
  metadata:
    name: rawPayload
    value: "true"
scopes:
- app1
- app2
```

## Steps to Reproduce the Problem

Try to use rawPayload feature in pubsub via the Subscription CRD.

## Release Note

RELEASE NOTE:

**Comment by pkedy** [comment]
I'm working on this right now and considering a small change to the YAML, specifically changing the metadata to a map instead of a list of name/value pairs. That makes it congruent to the API structure that exists now in the subscriptions callback. The only reason _not_ to make that change is if we wanted to use secrets in the metadata.

@yaron2 @artursouza can you think of a reason secrets would be used for this use case?

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  route: /dsstatus
  pubsubname: pubsub
  # metadata DOES exist in the CRD.
  metadata:
    rawPayload: "true".  # <--- Change here
scopes:
- app1
- app2
```
