### ISSUE TITLE
Unable to setup MongoDB cluster as statestore

### ISSUE THREAD

**Issue by nielsbauman** [dapr/dapr#3255]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

Hi there,

I'm trying to set up a MongoDB cluster as statestore in DAPR, but I can't get it to work.

I have the following `mongo.yaml` in my components directory:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongostate
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: xxxxx.mongodb.net:27017
  - name: username
    value: xxxxx
  - name: password
    value: xxxxx
```

I run the following command:
```
dapr run --app-id myapp --dapr-http-port 3500
```

And the error I'm getting is:
> process component mongostate error: init timeout for component mongostate exceeded after 5s  app_id=myapp instance=NIELS scope=dapr.runtime type=log ver=1.2.0

I was however able to get it working with a locally running docker container from mongo. I have also tried setting `operationTimeout` in the `mongo.yaml`, but that made no difference at all (it would still fail after 5 seconds). Last but not least, I am able to connect to the mongo cluster through the mongo shell _and_ through the mongo compass application.

What steps can I take to debug this further and hopefully resolve this?

Thanks in advance,

Niels
