### ISSUE TITLE
Service-to-service invocation fails in Kubernetes (AWS EKS)

### ISSUE THREAD

**Issue by djojoz** [dapr/dapr#3428]
## In what area(s)?

> /area runtime

> /area operator

/area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.2.x

## Expected Behavior

Service-to-service invocation through HTTP in Kubernetes deployments should work with no error.

## Actual Behavior

The http call returns:
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: my-app, err: failed to invoke target my-app after 3 retries"}
```

## Steps to Reproduce the Problem

I'm running Dapr on Kubernetes (Amazon EKS + Fargate).
I installed it using `dapr init -k --enable-mtls=false` (enabling mtls causes a different issue).
`dapr status -k` says that everything is running and healthy.
The sidecars are successfully injected to my deployments but I have an issue with service-to-service invocation. The http call returns:
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: my-app, err: failed to invoke target my-app after 3 retries"}
```
In debug mode, the logs on a sidecar show:
```
time="2021-07-11T21:33:24.960099188Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.dapr-system.svc.cluster.local:50005" app_id=api-gateway instance=deployment-api-gateway-test-5f987d4b77-fsxxp scope=dapr.runtime.actor.internal.placement type=log ver=1.2.0
time="2021-07-11T21:33:24.969458206Z" level=debug msg="error connecting to placement service: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=api-gateway instance=deployment-api-gateway-test-5f987d4b77-fsxxp scope=dapr.runtime.actor.internal.placement type=log ver=1.2.0
```
(the issue happens in both 1.2.0 and 1.2.2)

Here are the annotations on one of my deployments:
```
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: 'api-gateway'
        dapr.io/app-port: '3000'
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-delay-seconds: "60"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "60"
```
I made sure that `dapr.io/app-port` and `containerPort` are the same and extended liveness-probe as it is one of the recommended troubleshooting steps.

Service-to-service invocation works fine when I run on my local machine using `dapr run` and calling `http://localhost:{DAPR_HTTP_PORT}/v1.0/invoke/{SERVICE_NAME}/method`.

## Release Note

RELEASE NOTE:
