### ISSUE TITLE
Dapr sidecar keeps shutting itself down when deployed to container instances via az aks virtual node

### ISSUE THREAD

**Issue by WhoAteDaCake** [dapr/dapr#3464]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x

## Expected Behavior

Using dapr in combination with virtual-nodes on azure aks, should work

## Actual Behavior

Pod deployed via: 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/log-level: "debug"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: aci-helloworld
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
```

The dapr sidecard keeps shutting itself down: https://pastebin.com/kDNaXb9d

## Steps to Reproduce the Problem

`kubectl apply -f dapr-test.yml`

## Release Note

RELEASE NOTE:

Fix dapr sidecard shutdown in container instances
