### ISSUE TITLE
DaprClient not finding correct port to invoke call?

### ISSUE THREAD

**Issue by xavidram** [dapr/dapr#3474]
## In what area(s)?

/area runtime

## Background

I am trying to configure a multiple service project using `tye` and `dapr`. Following the documentation provided on both github repositories I landed on the following tye.yaml

This is the tye.yaml
```
name: sampleapp
extensions:
- name: dapr
  log-level: debug
services:
- name: clients
  project: src/Services/Clients.API/Clients.API.csproj
  bindings:
  - port: 3101
- name: attendants
  project: src/Services/Members.API/Members.API.csproj
  bindings:
  - port: 3102
- name: webapp
  project: src/Web/WebApp.UI/WebApp.UI.csproj
```

When running the yaml file. All containers spin up correctly. Dapr creates the sidecars for the `clients.api` and `members.api`. The webapp is served on port `5000` while the other two have their ports assigned.

The sidecars are given their own random port that tye finds and assigns. I can send a postman request via the invoke method to the sidecar as such `http://localhost:{client-sidecarport}/v1.0/invoke/clients/method/clients`  and I get the response data. I can even run a basic request to the `client.api` project as such: `http://localhost:3101/clients` and retrieve the same correct response.

In the webapp however I cannot. I have a blazor wasm web application and this is how I try to create the http client based on the documention.

`
builder.Services.AddScoped<IClientService, ClientService>(_ => new ClientService(DaprClient.CreateInvokeHttpClient("clients")));
`

In the ClientService I simply make an httpclient call to the endpoint:

```
public async Task<List<Client>> Get() {
	var clients =  await _http.GetFromJsonAsync<List<Client>>("clients");

	return clients;
}
```

When I look at the network request I see the following:

`http://localhost:3500/v1.0/invoke/clients/method/clients``

When looking at the dapr client source code I see that if no DAPR_HTTP_PORT variable is not found it defaults to port 3500, which I see is very common in the documentation for service invocation. But no where does someone define it. I know tye  will create the --dapr-http-port randomly. 

### Question

So finally the question. Does the DapperClient.CreateinvokeHttpClient("appid") go search for the dapr http port for the given appID? And should it be hard code defined somewhere? I am under the assumption that the dapr client would search the dapr run applications for the given ID and get the details from there.
