### ISSUE TITLE
Local Secret Store inconsistencies with Kubernetes Secret Store

### ISSUE THREAD

**Issue by greenie-msft** [dapr/dapr#3568]
## In what area(s)?

/area runtime

## What version of Dapr?

1.3

## Expected Behavior
Secretstores.local.file does not support a secret with multiple keys like k8s does: https://docs.dapr.io/reference/api/secrets_api/#response-with-multiple-keys-in-a-secret-eg-kubernetes.
```
Kubernetes Secret:
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  key1: value1
  key2: value2
```
Request: http://localhost:3500/v1.0/secrets/kubernetes/test-secret
 
 Returns: 
 ```{ "key1": "value1", "key2": "value2"}```

Secretstores.local.file with a secret with mulitple keys:
```
{
    "test-secret": {
          "key1": "value1",
          "key2": "value2"
    }
}
```
Request : http://localhost:3500/v1.0/secrets/localsecretstore/test-secret

Returns: 
```{"errorCode":"ERR_SECRET_GET","message":"failed getting secret with key test-secret from secret store localsecretstore: secret test not found"}```

This behavior causes developers to write conditional code depending on the secret-store/environment. 

## Actual Behavior

I would expect that the same request I make for a secret with multiple keys in k8s behaves similarly to a local secret store. 

## Steps to Reproduce the Problem

See above

## Release Note

RELEASE NOTE:
