### ISSUE TITLE
[Proposal] Resiliency policies across all building blocks

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#3586]
/area runtime
/area operator

The goal of this proposal is to create a mechanism where [resiliency patterns](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/application-resiliency-patterns) can be applied consistently configured across all Dapr building blocks.

Design goals are:

* Support high-value resiliency policies: Timeouts, [Retries/Back off](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry) and [Circuit Breakers](https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)
* Resiliency policies are configured at the application scope
* Compatibility across all component types and service invocation
* Developers must opt-in, default behavior is unchanged
* Policies can be configured with sane defaults
* Rules can be used to assign specific policies to Dapr API operation

Non-goals are:

* Distributed circuit breaking (additive feature)
* [Bulkheads](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead) and [Throttling](https://docs.microsoft.com/en-us/azure/architecture/patterns/throttling): These can be addressed by future proposals
* Fallback operations: These would be handled in code, not declaratively

Because this proposal targets many resiliency policy types and spans across all building blocks, it is related to several existing issues:

* #1820
* #3000
* #777
* #2716 (Required for timeouts & retry)

## Design

Even the simplest resiliency configuration can be 100+ lines of YAML. To prevent polluting the main configuration, a new `Resiliency` CRD is proposed in order to promote clear separation of concerns from other features like RBAC. It also creates a distinct boundary for SREs and architects to work in without worrying about impacting other aspects of the system. The new CRD has three main sections: **policies**, **buildingBlocks** and **apis**.

### Policy definition

The `policies` section is where timeout, retry and circuit breaker polices are defined. Each is given a name so they can be referred to from the `buildingBlocks` and `apis` sections.

#### Timeouts

Timeouts only require a duration expressed in [Go's time.Duration format](https://pkg.go.dev/time#ParseDuration).

#### Retries

Retries follow either a `constant` or `exponential` configuration with unique settings for each. These will be based on the existing [dapr/kit retry package](https://github.com/dapr/kit/tree/main/retry) which uses the popular `github.com/cenkalti/backoff` package.

Constant configuration:

| Field                     | Description                                 | Default   |
|---------------------------|---------------------------------------------|-----------|
| policy                    | Should be set to `constant`.                |           |
| duration                  | The duration between tries.                 | `0` meaning that retries are immediate |
| maxRetries                | Optional maximum number retries.            |                     |

Exponential back off configuration:

| Field                     | Description                                 | Default   |
|---------------------------|---------------------------------------------|-----------|
| policy                    | Should be set to `exponential`.             |           |
| initialInterval           | The initial retry interval.                 | `500ms`   |
| randomizationFactor       | The randomization factor for calculating the randomized interval. | `0.5`     |
| multiplier                | The multipler for the next retry interval.  | `1.5`     |
| maxInterval               | Caps the randomized retry interval.         | `60s`     |
| maxElapsedTime            | Caps the time spent retrying the operation. Setting this to `0` will try indefinitely.          | `15m`     |
| maxRetries                | Optional maximum number retries.            |           |

The calculation of the interval is:

```
Randomized interval = RetryInterval *
                      [range of 1 - RandomizationFactor to 1 + RandomizationFactor]
```

#### Circuit breakers

Circuit breakers are unique because they store temporal values for transitioning between closed, half open and open states. This means that instances of circuit breakers should be scoped to Dapr's building blocks (service invocation and components). This is a key difference compared to timeouts and retries which can be reused across several components. Because of this, circuit breaker configurations are treated as named templates and automatically instantiated for each building block used by the application.

Circuit breakers will leverage an existing, battle tested library such as [`github.com/sony/gobreaker`](https://github.com/sony/gobreaker). The configuration settings will likely be aligned with the library. For example:

| Field                     | Description                                                                                     | Default   |
|---------------------------|-------------------------------------------------------------------------------------------------|-----------|
| maxRequests               | The maximum number of requests allowed to pass through when the circuit breaker is half-open.   | `1`       |
| interval                  | The cyclic period of the closed state for the circuit breaker to clear the internal counts. If `0`, the circuit breaker doesn't clear internal counts during the closed state. | `0s`       |
| timeout                   | The period of the open state, after which the state of the circuit breaker becomes half-open.   | `60s`     |
| trip                      | A [CEL expression](https://opensource.google/projects/cel) evaluated with the circuit breaker's internal counts whenever a request fails in the closed state. If it evaluates to true, the circuit breaker will be placed into the open state. | `consecutiveFailures > 5`     |

The following variables that reflect the circuit breaker's internal state are available to the `trip` CEL expression:

| Variable             | Description                                   |
|----------------------|-----------------------------------------------|
| requests             | The total number of requests                  |
| totalSuccesses       | The total number of successful requests       |
| totalFailures        | The total number of failed requests           |
| consecutiveSuccesses | The number of consecutive successful requests |
| consecutiveFailures  | The number of consecutive failed requests     |

### Building blocks

The `buildingBlocks` section covers most scenarios by applying policies at the service and component level. This section has three sub sections:

* `services` - used for service invocation. Circuit breakers would ideally be scoped to the service endpoint so the application can avoid calling a single bad instance of an application pool. To achieve this, circuit breakers will need to work closely with the service discovery and load balancing functions of Dapr. For a given **Dapr App ID**, one or all of `timeout`, `retry` and `circuitBreaker` can be specified.

* `components` - used for Dapr-to-component communication. Circuit breakers would have a 1-to-1 relationship with component instances. So a circuit breaker named "pubsubCB" would be instantiated for both a Kafka (e.g. kafka1) and Redis (e.g. redis2) component. For a given **component name** (i.e. `metadata.name`), one or all of `timeout`, `retry` and `circuitBreaker` can be specified.

* `routes` - used for component-to-Dapr communication. In other words, Dapr sending events to your application. Routes are defined in subscriptions (both declarative and programmatic) and soon [input bindings](#3566). Circuit breakers have a 1-to-1 relationship with each application route. For a given **route/path** (e.g `dsstatus`), one or all of `timeout`, `retry` and `circuitBreaker` can be specified.

Note: Observability, HTTP middleware, and name resolution building blocks are out of scope.

### Specific API scenarios

The `apis` section contains rules for how Dapr API calls override policies assigned in the `buildingBlocks` section.  For each of the Dapr API operations below, timeout and retry policies can be overridden to cater to specific scenarios in the application (e.g. Calling an operation that takes several seconds to complete).

* Service Invocation
    * invoke (should HTTP and gRPC be separate?)
* Actors
    * actorinvoke
    * actordurableinvoke (future feature)
    * setreminder (or is that handled at the state store?)
* Bindings
    * input (read?)
    * output (send?)
* Pub/Sub
    * publish
    * subscribe (which is really message delivery?)
* State Stores (including actor state?)
    * getstate
    * setstate
    * deletestate
    * getbulkstate
    * setbulkstate
    * deletebulkstate
* Secret Stores
    * getsecret
    * getbulksecret

Note: Overriding circuit breakers for specific APIs is not permitted by design.

Each of the operations has a list of rules based on [CEL](https://opensource.google/projects/cel). If the rule matches, the name of `timeout` and `retry` policies are used for the API operation. This will be a similar experience to using the experimental [PubSub routing feature](#3406).

## Example YAML configuration

This example shows policies for a combination of service invocation and pubsub components.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: daprResiliency
# Like in the Subscriptions CRD, scopes lists the Dapr App IDs that this
# configuration applies to.
scopes:
  - app1
  - app2
spec:

#------------------------------------------------------------------------------
# PHASE 1: Basic policy definition and applying policies to building blocks
#------------------------------------------------------------------------------

  policies:
    # Timeouts are simple named durations.
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s

    # Retries are named templates for and are instantiated for life of the operation.
    retries:
      general: {} # Sane defaults

      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 10

      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: 0 # Retry indefinitely

      important:
        policy: constant
        duration: 5s
        maxRetries: 30

      someOperation:
        policy: exponential
        maxInterval: 15s

      largeResponse:
        policy: constant
        duration: 5s
        maxRetries: 3

    # Circuit breakers are automatically instantiated per component, service endpoint, and application route.
    # using these settings as a template. See logic below under `buildingBlocks`.
    # Circuit breakers maintain counters that can live as long as the Dapr sidecar.
    circuitBreakers:
      general: {} # Sane defaults

      pubsubCB:
        maxRequests: 1
        interval: 8s
        timeout: 45s
        trip: consecutiveFailures > 8

  # This section specifies default policies for:
  # * service invocation
  # * requests to components
  # * events sent to routes
  buildingBlocks:
    services:
      appB:
        timeout: general
        retry: general
        # Circuit breakers for services are scoped per endpoint (e.g. hostname + port).
        # When a breaker is tripped, that route is removed from load balancing for the configured `timeout` duration.
        circuitBreaker: general

    components:
      # For state stores, policies apply to saving and retrieving state.
      # Watching, which is not implemented yet, is out of scope.
      statestore1:
        timeout: general
        retry: general
        # Circuit breakers for components are scoped per component configuration/instance (e.g. redis1).
        # When this breaker is tripped, all interaction to that component is prevented for the configured `timeout` duration.
        circuitBreaker: general

      # For Pub/Sub, policies apply only to publishing.
      # Subscribing/consuming is handled by routes.
      pubsub1:
        retry: pubsubRetry
        circuitBreaker: pubsubCB

      pubsub2:
        retry: pubsubRetry
        circuitBreaker: pubsubCB
    
    # Routes represent the application's URI/paths that receive incoming events from both
    # PubSub and Input binding components. The route values correspond to the value configured
    # in the Subscription configuration or programmatic call. For input bindings, this is
    # configured in the component metadata via #3566.
    routes:
      'dsstatus.v3':
        timeout: general
        retry: general
        circuitBreaker: general

#------------------------------------------------------------------------------
# PHASE 2: Overriding policies for specific Dapr API operations
#------------------------------------------------------------------------------

  apis:
    invoke:
      - match: appId == "appB"
        # Nested rules: Prevent duplicative checks in rules.
        # Its likely that controler-gen does not support this
        # but apiextensionsv1.JSON can be used as workaround.
        rules:
          - match:
              request.method == "GET" &&
              request.metadata.count > 1000
            timeout: largeResponse
            retry: largeResponse
          - match:
              request.path == "/someOperation"
            retry: someOperation

    publish:
      - match: |
          event.type == "important.event.v1"
        timeout: important
        retry: important

    # subscribe is when Dapr attempting to deliver a pubsub event to an application route.
    subscribe:
      - match: |
          event.type == "important.event.v1"
        timeout: important
        retry: retryForever
```

Default `resiliency.yml` that could be installed by `dapr init`.  Might include commented out examples for Redis.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: daprResiliency
scopes:
spec:
  policies:
    # Timeouts are simple named durations.
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s

    # Retries are named templates for and are instantiated for life of the operation.
    retries:
      general: {} # Sane defaults

    # Circuit breakers are automatically instantiated per component, service endpoint, and application route.
    # using these settings as a template. See logic below under `buildingBlocks`.
    # Circuit breakers maintain counters that can live as long as the Dapr sidecar.
    circuitBreakers:
      general: {} # Sane defaults

  # This section specifies default policies for:
  # * service invocation
  # * requests to components
  # * events sent to routes
  buildingBlocks:
    services:

    components:
    
    # Routes represent the application's URI/paths that receive incoming events from both
    # PubSub and Input binding components. The route values correspond to the value configured
    # in the Subscription declarative or programmatic configurations.
    routes:

  apis:
    invoke:
    publish:
    subscribe:
```

## Implementation phases

As seen in the YAML example, this feature is proposed to be implemented in two phases:

* Phase 1: Basic policy definition and applying policies to building blocks
* Phase 2: Overriding policies for specific Dapr API operations

The reasoning is that Phase 2 should have more time to receive feedback from the community. It is an incremental feature that has several touch points in the API code. There could be learning from implementing Phase 1 that could influence the approach in Phase 2.

## Cautions / Considerations

Resiliency features can often be misconfigured.

* Dropping broker messages (e.g. Kafka)
* Writing duplicate records
* Self-inflicted DoS / thundering herd

What errors in Dapr are retriable or permanent?

* Malformed queries (400) vs communication error (socket read error)
* Record not found (404) vs an internal server error (500)
* Component or service may enforce rate limiting (429) and return a prescribed retry interval (which are currently not returned)
* Updates to data cannot always be retried without idempotency or record versions/timestamps (concurrency)

Timeouts and retries rely heavily on the Context being passed through Dapr's runtime and components. **A review of current error handling and usage of `context.Context` should be part of implementing this feature.**

## Vote: Lists vs. Keys/Maps in YAML?!

Thanks for reading this far! Here is something you can weigh in on and maybe have some fun at the same time!

The Dapr maintainers would like to know your preference when it comes to "named things" in YAML.

Do you prefer...

[Using keys/maps (as the example above)](https://gist.github.com/pkedy/3cac178fec85671757763604eee9874a)
or
[Using lists instead](https://gist.github.com/pkedy/7ba7493144b25ca2e02bc6db41b2a142)

While, Dapr uses lists in come cases (e.g. component metadata), don't let that influence your decision ;)

[![](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/Keys%21)](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/Keys%21/vote)
[![](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/Lists%21)](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/Lists%21/vote)
[![](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/I%20could%20care%20less%21)](https://api.gh-polls.com/poll/01FDX774Z53NGHA7M65PEX43Z7/I%20could%20care%20less%21/vote)

Thanks!
