### ISSUE TITLE
App has not subscribed to binding X. .NET Core

### ISSUE THREAD

**Issue by itsoli91** [dapr/dapr#3608]
## .NET Core App
Hi Guys. 

I want to write an application that listens to a topic on MQTT Broker and print the message on console.

Binding configuration:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: telemetry
spec:
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://mqtt.broker:1883
  - name: topic
    value: telemetry/upload
  - name: consumerID
    value: "{uuid}"
```

Docker-Compose:

```
// docker-compose.yaml
version: '3.4'

services:
  mqtt.broker:
    image: vernemq/vernemq

  transport.mqtt:
    image: ${DOCKER_REGISTRY-}transportmqtt
    build:
      context: .
      dockerfile: src/Services/Transport/Transport.MQTT/Dockerfile

  transport.mqtt-dapr:
    image: "daprio/daprd:latest"




// docker-compose.override.yaml
version: '3.4'


services:

  mqtt.broker:
    container_name: mqtt.broker
    image: vernemq/vernemq
    environment:
     - DOCKER_VERNEMQ_ACCEPT_EULA=yes
     - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    ports:
     - "1883:1883"
    networks:
     - vangurdiot


  transport.mqtt:
    container_name: transport.mqtt
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "13000:80"
      - "50001:50001"
    depends_on:
    - mqtt.broker
    networks:
     - vangurdiot

  transport.mqtt-dapr:
    container_name: transport.mqtt-dapr
    command: [ "./daprd",
               "-app-id", "transport.mqtt",
               "-app-port", "80",
               "-components-path", "/components"]
    depends_on:
      - transport.mqtt
      - mqtt.broker
    network_mode: "service:transport.mqtt"
    volumes:
    - ./dapr/components/:/components   



networks:
 vangurdiot:
```

.NET Core Startup class

```
 public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddDapr();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            // Use Cloud Events
            app.UseCloudEvents();

            app.UseEndpoints(endpoints =>
            {
                // Map subscriber handler
                endpoints.MapSubscribeHandler();
                endpoints.MapControllers();
            });
        }
    }
```

And this is my Telemetry Controller

```
    [ApiController]
    [Route("telemetry")]
    public class TelemetryController : ControllerBase
    {
        private readonly ILogger<TelemetryController> _logger;

        public TelemetryController(ILogger<TelemetryController> logger)
        {
            _logger = logger;
        }

        [HttpPost("upload")]
        public ActionResult Post()
        {
            try
            {
                Console.WriteLine("I am here");
                _logger.LogInformation("I'm here");
                return Ok();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error occurred while processing telemetry upload");
                return StatusCode(500);
            }
        }
    }
```

When I run the application it seems from log that it is reading the binding but at last line has written that **`level=info msg="app has not subscribed to binding telemetry." app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0`**

here is the complete log

```

time="2021-09-01T16:49:51.517795Z" level=info msg="starting Dapr Runtime -- version 1.3.0 -- commit 4bab7576ed68a9ece1a4743a7925f18ef583775a" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5178521Z" level=info msg="log level set to: info" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5179542Z" level=info msg="metrics server started on :9090/" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.metrics type=log ver=1.3.0

time="2021-09-01T16:49:51.518683Z" level=info msg="loading default configuration" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5188727Z" level=info msg="standalone mode configured" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5188883Z" level=info msg="app id: transport.mqtt" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5191351Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5196851Z" level=info msg="local service entry announced: transport.mqtt -> 172.24.0.3:45201" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.contrib type=log ver=1.3.0

time="2021-09-01T16:49:51.5197117Z" level=info msg="Initialized name resolution to mdns" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5267337Z" level=info msg="waiting for all outstanding components to be processed" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5292272Z" level=info msg="successful init for output binding telemetry (bindings.mqtt/v1)" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5312746Z" level=info msg="successful init for input binding telemetry (bindings.mqtt/v1)" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5313143Z" level=info msg="component loaded. name: telemetry, type: bindings.mqtt/v1" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5313448Z" level=info msg="all outstanding components processed" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5315078Z" level=info msg="enabled gRPC tracing middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.grpc.api type=log ver=1.3.0

time="2021-09-01T16:49:51.5315272Z" level=info msg="enabled gRPC metrics middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.grpc.api type=log ver=1.3.0

time="2021-09-01T16:49:51.5318425Z" level=info msg="API gRPC server is running on port 50001" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5321332Z" level=info msg="enabled metrics http middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.http type=log ver=1.3.0

time="2021-09-01T16:49:51.5321643Z" level=info msg="enabled tracing http middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.http type=log ver=1.3.0

time="2021-09-01T16:49:51.5321783Z" level=info msg="http server is running on port 3500" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.532185Z" level=info msg="The request body size parameter is: 4" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5322272Z" level=info msg="enabled gRPC tracing middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.grpc.internal type=log ver=1.3.0

time="2021-09-01T16:49:51.5322364Z" level=info msg="enabled gRPC metrics middleware" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime.grpc.internal type=log ver=1.3.0

time="2021-09-01T16:49:51.5322622Z" level=info msg="internal gRPC server is running on port 45201" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5322737Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5329268Z" level=info msg="application discovered on port 80" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5480316Z" level=info msg="application configuration loaded" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5502868Z" level=warning msg="failed to init actors: actors: couldn't connect to placement service: address is empty" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5503783Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 31.5921ms" app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0

time="2021-09-01T16:49:51.5573404Z" level=info msg="app has not subscribed to binding telemetry." app_id=transport.mqtt instance=bfb89a5e5e36 scope=dapr.runtime type=log ver=1.3.0
```

I tried to publishing to topic `telemetry/upload` using other MQTT clients and I'm sure that message is published in topic, but nothing is shown in the console of .Net core app, what I'm missing ?
