### ISSUE TITLE
When I use rabbitmq as binding, I got an Error:Exception (501) Reason: \"EOF\"

### ISSUE THREAD

**Issue by cysnet** [dapr/dapr#3715]
When I use rabbitmq as binding, I got an Error:Exception (501) Reason: \"EOF\"

the binding yaml is 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: RabbitBinding
spec:
  type: bindings.rabbitmq
  metadata:
  - name: host
    value: amqp://localhost:5672
  - name: queueName
    value: rabbitmq-worker-input
```

and the Error is 
```
time="2021-09-27T16:16:52.1035207+08:00" level=error msg="failed to init output binding RabbitBinding (bindings.rabbitmq/v1): Exception (501) Reason: \"EOF\"" app_id=frontend instance=chesterchen-lap scope=dapr.runtime type=log ver=1.4.0
time="2021-09-27T16:16:52.1035207+08:00" level=error msg="failed to init output bindings: Exception (501) Reason: \"EOF\"" app_id=frontend instance=chesterchen-lap scope=dapr.runtime type=log ver=1.4.0
```
