### ISSUE TITLE
Subcription routing fails to apply routes

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#3740]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.4.0 (.NET SDK cli)
1.4.1 K8s
## Expected Behavior

Declarative subscription should route messages to the right endpoints.

## Actual Behavior

All messages are sent to the default route. No error in dapr logs

## Steps to Reproduce the Problem

My subscription:

```
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsubapi-subscription
  namespace: dapr
spec:
  topic: weatherfc
  routes:
    rules:
      - match: event.data.mood == "Rain"
        path: /WeatherForecast/RainEvent
      - match: event.data.mood == "Snow"
        path: /WeatherForecast/SnowEvent
    default: /WeatherForecast/WeatherEvent  
  pubsubname: pubsub
scopes:
pubsubapi
```

The event payload in the CloudEvent format - app.UseCloudEvents(); (extracted from Azure SB):
```
{
  "id":"33f6f496-b0a2-478e-b796-1e7a311742ce",
  "type":"com.dapr.event.sent",
   "pubsubname":"pubsub",
   "data":{"mood":"Rain","id":"587e0969-70dd-4363-842b-bec22e0c8bff","creationDate":"2021-10-07T07:37:00.260613Z"},
   "specversion":"1.0",
    "datacontenttype":"application/json",
    "source":"pubsubapi",
    "topic":"weatherfc","
    traceid":"00-943f38f0df27e441893fcb77738f5226-4bb157a3d78cde5e-00"
}
```
As you can see in the payload, mood is set to "Rain", which should match one of the route  rules but it always goes through the default one. Nothing is reported to the daprd logs although debug mode is enabled.

## Release Note

RELEASE NOTE:
