### ISSUE TITLE
Multiple subscriber for a topic in Pub/Sub component with Event hub is not working as expected

### ISSUE THREAD

**Issue by gagzm** [dapr/dapr#3753]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hello Team,

We have identified that the Behavior of Dapr (Pub/Sub) along with Event Hub is not as expected when we have multiple subscribers components of one topic. Following are the details:

1. Published messages are not delivered to a defined route for that topic every time.
2. If delivered, Published messages are not delivered to all the subscribers. 

 It works perfectly fine while testing with Redis. Please watch the video below and I have also attached the code. 

https://www.loom.com/share/3dc3e521fe404e448640de18ed8d7ccb 

**Pub/Sub Component**

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
    - name: connectionString
      value: ""
    - name: storageAccountName
      value: ""
    - name: storageAccountKey
      value: ""
    - name: storageContainerName
      value: ""
auth:
  secretStore: kubernetes
```

**Publisher**

```
kind: Service
apiVersion: v1
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  selector:
    app: react-form
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-form
  template:
    metadata:
      labels:
        app: react-form
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "react-form"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: react-form
        image: dapriosamples/pubsub-react-form:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

```

**Subscriber 1**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventconsumer
  labels:
    app: eventconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventconsumer
  template:
    metadata:
      labels:
        app: eventconsumer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "eventconsumer"
        dapr.io/app-port: "5000"
    spec:
      containers:
        - name: eventconsumer
          image: dapriosamples/pubsub-python-subscriber:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

```

**Subscriber 2**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackwaysconsumergroup
  labels:
    app: stackwaysconsumergroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackwaysconsumergroup
  template:
    metadata:
      labels:
        app: stackwaysconsumergroup
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "stackwaysconsumergroup"
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: stackwaysconsumergroup
          image: dapriosamples/pubsub-node-subscriber:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

```

Thanks for all your help.
