### ISSUE TITLE
Self-Hosted Mode: Warning with metadata is configured in a subscription YAML

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#3754]
It appears as though in self hosted mode, Dapr tries to parse Subscription YAMLs as Components, which logs a warning.

## In what area(s)?

/area runtime

## What version of Dapr?

1.x

## Expected Behavior

Subscriptions YAML are filtered out when loading and parsing Component YAMLs.

## Actual Behavior

When a Subscription YAML is encountered that contains `metadata`, it fails to parse as a component and a warning message is logged (but should not affect the operation of the application).

```
daprd load components error when parsing components yaml resource in...
```

## Steps to Reproduce the Problem

Put metadata in the subscription YAML

```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: mysubscriptions
  namespace: default
spec:
  pubsubname: pubsub
  topic: inventory
  metadata:
    rawPayload: true
  routes:
    rules:
      - match: "event.type == 'widget'"
        path: widgets
      - match: "event.type == 'gadget'"
        path: gadgets
    default: products
```

## Release Note

RELEASE NOTE: **FIX** Ignore non-components when loading Component YAMLs in self-hosted mode.
