### ISSUE TITLE
How to expose dapr side car as a service?

### ISSUE THREAD

**Issue by abnormall** [dapr/dapr#3760]
## In what area(s)?

Environment:
In AKS

## Ask your question here
Question:
How to expose dapr side car as a service using LoadBalancer?

Problem:
I tried but failed.

My yaml file is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
  labels: 
    app: k8s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "k8s-test"
        dapr.io/app-port: "4001"
    spec:
      containers:
        - name: k8s-test
          image: simpllly/bjli-docker-hub:20210906
          ports:
            - name: http
              containerPort: 4001

---
kind: Service
apiVersion: v1
metadata:
  name: k8s-test
  labels:
    app: k8s-test
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 100
    protocol: TCP
    targetPort: 4002
  sessionAffinity: None
  selector:
    app: k8s-test
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-test-dapr
  labels:
    app: k8s-test-dapr
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 200
    protocol: TCP
    targetPort: 3500
  sessionAffinity: None
  selector:
    app: k8s-test-dapr




```
