### ISSUE TITLE
pubsub kafka can not be used

### ISSUE THREAD

**Issue by darren-wang** [dapr/dapr#3766]
I'm trying to use kafka as pubsub backend according to the dmo:

https://github.com/azure-octo/dapr-kafka-csharp/blob/master/deploy/kafka-pubsub.yaml

I changed the `brokers` section and here is my yaml:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-kafka-pubsub
  namespace: my-namespace
spec:
  type: pubsub.kafka
  metadata:
    - name: brokers
      value: "10.230.205.8:9092,10.230.205.9:9092"
    - name: authRequired
      value: "false"
```

I can ping and telnet the kafka broker successfully, and connect to it with kafka's official java SDK.

However, that yaml keeps my daprd from starting, and logs as follow:

```
error intializing pub sub pubsub.kafka/v1: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

and then daprd exits.

It's ok to use redis as pubsub backend, I can't even start the sidecar using kafka as pubsub backend. 

Any idea how to solve this question？

**Comment by Taction** [comment]
Is tls enabled on your Kafka backend?

**Comment by yaron2** [comment]
@darren-wang can you try pointing to a Kafka service and not direct pod IP? also, what Kafka installation are you using? I recommend you test with this one: https://bitnami.com/stack/kafka/helm. (assuming you're using Kubernetes)

**Comment by darren-wang** [comment]
> @darren-wang can you try pointing to a Kafka service and not direct pod IP? also, what Kafka installation are you using? I recommend you test with this one: https://bitnami.com/stack/kafka/helm. (assuming you're using Kubernetes)

@yaron2 Yeah, thanks, I'm deploying my dapr services and dapr apps on k8s, but our kafka cluster are not since they are hosted by another team and they only provides server IPs. I have to adapt to them, sad.

Our kafkas are of version 0.10.x. I think it is pretty old and could this be the reason?

Also, do you know the supported version list of kafka backends so I can check if it is version reasons. And a clear version support list is really important for  corporate users to adopt dapr.

**Comment by johnseed** [comment]
Same issue here. 
Redis, rabbitmq is working fine, but Kafka keep getting error "Invalid receive (size = 369295616 larger than 104857600)".
Tried [Bitnami kafka](https://bitnami.com/stack/kafka), [wurstmeister/kafka](https://hub.docker.com/r/wurstmeister/kafka), [Offical APACHE KAFKA](https://kafka.apache.org/quickstart) with no luck.

### Error info
dapr:
```
08T04:49:36.899888548Z" level=warning msg="error initializing pub sub pubsub.kafka/v1: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)" app_id=orderprocessing instance=086ac359ee2c scope=dapr.runtime type=log ver=1.6.0
```
Kafka:
```
[2022-03-08 05:15:49,375] WARN [SocketServer listenerType=ZK_BROKER, nodeId=1001] Unexpected error from /172.25.0.8; closing connection (org.apache.kafka.common.network.Selector)

org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)

at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)

at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)

at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)

at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)

at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)

at org.apache.kafka.common.network.Selector.poll(Selector.java:481)

at kafka.network.Processor.poll(SocketServer.scala:989)

at kafka.network.Processor.run(SocketServer.scala:892)

at java.lang.Thread.run(Thread.java:748)
```

## Code
repo [johnseed](https://github.com/johnseed)/[dapr-pubsub-demo](https://github.com/johnseed/dapr-pubsub-demo)
### pubsub yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order_pub_sub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:9092"
  - name: authType # Required.
    value: "none"
  - name: authRequired
    value: "false"
scopes:
  - orderprocessing
  - checkout
```

### Pub
```C#
string PUBSUB_NAME = "order_pub_sub";
string TOPIC_NAME = "orders";
Random random = new Random();

while (true)
{
    try
    {
        System.Threading.Thread.Sleep(5000);
        int orderId = random.Next(1, 1000);
        CancellationTokenSource source = new CancellationTokenSource();
        CancellationToken cancellationToken = source.Token;
        using var client = new DaprClientBuilder().Build();
        //Using Dapr SDK to publish a topic
        await client.PublishEventAsync(PUBSUB_NAME, TOPIC_NAME, orderId, cancellationToken);
        Console.WriteLine("Published data: " + orderId);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}

```

### Sub
```C#
    [ApiController]
    public class CheckoutServiceController : Controller
    {
        //Subscribe to a topic 
        [Topic("order_pub_sub", "orders")]
        [HttpPost("/checkout")]
        public string GetCheckout([FromBody] int orderId)
        {
            Console.WriteLine("Subscriber received : " + orderId);
            return "Subscriber received : " + orderId;
        }
    }
```

### Kafka 
```yaml
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orders:1:1"
    restart: unless-stopped
```

**Comment by yaron2** [comment]
> 

Will take a look

**Comment by Taction** [comment]
@johnseed can you help have a try with this pubsub yaml?
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order_pub_sub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:9092"
  - name: authType # Required.
    value: "none"
  - name: authRequired
    value: "false"
  - name: disableTls
    value: "true"
scopes:
  - orderprocessing
  - checkout
```

**Comment by darren-wang** [comment]
> @johnseed can you help have a try with this pubsub yaml?
> 
> ```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: order_pub_sub
> spec:
>   type: pubsub.kafka
>   version: v1
>   metadata:
>   - name: brokers # Required. Kafka broker connection setting
>     value: "kafka:9092"
>   - name: authType # Required.
>     value: "none"
>   - name: authRequired
>     value: "false"
>   - name: disableTls
>     value: "true"
> scopes:
>   - orderprocessing
>   - checkout
> ```

what is the minimum version of kafka cluster that this component support, I'm using kafka 0.10.0.1 and `ip:port` as `brokers`(e.g. 123.123.123.123:9092) and  the sidecar failed with :

```
client has run out of available brokers to talk to (Is your cluster reachable?)
```

And I'm sure that the network is connected and the test cluster does not need authentication.

I think there should be a version list that our component supports.

**Comment by darren-wang** [comment]
> @johnseed can you help have a try with this pubsub yaml?
> 
> ```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: order_pub_sub
> spec:
>   type: pubsub.kafka
>   version: v1
>   metadata:
>   - name: brokers # Required. Kafka broker connection setting
>     value: "kafka:9092"
>   - name: authType # Required.
>     value: "none"
>   - name: authRequired
>     value: "false"
>   - name: disableTls
>     value: "true"
> scopes:
>   - orderprocessing
>   - checkout
> ```

what is the minimum version of kafka cluster that this component support, I'm using kafka 0.10.0.1 and `ip:port` as `brokers`(e.g. 123.123.123.123:9092) and  the sidecar failed with :

```
client has run out of available brokers to talk to (Is your cluster reachable?)
```

And I'm sure that the network is connected and the test cluster does not need authentication.

I think there should be a version list that our component supports.

**Comment by Taction** [comment]
The default version is 2.0.0.0, and you can define it with `version`. I am currently not sure the supported range but you can have a try by adding:

```
- name: version
    value: "0.10.0.1"
```

**Comment by johnseed** [comment]
> @johnseed can you help have a try with this pubsub yaml?
> 
> ```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: order_pub_sub
> spec:
>   type: pubsub.kafka
>   version: v1
>   metadata:
>   - name: brokers # Required. Kafka broker connection setting
>     value: "kafka:9092"
>   - name: authType # Required.
>     value: "none"
>   - name: authRequired
>     value: "false"
>   - name: disableTls
>     value: "true"
> scopes:
>   - orderprocessing
>   - checkout
> ```

It worked! Thank you so much.

**Comment by darren-wang** [comment]
I'm using dapr-1.5.1, and,

1. I confirmed that `brokers` field supports `IP1:PORT,IP2:PORT` brokers string.
2. pubsub.kafka supports kafka `0.10.0.1`

here is my yaml:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub_name
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers 
    value: "123.123.123.123:9092,123.123.123.124:9092,123.123.123.125:9092" # example
  - name: version
    value: "0.10.0.1"
  - name: authType
    value: "none"
  - name: authRequired
    value: "false"
  - name: disableTls
    value: "false"
  - name: skipVerify
    value: "false"
```
