### ISSUE TITLE
actors: state store does not exist or incorrectly configured

### ISSUE THREAD

**Issue by ChuchoCoder** [dapr/dapr#3771]
## In what area(s)?
/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.4.3

## Expected Behavior

Actors example from dotnet-sdk to work correctly

I don't understand why is throwing an error related to the state store for the actors as I am using the default configuration. 

I have tried the following:
- Removed all containers
- Restarted docker
- Restarted my machine

## Actual Behavior

Getting the following errors
```
time="2021-10-14T13:45:56.1525444-03:00" level=error msg="error getting reminders for actor type DemoActor: actors: state store does not exist or incorrectly configured" app_id=demo_actor instance=NOTEBOOKscope=dapr.runtime.actor type=log ver=1.4.3
time="2021-10-14T13:45:56.1566199-03:00" level=info msg="placement tables updated, version: 0" app_id=demo_actor instance=NOTEBOOKscope=dapr.runtime.actor.internal.placement type=log ver=1.4.3
time="2021-10-14T13:45:58.4092253-03:00" level=error msg="error getting reminders for actor type DemoActor: actors: state store does not exist or incorrectly configured" app_id=demo_actor instance=NOTEBOOK scope=dapr.runtime.actor type=log ver=1.4.3
```

## Steps to Reproduce the Problem

Follow steps as described in: https://github.com/dapr/dotnet-sdk/tree/master/examples/Actor

- Install Dapr `dapr init`
- Run ` dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run`

I am using the default statestore.yaml that dapr installs.
**statestore.yaml**
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true" 
```
