### ISSUE TITLE
Change dapr's internal port names

### ISSUE THREAD

**Issue by stephaneey** [dapr/dapr#3779]
Hello,

Is there a reason why Dapr's HTTP and gRPC ports are named respectively dapr-http and dapr-grc? This is causing issues when used together with Istio (and probably other products), which expect standard port names to be used, meaning in this case "http" and "grpc".

When using AuthorizationPolicy in Istio, Dapr's port names are causing issues. Changing these names in the Dapr-created service does the trick but sounds like a hack.

Thanks
Best regards

**Comment by stephaneey** [comment]
I managed to get it work through a service entry but not sure if this could have a side-effect. 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: orderprocessing
  namespace: microserviceapp
spec:
  hosts:
  - orderprocessing-dapr.microserviceapp.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: dapr-http
    number: 80
    protocol: HTTP
  resolution: DNS

```
However, the question remains.
