### ISSUE TITLE
dapr-placement-server does not respect mTLS setting

### ISSUE THREAD

**Issue by aytekinar** [dapr/dapr#3784]
## In what area(s)?

/area runtime

/area placement

## What version of Dapr?

1.4.3

## Expected Behavior

Dapr'ized Kubernetes deployments should work.

## Actual Behavior

Dapr'ized Kubernetes deployments do not work due to the sidecar container reporting the following:

```bash
$ kubectl -n dapr-study-group logs go-app-79576b758c-jl8hp daprd
time="2021-10-18T21:40:38.528345693Z" level=info msg="starting Dapr Runtime -- version 1.4.3 -- commit a8ee30180e1183e2a2e4d00c283448af6d73d0d0" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3
time="2021-10-18T21:40:38.528375319Z" level=info msg="log level set to: debug" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3
time="2021-10-18T21:40:38.528482071Z" level=info msg="metrics server started on :9090/" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.metrics type=log ver=1.4.3
time="2021-10-18T21:40:38.528593671Z" level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3
```

## Steps to Reproduce the Problem

Install Dapr by issuing `helm upgrade dapr dapr/dapr --install --namespace dapr-system --values values.yaml --version 1.4` with the following `values.yaml` file:

```yaml
global:
  registry: dockerhub-proxy.company.com/daprio
  tag: "1.4.3"
  dnsSuffix: ".cluster.local"
  logAsJson: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: ""
  nodeSelector: {}
  ha:
    enabled: true
    replicaCount: 3
    disruption:
      minimumAvailable: ""
      maximumUnavailable: "25%"
  prometheus:
    enabled: true
    port: 9090
  mtls:
    enabled: false
    workloadCertTTL: 24h
    allowedClockSkew: 15m
  daprControlPlaneOs: linux
dapr_dashboard:
  image: 
    registry: dockerhub-proxy.company.com/daprio
```

Then, deploy a sample/dummy Dapr'ized application (in this example, I am going to show my `go-app`). The app does not start due to `CrashLoopBackOff`:

```bash
$ kubectl -n dapr-study-group get pods 
NAME                      READY   STATUS             RESTARTS   AGE
go-app-79576b758c-jl8hp   1/2     CrashLoopBackOff   6          9m47s
go-app-79576b758c-ph7vd   1/2     CrashLoopBackOff   6          9m31s
go-app-79576b758c-szvqp   1/2     CrashLoopBackOff   6          9m31s

$ kubectl -n dapr-study-group logs go-app-79576b758c-jl8hp daprd
time="2021-10-18T21:45:30.524358564Z" level=info msg="starting Dapr Runtime -- version 1.4.3 -- commit a8ee30180e1183e2a2e4d00c283448af6d73d0d0" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3
time="2021-10-18T21:45:30.524403851Z" level=info msg="log level set to: debug" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3
time="2021-10-18T21:45:30.524515148Z" level=info msg="metrics server started on :9090/" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.metrics type=log ver=1.4.3
time="2021-10-18T21:45:30.52465069Z" level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=go-app instance=go-app-79576b758c-jl8hp scope=dapr.runtime type=log ver=1.4.3

$ kubectl -n dapr-study-group describe pods go-app-79576b758c-jl8hp | grep -Ei '(dapr_|tls)'
      DAPR_HTTP_PORT:  3500
      DAPR_GRPC_PORT:  50001
      DAPR_TRUST_ANCHORS:     
      DAPR_CERT_CHAIN:        
      DAPR_CERT_KEY:

$ kubectl -n dapr-system get deployments,statefulsets
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dapr-dashboard          1/1     1            1           43m
deployment.apps/dapr-operator           3/3     3            3           43m
deployment.apps/dapr-sentry             3/3     3            3           43m
deployment.apps/dapr-sidecar-injector   3/3     3            3           43m

NAME                                     READY   AGE
statefulset.apps/dapr-placement-server   3/3     43m

$ kubectl -n dapr-system logs -l app=dapr-placement-server | grep -i mtls
time="2021-10-18T21:10:43.432773738Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.4.3
time="2021-10-18T21:10:44.367554216Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-placement-server-1 scope=dapr.placement type=log ver=1.4.3
time="2021-10-18T21:10:43.344643154Z" level=info msg="mTLS enabled, getting tls certificates" instance=dapr-placement-server-2 scope=dapr.placement type=log ver=1.4.3
```

It's worth noting that I mistakenly installed `dapr` first with `global.mtls.enabled=true`, and later, I switched to `global.mtls.enabled=false`. It's also worth mentioning that I have not used the bare `helm upgrade ...` command; instead, I have installed `dapr` by using the ArgoCD installation on our cluster (while pointing to the `dapr` chart in its `source` field).

## Release Note

RELEASE NOTE:
