### ISSUE TITLE
Error in sidecars after upgrading from 1.3.1 to 1.4.0

### ISSUE THREAD

**Issue by berkaysakarg** [dapr/dapr#3793]
## In what area(s)?

> /area test-and-release

## What version of Dapr?

> 1.4.0

## Expected Behavior

upgrading DAPR from 1.3.1 to 1.4.0 should work without an error in the sidecars.

## Actual Behavior

I upgraded DAPR from 1.3.1 to 1.4.0
then sidecars failed.

## Steps to Reproduce the Problem

We use DAPR helm chart. After the upgrade we see an error in the sidecar logs.
`failed to append PEM root cert to x509 CertPool`

Sidecar Logs:
![image](https://user-images.githubusercontent.com/30413093/138248726-93b7791c-c0e7-4aaf-8e1f-41f6c2a19524.png)
## Release Note

RELEASE NOTE: **FIX** Bug in runtime about appending PEM root cert

**Comment by fjvela** [comment]
Did you try to upgrade to 1.4.3?

**Comment by PeterGerrard** [comment]
We have upgraded to both 1.4.0 and 1.4.3 and seen the error

**Comment by fjvela** [comment]
Today one of our cluster has been upgraded to 1.21.5 (EKS) and It's running dapr 1.4.3 without any problem.

Did you try to uninstall it and install it?
if you are using helm3 to upgrade Darp did you upgrade CRD?

**Comment by PeterGerrard** [comment]
When going to 1.4.3 we didn't originally but did now. It now gets the same error as when we update to 1.4.0.

```
$> kubectl logs -n platform email-784b7f5b85-dzv6s daprd
time="2021-11-04T09:36:45.193683297Z" level=info msg="starting Dapr Runtime -- version 1.4.3 -- commit a8ee30180e1183e2a2e4d00c283448af6d73d0d0" app_id=email instance=email-784b7f5b85-dzv6s scope=dapr.runtime type=log ver=1.4.3
time="2021-11-04T09:36:45.193714498Z" level=info msg="log level set to: info" app_id=email instance=email-784b7f5b85-dzv6s scope=dapr.runtime type=log ver=1.4.3
time="2021-11-04T09:36:45.193820504Z" level=info msg="metrics server started on :9090/" app_id=email instance=email-784b7f5b85-dzv6s scope=dapr.metrics type=log ver=1.4.3
time="2021-11-04T09:36:45.19393071Z" level=fatal msg="failed to append PEM root cert to x509 CertPool" app_id=email instance=email-784b7f5b85-dzv6s scope=dapr.runtime type=log ver=1.4.3
```

**Comment by PeterGerrard** [comment]
For reference here is the config we use to install dapr:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  chart:
    spec:
      chart: dapr
      version: 1.4.3
      sourceRef:
        kind: HelmRepository
        name: dapr
  interval: 1h
  releaseName: dapr
  targetNamespace: dapr-system
  dependsOn:
    - name: redis
      namespace: redis
  values:
    global:
      mtls:
        # use only linkerd for mTLS
        enabled: false
    dapr_sentry:
      replicaCount: 0
      tls:
        # Workaround for failed helm deploy issue when not using dapr sentry: https://github.com/dapr/dapr/issues/2808
        issuer:
          certPEM: "https://github.com/dapr/dapr/issues/2808"
          keyPEM: "https://github.com/dapr/dapr/issues/2808"
        root:
          certPEM: "https://github.com/dapr/dapr/issues/2808"
    dapr_placement:
      replicaCount: 0
    dapr_dashboard:
      replicaCount: 0
```
