### ISSUE TITLE
Kubernetes -darp service is created as Headless

### ISSUE THREAD

**Issue by andrey-dubnik** [dapr/dapr#3794]
## In what area(s)?

> /area runtime

## What version of Dapr?

1.4.

## Expected Behavior

Service should be created as a Cluster IP rather than Headless which would actually enable the load balancer on port 80->3500

## Actual Behavior

curl -v -H 'dapr-app-id: echoserver' http://echoserver-dapr.default:3500/
HTTP-200

curl -v -H 'dapr-app-id: echoserver' http://echoserver-dapr.default:80/
curl: (56) Recv failure: Connection reset by peer

## Steps to Reproduce the Problem

```
NAMESPACE=default
OPERATION=apply

cat <<EOF | kubectl ${OPERATION} -n ${NAMESPACE} -f -
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: echoserver-opa
spec:
  type: middleware.http.opa
  version: v1
  metadata:

    # causes segment violation
    # - name: defaultStatus
    #   value: 403

    - name: rego
      value: |
        package http
        default allow = {
            "allow": false,
            "status_code": 301,
            "additional_headers": {
                "Location": "https://my.redirect.site"
            }
        }
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: echoserver-config
spec:
  httpPipeline:
    handlers:
    - name: echoserver-opa
      type: middleware.http.opa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "echoserver"
        dapr.io/config: "echoserver-config"
        # kuma.io/sidecar-injection: "disabled"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.10
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
      serviceAccountName: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dapr.io/app-id: echoserver
    prometheus.io/path: /
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    dapr.io/enabled: "true"
  name: echoserver-dapr-cluster
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: echoserver
    uid: d133a353-9c0f-430d-a307-416f1ac168e2
spec:
  ports:
  - name: dapr-http
    port: 80
    protocol: TCP
    targetPort: 3500
  - name: dapr-grpc
    port: 50001
    protocol: TCP
    targetPort: 50001
  - name: dapr-internal
    port: 50002
    protocol: TCP
    targetPort: 50002
  - name: dapr-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: echoserver
  sessionAffinity: None
  type: ClusterIP
EOF
```

Calling the ClusterIP service results in Dapr success

curl -v -H 'dapr-app-id: echoserver' http://echoserver-dapr-cluster.default/
HTTP-200
