### ISSUE TITLE
Envoy (Kuma) to Dapr does not like HTTP and only works with TCP

### ISSUE THREAD

**Issue by andrey-dubnik** [dapr/dapr#3824]
Hi, I'm trying to pair Kuma Mesh with Dapr which overall works with a small but which I hope someone can help clarifying... 

When I'm setting up the traffic flow the only protocol I can use to get Dapr to work is a TCP, Envoy (or Kuma) just do not seem to like the way Dapr replies. This have an implication as I'm not able to use any L7 rules for that as it all boils down to me calling Dapr sidecar on 80 -> 3500.

In the scenario I'm setting up the service, specifically specifying the TCP as a protocol (example have http, which breaks)

```
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    80.service.kuma.io/protocol: http # dapr seem to only willing to work on tcp, weird
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3500
    protocol: TCP
  selector:
    app: echoserver
```

Calling it with the HTTP protocol would result in this

> `curl http://echoserver.meshdev.svc.80.mesh/`
> upstream connect error or disconnect/reset before headers. reset reason: protocol error

Calling it with the TCP is fine and it is HTTP-200 with the expected response

## Why this matters?

I would like Mesh to do the discovery and mTLS and Dapr to act as a middleware + cloud service abstraction (Macro Mesh) and same time make it transparent for the end users by tweaking the header on the way to the service and adding dapr application ID there so the URL does not have to change for the consumers of the service like this

```
conf:
    http:
    - match:
        path:
          prefix: "/"
      modify:
        requestHeader:
          add:
            - name: dapr-app-id
              value: echoserver
      destination:
        kuma.io/service: echoserver_meshdev_svc_80
    destination:
      kuma.io/service: echoserver_meshdev_svc_80
```

Without working HTTP there won't be possible to highjack the Header nor any L7 features of the mesh will apply to the Dapr bound connection.

**Comment by andrey-dubnik** [comment]
I've run additional cases and it seem there are different Headers and servers responding when it comes to the protocol, e.g. for http envoy is the responding body where in the tcp it is fasthttp. I'm not sure if this is relevant to the issue but though worth sending those out.

## Case #1 - point to the workload service

```
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    80.service.kuma.io/protocol: http
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
EOF
```

```
curl -v http://echoserver.meshdev.svc.80.mesh/
```

```
*   Trying ::ffff:240.0.0.9:80...
* Connected to echoserver.meshdev.svc.80.mesh (::ffff:240.0.0.9) port 80 (#0)
> GET / HTTP/1.1
> Host: echoserver.meshdev.svc.80.mesh
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 779
< etag: W/"30b-22NGuXbawhseC+i3zwuUKntymhI"
< date: Wed, 03 Nov 2021 14:38:21 GMT
< x-envoy-upstream-service-time: 2
< server: envoy
<
{
  "path": "/",
  "headers": {
    "host": "echoserver.meshdev.svc.80.mesh",
    "user-agent": "curl/7.74.0",
    "accept": "*/*",
    "x-forwarded-proto": "http",
    "x-request-id": "6c00d141-724f-4f0c-85bf-a21d57b4823d",
    "x-forwarded-client-cert": "By=spiffe://default/echoserver-dapr-cluster_meshdev_svc_50001;Hash=87c276044d1a19f79565543e9688f63b8bb9bdd35a6ea94d8438be07efa588e5;URI=spiffe://default/curlbox_meshdev_svc_80"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "echoserver.meshdev.svc.80.mesh",
  "ip": "::ffff:127.0.0.1",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [
    "svc",
    "meshdev",
    "echoserver"
  ],
  "xhr": false,
  "os": {
    "hostname": "echoserver-6f44f666bd-z7jvw"
  },
  "connection": {}
```

## Case #2 - point to the Dapr sidecar with the HTTP protocol

apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    80.service.kuma.io/protocol: http # dapr seem to only willing to work on tcp, weird
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3500
    protocol: TCP
  selector:
    app: echoserver

```
curl -v -H 'dapr-app-id: echoserver'  http://echoserver.meshdev.svc.80.mesh/
```

```
upstream connect error or disconnect/reset before headers. reset reason: protocol error
```

## Case #3 - point to the Dapr sidecar with the TCP protocol

```
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    80.service.kuma.io/protocol: tcp # dapr seem to only willing to work on tcp, weird
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3500
    protocol: TCP
  selector:
    app: echoserver
```

```
curl -v -H 'dapr-app-id: echoserver'  http://echoserver.meshdev.svc.80.mesh/
```

```
*   Trying 240.0.0.9:80...
* Connected to echoserver.meshdev.svc.80.mesh (240.0.0.9) port 80 (#0)
> GET / HTTP/1.1
> Host: echoserver.meshdev.svc.80.mesh
> User-Agent: curl/7.74.0
> Accept: */*
> dapr-app-id: echoserver
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: fasthttp
< Date: Wed, 03 Nov 2021 13:52:27 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 544
< Location: https://my.redirect.site
< X-Powered-By: Express
< Etag: W/"220-JzBa9iBVldx/eUS8+XSsMFR9U2o"
< Connection: keep-alive
< Keep-Alive: timeout=5
< Traceparent: 00-4280ba16495d0fdfd555029023218339-f263f615a90dae9f-00
<
{
  "path": "/",
  "headers": {
    "user-agent": "curl/7.74.0",
    "host": "127.0.0.1:8080",
    "content-type": "application/json",
    "accept": "*/*",
    "dapr-app-id": "echoserver",
    "traceparent": "00-4280ba16495d0fdfd555029023218339-f263f615a90dae9f-00"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "127.0.0.1",
  "ip": "::ffff:127.0.0.1",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "echoserver-6f44f666bd-z7jvw"
  },
  "connection": {}
* Connection #0 to host echoserver.meshdev.svc.80.mesh left intact
```
