### ISSUE TITLE
gRPC Proxying on Kubernetes is not working

### ISSUE THREAD

**Issue by omidb** [dapr/dapr#3869]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

I'm trying to follow the Kubernetes example for gRPC Proxying and I have no luck. It works fine with `dapr run` locally but when I try to do the same thing on Kubernetes I get the following error:
```bash
  File "/project/helloworld/client.py", line 14, in run
    response = await stub.SayHello(request=HelloRequest(name='you'), metadata=metadata)
  File "/usr/local/lib/python3.8/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1636338980.842821977","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3158,"referenced_errors":[{"created":"@1636338980.842735374","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
```

Steps I take:

1. `dapr init -k`
2. Applying the config mentioned here: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/
Here is the config:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: serverconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  features:
    - name: proxy.grpc
      enabled: true
```
3. Deploy my Server app using the config mentioned in the tutorial:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app
  namespace: default
  labels:
    app: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "server"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
        dapr.io/config: "serverconfig"
spec:
      containers:
      - name: helloworld
        image: myrepo/helloworld:v1
        imagePullPolicy: Never #it's local
        ports:
        - containerPort: 50051
```
4. Applying the config for the test client:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "testapp"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50007"
        dapr.io/config: "serverconfig"
    spec:
      containers:
      - name: foo
        image: myrepo/testapp:v1
        imagePullPolicy: Never
        ports:
          - containerPort: 50007
```

Any idea why this is not working? I check the logs on the server and it's listening on the port but the client apparently cannot find it. Again, as I mentioned, the app works locally using `dapr run`. I also checked the dapr app name and they are consistent.
