### ISSUE TITLE
Operator stream EOF error every 60 minutes in daprd sidecar - Dapr v1.5.0, K8s 1.20.9

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#3946]
Across multiple kubernetes clusters, in both HA and Single instance configurations we see this error every 60 minutes on the dot. This then causes all components to be reloaded when the connection is re-established and exacerbates an issue with connections.

## Expected Behavior
Should not see an EOF error or reload components

## Actual Behavior
EOF logged every 60 minutes
`"error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF","scope":"dapr.runtime","time":"2021-11-25T12:06:38.347853275Z","type":"log","ver":"1.5.0"}`

Causes components to reload which exacerbates this issue - https://github.com/dapr/components-contrib/issues/1318

## Steps to Reproduce the Problem

- Dapr v1.5.0
- K8s 1.20.9
- Run a POD with multiple components
- Wait 60+ minutes, observe that EOF is displayed in daprd logs

## Release Note

Fix operator EOF

**Comment by Taction** [comment]
@slacksach I'm using Dapr v1.5.0 in one cluster, haven't reproduced this EOF issue. If you are using cross clusters, have you checked if those daprd in the same cluster have the same problem? This may be related to the configuration of the gateway.

Besides, components are only reloaded when their definition is updated. Disconnect with the operator will case daprd get the current components list, but will not recreate the component not changed.

The recreation of component will not close the old one, I will look into this later.

**Comment by slacksach** [comment]
> @slacksach I'm using Dapr v1.5.0 in one cluster, haven't reproduced this EOF issue. If you are using cross clusters, have you checked if those daprd in the same cluster have the same problem? This may be related to the configuration of the gateway.
> 
> Besides, components are only reloaded when their definition is updated. Disconnect with the operator will case daprd get the current components list, but will not recreate the component not changed.
> 
> The recreation of component will not close the old one, I will look into this later.

Thanks @Taction, we are using Dapr in 6 clusters at present but all within multiple AZ's in Azure. All exhibiting this same EOF issue.
Occurs across k8s versions - K8s 1.20.9, 1.20.7 and 1.20.5 and Dapr versions 1.4.x and 1.5, need to test 1.5.x

**Comment by yaron2** [comment]
I think I found the issue, will be fixed for `1.6`.

**Comment by yaron2** [comment]
@slacksach I tried reproducing this in multiple environments and couldn't get the EOF error after 60m. Did you get to try this without Istio? is there any other operation that triggers any sidecar changes every 60m?

**Comment by slacksach** [comment]
Thanks @yaron2, I'm not aware of anything that would trigger a change each 60 minutes but I'll do some more digging.

**Comment by Dazfl** [comment]
We are experiencing the same issue ... every 60 minutes we see the same error (`error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF`).

We are running a similar environment to @slacksach ... Dapr, K8s and Istio
Dapr - 1.5.1
K8s - 1.22.3-gke.700
Istio - 1.10.2

**Comment by yaron2** [comment]
> We are experiencing the same issue ... every 60 minutes we see the same error (`error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF`).
> 
> We are running a similar environment to @slacksach ... Dapr, K8s and Istio Dapr - 1.5.1 K8s - 1.22.3-gke.700 Istio - 1.10.2

Seems like Istio is the common element here.

**Comment by yaron2** [comment]
See here https://github.com/istio/istio/issues/23435.

Looks like the idleTimeout setting should be changed (defaults to 60m)

**Comment by slacksach** [comment]
Thanks @yaron2, we've been attempting to reproduce this issue locally via MiniKube, will look into the idleTimeout to see if it helps.

**Comment by slacksach** [comment]
@yaron2 @Dazfl I was able to cause this error by executing a restart on the dapr-operator deployment, I'm going to see if I can get it to occur downstream
{"app_id":"daprpublisherrepro-api","instance":"daprpublisherrepro-api-9b8498596-2g9q4","level":"error","msg":"error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF","scope":"dapr.runtime","time":"2022-01-10T12:09:30.736656089Z","type":"log","ver":"1.5.1"}

**Comment by yaron2** [comment]
> @yaron2 @Dazfl I was able to cause this error by executing a restart on the dapr-operator deployment, I'm going to see if I can get it to occur downstream. I looked into the idleTimeout (thanks for this @yaron2), unfortunately it looks like the istio team never implemented this via DestinationRule so I've asked them to re-open that, I've tried implementing via an EnvoyFilter, oddly I'm unable to get it to fail on Idle Timeout at all, even when set to 1s instead of 60 minutes. Will keep digging
> 
> > See here [istio/istio#23435](https://github.com/istio/istio/issues/23435).
> > Looks like the idleTimeout setting should be changed (defaults to 60m), or perhaps removed from the sidecar to control plane communication path.
> 
> {"app_id":"daprpublisherrepro-api","instance":"daprpublisherrepro-api-9b8498596-2g9q4","level":"error","msg":"error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF","scope":"dapr.runtime","time":"2022-01-10T12:09:30.736656089Z","type":"log","ver":"1.5.1"}

Actually EOF is exactly what you're supposed to see if the operator restarts, it just means the gRPC connection on the other side died. Unless your operator restarts itself every 60m (and then we should find out why) this doesn't seem to reproduce what's happening in your environment.

**Comment by slacksach** [comment]
Thanks @yaron2, yeah, I'm working through the many logs to try and correlate the behaviour, the EOF is always followed immediately by a component re-load, this error also appears

{"app_id":"my-api","instance":"my-api-64f586cf47-8ph79","level":"debug","msg":"received unauthorized component update, ignored. name: test, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T15:49:19.624804438Z","type":"log","ver":"1.5.1"}

**Comment by slacksach** [comment]
Update, on this particular issue, this appears to be just be a case of this scenario:
app-1 - 1 component with scope - app-1
app-2 - 1 component with scope - app-2

{"app_id":"my-api","instance":"my-api-64f586cf47-8ph79","level":"debug","msg":"received unauthorized component update, ignored. name: test, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T15:49:19.624804438Z","type":"log","ver":"1.5.1"}

When app-2 is created, the component update is also received by app-1 but app-1 discards is as unauthorised, as the level is debug I suspect this is just noise.

Now to the good news, I've been able to reproduce the component re-load error locally in MiniKube, however, the solution to the idleTimeout via istio is one that could very well result in leaking connections as setting 0s essentially never considers a connection as timed out, however, that aside, I've added an EnvoyFilter locally to Istio globally, it does not however seem to result in any change to the 60 minute rule, continuing to investigate.

The investigations continue.

**Comment by slacksach** [comment]
Success, here's a quick global Istio EnvoyFilter that will cause the following to happen quickly,
1. Operator EOF
2. Component reload (due to [1] above)
3. Connection Count growth (due to reload of components)
```
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"error","msg":"error from operator stream: rpc error: code = Unavailable desc = error reading from server: EOF","scope":"dapr.runtime","time":"2022-01-10T23:58:07.464489823Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsuba, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.467731623Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsubb, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.467835228Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsubc, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.467898258Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsubd, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.467947938Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsube, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.467992708Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received unauthorized component update, ignored. name: pubsubf, type: pubsub.rabbitmq/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.468035148Z","type":"log","ver":"1.5.1"}
{"app_id":"daprstaterepro-api","instance":"daprstaterepro-api-57d47445b4-r5x4n","level":"debug","msg":"received component update. name: statestore, type: state.mongodb/v1","scope":"dapr.runtime","time":"2022-01-10T23:58:07.468081038Z","type":"log","ver":"1.5.1"}
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: companies-api-experiment
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            idle_timeout: 5s
```

**Comment by slacksach** [comment]
@Dazfl @yaron2 here's a more targeted version, specifically for the dapr-operator,
Set idle_timeout: to 0s to disable the timeout just for inbound traffic to dapr-operator on port 6500.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: companies-api-experiment
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: dapr-operator
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 6500
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            idle_timeout: 10s
```
