### ISSUE TITLE
PostgreSQL and Secrets, "Missing postgreSQL connection string"

### ISSUE THREAD

**Issue by cero-t** [dapr/dapr#3992]
## In what area(s)?

> /area runtime

## Ask your question here

I tried to use PostgreSQL datastore with its connection string in secrets, but I could not start it successfully.

components/postgresql-store.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresql-store
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: postgresql-secret
      key: connection
```

components/postgresql-secret.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresql-secret
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/postgresql-secret.json
```

components/postgresql-secret.json
```json
{
  "connection": "host=localhost user=postgres password=secretpassword port=5432 connect_timeout=10 database=postgres"
}
```

And ran PostgreSQL on docker.
```
docker run -d --name dapr_postgres -p 5432:5432 -e POSTGRES_PASSWORD=secretpassword postgres
```

I started dapr by this command.
```
dapr run --app-port 8080 --components-path ./components ./mvnw spring-boot:run
```

or started without my appliction
```
dapr run --components-path ./components
```

But this error occurred.
```
WARN[0000] component postgresql-store references a secret store that isn't loaded:   app_id=Ringerquilt-Foot instance=macmini scope=dapr.runtime type=log ver=1.5.0
ERRO[0000] Missing postgreSQL connection string          app_id=Ringerquilt-Foot instance=macmini scope=dapr.contrib type=log ver=1.5.0
WARN[0000] error initializing state store postgresql-store (state.postgresql/v1): missing connection string  app_id=Ringerquilt-Foot instance=macmini scope=dapr.runtime type=log ver=1.5.0
WARN[0000] process component error daprd process will exited, gracefully to stop  app_id=Ringerquilt-Foot instance=macmini scope=dapr.runtime type=log ver=1.5.0
```

Am I doing something wrong? Or doesn't the PostgreSQL statestore component support the secretKeyRef yet?

Thanks.

**Comment by cero-t** [comment]
I confirmed the secret string could be get propery (without postgresql-store.yaml).

When I used secrets API directly,
```
curl localhost:49428/v1.0/secrets/postgresql-secret/connection 
```

and I got connection string.
```json
{"connection":"host=localhost user=postgres password=secretpassword port=5432 connect_timeout=10 database=postgres"}
```

**Comment by cero-t** [comment]
I'm sorry, I solved it myself. I misunderstood the spec of secrets.

It works well with the following configuration.
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresql-store
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: connection
      key: connection
auth:
  secretStore: postgresql-secret
```
