### ISSUE TITLE
Unable to retrieve secret from Kubernetes secret store

### ISSUE THREAD

**Issue by guyzyl** [dapr/dapr#4004]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area operator

## Ask your question here
I'm having issues retreiving secrets from a Kubernetes secret store.

I created the k8s secret:
`kubectl create secret generic secret-store --from-literal=hello=world`

I defined the following Dapr secret store component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: ""
```

And when I try to retrieve the secret:
`curl http://localhost:3500/v1.0/secrets/secret-store/hello`

I receive an error that the secret doesn't exist:
`{"errorCode":"ERR_SECRET_GET","message":"failed getting secret with key hello from secret store secret-store: secrets \"hello\" not found"}`

I'm running it all on minikube, with Dapr deployed using the Helm chart.
