### ISSUE TITLE
ERR_DIRECT_INVOKE: fail to invoke: app channel is not initialized

### ISSUE THREAD

**Issue by geekgao** [dapr/dapr#4017]
We deploy app to k8s cluster (TLS disabled). But app caller is error, like this:

```
-68time="2021-12-10T06:51:19.208123551Z" level=debug msg="retry count: 1, grpc call failed, ns: default, addr: policy-dapr.default.svc.cluster.local:50002, appid: policy, err: rpc error: code = Internal desc = app channel is not initialized" app_id=idp instance=idp-5dfd6bcc8d-mlz6j scope=dapr.runtime.direct_messaging type=log ver=1.5.1
-672021-12-10 06:51:20.210 ERROR 1 --- [nio-9000-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.dapr.exceptions.DaprException: ERR_DIRECT_INVOKE: fail to invoke, id: policy, err: rpc error: code = Internal desc = app channel is not initialized] with root cause
-66
-65io.dapr.exceptions.DaprException: ERR_DIRECT_INVOKE: fail to invoke, id: policy, err: rpc error: code = Internal desc = app channel is not initialized
-64        at io.dapr.client.DaprHttp$ResponseFutureCallback.onResponse(DaprHttp.java:350) ~[dapr-sdk-1.2.0.jar!/:na]
-63        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.0.jar!/:na]
-62        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
-61        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
-60        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
-59        Suppressed: java.lang.Exception: #block terminated with an error
-58                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.7.jar!/:3.4.7]
```

**io.dapr.exceptions.DaprException: ERR_DIRECT_INVOKE: fail to invoke, id: policy, err: rpc error: code = Internal desc = app channel is not initialized**  

Any suggestions?

---
This is my k8s conf piece:

```
spec:
  replicas: 4
  selector:
    matchLabels:
      app: accountrpc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accountrpc
      annotations:
        dapr.io/app-id: policy
        dapr.io/app-port: '50052'
        dapr.io/app-protocol: grpc
        dapr.io/enabled: 'true'
        dapr.io/sidecar-memory-request: 128Mi
    spec:
      containers:
        - name: accountrpc
          image: accountrpc:v1
          ports:
            - containerPort: 50052
              protocol: TCP
```

seems the port and host is ok:
```

root@testdapr-675dbdddb7-wq4jt:/app# curl --http0.9 http://policy-dapr.default.svc.cluster.local:50002 -vvv
*   Trying 172.17.5.50:50002...
* Connected to policy-dapr.default.svc.cluster.local (172.17.5.50) port 50002 (#0)
> GET / HTTP/1.1
> Host: policy-dapr.default.svc.cluster.local:50002
> User-Agent: curl/7.74.0
> Accept: */*
> 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```
Network is works.
