### ISSUE TITLE
grpc occur last connection error: connection closed error when cert expires 

### ISSUE THREAD

**Issue by fanspace** [dapr/dapr#4063]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
dapr version  1.5.1   kubernetes  1.18
I build a grpc project in k8s base on 
https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/
it works, 
but after a day, the clinet can not connect to server, it occur  **last connection error: connection closed** error.

below is a part of dapr logs,

`
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"starting workload cert expiry watcher. current cert expires on: 2021-12-28 07:09:29 +0000 UTC","scope":"dapr.runtime.grpc.internal","time":"2021-12-27T06:54:29.608029857Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"application discovered on port 7999","scope":"dapr.runtime","time":"2021-12-27T06:54:29.608694381Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s","scope":"dapr.runtime.actor","time":"2021-12-27T06:54:29.609024459Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"dapr initialized. Status: Running. Init Elapsed 41.609274ms","scope":"dapr.runtime","time":"2021-12-27T06:54:29.609078349Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"placement tables updated, version: 0","scope":"dapr.runtime.actor.internal.placement","time":"2021-12-27T06:54:29.629276474Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"renewing certificate: requesting new cert and restarting gRPC server","scope":"dapr.runtime.grpc.internal","time":"2021-12-27T23:52:59.608485156Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"sending workload csr request to sentry","scope":"dapr.runtime.grpc.internal","time":"2021-12-27T23:52:59.608699648Z","type":"log","ver":"1.5.1"}
{"app_id":"testgw","instance":"testgw-7b86c498d-bzj7c","level":"info","msg":"certificate signed successfully","scope":"dapr.runtime.grpc.internal","time":"2021-12-27T23:52:59.640364984Z","type":"log","ver":"1.5.1"}`

it looks normal.  singed certificate with 24hour life cycle, and resinged automatically, 
but after old cert expired on 2021-12-28 07:09:29,
(at logs line 1 "msg":"starting workload cert expiry watcher. current cert expires on: 2021-12-28 07:09:29 +0000)
clinet can not connect server immediately.
it will work again when client restart

**Comment by yaron2** [comment]
What is the "client" in your scenario? is it the app calling Dapr?

If the client is your app, when you say "restart" you mean the pod being restarted?

Also, can you run your app with the `dapr.io/log-level: debug` annotation and paste the updated logs here?

**Comment by fanspace** [comment]
thanks for your help
the "client" means  grpc client app,    which connect grpc port 50001,  and  this client app  is a  restful web service at port 7999
the "server" is my grpc server app, which  listening  at  port such as  8099 ...
when clinet occur connect closed,   i  had to  cmd  "kubectl delete pod xxsxxxx"  ,   the grpc client pod  will restart and all it works again
due to i dunno how to setup a shoter cert life cycle,  i can only get debug logger  after 24 hours.
*******************************************************************************************************************
**### grpc server**

**main**
```
var SGrpcService = entrypoint.SGrpcService{}
listen, err := net.Listen("tcp", "0.0.0.0" + settings.Cfg.ServiceSettings.ListenAddress) // :7999
if err != nil {
   log.Error(err.Error())
   os.Exit(1)
}
s := grpc.NewServer()
training.RegisterSGrpcServer(s, SGrpcService)
log.Info(" Grpc Server Starting on " + settings.Cfg.ServiceSettings.ListenAddress)
s.Serve(listen)

```
**service**
```
func SayHello(req *pb.TestMInfo)(*pb.CommonStrResponse, error) {
   res := new(pb.CommonStrResponse)
   if req.Name == "" {
      return res,  errors.New("wrong params")
   }

   res.Success = true
   res.Res = "Hello " + req.Name
   return res, nil
}

```
### **grpc client**
 
**service**
```
func SayHello(req *pb.TestMInfo) (*pb.CommonStrResponse, error){
   pool,err := GetGrpcPool("trpc")   // connect grpc on port 50001
   if err != nil {
      log.Error(err.Error())
      return nil, err
   }
   defer pool.Close()
   c := pb.NewSGrpcClient(pool)
   ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
   defer cancel()
   ctx = metadata.AppendToOutgoingContext(ctx, "dapr-app-id", "testgrpcm")
   r, err := c.SayHello(ctx, req)
   if err != nil {
      log.Error(err.Error())
   }
   return r, err
}

func dialgrpc(address string) (*grpc.ClientConn,error) {
   conn, err := grpc.Dial(address, grpc.WithInsecure(), grpc.WithBlock())
   if err != nil {
      log.Error(err.Error())
      return nil, err
   }
   return conn, err
}


func GetGrpcPool(grpcname  string) (*grpc.ClientConn, error) {
   //conn :=  GrpcPools[grpcname]
   //if conn == nil {
      if addr, ok := settings.Cfg.GrpcSettings[grpcname]; ok {   // port : 50001
         return dialgrpc(addr)
      } else {
         return nil,  errors.New(relations.CUS_ERR_4004)
      }
   //}
   //return conn, nil
}

```

### **main**
```
srv := server.NewServer()
   defer srv.ShutDown()
   // go rabbitmq.InitRabConsumer()
   srv.Router = router  // gin router
   err := srv.Start()  // gin start
   if err != nil {
      log.Error(err.Error())
      log.Info("Server has stopped")
      os.Exit(0)
   }
```

**********************************************************************************
### **k8s  yaml**

Client App 
```

apiVersion: v1
kind: Service
metadata:
  name: testgw
  namespace: dapr 
  labels:
    app: testgw
spec:
  selector:
    app: testgw
  ports:
  - protocol: TCP
    port: 7999
    targetPort: 7999
    nodePort: 32021
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgw
  namespace: dapr
  labels:
    app: testgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgw
  template:
    metadata:
      labels:
        app: testgw
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "testgw"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "7999"
        dapr.io/config: "dapronlyzipkinconfig"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: testgw
        image: 192.168.0.239:5000/testgwk8s:1.2
        ports:
        - containerPort: 7999
        imagePullPolicy: Always
```

**Server App**

```
apiVersion: v1
kind: Service
metadata:
  name: testgrpc-svc
  namespace: dapr 
  labels:
    app: testgrpc
spec:
  selector:
    app: testgrpc
  ports:
  - protocol: TCP
    port: 8099
    targetPort: 8099
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrpc-instance
  namespace: dapr 
  labels:
    app: testgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrpc
  template:
    metadata:
      labels:
        app: testgrpc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "testgrpc"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "8099"
        dapr.io/config: "dapronlyzipkinconfig"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: testgrpc
        image: 192.168.0.239:5000/testgrpck8s:1.2
        ports:
        - containerPort: 8099
        imagePullPolicy: Always

```

I test zipkin and elk , it all works
![11111](https://user-images.githubusercontent.com/14883295/147617678-00416200-0d04-4e30-a023-b935468368c8.png)
![2](https://user-images.githubusercontent.com/14883295/147617686-e03136b5-ee2f-48cd-960c-66f4eb962e19.png)


but i find sth in log
[GIN] 2021/12/29 - 08:33:54 | 404 |       3.484µs |       127.0.0.1 | PRI      "*"
[GIN] 2021/12/29 - 08:36:10 | 404 |       2.867µs |       127.0.0.1 | PRI      "*"
[GIN] 2021/12/29 - 08:38:00 | 404 |       3.252µs |       127.0.0.1 | PRI      "*"
[GIN] 2021/12/29 - 08:40:15 | 404 |       3.007µs |       127.0.0.1 | PRI      "*"
[GIN] 2021/12/29 - 08:42:20 | 404 |       2.991µs |       127.0.0.1 | PRI      "*"
i have no idea what it means
