### ISSUE TITLE
Dapr sidecar injector does not complete its job

### ISSUE THREAD

**Issue by abelperezok** [dapr/dapr#4074]
## In what area(s)?

> /area runtime

> /area operator

## What version of Dapr?

> 1.5.1

## Expected Behavior

After installing dapr runtime in the kubernetes cluster (EKS) I expect that a new deployment will trigger the sidecar injector to add a dapr sidecar to my pod.

## Actual Behavior

However, it seems to do this half-way, it creates a new service (my manifest didn't contain one) with the same name of the deployment and a suffix "-dapr", but my pod keeps as 1/1 Running. 

## Steps to Reproduce the Problem

I tried three different ways to deploy dapr to my cluster 

* via cli `dapr init -k`
* via helm with ha
* via helm without ha

None of them seem to make a difference. To simplify I settled with helm no-ha and `logLevel` set to `DEBUG` and some resource limits and requests as per recommendation, this is the `values.yaml` file:

```yaml
global:
  ha:
    enabled: false

dapr_operator:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "1"
  logLevel: DEBUG

dapr_sidecar_injector:
  resources:
    requests:
      memory: "30Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "1"
  logLevel: DEBUG

dapr_sentry:
  resources:
    requests:
      memory: "30Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "1"
  logLevel: DEBUG

dapr_placement:
  resources:
    requests:
      memory: "75Mi"
      cpu: "250m"
    limits:
      memory: "150Mi"
      cpu: "1"
  logLevel: DEBUG

dapr_dashboard:
  resources:
    requests:
      memory: "20Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  logLevel: DEBUG
```
Deploy dapr to my cluster using this helm command:

`helm upgrade --install dapr dapr/dapr   --version=1.5.1   --namespace dapr-system --create-namespace --values values.yaml --wait`

Inspect everything is deployed:

```
$ kubectl get all -n dapr-system 
NAME                                         READY   STATUS    RESTARTS   AGE
pod/dapr-dashboard-5b5cf466d9-fhsxs          1/1     Running   0          108s
pod/dapr-operator-54f9fb574c-r26lb           1/1     Running   0          108s
pod/dapr-placement-server-0                  1/1     Running   0          108s
pod/dapr-sentry-7cbd5bcb7b-t9jpm             1/1     Running   0          108s
pod/dapr-sidecar-injector-7f76c88cb8-xbszl   1/1     Running   0          108s

NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
service/dapr-api                ClusterIP   10.100.87.190   <none>        80/TCP               108s
service/dapr-dashboard          ClusterIP   10.100.228.41   <none>        8080/TCP             108s
service/dapr-placement-server   ClusterIP   None            <none>        50005/TCP,8201/TCP   108s
service/dapr-sentry             ClusterIP   10.100.15.251   <none>        80/TCP               108s
service/dapr-sidecar-injector   ClusterIP   10.100.49.139   <none>        443/TCP              108s
service/dapr-webhook            ClusterIP   10.100.246.44   <none>        443/TCP              108s

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dapr-dashboard          1/1     1            1           108s
deployment.apps/dapr-operator           1/1     1            1           108s
deployment.apps/dapr-sentry             1/1     1            1           108s
deployment.apps/dapr-sidecar-injector   1/1     1            1           108s

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/dapr-dashboard-5b5cf466d9          1         1         1       108s
replicaset.apps/dapr-operator-54f9fb574c           1         1         1       108s
replicaset.apps/dapr-sentry-7cbd5bcb7b             1         1         1       108s
replicaset.apps/dapr-sidecar-injector-7f76c88cb8   1         1         1       108s

NAME                                     READY   AGE
statefulset.apps/dapr-placement-server   1/1     108s

NAME                               AGE
configuration.dapr.io/daprsystem   109s
```

Deploy a very simple test deployment (taken from the docs) with annotations, this is the file `node-test.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
```
Next, deploy the yaml manifest via kubectl cli. 

```
$ kubectl apply -f node-test.yaml 
deployment.apps/nodeapp created
```

Inspect the pod in default namespace, see it gets 1/1 instead of 2/2 or even 1/2 with some errors. 

```
$ kubectl get pods 
NAME                       READY   STATUS    RESTARTS   AGE
nodeapp-86977644bf-ltm2v   1/1     Running   0          19s
```

Inspect the services in default namespace.

```
$ kubectl get svc
NAME           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                               AGE
kubernetes     ClusterIP   10.100.0.1   <none>        443/TCP                               352d
nodeapp-dapr   ClusterIP   None         <none>        80/TCP,50001/TCP,50002/TCP,9090/TCP   73s
```
There is in fact a new services that is not part of the manifest above. 

Inspecting the logs from the sidecar injector, that's all I can see, which is not a lot considering it's set to debug.

```
$ kubectl logs -l app=dapr-sidecar-injector -n dapr-system
time="2021-12-31T10:23:20.28080175Z" level=info msg="log level set to: DEBUG" instance=dapr-sidecar-injector-7f76c88cb8-xbszl scope=dapr.injector type=log ver=unknown
time="2021-12-31T10:23:20.287660639Z" level=info msg="metrics server started on :9090/" instance=dapr-sidecar-injector-7f76c88cb8-xbszl scope=dapr.metrics type=log ver=unknown
time="2021-12-31T10:23:20.287918191Z" level=info msg="starting Dapr Sidecar Injector -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368" instance=dapr-sidecar-injector-7f76c88cb8-xbszl scope=dapr.injector type=log ver=unknown
time="2021-12-31T10:23:20.294688331Z" level=info msg="Healthz server is listening on :8080" instance=dapr-sidecar-injector-7f76c88cb8-xbszl scope=dapr.injector type=log ver=unknown
time="2021-12-31T10:23:20.342776209Z" level=info msg="Sidecar injector is listening on :4000, patching Dapr-enabled pods" instance=dapr-sidecar-injector-7f76c88cb8-xbszl scope=dapr.injector type=log ver=unknown
```

Inspecting the logs from the operator, this is what I see:

```
$ kubectl logs -l app=dapr-operator -n dapr-system
time="2021-12-31T10:23:22.648268454Z" level=info msg="Successfully patched webhook in CRD \"subscriptions.dapr.io\"" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator type=log ver=unknown
time="2021-12-31T10:23:23.250022707Z" level=info msg="certificates detected" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator type=log ver=unknown
time="2021-12-31T10:23:23.250218933Z" level=info msg="tls certificates loaded successfully" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator type=log ver=unknown
time="2021-12-31T10:23:23.251309199Z" level=info msg="Healthz server is listening on :8080" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator type=log ver=unknown
time="2021-12-31T10:23:23.251236324Z" level=info msg="starting gRPC server" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator.api type=log ver=unknown
I1231 10:23:37.812139       1 leaderelection.go:253] successfully acquired lease dapr-system/webhooks.dapr.io
I1231 10:23:38.213286       1 leaderelection.go:253] successfully acquired lease dapr-system/operator.dapr.io
time="2021-12-31T10:29:28.091732407Z" level=debug msg="no service for deployment found, deployment: default/nodeapp" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator.handlers type=log ver=unknown
time="2021-12-31T10:29:28.091873278Z" level=debug msg="enableMetrics: true" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator.handlers type=log ver=unknown
time="2021-12-31T10:29:28.115135878Z" level=debug msg="created service: default/nodeapp-dapr" instance=dapr-operator-54f9fb574c-r26lb scope=dapr.operator.handlers type=log ver=unknown
```

These are the logs from placement server:

```
$ kubectl logs -l app=dapr-placement-server -n dapr-system
time="2021-12-31T10:23:22.30186249Z" level=debug msg="votes%!(EXTRA []interface {}=[needed 1])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.5.1
time="2021-12-31T10:23:22.301880426Z" level=debug msg="vote granted%!(EXTRA []interface {}=[from dapr-placement-0 term 2 tally 1])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.5.1
time="2021-12-31T10:23:22.301891832Z" level=debug msg="election won%!(EXTRA []interface {}=[tally 1])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.5.1
time="2021-12-31T10:23:22.301905706Z" level=debug msg="entering leader state%!(EXTRA []interface {}=[leader Node at 127.0.0.1:8201 [Leader]])" instance=dapr-placement-server-0 scope=dapr.placement.raft type=log ver=1.5.1
time="2021-12-31T10:23:23.250471283Z" level=info msg="certificates detected" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
time="2021-12-31T10:23:23.250588085Z" level=info msg="tls certificates loaded successfully" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
time="2021-12-31T10:23:23.250614509Z" level=info msg="placement service started on port 50005" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
time="2021-12-31T10:23:23.252695682Z" level=info msg="cluster leadership acquired" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
time="2021-12-31T10:23:23.251580746Z" level=info msg="Healthz server is listening on :8080" instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
time="2021-12-31T10:23:23.255296003Z" level=info msg="leader is established." instance=dapr-placement-server-0 scope=dapr.placement type=log ver=1.5.1
```

The logs from sentry:

```
$ kubectl logs -l app=dapr-sentry -n dapr-system
time="2021-12-31T10:23:21.755778275Z" level=info msg="Healthz server is listening on :8080" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:23.685422816Z" level=warning msg="issuer credentials changed. reloading" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:23.685579499Z" level=info msg="certificate authority loaded" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:24.685505545Z" level=warning msg="issuer credentials changed. reloading" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:24.694114225Z" level=info msg="trust root bundle loaded. issuer cert expiry: 2022-12-31 10:23:21 +0000 UTC" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:24.69571272Z" level=info msg="validator created" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:24.695752327Z" level=info msg="sentry certificate authority is running, protecting ya'll" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:25.685641524Z" level=warning msg="issuer credentials changed. reloading" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:26.68606082Z" level=warning msg="issuer credentials changed. reloading" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
time="2021-12-31T10:23:27.686858708Z" level=warning msg="issuer credentials changed. reloading" instance=dapr-sentry-7cbd5bcb7b-t9jpm scope=dapr.sentry type=log ver=unknown
```

I can see no errors in any of the logs, could anyone point me out where else to look for some more information ? 

### Additional information 

The cluster I'm using is hosted on Amazon EKS, this is the version:

```
$ kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.2-eks-0389ca3
```

I tried all this in a computer running minikube and it works 100% correctly.

In the past I've had issues deploying additions to the cluster due to the network CNI, I'm using Calico from https://docs.projectcalico.org/manifests/calico-vxlan.yaml, I only tweaked the IPv4 pool CIDR to a different range. Most issues were related to the control plane not being able to  reach the pods and services (due to calico networking) so I had to set the `hostNetwork` to `true` is several occasions. Could this be the case this time ?

## Release Note

RELEASE NOTE: Not sure what to put here, it might be a condition specific of my cluster and not actual bug.
