### ISSUE TITLE
How to implement multiple publisher and subscriber using Dapr for the same Azure Storage Account?

### ISSUE THREAD

**Issue by viveknuna** [dapr/dapr#4112]
I have implemented two sets of Publisher and Subscriber applications (Pub1, Sub1)and (Pub2, Sub2). which are using the same container in the storage account.

At a given time only one set of publisher and subscriber is working. for example, only Pub1 and Sub1 set is sending and receiving messages. But Pub2 and Sub2 set is not working.

Also, the Lease Status is **Leased**.

I have tried creating a different container **daprstatenew** as well within the same storage account, but this is also not working.

For now, I have found only one solution to make it work is to create a different storage account for different Publisher and Subscriber sets.

Is there any way to make it work only in one storage account? because I don't think it is good practice to create different storage accounts for each set.

This is my dapr configuration file content:

```
apiVersion: dapr.io/v1alpha1

kind: Component

metadata:

name: emailservice

spec:

type: pubsub.azure.eventhubs

version: v1

metadata:

- name: connectionString

  value: XXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

- name: consumerGroup         # EventHubs consumer group

  value: pendingemailsconsumer

- name: storageAccountName

  value: safxpaymentsdev

- name: storageAccountKey

  value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx

- name: storageContainerName

  value: daprstate
```
