### ISSUE TITLE
Globally manage DAPR options in kubernetes

### ISSUE THREAD

**Issue by Banchio** [dapr/dapr#4122]
/area runtime

Wondering if a way exists to globally set an option like dapr.io/http-max-request-size or dapr.io/http-read-buffer-size. I have several services in kubernetes cluster and instead of putting everywhere these settings I would like to set and manage those centrally (maybe overridden by the deployment itself). Is it possible?

Thanks

**Comment by Taction** [comment]
Thanks, I think the global configuration makes sense. 
Add a configMap maybe named `dapr-config-sidecar` contains configuration items for the sidecar, injector gets this config map content at startup and uses configs defined as the default value. example:
```
apiVersion: v1
data:
  http-max-request-size: "4"
  http-read-buffer-size: "4"
  # ... more configs
kind: ConfigMap
```
Configs from annotions > configs defined in config map > default value.

WDYT? @yaron2
