### ISSUE TITLE
High cardinality of path label overloads Prometheus

### ISSUE THREAD

**Issue by geertn** [dapr/dapr#4133]
Related issue: https://github.com/dapr/dapr/issues/1624

Dapr 1.5.1

I'm using Prometheus to monitor Dapr sidecars. I've got a high volume service in which many different paths are being called. Therefore the path label has high cardinality and I'm ending up with huge amounts of data (20MB+ on each scrape run) and Prometheus memory usage. 

We end up with huge amounts of time series like the following:
```
dapr_http_client_completed_count{app_id="appx",dapr_io_enabled="true",instance="10.2.8.2:9090",job="kubernetes-service-endpoints",method="GET",namespace="appx-ns",node="aks-systempool-vmss000003",path="appx/xxxx-3d21-4ed1-9590-xxx/addresses/xxxx-6c74-4c9b-bf11-xxx",service="appx-dapr",status="200",cluster="x"} 1 1641981974242
dapr_http_client_completed_count{app_id="appx",dapr_io_enabled="true",instance="10.2.8.2:9090",job="kubernetes-service-endpoints",method="GET",namespace="appx-ns",node="aks-systempool-vmss000003",path="appx/xxxx-7e42-234d-af2d-xxx/addresses/xxxx-9c97-234d-bc19-xxx",service="appx-dapr",status="200",cluster="x"} 1 1641981974242
dapr_http_client_completed_count{app_id="appx",dapr_io_enabled="true",instance="10.2.8.2:9090",job="kubernetes-service-endpoints",method="GET",namespace="appx-ns",node="aks-systempool-vmss000003",path="appx/xxxx-3040-234d-b350-xxx",service="appx-dapr",status="200",cluster="x"} 1 1641981974242
```

I can setup a relabel config to drop the label however that will still ingest 20MB+ from each pod every x seconds which is a problem. To work around this issue we had to disable dapr metrics completely for our high volume services.

I'd suggest either:
1. Dropping the path label
2. Make it configurable (on/off/path depth)

Some interesting discussions in other projects regarding the same type of issue:
https://github.com/prometheus/client_golang/issues/491
https://github.com/zsais/go-gin-prometheus/issues/36

**Comment by geertn** [comment]
Another related issue: https://github.com/dapr/dapr/issues/4703

**Comment by yaron2** [comment]
Triaged into 1.9. cc @artursouza @daixiang0

**Comment by artursouza** [comment]
We could offer a regex matching solution, so the path is replace by the pattern's "name":

Config:
```json
{
  "/customer/CUSTOMER_ID": "/customer/.+",
  "/order/ORDER_ID": "/order/.+"
}
```

Then the metric would have `path="/customer/CUSTOMER_ID"` instead of `path="/customer/123456567890"`

**Comment by shubham1172** [comment]
Prometheus has a relabel configuration that we can leverage:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

**Comment by geertn** [comment]
I believe you shouldn't allow the possibility of Dapr overloading monitoring systems (and possibly generating high costs when paying for amount of time series, which is a common thing). So the sensible thing would be to disable this by default. I'd rather have a generic way of configuring this so we don't have to adjust configs every time a developer adds new path.

**Comment by olvesh** [comment]
I just stumbled over this as well! 
The memory usage of the sidecar will be quite high if we were to fix this on ingest to Prometheus via relabelling, would like to have some way of configuring this. 
I understand that since this is a sidecar Dapr can not know what is an url-parameter and what is not, without some heuristics tool to do this.

Other solutions could be if the dapr-wrapped-app offers an OpenAPI description, the urls could be inferred from there.

**Comment by lmolkova** [comment]
I suggest following otel metrics spec here and remove path attribute altogether for service invocation. Perhaps it can stay as `http.route` for bindings as there (it seems) low-cardinality is guaranteed.

Since dapr metrics can't substitute in-app instrumentation anyway, applications can still report the level of details they need.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md

**Comment by yaron2** [comment]
> We could offer a regex matching solution, so the path is replace by the pattern's "name":
> 
> Config:
> 
> ```json
> {
>   "/customer/CUSTOMER_ID": "/customer/.+",
>   "/order/ORDER_ID": "/order/.+"
> }
> ```
> 
> Then the metric would have `path="/customer/CUSTOMER_ID"` instead of `path="/customer/123456567890"`

I think this design makes great sense. Instead of offering a simple remove path configuration, this allows mutating paths and including only the information that matters in the path.

As discussed with @artursouza the best place to put this would be in the Configuration CRD. I suggest the following:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
spec: 
  metrics:
    enabled: true
    configuration:
    - name: dapr_runtime_service_invocation_req_sent_total
      labels:
      - name: path
	regex:
          "/customer/CUSTOMER_ID": "/customer/.+"
          "/order/ORDER_ID": "/order/.+"
```

**Comment by geertn** [comment]
This looks like an elegant solution. However since paths can be added by persons/processes that might not be aware of the effect of the added cardinality this seems to still leave the possibility of adding a path without limiting the cardinality (or path depth) therefore still leaves open the possibility of overloading monitoring systems (or triggering rate limits etc).

For us to be able to enable the metrics by default we would need to be able to generically limit path depth without specifying each path. Did you think of this in this design? Can we for example do the following:

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
spec: 
  metrics:
    enabled: true
    configuration:
    - name: dapr_runtime_service_invocation_req_sent_total
      labels:
      - name: path
        regex:
          "/PLACEHOLDER": "/.+"
```

And given a large amount of paths (100k+) would this have a performance impact?
