### ISSUE TITLE
Getting seprate traces for the same code flow.

### ISSUE THREAD

**Issue by ankitkgcs** [dapr/dapr#4139]
## In what area(s)?

> /area runtime

> /area docs

## Ask your question here
I am setup two applications behind nginx ingress with dapr [setup.](https://dev.to/stevenjdh/create-a-kubernetes-nginx-controller-with-dapr-support-3e8n) When I am making a synchronous call from serviceA to serviceB I am getting two separate traces. First trace for ingress to srevice A and another trace for calling serviceB  from service A using invokeMethod(). As per documentation, I should be getting a single trace with entire flow.
   ```
   annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "serviceA"
        dapr.io/app-port: "8080"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
```

I am having below nginx configuration.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dapr
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /       
spec:
  ingressClassName: nginx
  rules:  
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-ingress-dapr
            port:
              number: 80
```  
dapr-config.yaml file has the following content.
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
```
