### ISSUE TITLE
Proposal: Configurable gRPC Middleware Pipelines

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#4153]
/area runtime
> /area operator
> /area placement
> /area docs

> /area test-and-release
## Describe the proposal
Allow Dapr to support user configurable gRPC middleware (interceptor) pipelines. I propose that we use a similar structure to how we currently support HTTP pipelines to make it consistent. This includes the definition of the middleware as components and the configuration of the middleware pipeline itself using the configuration file.
GRPC interceptors are different to HTTP middleware in that they can be applied to both client and server and support both unary and stream interceptors.
As the definition of the middleware component is separate to the configuration of the pipeline I'll break this proposal down into sections.

### GRPC Middleware Components
Unlike HTTP middleware which is defined by a single function signature, GRPC middleware (a.k.a. interceptors) comes in 4 types:
- [UnaryClient](https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/interceptor.go#L43)
- [StreamClient](https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/interceptor.go#L63)
- [UnaryServer](https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/interceptor.go#L84)
- [StreamServer](https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/interceptor.go#L101)

In order to support a future proof approach to gRPC middleware pipelines we should allow (not block) the eventual definition of all of these types as Dapr components types.

In terms of implementation, we can share a single GRPCMiddlewareRegistry that supports registering and creating different middleware types and just has multiple internal maps to avoid too much code pollution.
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: grpcmiddleware
spec:
  version: v1
  type: middleware.grpc.[server|client].[unary|stream]
  ...
```

### GRPC Middleware Pipelines
As mentioned above, for consistencies sake I think we should follow the same pattern as the HTTP middleware pipeline and use a configuration spec to define gRPC middleware pipelines too.
There are many locations within daprd where we either host a gRPC server or use a gRPC client.
I propose that we only allow users to configure the gRPC pipelines in the following places:
- Dapr's external gRPC API
- Dapr's gRPC app channel

And for now, not in the following places
- Dapr's internal gRPC API
- Dapr's internal gRPC client (for service invocation)
- Dapr's control plane clients

If we can think of a good use case to support user configurable gRPC interceptors on the daprd internal clients and servers then we can expand to support this later but I currently think this would cause more problems that it solves. However, I do propose we build the solution in a way that would support this later on if we wanted to add them.

#### Dapr's External gRPC API
Dapr's gRPC API can be configured using a `GRPCPipelineSpec` in the configuration file. Where `grpcPipeline` is the reserved name of the pipeline.
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: grpcpipeline
  namespace: default
spec:
  grpcPipeline:
    unary:
      - name: first
        type: middleware.grpc.server.unary.first
      - name: second
        type: middleware.grpc.server.unary.second
   stream:
      - name: first
         type: middleware.grpc.server.stream.first
      - name: second
         type: middleware.grpc.server.stream.second
```
We separate out the type of middleware into individual pipelines as they will be added to different interceptor chains on the gRPC server itself.

#### Dapr's gRPC App Channel
Dapr's gRPC App Channel is the channel over which `daprd` communicates with the user's app when configured to use the gRPC protocol. This means that we can construct a __client__ middleware pipeline for requests sent to the user's app. This will allow the users to avoid having to host additional middleware on their app's APIs when using gRPC. This is a lower priority feature than adding middleware to the Dapr gRPC API but I think it still offers some value to the user.
The app channel pipeline can be configured using a `GRPCAppPipelineSpec` in the configuration file. Where `grpcAppPipeline` is the reserved name of the pipeline.
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: grpcapppipeline
  namespace: default
spec:
  grpcAppPipeline:
    unary:
      - name: first
        type: middleware.grpc.client.unary.first
      - name: second
        type: middleware.grpc.client.unary.second
   stream:
      - name: first
         type: middleware.grpc.client.stream.first
      - name: second
         type: middleware.grpc.client.stream.second
```
### Diagram
![middelware drawio (1)](https://user-images.githubusercontent.com/7241190/150505472-0cc00271-847d-4181-94c8-3d9c80355db0.png)
