### ISSUE TITLE
when using consul for service name resolution, consul not do health check correctly in v1.6.0, but it works well on v1.5.1

### ISSUE THREAD

**Issue by hdget** [dapr/dapr#4169]
## In what area(s)?
/area runtime

## What version of Dapr?

> 1.6.0

## Expected Behavior

Assume using dapr to spawn an gateway http server(using gin) like this
```
dapr run --app-id gateway --app-port 8080--app-protocol grpc --config setting/dapr/config.yaml --components-path setting/dapr/components -- go run main.go
```

Here `go run main.go` try to start a gin http server and listen on port:8080

What we expect is the gateway service will be shown as healty in consul

## Actual Behavior

When using consul name resolution with dapr v1.5.1, the gateway service will be shown as healty status in consul management page quickly.  But if using consul name resolution with dapr v1.6.0, the same service took very long time to recogonize as healthy.

## Steps to Reproduce the Problem
- config.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      selfRegister: true
```

- gateway.go
```
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run()
}

```

Upgrading to v1.6.0 encounter above problem. And when using v1.5.1, the problem disappeared.

## Workaround

It need change `app-protocol` to `http` to workaround this issue. I checked `components-contrib/nameresolution/consul` codes between release-v1.5 and release-v1.6, but found no difference.
