### ISSUE TITLE
Multiple access control policies for a single app results in all of those operations being denied

### ISSUE THREAD

**Issue by gunniwho** [dapr/dapr#4202]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.6.0

## Expected Behavior

Expected app to be allowed to make a grpc service invocation when there is a policy in the access control config of the service being invoked that allows that app to perform that operation.

## Actual Behavior

When there are multiple policies in the service's access control config, none of them work.

## Steps to Reproduce the Problem

Create an access control config for a service like this

```
accessControl:
  defaultAction: deny
  policies:
  - appId: other-app
    namespace: app-namespace
    trustDomain: public
    operations:
    - action: allow
      name: SomeOperation
```

This works, i.e. when `other-app` in namespace `app-namespace` (they are actually both in the same namespace though) performs a grpc service invocation of an endpoint called `SomeOperation` , it is allowed. Now add two other endpoints to this ACL:

```
accessControl:
  defaultAction: deny
  policies:
  - appId: other-app
    namespace: app-namespace
    trustDomain: public
    operations:
    - action: allow
      name: SomeOperation
    - action: allow
      name: OtherOperation
    - action: allow
      name: YetAnotherOperation
```

Now none of these operations work anymore, i.e. if `other-app` performs a grpc service invocation of any of those endpoints, it will get a permission error.

I also noted that when used with the new grpc proxying feature, I had to specify the operation like `/Namespace/ServiceName/OperationName` and I had to include `httpVerb: [NONE]` for it to work (in the case of a single policy). Having to specify the namespace and service name is fine but it was a little surprising to have to include the http verb. Note that having multiple policies works under no circumstances.

I also noticed that I wasn't able to use the wildcard successfully, i.e. this would not work

```
accessControl:
  defaultAction: deny
  policies:
  - appId: other-app
    namespace: app-namespace
    trustDomain: public
    operations:
    - action: allow
      name: Get*
```

nor did this 

```
accessControl:
  defaultAction: deny
  policies:
  - appId: other-app
    namespace: app-namespace
    trustDomain: public
    operations:
    - action: allow
      name: /Namespace/ServiceName/Get*
      httpVerb: [NONE]
```

## Release Note

RELEASE NOTE: **FIX** multiple access control policies for a single app not working
