### ISSUE TITLE
dapr & istio - mTLS disabled missing DAPR_TRUST_ANCHORS

### ISSUE THREAD

**Issue by c-thiel** [dapr/dapr#4224]
## In what area(s)?

/area runtime
/area operator

## What version of Dapr?
1.6.0

## Actual Behavior
I am running istio with dapr. I have installed dapr with helm using the following configuration in namespace dapr-system:
```yaml
global:
  mtls:
    enabled: false
```

Upon sidecar injection with the following annotation in "namespace-b" with istio enabled I get the following error of dapr:

```yaml
annotations:
  dapr.io/app-id: api-administration
  dapr.io/app-port: "50050"
  dapr.io/enabled: "true"
```

I am getting the following Error:
`level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=api-administration instance=foo-administration-api-v1-65f66d888f-vj7z7 scope=dapr.runtime type=log ver=1.6.0`

I am not exactly sure where this is coming from but using the search I came accross this line:
https://github.com/dapr/dapr/blob/4cc5321eee383003ce34c6b105f12f867208a67c/pkg/runtime/cli.go#L227

If so, is this intentional to not be able to disable mTLS on kubernetes or am I missing something?

**Comment by c-thiel** [comment]
I re-installed dapr this morning, deleted all components and re-applied them. Without adding a single commit to the helm chart it is now working. Maybe I was just a little too fast in applying some annotations. Nevertheless, it's working now. Closing the issue.

**Comment by spolab** [comment]
I actually have the same problem with Traefik, the application pods keeps on restarting but at no point it gets stable.

**Comment by Itchimonji** [comment]
I have the same problem.

Here are the error logs from the dapr-sidecar:

```
time="2023-07-09T19:06:01.595999728Z" level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=app-123 instance=app-123 scope=dapr.runtime type=log ver=1.11.1
```

I deployed dapr with Helm and here are my configuration of the sidecar:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: test-tracing
  namespace: test
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
```

Does anyone have any idea what I'm doing wrong?
Thank you for help
