### ISSUE TITLE
Dapr sidecar not injected in Pod

### ISSUE THREAD

**Issue by jaredhshuai** [dapr/dapr#4270]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.6.0

## Expected Behavior

> When we create a Pod object in kubernetes, the sidecar injection should happen in the pod in question.

## Actual Behavior

> Sidecar injection does not happen if the kind is Pod and hence we can not communicate with any of the services from within the created Pod.

## Steps to Reproduce the Problem

**Environment** :

>  Kubernetes:  v1.23.3
> Weave Net:    v2.8.1
> Docker:         v20.10.12
> Dapr:            v1.6.0 
> Helm:            v3.8.0

**Steps:**

1. Deploy dapr using helm or cli.  -- both tried
```
helm upgrade --install dapr dapr/dapr \
--version=1.6 \
--namespace dapr-system \
--create-namespace \
--set global.logAsJson=true \
--wait
```

2. Create a Pod object to be deployed in kubernetes cluster. (YAML used for same is attached)
```
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service01
  namespace: dapr-demo
  labels:
    app: service01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service01
  template:
    metadata:
      labels:
        app: service01
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service01"
        dapr.io/app-port: "80"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-delay-seconds: "10"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: service01
          image: docker.io/k8schina/service01:v1
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service02
  namespace: dapr-demo
  labels:
    app: service02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service02
  template:
    metadata:
      labels:
        app: service02
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service02"
        dapr.io/app-port: "80"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-delay-seconds: "10"
    spec:
      containers:
        - name: service02
          image: docker.io/k8schina/service02:v1
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service02
  namespace: dapr-demo
spec:
  type: NodePort
  selector:
    app: service02
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
```

3. We can observe that container in the pod is running successfully, however there's no sidecar injected, there is only one container in the pod.
```
kubectl get pods -n dapr-demo
---
NAME                         READY   STATUS    RESTARTS   AGE
service01-5fbb4864dd-pk5d7   1/1     Running   0          86s
service01-5fbb4864dd-tsbzl   1/1     Running   0          89s
service02-94d67f9d6-t79kb    1/1     Running   0          89s
```

```
kubectl describe pod service01-5fbb4864dd-pk5d7 -n dapr-demo
---
Name:         service01-5fbb4864dd-pk5d7
Namespace:    dapr-demo
Priority:     0
Node:         node-slave/192.168.0.204
Start Time:   Fri, 18 Feb 2022 22:00:11 +0800
Labels:       app=service01
              pod-template-hash=5fbb4864dd
Annotations:  dapr.io/app-id: service01
              dapr.io/app-port: 80
              dapr.io/enabled: true
              dapr.io/log-as-json: true
              dapr.io/sidecar-liveness-probe-delay-seconds: 10
              dapr.io/sidecar-readiness-probe-delay-seconds: 10
Status:       Running
IP:           10.44.0.7
IPs:
  IP:           10.44.0.7
Controlled By:  ReplicaSet/service01-5fbb4864dd
Containers:
  service01:
    Container ID:   docker://e2aeae021d532ee7c65dec9d087845f63ad5e7ab89549652a09121457890bac4
    Image:          docker.io/k8schina/service01:v1
    Image ID:       docker-pullable://k8schina/service01@sha256:8ead4a7aa2eac005badfbac0c615b2be930aada2a17994e7891b720c62da2abb
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 18 Feb 2022 22:01:34 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-f77br (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-f77br:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  16m   default-scheduler  Successfully assigned dapr-demo/service01-5fbb4864dd-pk5d7 to node-slave
  Normal  Pulling    16m   kubelet            Pulling image "docker.io/k8schina/service01:v1"
  Normal  Pulled     14m   kubelet            Successfully pulled image "docker.io/k8schina/service01:v1" in 1m22.295189838s
  Normal  Created    14m   kubelet            Created container service01
  Normal  Started    14m   kubelet            Started container service01
```

4. The operator is ok
```
kubectl logs -l app=dapr-operator -n dapr-system
---
I0218 13:59:05.848749       1 leaderelection.go:243] attempting to acquire leader lease dapr-system/operator.dapr.io...
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"getting tls certificates","scope":"dapr.operator","time":"2022-02-18T13:59:06.050702529Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"tls certificates loaded successfully","scope":"dapr.operator","time":"2022-02-18T13:59:06.050800079Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"starting gRPC server","scope":"dapr.operator.api","time":"2022-02-18T13:59:06.051057944Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"Healthz server is listening on :8080","scope":"dapr.operator","time":"2022-02-18T13:59:06.051135207Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"starting webhooks","scope":"dapr.operator","time":"2022-02-18T13:59:06.05300745Z","type":"log","ver":"1.6.0"}
I0218 13:59:06.053046       1 leaderelection.go:243] attempting to acquire leader lease dapr-system/webhooks.dapr.io...
{"instance":"dapr-operator-5654bb56b5-k22d8","level":"info","msg":"Successfully patched webhook in CRD \"subscriptions.dapr.io\"","scope":"dapr.operator","time":"2022-02-18T13:59:06.068665439Z","type":"log","ver":"1.6.0"}
I0218 13:59:21.629493       1 leaderelection.go:253] successfully acquired lease dapr-system/operator.dapr.io
I0218 13:59:21.909520       1 leaderelection.go:253] successfully acquired lease dapr-system/webhooks.dapr.io
```

5. The injector is ok.
```
kubectl logs -l app=dapr-sidecar-injector -n dapr-system
---
{"instance":"dapr-sidecar-injector-6958dbd87f-rxx6b","level":"info","msg":"log level set to: info","scope":"dapr.injector","time":"2022-02-18T13:59:04.605293494Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-sidecar-injector-6958dbd87f-rxx6b","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2022-02-18T13:59:04.605653707Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-sidecar-injector-6958dbd87f-rxx6b","level":"info","msg":"starting Dapr Sidecar Injector -- version 1.6.0 -- commit 4bb25fab444c4f1a1bf0ffd74293dbd4fdcea580","scope":"dapr.injector","time":"2022-02-18T13:59:04.605719153Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-sidecar-injector-6958dbd87f-rxx6b","level":"info","msg":"Healthz server is listening on :8080","scope":"dapr.injector","time":"2022-02-18T13:59:04.608339672Z","type":"log","ver":"1.6.0"}
{"instance":"dapr-sidecar-injector-6958dbd87f-rxx6b","level":"info","msg":"Sidecar injector is listening on :4000, patching Dapr-enabled pods","scope":"dapr.injector","time":"2022-02-18T13:59:04.63978181Z","type":"log","ver":"1.6.0"}
```

## Release Note

> **FIX** Dapr sidecar NOT injected in Pod.

**Comment by abelperezok** [comment]
I've got no experience with Weave network CNI, this is not the same situation I encountered with EKS and Calico. In this situation the control plain did reach the admission webhook and the container injection also happened. It's the injected container is the one suddenly crashing.
@jaredhshuai could you enable debug in your dapr deployment so you can see what exactly is not able to connect to ?
@yaron2 is it possible to do ? if so, how ?

**Comment by abelperezok** [comment]
@yaron2 At least with EKS-Calico it's not necessary to enable the hostNetworks other than the sidecar injector to achieve success.

**Comment by jaredhshuai** [comment]
hi @abelperezok 

- I have enabled debug in my darp deployment
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service02
  template:
    metadata:
      labels:
        app: service02
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service02"
        dapr.io/app-port: "80"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-delay-seconds: "10"
        dapr.io/log-as-json: "true"
        dapr.io/enable-debug: "true"
```

- Find error:
```
kubectl get pods -n dapr-demo
---
NAME                         READY   STATUS             RESTARTS        AGE
service01-7cc7c54c65-g4jzw   1/2     CrashLoopBackOff   9 (2m25s ago)   23m
service01-7cc7c54c65-gsf8c   1/2     CrashLoopBackOff   9 (107s ago)    23m
service02-6d849d9f97-mk286   1/2     CrashLoopBackOff   9 (104s ago)    23m
```
```
kubectl describe pod service02-6d849d9f97-mk286 -n dapr-demo
---
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  24m                    default-scheduler  Successfully assigned dapr-demo/service02-6d849d9f97-mk286 to node-slave
  Normal   Pulling    24m                    kubelet            Pulling image "docker.io/k8schina/service02:v1"
  Normal   Pulled     23m                    kubelet            Successfully pulled image "docker.io/k8schina/service02:v1" in 55.599760956s
  Normal   Created    23m                    kubelet            Created container service02
  Normal   Started    23m                    kubelet            Started container service02
  Normal   Pulled     22m (x4 over 23m)      kubelet            Container image "docker.io/daprio/daprd:1.6.0" already present on machine
  Normal   Created    22m (x4 over 23m)      kubelet            Created container daprd
  Warning  Failed     22m (x4 over 23m)      kubelet            Error: failed to start container "daprd": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/dlv": stat /dlv: no such file or directory: unknown
  Warning  BackOff    4m11s (x103 over 23m)  kubelet            Back-off restarting failed container

```
