### ISSUE TITLE
Should Dapr service use probe annotation instead of scrape

### ISSUE THREAD

**Issue by jjcollinge** [dapr/dapr#4272]
Currently the Dapr Kubernetes service uses the `prometheus.io/scrape` annotation. Given that `kubernetes_sd_configs` with a role of `service` uses the [Prometheus Blackbox](https://github.com/prometheus/blackbox_exporter) exporter, I think it's more idiomatic to use the `prometheus.io/probe` annotation.

This then works with a typical Prometheus configurations:
```yaml
 kubernetes_sd_configs:
        - role: service
        metrics_path: /probe
        params:
          module:
          - http_2xx
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_probe
         ...
```
Resulting in the services working as expected:
![image](https://user-images.githubusercontent.com/7241190/154728454-0d91878a-045b-43af-afd7-8c4a94b47460.png)

Change required here: https://github.com/dapr/dapr/blob/bdd702c480c87a046638154bdd7bd9a1afb828fa/pkg/operator/handlers/dapr_handler.go#L197
