### ISSUE TITLE
Keda ScaledJob - no sidecar

### ISSUE THREAD

**Issue by m-carter1** [dapr/dapr#4284]
Dapr CLI version: 1.6.0
Dapr Runtime version: 1.6.0
Dapr Client version: 1.6.0

I have a Keda ScaledJob deployed in Kubernetes which is scaled to zero and will scale up when a message is detected on a queue,  once it has run to completion it will shutdown, this is working fine

However, the dapr sidecar is not being injected so I am unable to call the other dapr services. 
There aren't any errors in the logs. 

please advise

yaml below

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: jobs-app
  namespace: jobs-app-namespace
  labels:
    deploymentName: jobs-app
spec:
  jobTargetRef:
    parallelism: 1 
    completions: 1 
    backoffLimit: 6 
    ttlSecondsAfterFinished: 259200
    template:
      metadata:
         labels:
           app: jobs-app
           aadpodidbinding: k8s-vault-identity
           version: 0.1.0
         annotations:
           dapr.io/enabled: "true"
           dapr.io/app-id: "jobapp"
           dapr.io/app-port: "5010"
      spec:
         containers:
         - name: jobs-app
           image: <acr-url>/jobsapp:latest
           ports:
           - containerPort: 5010
             protocol: TCP
           imagePullPolicy: Always
           env:
           - name: AzureVault__KeyVaultName
             value: "keyvault"          
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: keda__servicebus__connection
             valueFrom:
               secretKeyRef:
                 name: job-secret
                 key: SERVICEBUS_QUEUE_CONNECTIONSTRING        
         terminationGracePeriodSeconds: 30 
         nodeSelector:
           jobstype: JobPool1
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: jobstype
                   operator: In
                   values: 
                   - JobPool1
         tolerations:
           - key: podtype
             operator: "Equal"
             value: job
             effect: "NoSchedule"
         restartPolicy: OnFailure
  pollingInterval: 20  
  maxReplicaCount: 100 
  successfulJobsHistoryLimit: 200   
  failedJobsHistoryLimit: 200   
  scalingStrategy:
    strategy: "accurate" 
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: jobsqueue
      namespace: jobs-namespace
      messageCount: "1" 
      connectionFromEnv: keda__servicebus__connection
```
