### ISSUE TITLE
When version exists in labels of Deployment, dapr may not be able to complete the creation of svc

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4304]
/area operator

> 1.6.0

brief  deploy yml 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    version: v3-1-1236
  name: test-3.1.1236
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
      version: v3-1-1236
  template:
    metadata:
      annotations:
        dapr.io/app-id: test
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1000"
        dapr.io/log-level: debug
      labels:
        app: test
        version: v3-1-1236
    spec:
      containers:
      - image: test:v3-1-1236
```
svc yml at this time
```
#brief
apiVersion: v1
kind: Service
metadata:
  annotations:
    dapr.io/app-id:test
    prometheus.io/path: /
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    dapr.io/enabled: "true"
  name: test-dapr
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: test-3.1.1236
```

1.If I add a new version `Deployment`(3-1-1237)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    version: v3-1-1237
  name: test-3.1.1237
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
      version: v3-1-1237
  template:
    metadata:
      annotations:
        dapr.io/app-id: test
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1000"
        dapr.io/log-level: debug
      labels:
        app: test
        version: v3-1-1237
    spec:
      containers:
      - image: test:v3-1-1237
```
2. Then delete the previous version `Deployment`(3.1.1236)
3. `test-dapr` will not be created at this time
