### ISSUE TITLE
Create a specified or default label when Dapr sidecar is injected

### ISSUE THREAD

**Issue by blublinsky** [dapr/dapr#4366]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature
When using Prometheus operator https://github.com/prometheus-operator/prometheus-operator, the pods to scrape are defined using pod monitors https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#include-podmonitors  which are using matchLabels. Automatically creating well-defined labels will simplify pod monitors creation

## Release Note

Dapr Prometheus documentation https://docs.dapr.io/operations/monitoring/metrics/prometheus/ can/should be updated with sample pod monitors leveraging such labels

RELEASE NOTE:

**Comment by NickLarsenNZ** [comment]
@ItalyPaleAle can this please be reopened?

I'm wanting to create a single PodMonitor, but that only allows matching on labels.
Being able to add additional pod labels would be good too.

In the meantime, I'll just add a placeholder label on the pod so the PodMonitor can reference it.

**Comment by blublinsky** [comment]
I like `dapr.io/managed-by: sidecar-injector`

**Comment by NickLarsenNZ** [comment]
It would also be nice to add a label for whether the metrics server is enabled.

My use case is to have a single `PodMonitor` deployed alongside the dapr-operator, and have it scrape metrics across any sidecars. Eg:

```yml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dapr-sidecar
spec:
  selector:
    # see: https://github.com/dapr/dapr/issues/4366
    matchLabels:
      dapr.io/managed-by: sidecar-injector
      dapr.io/metrics-enabled: "true" # note, there is a real annotation called "dapr.io/enable-metrics", but I think this one should be past-tense
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: dapr-metrics
  podTargetLabels:
  - app
  - app.kubernetes.io/name
  - app.kubernetes.io/instance
  - app.kubernetes.io/version
  - app.kubernetes.io/component
  - app.kubernetes.io/part-of
  - app.kubernetes.io/managed-by
```
