### ISSUE TITLE
Dapr liveness and readiness probe failed in AKS

### ISSUE THREAD

**Issue by ankitkgcs** [dapr/dapr#4443]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
> 1.6.0

## Expected Behavior
Dapr liveness and readiness probe should pass.

## Actual Behavior
Dapr liveness and readiness probe failed.

## Steps to Reproduce the Problem
Provision a container in AKS that has a Dapr side-car.
Run the following command.
`kubectl describe pod <pod_name> -n <namespace>`

![image](https://user-images.githubusercontent.com/36360842/160623282-d7230a8e-0fd0-4e6b-a994-eac18fc0f7ac.png)

Even though the application is working fine but the dapr liveness and readiness probe is failing.

**Comment by wimvc1** [comment]
Do you have an `/healthz` endpoint?
Docs: https://docs.dapr.io/developing-applications/building-blocks/observability/sidecar-health/

**Comment by ankitkgcs** [comment]
Tested by adding `/healthz` endpoint but still the Dapr liveness and readiness probes are failing.
```
livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
````
![image](https://user-images.githubusercontent.com/36360842/162475946-60338805-bb8e-4ccc-8579-57222b2601fa.png)
