### ISSUE TITLE
Support defining a component on runtime

### ISSUE THREAD

**Issue by itsoli91** [dapr/dapr#4468]
Hi, 

Imagine I have defined a CRON Binding, how can I updated the CRON expression dynamically from my app?
Is it possible to change configuration of components on runtime?
My App Calls an API of sidecar --> define a component for itself.

**Comment by ItalyPaleAle** [comment]
Are you running on Kuberentes? One option could be to invoke the K8s APIs to change the component definition

**Comment by itsoli91** [comment]
Currently just using docker-compose for development, but soon we will use k8s for production.
But my question is more general: Is Dapr going to have this feature in future?

Just consider this example

Currently to setup cron binding we create a component of type bindings.cron like below and put this file inside k8s or inside a components folder beside docker-compose file:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 15m" # valid cron schedule
```

But what I need is something like this : when service and sidecar started and running, we should be able to call an api (usually with SDKs) with this body to setup the above component:

Call `https://{SIDECAR_ADD}:{SIDECAR_PORT}/v1.0/components/new`
```
{
  "apiVersion": "dapr.io/v1alpha1",
  "kind": "Component",
  "metadata": {
    "name": "<NAME>",
    "namespace": "<NAMESPACE>"
  },
  "spec": {
    "type": "bindings.cron",
    "version": "v1",
    "metadata": [
      {
        "name": "schedule",
        "value": "@every 15m"
      }
    ]
  }
}
```
