### ISSUE TITLE
General "Resiliency" question

### ISSUE THREAD

**Issue by wimvc1** [dapr/dapr#4568]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

 /area docs

> /area test-and-release

## Ask your question here

I have 2 general questions about the new "[resiliency](https://docs.dapr.io/operations/resiliency/resiliency-overview/#related-links)" features introduces as preview feature in Dapr v1.8

1. When applying `retry` and/or `circuit breaker` to an app or component, what logic does Dapr use to kick in those features? Is there a way to configure this logic?

Example:  `App 1` does a service to service call to `App 2`

When `App 2` returns a HTTP response with status code not in the `2XX` range, the `retry` and/or `CB` kicks in.
This is good for most `5XX` responses (or network related issues) but seems illogical for most `4XX` responses (like 400, 402, 404, ...)

 2. When applying a `retry` policy to an app and/or component, what happens when the application instance crashes? Will the retries be lost for that particular crashed instance?

**Comment by callebjo** [comment]
Great  question Wim ...  looking  forward to answers. (Y)

**Comment by halspang** [comment]
@wimvc1 - Thanks for raising this issue!

> When applying retry and/or circuit breaker to an app or component, what logic does Dapr use to kick in those features? Is there a way to configure this logic?

You're correct that it retries on any error, including `4xx` responses. For the initial version of resiliency, we took the approach of more retries is better than no retries. In the future, we may add in additional filters/scenarios that you can trigger a retry off of. I know there were plans to add in more CEL level expressions for Phase 2 of resiliency.

You can set the circuit breaker logic, but it's fairly limited at the moment looking for either consecutive or total failures/successes over a given interval.

> When applying a retry policy to an app and/or component, what happens when the application instance crashes? Will the retries be lost for that particular crashed instance?

Retries live in the sidecar, so if your app goes down it doesn't really matter. Though it would probably continue to fail the retries until an appropriate replacement has come up. That could cause the retries to end based on how long that takes.

**Comment by wimvdc** [comment]
> @wimvc1 - Thanks for raising this issue!
> 
> > When applying retry and/or circuit breaker to an app or component, what logic does Dapr use to kick in those features? Is there a way to configure this logic?
> 
> You're correct that it retries on any error, including `4xx` responses. For the initial version of resiliency, we took the approach of more retries is better than no retries. In the future, we may add in additional filters/scenarios that you can trigger a retry off of. I know there were plans to add in more CEL level expressions for Phase 2 of resiliency.
> 
> You can set the circuit breaker logic, but it's fairly limited at the moment looking for either consecutive or total failures/successes over a given interval.
> 
> > When applying a retry policy to an app and/or component, what happens when the application instance crashes? Will the retries be lost for that particular crashed instance?
> 
> Retries live in the sidecar, so if your app goes down it doesn't really matter. Though it would probably continue to fail the retries until an appropriate replacement has come up. That could cause the retries to end based on how long that takes.

Thanks for the response.
I have checked the roadmap / board but couldn't find anything related to `CEL level expressions for Phase 2 of resiliency`
Do you have a link / issue number by any chance? It would be nice if we could track this progress.

**Comment by halspang** [comment]
We just have the original issue which outlines Phase 2. I don't know if we ever determined if it was going to be CEL specifically, it just seems like the right tool.

https://github.com/dapr/dapr/issues/3586

I'll see if I can't compile a "future features" issue that references some of the resiliency updates that we're targeting going forward.

**Comment by adi-braniste** [comment]
Hi, I am trying to enable resiliency for pubsub but for some reason the resiliency.yaml is not applied. There are no related logs in the sidecar and the retry policy is not applied (retries are performed endlessly each 5s).
Any ideas what could be wrong?

**/components/resiliency.yaml**
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliencyConfig
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 10s
        maxRetries: 3
  targets:
    components:
      pubsub:
        outbound:
          retry: pubsubRetry
        inbound:
          retry: pubsubRetry
```

**/configuration/config.yaml**
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: featureconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
  features:
    - name: Resiliency
      enabled: true
```

**docker-compose.yaml**
```
...
myfrontend-dapr:
    image: "daprio/daprd:latest"
    restart: on-failure:3
    command: [ "./daprd", 
      "-app-id", "MyFrontEnd", 
      "-app-port", "80", 
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"]
    depends_on:
      - myfrontend
      - broker
    network_mode: "service:myfrontend"
    volumes:
      - "./local-development/dapr/components/:/components"
      - "./local-development/dapr/configuration/:/configuration"
    networks:
      - local-development_default
...

```
Thanks.
