### ISSUE TITLE
Retry policy with kafka-pubsub

### ISSUE THREAD

**Issue by osamaz26** [dapr/dapr#4592]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

I have used the following config for the retry policy

```
    retries:
      general:
        duration: 2s
        maxRetries: 5
        policy: constant
```
It seems the sidecar respects the duration between the tries but after the max retries reached, the app receives the same message again. I'm using kafka-pubsub with .net sdk to consume messages with Resiliency activated. 

My question is what happens after the maxRetries is reached? Should the sidecar assume that the messages is consumed successfully after the maxRetries is reached?
