### ISSUE TITLE
SQS binding missing endpoint option (and others) from the pubsub integration

### ISSUE THREAD

**Issue by rbisecke** [dapr/dapr#4596]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.6.0

## Expected Behavior

When testing dapr integrations locally with a localstack image to simulate AWS, the sqs/sns pub sub binding allowed for a custom endpoint to be provided: [AWS SNS/SQS](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/). The sqs binding however is missing this option, preventing the use of the localstack image for testing: [AWS SQS](https://docs.dapr.io/reference/components-reference/supported-bindings/sqs/). This also applies to any of the sqs specific values in the pubsub specific spec that don't exist in the SQS binding. 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: items
  - name: region
    value: us-west-2
  - name: accessKey
    value: *****************
  - name: secretKey
    value: *****************
  - name: sessionToken
    value: *****************
    # - name: endpoint # Optional.   <-- missing
    #   value: "http://localhost:4566"
...
```
