### ISSUE TITLE
Option to prefix state key with namespace

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#4676]
## In what area(s)?

/area operator

## Describe the feature
It would be great if there was an option to automatically prefix a state store key with the namespace, such that

`{appId}||{key}` becomes `{namespace}||{appId}||{key}`

**Example** 

Two state store components (with the same name, but in different namespaces) which target the same Postgres database instance : 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myStateStore
  namespace: NS1
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "Driver={PostgreSQL};Server=IP address;Port=5432;Database=myDataBase;Uid=myUsername;Pwd=myPassword;"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myStateStore
  namespace: NS2
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "Driver={PostgreSQL};Server=IP address;Port=5432;Database=myDataBase;Uid=myUsername;Pwd=myPassword;"
```

The `myStateStore` component is used in an App with an AppId of `myService` - however the App is deployed twice, in separate namespaces `NS1` and `NS2`

Saving a key called `weapon` in both Apps, would generate the following keys.

`NS1||myService||weapon`
`NS2||myService||weapon`

**Motivation**

This is so we can utilise the same underlying state store across many Apps across many Namespaces.

We would like to deploy several copies of our entire system to the same k8s cluster, for dev/test scenarios. To manage costs and operational burden, we would like to utilise just a single underlying state store (AWS RDS Postgres) rather than spinning up a Postgres instance per copy of the system.

The illustration below shows 3 Teams (Team A, Team B and Team C) each having their own complete deployment of System X.

![image](https://user-images.githubusercontent.com/4224880/170790045-dc87b139-b560-4a34-8159-1d5515923ea8.png)

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
I agree this would be a very useful addition to the state sharing strategies we have today. I've heard the demand for this from other users as well. We already have the means to support key prefixes via defined strategies today, so this would essentially mean adding a new `namespace` strategy.

**Comment by saber-wang** [comment]
@yaron2 I think all components that depend on external objects need similar settings.

**Comment by yaron2** [comment]
PR issued here here: https://github.com/dapr/dapr/pull/4677.

In accordance with our current prefix strategy, a new `namespace` strategy was added:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: NS1
spec:
  type: state.redis
  version: v1
  metadata:
  - name: keyPrefix
    value: namepsace
```

Note @olitomlinson that keys are generated as `NS1.myService||key`. This is because the `||` separator is used to separate the actual key name.
