### ISSUE TITLE
how to deploy application to not default cluster domain

### ISSUE THREAD

**Issue by AdamvvYau** [dapr/dapr#4739]
> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

k8s clusterDomain isn't cluster.local but like "cluster.lhz-k8suat"

dapr init with params:
  dnsSuffix: ".cluster.lhz-k8suat"
dapr_sentry:
  trustDomain: cluster.lhz-k8suat
dapr_sidecar_injector:
  kubeClusterDomain: cluster.lhz-k8suat

Then two services , serviceA & serviceB,  the dapr sidecar could be injected ,also can be saw at dapr dashboard,but serviceA could not invoke  serviceB. error message like this:

{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: edgeservice, err: failed to invoke target edgeservice after 3 retries"
}

**Comment by AdamvvYau** [comment]
is any setting wrong?

**Comment by pasfoter** [comment]
the problem is the same I can't change the dns suffix (daprio/dapr:1.9.4)

            - name: KUBE_CLUSTER_DOMAIN
              value: ololo.com
error:
time="2022-11-29T11:13:50.561670278Z" level=debug msg="retry count: 2, grpc call failed, ns: test, addr: zif-cm-provider-udl-service-dapr.test.svc.cluster.local:50002, appid: zif-cm-provider-udl-service, err: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup zif-cm-provider-udl-service-dapr.test.svc.cluster.local on 10.96.0.10:53: no such host\"" app_id=zif-cm-engine-mvel 

why doesn't it respond to the variable KUBE_CLUSTER_DOMAIN?

**Comment by exzenous** [comment]
I am having the same problem. I wonder if there're still hard-coded "cluster.local" domain within the code.

**Comment by hungn17** [comment]
I am having the same problem , can not use service invocation in K8s when cluster domain is not "cluster.local" . Dapr sidecar when call to another dapr sidecar always resolve to svc.cluster.local that lead to the unavailable desc !! 

Example error log with Quickstart : 
time="2023-11-27T10:11:53.362465875Z" level=debug msg="retry count: 3, grpc call failed, ns: default, addr: nodeapp-dapr.default.svc.cluster.local:50002, appid: nodeapp, err: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=pythonapp instance=pythonapp-7dbf8485c4-t7shd scope=dapr.runtime.direct_messaging type=log ver=1.9.3

**Comment by exzenous** [comment]
Hi all, 
I finally can deploy my application with Dapr on Kubernetes that has custom domain name by do the following
1) Deploy Dapr with Helm with this value (Tested on Dapr 1.10.1)
```
dapr_sidecar_injector:
  kubeClusterDomain: your-domain.k8s.cluster
```
2) You need to add Dapr Application Configuration for Kubernetes cluster domain and in pod annotation need to utilise them [Dapr Doc - Kubernetes DNS name resolution provider](https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-kubernetes/)
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
  namespace: "your-application-namespace"
spec:
  nameResolution:
    version: v1  # I don't know why according to docs, there isn't need one but when applying, it need this field
    component: "kubernetes"
    configuration:
      clusterDomain: "your-domain.k8s.cluster" 
```
```
annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nodeapp"
    dapr.io/app-port: "3000"
    dapr.io/config: "myappconfig"  ## Add this to your deployment or whatever you using
```
