### ISSUE TITLE
In Memory Pub/Sub fails apply to Kubernetes

### ISSUE THREAD

**Issue by tlawrie** [dapr/dapr#4740]
## In what area(s)?

Components on Kubernetes

## What version of Dapr?

1.7.4

## Expected Behavior

According to the documentation you create the In Memory pub/sub component with no spec.metadata field

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-inmemory/

## Actual Behavior

```
error: error validating "manifests/pubsub.yaml": error validating data: ValidationError(Component.spec): missing required field "metadata" in io.dapr.v1alpha1.Component.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

## Steps to Reproduce the Problem

Attempt to apply the YAML from the documentation

**Comment by Taction** [comment]
I think setting the `metadata` as required is useful, but in-memory pubsub component does not need metadata. I recommend changing the in-memory component in the tutorial to:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.in-memory
  version: v1
  metadata: []
```
