### ISSUE TITLE
Error for connect a dapr to HashiCorp vault for secret management

### ISSUE THREAD

**Issue by erfuuan** [dapr/dapr#4779]
Hello everyone
I want to connect  dapr to HashiCorp vault for secret management and I have a problem to get a vaule in dapr:
I connect a dapr to vault with this configuration :
 //===================================
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://127.0.0.1:8200" 
  - name: vaultToken 
    value : "myroot"
  - name: skipVerify
    value: true
  - name: enginePath
    value: "kv"
```

 //===================================
and when I run my nodejs sdk code I get this error:

```
== APP == Error: {"errorCode":"ERR_SECRET_GET","message":"failed getting secret with key my-app from secret store vault: getSecret my-app failed secret key or version not exist"}
== APP ==     at HTTPClient.<anonymous> (/home/erfan/work/quickstarts/secrets_management/javascript/sdk/order-processor/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:136:23)
== APP ==     at Generator.next (<anonymous>)
== APP ==     at fulfilled (/home/erfan/work/quickstarts/secrets_management/javascript/sdk/order-processor/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:17:58)
== APP ==     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
my-app is my key and my sercret in vault
can someone help me about this problme?
