### ISSUE TITLE
General Resiliency Questions

### ISSUE THREAD

**Issue by safari137** [dapr/dapr#4831]
## In what area(s)?

> /area runtime

## Ask your question here

1. When setting up the resiliency config, I tried to apply this at the scope and app level, but it did not work until I applied it at the component level.  This makes sense to me since an app could have many components.  It might have saved me some time if that was documented though. -> https://docs.dapr.io/operations/resiliency/resiliency-overview/
2. I have the following retry setup, but the behavior isn't exactly what I expected.
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
scopes:
  - publisher
  - subscriber
spec:  
  policies:
    retries:
      pubsubRetry:
          policy: constant
          duration: 5s
          maxRetries: 3
  targets:
    apps: 
      subscriber:
        retry: pubsubRetry
    components:
      pubsub:
        inbound:
          retry: pubsubRetry
```

**Expected behavior**: 
- Three attempts to deliver to the subscriber
- ~5 seconds apart and no more attempts after
- No more attempts after maxRetries (3)

**Actual behavior**: 
- Three attempts to deliver to the subscriber
- ~5 seconds apart 
- This cycle is repeated every ~1 minute for what seems to be infinity

What is dapr actually doing here?  Is it executing a read/lock of the message for the duration of my retry policy (duration * maxRetries) and then returning it to the broker?  From there I would assume it will be replayed according to the message broker's policy until it is dead lettered?

**Comment by halspang** [comment]
I'm not exactly sure what you're asking for in the documentation for your first point. Can you elaborate a bit more?

For your 2nd point, you're right that it's just being redelivered endlessly. Currently, resiliency and component level retries don't know about each other/how to interact. So, your resiliency policy is being run, and once the retries are exhausted it returns it to the broker. It's then up to the broker to decide what to do with it. In your case, it appears to be delivering forever.

**Comment by safari137** [comment]
@halspang thanks for confirming the second point!

As for the first point:

The documentation says:

> Policies can then be applied to [targets](https://docs.dapr.io/operations/resiliency/targets/), which include:
> - [Apps](https://docs.dapr.io/operations/resiliency/targets/#apps) via service invocation
> - [Components](https://docs.dapr.io/operations/resiliency/targets/#components)
> - [Actors](https://docs.dapr.io/operations/resiliency/targets/#actors)

However, if I set this up with just a target of apps, it does not seem to take effect.
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
scopes:
  - publisher
  - subscriber
spec:  
  policies:
    retries:
      pubsubRetry:
          policy: constant
          duration: 5s
          maxRetries: 3
  targets:
    apps: 
      subscriber:
        retry: pubsubRetry
```

So I'm assuming while I can use the targets to narrow down the "scope" of the policy, minimally, I must use the components target.  Or is my issue that the apps target is only for service invocation (that part just sunk in).
