### ISSUE TITLE
Some configurations of `dapr sidecar` should support global configuration

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4853]
## In what area(s)?

 /area runtime

## Describe the proposal
At present, many `dapr sidecar` configurations can only be configured on each `deploy`
for example: Handle large http body requests
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/app-port: "8000"
        dapr.io/http-max-request-size: "16"
```
There are many other `sidecar` configurations:
        `dapr.io/sidecar-memory-request: "56Mi"`
        `dapr.io/sidecar-cpu-request: "200m"`
        `dapr.io/sidecar-memory-limit: "512Mi"`
        `dapr.io/sidecar-cpu-limit: "1000m"`
        `......`

## Design

Maybe you can use `Configuration` to unify the configuration
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  sidecar:
    - name: http-max-request-size
      enabled: "16"
```
use:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/app-port: "8000"
        dapr.io/config: "appconfig"
```
