### ISSUE TITLE
Invocation Issues and Mysterious URL Changes on Local Kubernetes Deployment

### ISSUE THREAD

**Issue by LilCSharp** [dapr/dapr#4857]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Issue in Question
Hello!

I have a set of two ASP.NET Core services that have the ability to send GET requests to receive basic information from each other. I am facing two primary issues. I currently have a functional Docker Compose file that, when launched, will return the correct JSON from the request when I curl from within one of the containers (the logic containers, not the Dapr containers).

When testing the service invocation using my Docker Compose deployment, I receive the expected output and this message on the requested container:
` Request starting HTTP/1.1 GET http://127.0.0.1:<other app port>/controller/<controller method> application/json`

When testing with my Kubernetes implementation (on the container that I send the request from), the result of the curl is:
`{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: <app id>, err: failed to invoke target <app id> after 3 retries"}`

And on the container receiving the request the result of the curl is: 
`Request starting HTTP/1.1 GET http://127.0.0.1:<other app port>/dapr/config application/json`

I suspect that the reason for the failed invocation is because something is changing the invocation URL when it reaches the other Dapr container, but I can't seem to find what it is that is causing the issue. Any suggestions as to what I should look into? Thanks.

The way that I'm configuring Dapr with Kubernetes is here:

```
kind: Service
apiVersion: v1
metadata:
  name: <name>app
  labels:
    app: <name>
spec:
  selector:
    app: <name>
  ports:
  - protocol: TCP
    port: 80
    targetPort: <app port>
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>app
  labels:
    app: <name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <name>
  template:
    metadata:
      labels:
        app: <name>
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "<name>app"
        dapr.io/app-port: "<app port>"
        dapr.io/enable-api-logging: "true"
        dapr.io/sidecar-listen-addresses: 0.0.0.0
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: <name>
        image: <local image>
        envFrom: 
        - configMapRef: 
            name: env-config
        ports: 
        - containerPort: <app port>
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: env-config
  namespace: default
data: 
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:<app port>
```
