### ISSUE TITLE
ERROR: for ptf-dapr  Cannot start service ptf-dapr: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "daprd": executable file not found in $PATH: unknown       ERROR: for ptf-dapr  Cannot start service ptf-dapr: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "daprd": executable file not found in $PATH: unknown      ERROR: Encountered errors while bringing up the project. make: *** [Makefile:5: up] Error 

### ISSUE THREAD

**Issue by perymerdeka** [dapr/dapr#4915]
I just used Dapr to develop microservices.

I use Flask as the framework, I use docker and docker compose for deployment, I run the command

` ["daprd", "-app-id", "flask-ptf", "-placement-host-address", "placement:50006","-components-path", "/app/backend/components/" ]`

to run dapr with docker compose.

reference
* https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/
* https://github.com/dapr/samples/blob/master/hello-docker-compose/docker-compose.yml

but i got an error like this

`
Cannot start service ptf-dapr: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "daprd": executable file not found in $PATH: unknown
`

here is my `docker-compose.yml` file

```yaml
# docker-compose.yml
version: "3.9"

services:
  ptf-api:
    container_name: "flask-ptf-container"
    restart: always
    builds:
      context: .
    working_dir: /app/backend
    env_file:
      - .env
    volumes:
      - .:/app
      - media_volume:/app/backend/media
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - placement
    networks:
      - flask-ptf-network
  db:
    container_name: "ptf-db"
    restart: on-failure
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5434:${DB_PORT}
    volumes:
    - data: /var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - flask-ptf-network
  ptf-dapr:
    container_name: ptf-dapr
    image: daprio/daprd:edge
    restart: on-failure
    env_file: .env
    working_dir: /app/backend/
    command: ["daprd", "-app-id", "flask-ptf", "-placement-host-address", "placement:50006","-components-path", "/app/backend/components/ "]
    depends_on:
      - ptf-api
      - db
    volumes:
      - ./components:/app/backend/components/
    networks:
      - flask-ptf-network

  ###########################
  # Dapr placement service
  ###########################
  placements:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - flask-ptf-network

networks:
    flask-ptf-network:
        drivers: bridge
volumes:
  data:
  components:
  media_volume:
```

```dockerfile
FROM python:3.9-bulleye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFRED=1

ENV VIRTUAL_ENV=/opt/venv

RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# PDFTK Setup
RUN apt update -y
RUN apt install pdftk -y
RUN apt install --fix-missing -y
RUN apt update -y

RUN mkdir /app

RUN ls /app
WORKDIR /app

RUN pip install --upgrade pip
ADD requirements.txt /app/
RUN pip install -r requirements.txt --no-cache-dir

# # Install Dapr
# RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

# # Install daprd
# ARG DAPR_BUILD_DIR
# COPY $DAPR_BUILD_DIR /usr/local/bin
# ENV PATH="/usr/local/bin/:${PATH}"
# RUN dapr init --slim

ADD . /apps/
```
anyone know why daprd is not initiated, and when i join the documentation

* https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/

an error like this appears
`
./daprd: No Such files or directory
`

does anyone know the cause of the error?
