### ISSUE TITLE
Error thrown while using HTTP Configuration Subscribe API 

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/dapr#4968]
## In what area(s)?

 /area runtime

## What version of Dapr?

 1.8.3

## Actual Behavior

Encountered error while receiving the subscribed configuration changes. Below is the error message got in my console - 

_ERRO[0016] panic in handleSubscribedChange(）method and recovered: runtime error: invalid memory address or nil pointer dereference  app_id=test instance=Pravins-MacBook-Pro.local scope=dapr.contrib type=log ver=1.8.3_

## Steps to Reproduce the Problem

1. Run a sample app -
```
dapr run --log-level debug --app-id test --dapr-http-port 3500 --components-path ./components/configuration
```
Redis yaml file - 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configstore
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```

2. Call the susbcribe API - 
```
`curl -X GET 'http://localhost:3500/v1.0-alpha1/configuration/configstore/subscribe'
Sample response - 
{"id":"c2793708-5957-4fa3-9825-d3f2bc25731a"}%
```

3. Now as soon as we try to update to update the any key's value in redis store, we get the below error - 

_ERRO[0016] panic in handleSubscribedChange(）method and recovered: runtime error: invalid memory address or nil pointer dereference  app_id=test instance=Pravins-MacBook-Pro.local scope=dapr.contrib type=log ver=1.8.3_

This works fine in case of gRPC API. So wondering why I am getting exception in case of HTTP.
