### ISSUE TITLE
pubsub kafka :grpc: the client connection is closing

### ISSUE THREAD

**Issue by qiangmzsx** [dapr/dapr#4976]
## In what area(s)?
> /area runtime

## What version of Dapr?
Runtime version: 1.8.3

## Expected Behavior

Multiple grpc streaming requests over the dapr grpc proxy should be supported.

## Actual Behavior
2022/08/05 16:47:25 error publishing event unto ddkafka_test_01 topic: rpc error: code = Canceled desc = grpc: the client connection is closing

## Steps to Reproduce the Problem

kafka.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mykafka
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "10.1.0.107:9092,10.1.0.107:9093"
  - name: topics
    value: ddkafka_test_01
  - name: consumerGroup
    value: ddkafka_test_cg
  - name: maxMessageBytes # Optional.
    value: 1024
  - name: consumeRetryInterval # Optional.
    value: 200ms
  - name: version # Optional.
    value: 1.1.0
  - name: publishTopic
    value: ddkafka_test_01
  - name: authRequired
    value: "false"
```
code
```
r.GET("/kafka/send", func(ctx *gin.Context) {
		client, err := dapr.NewClient()
		if err != nil {
			panic(err)
		}
		defer client.Close()

		if err := client.PublishEvent(ctx, "mykafka", "ddkafka_test_01", "my name is one"+time.Now().Format(time.RFC3339)); err != nil {
			log.Print(err)
			// panic(err)
		}
		ctx.JSON(http.StatusOK, "send")
	})
```
$ dapr run --app-id demo1 --app-port 5000  --dapr-grpc-port 60001  --dapr-http-port 8088 ./demo1 enable-api-logging
$ curl --location --request GET 'http://127.0.0.1:8088/v1.0/invoke/demo1/method/kafka/send'

== APP == [GIN] 2022/08/05 - 16:47:21 | 200 |   33.578628ms |       127.0.0.1 | GET      "/kafka/send"
== APP == [GIN] 2022/08/05 - 16:47:25 | 200 |      137.25µs |       127.0.0.1 | GET      "/kafka/send"
== APP == 2022/08/05 16:47:25 error publishing event unto ddkafka_test_01 topic: rpc error: code = Canceled desc = grpc: the client connection is closing
