### ISSUE TITLE
Sidecars inject pods failed.

### ISSUE THREAD

**Issue by SakaZhang** [dapr/dapr#4996]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

 /area operator

 /area placement

> /area docs

> /area test-and-release

## Inject pods failed when apply calico networkpolicy
When i apply calico NetworkPolicy, darp's sidecars inject failed.

It looks like  :
```
dada-backend-python-6cb958468-lb426        2/2     Running   0          18h
dada-backend-python-6cb958468-rcg9h        1/1     Running   0          33m
```
My calico networkpolicy:
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-app-policy
spec:
  namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name not in {"kube-system", "calico-system", "cert-manager", "nginx-ingress", "sre", "tigera-operator", "kube-node-lease", "velero" }
  types:
    - Ingress
```

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-dada
spec:
  order: 900
  namespaceSelector: ns == 'dada' # The ns dada contains mypod and dapr
  ingress:
    - action: Allow
      source:
        selector: app in {'dapr-sidecar-injector', 'dada-client-actor', 'actor-gc-worker', 'dada-backend-couchdb', 'dada-backend-python', 'dada-chatroom-actor', 'dada-couchdb-nginx', 'dada-helper-actor', 'dada-user-actor', 'dapr-ha-redis', 'data-emcee-actor', 'dada-backend-server', 'nginx-ingress', 'dapr-dashboard', 'dapr-operator', 'dapr-placement', 'dapr-sentry', 'dapr-sidecar-injector', 'data-emcee-actor', 'zipkin', 'dapr-placement-serve', 'internal-ingress-controller'}
```
The dapr version is 1.4.4 and calico version is  v3.21.4 on aks.
