### ISSUE TITLE
when the Deadletter is not subscribed, the message will be lost

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#5013]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

## Ask your question here
In the new version, deadletter is provided, but if only dead letter is declared, no subscription will be generated, which will lead to the loss of messages.

**Comment by yaron2** [comment]
How will messages be lost if they are not subscribed to in the first place?

**Comment by zevsap** [comment]
что?


Отправлено из Yahoo Почты на iPhone


Пользователь среда, августа 24, 2022, 1:55 AM написал Yaron Schneider ***@***.***>:




How will messages be lost if they are not subscribed to in the first place?

**Comment by saber-wang** [comment]
@yaron2 
pubsub:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: testpubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "host"
  - name: deliveryMode
    value: "2"
  - name: enableDeadLetter # Optional enable dead Letter or not
    value: "false"
```

Subscription:
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order
spec:
  topic: orders
  route: /api/v1/test/exceptiontest
  pubsubname: testpubsub
  deadLetterTopic: poisonMessages
```
Exchanges has
![image](https://user-images.githubusercontent.com/45062099/186301078-37cbc55c-2d63-43d6-bf94-eb45922f05e3.png)

But there are no queues
![image](https://user-images.githubusercontent.com/45062099/186301296-6599b78f-7d6b-402d-b0cc-7cce388ac544.png)

At this time, when the `orders` subscription is wrong, all the messages forwarded to the Deadletter (poisonMessages) are lost

I think that for dead letters, we should ensure the existence of queues, no matter whether we subscribe to dead letters or not.
