### ISSUE TITLE
Does dapr support the AMPQs (Secure AMPQ) protocol when using rabbitmq for pubsub?

### ISSUE THREAD

**Issue by bab5470** [dapr/dapr#5014]
Does dapr support the AMPQs (Secure AMPQ) protocol when using rabbitmq for pubsub?

When we specify the following in our dapr pubsub config our setup works:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: backend
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://username:password@rabbitmq.data.svc.cluster.local:5672"
  - name: exchangeKind
    value: topic
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
```

When we switch the config as follows it breaks:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: backend
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqps://username:password@rabbitmq.data.svc.cluster.local:5671"
  - name: exchangeKind
    value: topic
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
```

Note all we've changed is the protocol from ampq to ampqs and the port from 5672 to 5671.

We are using our own internal CA when securing rabbitmq so I don't know if there is some way to get the daprd sidecar to trust our internal CA's cert when connecting to rabbitmq?

Thanks,
Brad
