### ISSUE TITLE
Add recommended labels to Dapr control plane Kubernetes objects

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#5029]
## In what area(s)?

/area hosting

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Kubernetes recommends some common labels for all Kubernetes objects.

> A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand. In addition to supporting tooling, the recommended labels describe applications in a way that can be queried.

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

Some of Dapr control plane resources already contain these labels, but all of them do not. This will help us query objects in useful ways - for e.g., "get all Dapr control plane k8s objects", or "what is the Dapr version of this k8s object", etc. 

This proposal is to add the following well-known recommended labels to all our Dapr control plane objects -

| name | description | example |
| -- | -- | -- |
| app.kubernetes.io/name | The name of the application |  my-dapr 
| app.kubernetes.io/version | The current version of the application (e.g., a semantic version, revision hash, etc.) | 1.8.4
| app.kubernetes.io/component | The component within the architecture | sidecar-injector
| app.kubernetes.io/part-of |  The name of a higher level application this one is part of | dapr
| app.kubernetes.io/managed-by| The tool being used to manage the operation of an application | helm

## Release Note

RELEASE NOTE: **ADD** Recommended labels to Dapr control plane Kubernetes objects

**Comment by yaron2** [comment]
The following labels exist today for all control plane Kubernetes resources:

```

labels:
        app: dapr-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/name: dapr
        app.kubernetes.io/part-of: dapr
        app.kubernetes.io/version: 1.8.2
```
