### ISSUE TITLE
dapr'actor for k8s have a exception: INTERNAL: error invoke actor method: error finding address for actor type DemoActor with id fc955d2e-14e1-4dc4-ac9e-f10f86a20c21

### ISSUE THREAD

**Issue by songyang133** [dapr/dapr#5058]
hello,everyone!
I tried to implement the actor case for DAPR in Java. My idea is to register the implementation class first, then create the actor, and then use ActorId to execute the actor. However, in the K8S cluster or local deployment, the following error is reported when register reminder.
 **INTERNAL: error invoke actor method: error finding address for actor type DemoActor with id fc955d2e-14e1-4dc4-ac9e-f10f86a20c21**
The stack is represented as:
`Exception in thread "main" io.dapr.exceptions.DaprException: INTERNAL: error invoke actor method: error finding address for actor type DemoActor with id fc955d2e-14e1-4dc4-ac9e-f10f86a20c21
at io.dapr.exceptions.DaprException.propagate(DaprException.java:194)
at io.dapr.actors.client.DaprGrpcClient$2.onError(DaprGrpcClient.java:129)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Suppressed: java.lang.Exception: #block terminated with an error
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
at reactor.core.publisher.Mono.block(Mono.java:1707)
at io.dapr.actors.client.ActorProxyImpl.invoke(ActorProxyImpl.java:164)
at com.sun.proxy.$Proxy3.registerReminder(Unknown Source)
at com.songyang.dapr.examples.src.main.java.io.dapr.examples.actors.DemoActorService.callActorForever(DemoActorService.java:113)
at com.songyang.dapr.examples.src.main.java.io.dapr.examples.actors.DemoActorService.lambda$main$0(DemoActorService.java:94)
at java.util.HashMap.forEach(HashMap.java:1288)
at com.songyang.dapr.examples.src.main.java.io.dapr.examples.actors.DemoActorService.main(DemoActorService.java:92)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: error invoke actor method: error finding address for actor type DemoActor with id fc955d2e-14e1-4dc4-ac9e-f10f86a20c21
... 14 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: error invoke actor method: error finding address for actor type DemoActor with id fc955d2e-14e1-4dc4-ac9e-f10f86a20c21
at io.grpc.Status.asRuntimeException(Status.java:535)
... 13 more`
**My code is denoted by**
```
public class DemoActorService {
    private static final int NUM_ACTORS = 3;
    private static Map<ActorId, DemoActor> actorMap = new HashMap<>();
    public static void main(String[] args) throws Exception {
        ActorRuntime.getInstance().getConfig().setActorIdleTimeout(Duration.ofSeconds(30));
        // How often actor instances are scanned for deactivation and balance.
        ActorRuntime.getInstance().getConfig().setActorScanInterval(Duration.ofSeconds(10));
        // How long to wait until for draining an ongoing API call for an actor instance.
        ActorRuntime.getInstance().getConfig().setDrainOngoingCallTimeout(Duration.ofSeconds(10));
        // Determines whether to drain API calls for actors instances being balanced.
        ActorRuntime.getInstance().getConfig().setDrainBalancedActors(true);
        // Register the Actor class.
        ActorRuntime.getInstance().registerActor(DemoActorImpl.class);
         TimeUnit.SECONDS.sleep(3);
        try (ActorClient client = new ActorClient()) {
            ActorProxyBuilder<DemoActor> builder = new ActorProxyBuilder<>(DemoActor.class, client);
            // create actor
            for (int i = 0; i < NUM_ACTORS; i++) {
                ActorId actorId = ActorId.createRandom();
                actorMap.put(actorId, builder.build(actorId));
            }
            TimeUnit.SECONDS.sleep(3);
            ArrayList<Future<String>> resultList = new ArrayList<>();
            //run
            actorMap.forEach((actorId, demoActor) ->
                            callActorForever(actorId.toString(), demoActor)
            );
            TimeUnit.SECONDS.sleep(3);
        }
    }

       private static final String callActorForever(String actorId, DemoActor actor) {
        //***now error here***
        actor.registerReminder();
        // Now, we run until thread is interrupted.
        while (!Thread.currentThread().isInterrupted()) {
            // Invoke actor method to increment counter by 1, then build message.
            int messageNumber = actor.incrementAndGet(1).block();
            String message = String.format("Actor %s said message #%d", actorId, messageNumber);
            // Invoke the 'say' method in actor.
            String result = actor.say();
            System.out.printf("Actor %s got a reply: %s%n", actorId, result);
            try {
                // Waits for up to 1 second.
                Thread.sleep((long) (1000 * Math.random()));
            } catch (InterruptedException e) {
                // We have been interrupted, so we set the interrupted flag to exit gracefully.
                Thread.currentThread().interrupt();
            }
        }
        return "ok";
    }
}

```
**my demoActor is**

```
@ActorType(name = "DemoActor")
public interface DemoActor {

  void registerReminder();

  @ActorMethod(name = "echo_message")
  String say();

  void clock(String message);

  @ActorMethod(returns = Integer.class)
  Mono<Integer> incrementAndGet(int delta);
}
```

**My implementation class is**

```
public class DemoActorImpl extends AbstractActor implements DemoActor, Remindable<Integer> {

  /**
   * Format to output date and time.
   */
  private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

  public DemoActorImpl(ActorRuntimeContext runtimeContext, ActorId id) {
    super(runtimeContext, id);

    super.registerActorTimer(
        null,
        "clock",
        "ping!",
        Duration.ofSeconds(2),
        Duration.ofSeconds(1)).block();
  }

 
  @Override
  public void registerReminder() {
    super.registerReminder(
        "myremind",
        (int) (Integer.MAX_VALUE * Math.random()),
        Duration.ofSeconds(5),
        Duration.ofSeconds(2)).block();
  }

  @Override
  public String say() {
//    Calendar utcNow = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
//    String utcNowAsString = DATE_FORMAT.format(utcNow.getTime());
//
//    // Handles the request by printing message.
//    System.out.println("Server say method for actor "
//        + super.getId() + ": "
//        + (something == null ? "" : something + " @ " + utcNowAsString));
//
//    super.getActorStateManager().set("lastmessage", something).block();
    System.out.println("say");
    return "say";
  }

  @Override
  public Mono<Integer> incrementAndGet(int delta) {
    return super.getActorStateManager().contains("counter")
        .flatMap(exists -> exists ? super.getActorStateManager().get("counter", int.class) : Mono.just(0))
        .map(c -> c + delta)
        .flatMap(c -> super.getActorStateManager().set("counter", c).thenReturn(c));
  }

  @Override
  public void clock(String message) {
    Calendar utcNow = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
    String utcNowAsString = DATE_FORMAT.format(utcNow.getTime());
    // Handles the request by printing message.
    System.out.println("Server timer for actor "
        + super.getId() + ": "
        + (message == null ? "" : message + " @ " + utcNowAsString));
  }

  @Override
  public TypeRef<Integer> getStateType() {
    return TypeRef.INT;
  }

  @Override
  public Mono<Void> receiveReminder(String reminderName, Integer state, Duration dueTime, Duration period) {
    return Mono.fromRunnable(() -> {
      Calendar utcNow = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
      String utcNowAsString = DATE_FORMAT.format(utcNow.getTime());

      String message = String.format("Server reminded actor %s of: %s for %d @ %s",
          this.getId(), reminderName, state, utcNowAsString);

      // Handles the request by printing message.
      System.out.println(message);
    });
  }
}
```

**in my k8s cluster ,my deploy ymal is**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprdemo
  labels:
    app: daprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprdemo
  template:
    metadata:
      labels:
        app: daprdemo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprdemo"
        dapr.io/port: "32767"
       # dapr.io/config: "appconfig"
    spec:
      containers:
      - name: daprdemo
        image: oraps-private-acr.bugongsoft.com/dapr:v0.2
        ports:
        - containerPort: 32768
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 192.168.75.132:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
```

**I hope you can help me. Thank you very much!!**
