### ISSUE TITLE
[FEATURE REQ] Authorization Component

### ISSUE THREAD

**Issue by mstrYoda** [dapr/dapr#5094]
## In what area(s)?

/area runtime

## Describe the feature

Authorization, as a cross-cutting concern is a highly required feature in microservices. It might be good to have authz in Dapr as a building block.

We can create a port for authz component and different authz implementations might plug into this port like pubsub or other components that can have different implementations.

With the authorization component, we can bring zanzibar (keto, spicedb, etc.) integrations into Dapr. And also any other authz solutions can be integrated with Dapr (for ex: keycloak). Or people might decide to plug a policy engine to make authorization decisions.

I've using Istio and it has [various authorization solutions](https://istio.io/latest/docs/tasks/security/authorization/). One of them is the [External Authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/) feature. [better-ext-authz](https://istio.io/latest/blog/2021/better-external-authz/)

I imagine a component like the below for the most basic version of authorization:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: x-authorization
  namespace: default
spec:
  type: authz.implName
  version: v1
  metadata:
  - endpoint: /users
    method: GET
    allowedRoles: ["user"]
  - endpoint: /admin
    method: POST
    allowedRoles: ["admin"]
```

I would love to develop this feature. WDYT?

## Release Note

RELEASE NOTE:

ADD authorization component in Dapr.
