### ISSUE TITLE
CosmosDb context deadline exceeded

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#5124]
## In what area(s)?
/area runtime

## What version of Dapr?
1.8.4
Using DotNet SDK

## Expected Behavior
The cosmos db api calls should use the timeout defined in the component file (initTimeout).

## Actual Behavior
When the initTimeout is not defined, we can see that the timeout is 5 seconds as expected. But when defining the initTimeout to any value (for example 1m), the timeout is 10 seconds.

## Steps to Reproduce the Problem

Run any application with a cosmos db statestore.

statestore.yaml :
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 1m
  metadata:
  - name: url
    value: "https://hello.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: "LogisticsPartner:Catalog:AzureCosmosDb:MasterKey"
      key:  masterKey
  - name: database
    value: dev
  - name: collection
    value: dev
  - name: actorStateStore
    value: true
auth:
  secretStore: secretstore

```

<img width="1494" alt="dapr" src="https://user-images.githubusercontent.com/6775094/188329173-daf31f32-a0c8-4713-b031-8c36be10dd9c.png">
