### ISSUE TITLE
Error finding address for actor type with Azure Cosmos DB 

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#5182]
## In what area(s)?
/area runtime

## What version of Dapr?
1.8.4

## Expected Behavior
No error when invoking actors

## Actual Behavior
Dapr.DaprApiException in System.Private.CoreLib.dll : "error invoke actor method: error finding address for actor type 'Dynamics365ReceiverActor' with id 'MnGdkklhj456-3c...'.

When using Redis or Memory state stores, actors work well. There are not any security or connection issues to CosmosDb as I can see that the 2 stored procedures have been created. If I delete the container or the stored procedures, they are created when I start the application.

I think that there is an underlying error that does not appear in the logger messages or in the exception.

Do we need to do any required actions on the database to make Dapr work with Cosmos DB?

Component :
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 5m
  metadata:
  - name: url
    value: "https://app-fno-dev.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: "LogisticsPartner:Catalog:AzureCosmosDb:MasterKey"
      key:  "LogisticsPartner:Catalog:AzureCosmosDb:MasterKey"
  - name: database
    value: dev
  - name: collection
    value: dev
  - name: actorStateStore
    value: true

auth:
  secretStore: secretstore

```
Log:
 
> [10:50:50 INF] detected actor state store: statestore
> [10:50:50 IN

Cosmos :
It contains the two stored procedures, but 0 items

<img width="566" alt="cosmossettings" src="https://user-images.githubusercontent.com/6775094/190603236-88642cd7-6a93-498b-9f77-cef9e01e270f.png">
F] component loaded. name: statestore, type: state.azure.cosmosdb/v1
