### ISSUE TITLE
PubSub only sending to single subscriber with some brokers

### ISSUE THREAD

**Issue by scott-moxham** [dapr/dapr#5244]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

## Ask your question here
I'm having issues with Dapr PubSub in our C# / .Net6 WebAPI project where it's only triggering ONE subscriber instead of all subscribers. On developer machines we run under Docker and have configured Dapr to use pubsub.redis for pubsub. I've tried switching brokers and RabbitMQ has the same issue as redis but Azure Service Bus sends to all subscribers.

I can see in our logs it's calling subscribe and the response contains a list of the different topic subscriptions and endpoints registered to handle the topics.

When a message is published, it only gets handled by one of the subscribers. The service that gets the message seems to vary, sometimes the reports service will handle it, other times the clients service will handle it, sometimes one of the others but it's only ever ONE.

I'm not really sure what else to look at to track this issue down. I'm beginning to think this may be a bug. I've asked about it on Discord and on StackOverflow with no responses, which indicates it's not something straightforward, leading me to think it's more likely to be a bug.

I'm using [TopicAttributes] to decorate controller actions as the subscription mechanism. Dapr.AspNetCore v1.8.0 nuget package. We're running on Windows 10, with Docker Desktop v4.11.1 (84025) and docker engine v20.10.17. Our images are based on mcr.microsoft.com/dotnet/aspnet:6.0.6-focal-amd64 and docker is using WSL 2 to run them.

Below are the three config files I've tried. The redis and rabbitMQ ones only send to ONE subscriber, the ServiceBus one sends to ALL subscribers. The config file is the only thing that I'm changing between tests, indicating to me that the problem is not in my code. Only one config file is present for each test.

````
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "xxxx"
  - name: consumerID
    value: "myGroup"
  - name: enableTLS
    value: "false"
  - name: processingTimeout
    value: "30s"
  - name: redisMaxRetries
    value: "5"
````

````
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: rabbitmq:5672
  - name: redisPassword
    value: "xxxxx"
  - name: consumerID
    value: "myGroup"
  - name: durable
    value: false  
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: requeueInFailure
    value: false
  - name: deliveryMode
    value: 0
  - name: requeueInFailure
    value: false
  - name: prefetchCount
    value: 0
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: false
  - name: backOffPolicy
    value: exponential
  - name: backOffInitialInterval
    value: 100
  - name: backOffMaxRetries
    value: 5
  - name: enableDeadLetter # Optional enable dead Letter or not
    value: true
  - name: maxLen # Optional max message count in a queue
    value: 3000
  - name: maxLenBytes # Optional maximum length in bytes of a queue.
    value: 10485760
  - name: exchangeKind
    value: fanout
````

````
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://xxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxx"
  - name: timeoutInSec
    value: 60
````

**Comment by ItalyPaleAle** [comment]
This is not really a Dapr issue, but it's about how pubsub brokers work. Some send a message to a single subscriber, some send the messages to all.

In the case of Azure Service Bus, the pubsub component uses ASB topic subscriptions, so all subscribers get a message. The binding however uses ASB queue subscriptions, so only 1 subscriber is notified of each message.

**Comment by scott-moxham** [comment]
Thanks for your reply @ItalyPaleAle, but I found the solution today.
The problem was that the `consumerId` was a static string so that all instances used the same Id and thus belonged to the same group and so only one received it.
By changing the consumerId to {uuid}, all instances have a different id and so all instances receive the message.
My config is now
````
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "xxxx"
  - name: consumerID
    value: "{uuid}"
  - name: enableTLS
    value: "false"
  - name: processingTimeout
    value: "30s"
  - name: redisMaxRetries
    value: "5"
````
