### ISSUE TITLE
kubectl logs show the error: flag provided but not defined: -enable-api-logging

### ISSUE THREAD

**Issue by DRRRRRRRRRRRRR** [dapr/dapr#5284]
Hi, Can someone help me. 
The darpd container failed to start as a siderCar When I apply the dapr in k8s. 
The kubectl logs show the error: flag provided but not defined: -enable-api-logging. 
It seems that I used the wrong image, but I did use the daprio/daprd: edge

I successfully installed dapr in an offline K8S environment and successfully applied redis statestore Component.
Both on dapr-sys namespace
Then I planned to release the service and sideCar
Here is my service.yaml
``` yaml
apiVersion: v1 
kind: Service 
metadata: 
  name: machinelearning 
spec: 
  selector: 
    app: machinelearning 
  ports: 
    - name: machinelearning 
      port: 80 
      targetPort: 80 
      externalIPs: 
      - 168.168.10.71 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: machinelearning-deployment 
spec: 
  selector: 
    matchLabels: 
      app: machinelearning 
    replicas: 1 
    template: 
      metadata: 
        labels: 
          app: machinelearning 
        annotations: 
          dapr.io/enabled: "true" 
          dapr.io/app-id: "ml" 
          dapr.io/app-port: "80" 
      spec: 
        containers: 
        - name: machinelearning 
          image: 168.168.10.72:5000/liems/machinelearning:0.4 
          ports: 
            - containerPort: 80
```
Then the above problems occurred
