### ISSUE TITLE
Declarative subscriptions are not picked up by running pods with dapr sidecar injected

### ISSUE THREAD

**Issue by MichaelHindley** [dapr/dapr#5297]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.8.4

## Expected Behavior

Given a declarative subscription definition like this in a file called `sub.yaml`;
```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order
spec:
  topic: orders
  route: /checkout
  pubsubname: orderpubsub
scopes:
  - checkout
  - publisher
```

when I  `kubectl apply -f sub.yaml`,
I expect messages published to that topic to be received by the scoped dapr apps on the `/checkout` route,
then when I run `kubectl delete -f sub.yaml`,
I expect to not receive messages published to the orders topic by the scoped apps,
but the scoped apps are still receiving messages as defined in the `sub.yaml`,
even though the subscription has been deleted,
causing application behavior drift from the declaratively configured subscription.

## Steps to Reproduce the Problem
Use the declarative app approach as described in the docs; https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#receiving-messages-with-topic-subscriptions, the quickstart setup can be used if modified to not have the programmatic code.

## Release Note

RELEASE NOTE:
