### ISSUE TITLE
Resiliency CRD should specify a list of target components

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/dapr#5306]
## In what area(s)?

> /area runtime

## Describe the proposal

The `dapr.io/v1alpha1` spec for `Resiliency` has a field (`spec.targets.components`) which is currently a map.

The map keys each refer to a `dapr.io/v1aplha1` `Component`.

The way it is done now is quite inflexible with tools such as Kustomize, where the resource name might be prefixed, suffixed, or transformed in some other way (See kubernetes-sigs/kustomize#4817).

In almost all other Kubernetes (or Kubernetes style manifests), resources are referred to in a value (with the key name being something like `name` or `componentName` for example).

So, I am proposing a `v1alpha2` spec that allows for specifying the component name as a value, instead of a key.

### Example

Given a component with the following spec:

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-orders # in my example, kustomize will add a prefix, and update name references in other (custom) resources.
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
  - name: natsURL
    value: "tls://nats"
```

#### Before

```yml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: api
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 2s
        maxRetries: 2
  targets:
    components:
      pubsub-orders: # this needs updating to contain the prefix
        inbound:
          retry: pubsubRetry
```

#### After

```yml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: api
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 2s
        maxRetries: 2
  targets:
    components:
    - name: pubsub-orders # now kustomize is able to fix references to it
      inbound:
        retry: pubsubRetry
```

> **Note**: I realise my use case is specific to:
> - Running in Kubernetes
> - Using Kustomize to fix references
>
> However, I do think that is make sense to align with existing ways to refer to other resources, which Dapr otherwise aligns itself with quite well.
