### ISSUE TITLE
Resiliency feature unable to be found in `kubectl api-resources`, so unable to configure

### ISSUE THREAD

**Issue by Intecpsp** [dapr/dapr#5383]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

 1.9.0

## Expected Behavior

Resiliency feature is enabled and either the default configs are used, or the user is allowed to overwrite them

## Actual Behavior

When adding
```
...
spec:
  ...
  features:
    - name: Resiliency
      enabled: true
...
```
And
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: dapr-resiliency
spec:
  policies:
    retries:
      DaprBuiltInServiceRetries:
        policy: exponential
        maxInterval: 2m
```
I am getting things like
```
Error listing resiliences: rpc error: code = Unknown desc = error listing resiliencies: no matches for kind "Resiliency" in version "dapr.io/v1alpha1"
Found 0 resiliency configurations.
Resiliency configuration loaded.
```
and
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Resiliency" in version "dapr.io/v1alpha1"
```

## Steps to Reproduce the Problem

1. Install Dapr 1.8.4 using Helm 3.6.1
2. Enable 'Resiliency' preview feature (https://docs.dapr.io/operations/support/support-preview-features/#current-preview-features and https://docs.dapr.io/operations/configuration/preview-features/#enabling-a-preview-feature)
3. Optional: try to override defaults (https://docs.dapr.io/operations/resiliency/policies/#overriding-default-retries)
4. Check `daprd` logs once deploying service(s)

## Release Note

RELEASE NOTE:
