### ISSUE TITLE
Proposal: Pluggable components annotation for Kubernetes

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5402]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

As pluggable components bootstrap is platform dependent (self-hosted vs Kubernetes), the pluggable component developers can't do anything to help configuration on those platforms. Similarly, the end-user requires specific knowledge to properly configure the used pluggable components. Currently, this knowledge is achieved by reading documentation to deeply understand how Dapr registers and communicates with the pluggable component. To exemplify that, look at the Kubernetes configuration below (copied from the [documentation](https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-registration/)) 
 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app
 labels:
   app: app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: app
 template:
   metadata:
     labels:
       app: app
     annotations:
       dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets" ## required, the default path where Dapr uses for registering components.
       dapr.io/app-id: "my-app"
       dapr.io/enabled: "true"
   spec:
     volumes: ## required, the sockets volume
       - name: dapr-unix-domain-socket
         emptyDir: {}
     containers:
       ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
       ##
       ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
       ### This is the pluggable component container.
       - name: component
         volumeMounts: # required, the sockets volume mount
           - name: dapr-unix-domain-socket
             mountPath: /tmp/dapr-components-sockets
         image: YOUR_IMAGE_GOES_HERE:YOUR_IMAGE_VERSION
 ```

As you can see, changes must be made to make your deployments/pod ready to use your pluggable components, the problem becomes worse when you have more than one pluggable component in use, hence more than one container. Most of the changes are totally related to Dapr and the pluggable component and nothing related to the application itself and severely degrade the user experience.

The main goal of this proposal is to make the environment setup smoother for the end-user. The pluggable component can still be orchestrated and managed by the user but the necessary environment setup will be handled by Dapr injector.
 
Currently, mounting volumes is the only thing that the user has to do manually when configuring deployments. Having control of this is also an opportunity to make a better setup for the future SDKs, this proposal adds a new annotation for the pod configuration `dapr.io/pluggable-components: "$COMPONENT_A,$COMPONENT_B,$COMPONENT_C"`, $COMPONENT_A, B and C being the name of the containers.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: app
labels:
  app: app
spec:
replicas: 1
selector:
  matchLabels:
    app: app
template:
  metadata:
    labels:
      app: app
    annotations:
      dapr.io/pluggable-components: "component"
      dapr.io/app-id: "my-app"
      dapr.io/enabled: "true"
  spec:
    containers:
      ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
      ##
      ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
      ### This is the pluggable component container.
      - name: component
        image: YOUR_IMAGE_GOES_HERE:YOUR_IMAGE_VERSION
```
 
This way the dapr Injector will:
1. Declare or reuse the declared unix-socket volume
2. Mount the volume and passes it as a environment variable for the container
3. Avoid injecting sidecar-related environment variables (like dapr-address and dapr-port)
