### ISSUE TITLE
Deploy dapr components using helm

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [dapr/dapr#5421]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

Hey! How I  can  properly deploy Dapr components using helm to kubernets cluster for example crond ? how it should connect and trigger some endpoint on api project? so, currently it not working at all, but locally with docker-compose it working fine.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: averageloadschedule
  namespace: <redacted>
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1m"
```
