### ISSUE TITLE
Dapr-ized  NGINX Ingress controller pods in a different namespace

### ISSUE THREAD

**Issue by micheleissa** [dapr/dapr#5426]
Note: I opened this because Slack will not let me register at all..

Thanks in advance for looking into this

I have followed several tutorials/videos on how to dapr-ize nginx ingress controller to allow mTLS between the ingress and the backend services. I got it to work when all the ingress-controller pods and services are deployed in the same namespace as the services to be communicated with, but in most real scenarios ingress controller resources are deployed in a separate namespace. Is there an example on how to do that?

**Comment by iamsourabh-in** [comment]
@micheleissa , I was trying to do the same **but stuck** , strugling to resolve it , having the ingress controller and the service pods to be in different namespace, the ingress though resides in the same namespace as nginx-controller.


No luck yet getting few issues!

```yaml

 # nginx controller pod annotations in the `ingress-nginx`  namespace

      podAnnotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nginx-ingress"
        dapr.io/app-port: "80"
        dapr.io/sidecar-listen-addresses: 0.0.0.0
        dapr.io/log-level: "debug"

```

# Ingress

```yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evolution-ingress
  namespace: ingress-nginx
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    
spec:
  rules:
  - host: evolution.k8
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-ingress-dapr # service created by dapr.
            port:
              number: 80

```
Image for Reference

![image](https://user-images.githubusercontent.com/22702292/199781469-beaf3f63-c97d-4a04-9731-f6580acde816.png)

Gives me the below Error:

```sh
curl --location --request POST 'https://evolution.k8//v1.0/invoke/processor/method/process' \
--header 'HOST: evolution.k8' \
--header 'dapr-app-id: uploader' \
--header 'Content-Type: application/json' \
--data-raw '{
    "BucketName":"",
    "Bucketkey":"",
    "bucketName":""
}'
```

{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: uploader, err: failed to invoke target uploader after 3 retries"
}

Image for Reference.

![image](https://user-images.githubusercontent.com/22702292/199781932-a05a2958-3dc8-4ce4-b3e2-69a54b9116ff.png)


Few Logs for dapr sidecar of the nginx 
```
time="2022-11-03T13:48:34.227070475Z" level=debug msg="retry count: 2, grpc call failed, ns: ingress-nginx, addr: uploader-dapr.ingress-nginx.svc.cluster.local:50002, appid: uploader, err: rpc error: code = Unavailable desc = last resolver error: produced zero addresses" app_id=nginx-ingress instance=ingress-nginx-controller-d6669d4dc-6c4bj scope=dapr.runtime.direct_messaging type=log ver=1.9.2

```

Logs from nginx controller conatiner.

```
192.168.65.3 - - [03/Nov/2022:13:47:26 +0000] "POST //v1.0/invoke/processor/method/process HTTP/1.1" 404 118 "-" "PostmanRuntime/7.29.2" 357 0.049 [ingress-nginx-nginx-ingress-dapr-80] [] 10.1.4.10:3500 118 0.050 404 e313675d6a5793e0c8965ca2f047aca3
192.168.65.3 - - [03/Nov/2022:13:48:36 +0000] "POST //v1.0/invoke/processor/method/process HTTP/1.1" 500 129 "-" "PostmanRuntime/7.29.2" 380 3.174 [ingress-nginx-nginx-ingress-dapr-80] [] 10.1.4.10:3500 129 3.170 500 3d037e2dbf9c2c18659f214cb109df5c
192.168.65.3 - - [03/Nov/2022:14:52:25 +0000] "POST //v1.0/invoke/processor/method/process HTTP/1.1" 500 129 "-" "PostmanRuntime/7.29.2" 380 3.123 [ingress-nginx-nginx-ingress-dapr-80] [] 10.1.4.10:3500 129 3.123 500 8e6881832cb87a177cea338bea310c29
192.168.65.3 - - [03/Nov/2022:16:38:33 +0000] "GET /Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads HTTP/1.1" 404 118 "-" "PostmanRuntime/7.29.2" 354 0.234 [ingress-nginx-nginx-ingress-dapr-80] [] 10.1.4.10:3500 118 0.220 404 919e31f7c431b6940107620f80ab61d5

```
