### ISSUE TITLE
How can I get the placement service to run as nonroot?

### ISSUE THREAD

**Issue by DarrenClevenger** [dapr/dapr#5448]
/area placement

How can I get the placement container to run as nonroot and is this even possible? 

I see this in the chart deployment template, but I'm not sure what 'forceInMemoryLog' means.
``` yaml
{{- if eq .Values.global.daprControlPlaneOs "linux" }}
        securityContext:
{{- if eq .Values.cluster.forceInMemoryLog true }}
          runAsNonRoot: {{ .Values.runAsNonRoot }}
{{- else }}
          runAsUser: 0
```
