### ISSUE TITLE
Dapr PubSub Usage

### ISSUE THREAD

**Issue by kochia4** [dapr/dapr#5465]
I need to use dapr with different server VMs, so not the same host.
I'm bit confused how pubsub uses redis or any other queue management tool

for now, let's assume I'm using declarative approach for subscribers.

We have a worker server, accessible from other servers, which doesn't need any component itself, just to be called when an event occurs and call the specified route.
let's have simple yaml under "./dapr-components " - `subscription.yaml`
```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: pubsub
spec:
  topic: files
  route: /files
  pubsubname: pubsub-vm
```` 

After running the worker server with following command (Rust app):
```bash
dapr run --app-id worker --app-port 3000 --components-path ./dapr-components -- cargo run
````
I assume it should be ready to receive events. 

---

Now move to a publisher server (different VM), which is responsible to receive calls from outside world.
Here we have default config files:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-vm
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```
So, I will just directly:
`dapr run --app-id order --dapr-http-port 3501`

Now, I'm using following url:
```
localhost:3501/v1.0/publish/pubsub-vm/files
```
but I'm not getting anything on the other end, worker server

Do, 
I need pubsub config file on the other side as well?

Is there any good guide for non-localhost setup with multiple devices?
