### ISSUE TITLE
Metadata API contains components that fail to load

### ISSUE THREAD

**Issue by tmacam** [dapr/dapr#5487]
## In what area(s)?

/area runtime

## What version of Dapr?

1.9.0

## Expected Behavior

If a component has `ignoreErrors: true` in its configuration AND it fails to load, it should not be present in the output of Metadata API.

## Actual Behavior

Metadata API lists APIs that fail to load.

## Steps to Reproduce the Problem

I am using Hashicorp Vault as an example here, but it should be the case with other components. HashiCorp requires that either `vaultToken` or `vaultTokenMountPath` be defined for its configuration, but not both. 

1. Create an empty directory `/tmp/dapr` and creathe the file `/tmp/dapr/hashicorp-vault.yaml` with the following contents

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-hashicorp-vault-TestTokenAndTokenMountPath-neither
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  ignoreErrors: true  # This component will fail to load but we don't want Dapr to FATAL because of it.
  metadata:
  - name: vaultAddr
    value: "http://127.0.0.1:8200"
  # no vaultToken or vaultTokenMountPath
```

2. Run Dapr pointing to this directory:

```shell
dapr run --app-id myapp --components-path=/tmp/dapr --app-protocol http --dapr-http-port 3501
```

3. Notice in Dapr output that the component failed to load:

```text
ERRO[0000] process component my-hashicorp-vault-TestTokenAndTokenMountPath-neither error: [INIT_COMPONENT_FAILURE]: initialization error occurred for my-hashicorp-vault-TestTokenAndTokenMountPath-neither (secretstores.hashicorp.vault/v1): token mount path and token not set  app_id=myapp instance=XXXXXXX scope=dapr.runtime type=log ver=1.9.0
```

4. Query the metadata API:

```shell
$ curl --silent http://localhost:3501/v1.0/metadata | jq .
{
  "id": "myapp",
  "actors": [],
  "extended": {
    "cliPID": "1401",
    "daprRuntimeVersion": "1.9.0"
  },
  "components": [
    {
      "name": "my-hashicorp-vault-TestTokenAndTokenMountPath-neither",
      "type": "secretstores.hashicorp.vault",
      "version": "v1",
      "capabilities": []
    }
  ]
}
```

5. Observe that this output lists the HashiCorp Vault component that fail to initialize and is thus not operational.

## Release Note

RELEASE NOTE: **FIX** Components with `ignoreErrors: true` that fail to load are not returned by Metadata API
