### ISSUE TITLE
Add Declarative Support to Bulk Subscribe

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#5499]
## In what area(s)?

/area runtime

/area docs

## Describe the feature
RIght now, Bulk Subscribe is added only for Programmatic Way. The ask is to be able to use Bulk Subscribe in a Decalarative Way as well.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
I like option 1 because it can allow Dapr to have sane defaults for maxBulkSubCount and maxBulkSubAwaitDurationMs

**Comment by artursouza** [comment]
I like Yaron's proposal better.

**Comment by DeepanshuA** [comment]
> Sane defaults are always a good practice to follow when possible.
> 
> Since the bulk functionality has multiple fields I think it makes sense to put it in it's own section. Can we allow something like this as a minimum?
> 
> ```yaml
> apiVersion: dapr.io/v1alpha1
> kind: Subscription
> metadata:
>   name: orders-subscription-mqtt
> spec:
>   topic: orders
>   route: /orders
>   pubsubname: mqtt-pubsub
>   bulkSubscribe:
>     enabled: "true"
>   metadata:
>     rawPayload: "true"
> ```
> 
> In the example above, bulk subscription is enabled with sane defaults that users can override. I think this actually mimics most pub/sub message brokers today.

OK, so if I understand correctly, we will have sane defaults mentioned in dapr/dapr code and they can be overridden by common metadata, something like this?

```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: orders-subscription-mqtt
spec:
  topic: orders
  route: /orders
  pubsubname: mqtt-pubsub
  bulkSubscribe: 
    enabled: "true"
  metadata:
    rawPayload: "true"
    maxBulkSubCount: "4"
    maxBulkSubAwaitDurationMs: "10000"
```

**Comment by artursouza** [comment]
In case of Yaron's proposal, it would move anything bulk related under `bulkSubscribe`:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: orders-subscription-mqtt
spec:
  topic: orders
  route: /orders
  pubsubname: mqtt-pubsub
  bulkSubscribe: 
    enabled: "true"
    maxBulkSubCount: "4"
    maxBulkSubAwaitDurationMs: "10000"
  metadata:
    rawPayload: "true"
```
