### ISSUE TITLE
Dapr does not log traces to otel-collector when in docker-compose network

### ISSUE THREAD

**Issue by mhmast** [dapr/dapr#5551]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.8.x

## Expected Behavior

Dapr logs traces of service calls to otel-collector when in a docker network. This also works when the network is removed.

## Actual Behavior

Dapr traces not showing up at the otel-collector. (Note that i also log to a file)

## Steps to Reproduce the Problem

I'm using docker-desktop for windows.
This is the docker-compose file I'm using. Note that service 1 and 2 are .net6 services and the names are substitutes for the original names. I recon for this issue they could theoretically be any service.

```
services:

#CUSTOM


  #Service 1
  service1:
    depends_on: 
      - mongo
      - placement
      - redis
    ports:
      - 9443:443
    networks:
      - network1
    environment:
       - ASPNETCORE_URLS=https://+
       - CertPass=123
    build: 
     dockerfile: Service1/Dockerfile
  
 
  #Service2
  service2:
    depends_on: 
      - service1
      - placement
      - redis
    networks:
      - network1
    ports:
      - 8443:443
    environment:
      - ASPNETCORE_URLS=https://+
      - CertPass=123
    build: 
     dockerfile: Service2/Dockerfile
  

#DAPR
  #DASHBOARD
  dapr-dashboard:
    image: "mhmast/dapr-dashboard:latest"
    depends_on: 
      - placement
      - redis
    networks:
      - network1
    ports:
      - 10000:8080
    command: [
        "--docker-compose-path","/compose/docker-compose.yml",
        "--docker-compose",
        "--components-path", "/components",
        "--config-path","/config/dapr-configuration.yaml"
    ] 
    volumes:
      - "./:/compose"
      - "./Config/Dapr/Components:/components" 
      - "./Config/Dapr/dapr-configuration.yaml:/config/dapr-configuration.yaml" 
     
  
  #Service1
  service1-dapr:
    image: "daprio/daprd:1.8.3" 
    command: [
      "./daprd",
     "--app-id", "service1",
     "--app-port", "443",
     "--components-path", "/components",
     "--config","/config/dapr-configuration.yaml",
     "--app-ssl"
     ]
    volumes:
      - "./Config/Dapr/Components/statestore.yaml:/components/statestore.yaml" 
      - "./Config/Dapr/dapr-configuration.yaml:/config/dapr-configuration.yaml" 
    depends_on:
      - service1
    network_mode: "service:service1"

      
  #Service 2
  service2-dapr:
    image: "daprio/daprd:1.8.3" 
    command: [
      "./daprd",
     "--app-id", "service2",
     "--app-port", "443",
     "--components-path", "/components",
     "--config","/config/dapr-configuration.yaml",
     "--log-level","debug",
        "--app-ssl",
      "--enable-api-logging"
     ]
    volumes:
      - "./Config/Dapr/Components/statestore.yaml:/components/statestore.yaml" 
      - "./Config/Dapr/dapr-configuration.yaml:/config/dapr-configuration.yaml"
    depends_on:
      - service2
    network_mode: "service:service2"

  
  #PLACEMENT
  placement:
    image: "daprio/placement:1.8.3"
    command: ["./placement", 
    "--port", "50006",
      "--log-level","debug",
        "--log-as-json",
    ]
    ports:
      - "50006:50006"
    networks:
      - network1
    depends_on:
      - otel

  #REDIS STATESTORE
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - network1

    #Commander
  rediscommander:
    image: rediscommander/redis-commander:latest
    ports: 
      - "8082:8081"
    networks: 
      - network1
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

# LOGGING

  #OTEL
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./Config/Otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP receiver
      - "9412:9412"   # Zipkin receiver
    depends_on:
      - elastic
    networks:
      - network1

   #KIBANA
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
    depends_on:
      - elastic
    networks:
      - network1

  
  #ELASTICSEARCH    
  elastic:
     ports:
      - "9200:9200"
     environment: 
       xpack.security.enabled: false
       discovery.type: single-node
     image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
     networks:
      - network1

  

#DATABASE
  mongo:
    image: mongo:latest
    volumes:
      - ./Database:/data/db
    networks:
      - network1

  mongo-express:
    image: mongo-express:latest
    depends_on: 
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - network1
    ports:
      - "8081:8081"

networks:
  # The presence of these objects is sufficient to define them
  network1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
   
```

The dapr-configuration.yaml :

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  mtls:
    enabled: false
  tracing:
    enabled: true
    samplingRate: "1"
    expandParams: true
    includeBody: true
    zipkin:
        endpoint: http://host.docker.internal:9412/api/v2/spans 
#Have tried with http://otel:9412/api/v2/spans  and the otlp endpoint as well
        tls:
          insecure: true

```

The otel collector config
```
# Configure receivers
# We only need otlp protocol on grpc, but you can use http, zipkin, jaeger, aws, etc.
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
receivers:
  zipkin:
    endpoint: 0.0.0.0:9412
  otlp:
    protocols:
      grpc:

# Configure exporters
exporters:
  elasticsearch:
     endpoints: [http://elastic:9200]
     logs_index: logs
     traces_index: logs
     tls:
       insecure: true
      
    #format: proto

  # Export to a file
  file:
    path: /etc/output/logs.json

# Configure processors (batch, sampling, filtering, hashing sensitive data, etc.)
# https://opentelemetry.io/docs/collector/configuration/#processors
processors:
  batch:

# Configure pipelines. Pipeline defines a path the data follows in the Collector
# starting from reception, then further processing or modification and finally
# exiting the Collector via exporters.
# https://opentelemetry.io/docs/collector/configuration/#service
# https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md#pipelines
service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [elasticsearch,file]
    #metrics:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch,file]
```
The dapr statestore.yaml component

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: actorStateStore
    value: true
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
```

## Release Note

RELEASE NOTE:
**FIX** Traces are being logged to external collector endpoint when inside a docker network
