### ISSUE TITLE
Resiliency retries not work

### ISSUE THREAD

**Issue by bookinstock** [dapr/dapr#5557]
## Resiliency retries not work

darp version : 1.9.4

I deployed dapr in kubernetes with feature resiliency enabled and resiliency configured

There is an apisix dapr app as an api gateway whose upstream is a dapr app name bff with 3 instances

I expect the retry feature would help me send failed requests to other healthy bff instance, it still retry the same failed instance, then response code 502

steps:
- client send request to api gateway
- stop 1 bff pod
- check whether response failed

seem like resiliency retires not work.

app architecture show below
<img width="416" alt="image" src="https://user-images.githubusercontent.com/9897776/203514985-df7c3a31-1893-4af3-a93f-84ee643e7284.png">

Resiliency config show below
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: enckeappresiliency
  namespace: ingress-apisix
# similar to subscription and configuration specs, scopes lists the Dapr App IDs that this
# resiliency spec can be used by.
scopes:
  - apisix-gateway
spec:
  # policies is where timeouts, retries and circuit breaker policies are defined.
  # each is given a name so they can be referred to from the targets section in the resiliency spec.
  policies:
    # timeouts are simple named durations.
    timeouts:
      general: 1s
      important: 60s
      largeResponse: 10s

    # retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 10

      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: -1 # retry indefinitely

      important:
        policy: constant
        duration: 200ms
        maxRetries: -1

      someOperation:
        policy: exponential
        maxInterval: 15s

      largeResponse:
        policy: constant
        duration: 5s
        maxRetries: 3

    # circuit breakers are automatically instantiated per component and app instance.
    # circuit breakers maintain counters that live as long as the Dapr sidecar is running. They are not persisted.
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 30s 
        trip: consecutiveFailures >= 5

      pubsubCB:
        maxRequests: 1
        interval: 8s
        timeout: 45s
        trip: consecutiveFailures > 8

  # targets are what named policies are applied to. Dapr supports 3 target types - apps, components and actors
  targets:
    apps:
      apisix-gateway:
        timeout: general
        retry: retryForever
        # circuit breakers for services are scoped app instance.
        # when a breaker is tripped, that route is removed from load balancing for the configured `timeout` duration.
        circuitBreaker: simpleCB

    actors:
      myActorType: # custom Actor Type Name
        timeout: general
        retry: important
        # circuit breakers for actors are scoped by type, id, or both.
        # when a breaker is tripped, that type or id is removed from the placement table for the configured `timeout` duration.
        circuitBreaker: simpleCB
        circuitBreakerScope: both ## 
        circuitBreakerCacheSize: 5000

    components:
      # for state stores, policies apply to saving and retrieving state.
      statestore1: # any component name -- happens to be a state store here
        outbound:
          timeout: general
          retry: retryForever
          # circuit breakers for components are scoped per component configuration/instance. For example myRediscomponent.
          # when this breaker is tripped, all interaction to that component is prevented for the configured `timeout` duration.
          circuitBreaker: simpleCB

      pubsub1: # any component name -- happens to be a pubsub broker here
        outbound:
          retry: pubsubRetry
          circuitBreaker: pubsubCB

      pubsub2: # any component name -- happens to be another pubsub broker here
        outbound:
          retry: pubsubRetry
          circuitBreaker: pubsubCB
        inbound: # inbound only applies to delivery from sidecar to app
          timeout: general
          retry: important
          circuitBreaker: pubsubCB
```

test results
<img width="502" alt="image" src="https://user-images.githubusercontent.com/9897776/203521531-1833187a-896f-48a1-9bb5-3829f1da5c88.png">

dapr log
<img width="685" alt="image" src="https://user-images.githubusercontent.com/9897776/203521445-b1418076-92f8-41df-988c-aa94964766be.png">

**Comment by yaron2** [comment]
cc @halspang

**Comment by bookinstock** [comment]
how to check whether the dapr resiliency configuration is correct in k8s?

**Comment by halspang** [comment]
The target needs to be the other app. In this case `bff`. The scope is what enables the app to load the configuration, it then applies policies to what you are calling, not what you are calling from.

**Comment by bookinstock** [comment]
@halspang thank your for your reply. I tried to change the target app to `bff`, but still not work. How can I check the resiliency config is ok? I couldn't find it in the dapr bashboard. Should I add any dapr annotation to make resiliency config work when I apply apisix app to k8s?

The apigateway and bff are actually in two different namespace, should I append namespace to the app name in the resiliency configuration (scopes and targets sections), such as 
```
scopes:
  - apisix-gateway.namespace1

...
targets:
    apps:
      bff.namespace2:
```

**Comment by bookinstock** [comment]
@halspang I also tried a simple example to check retires feature.

There are two dapr apps named `aaa` (1 pod) and `bbb` (3 pod)
`aaa` send request to `bbb`
<img width="493" alt="image" src="https://user-images.githubusercontent.com/9897776/204403389-4e7f33f7-dacc-4c1d-913c-9d402f6a9c04.png">

app aaa code:
```go
package main

import (
	"flag"
	"fmt"
	"html"
	"io"
	"log"
	"net/http"
)

func main() {

	port := flag.String("port", "foo", "a string")
	flag.Parse()

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("call hello")
		fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
	})

	http.HandleFunc("/hi", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("call hi")
		fmt.Fprintf(w, "Hi")
	})

	http.HandleFunc("/send", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("call send")
		resp, err := http.Get("http://localhost:3500/v1.0/invoke/bbb.default/method/hi")
		if err != nil {
			log.Fatalln(err)
		}
		if resp.StatusCode >= 500 {
			b, err := io.ReadAll(resp.Body)
			if err != nil {
				log.Fatalln(err)
			}
			fmt.Println("err response=", string(b))
			w.WriteHeader(http.StatusInternalServerError)
			fmt.Fprintf(w, "fail")
		} else {
			w.WriteHeader(http.StatusOK)
			fmt.Fprintf(w, "ok")
		}
	})

	fmt.Println("start server with port", *port)
	log.Fatal(http.ListenAndServe(*port, nil))

}

```
dapr config
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: featureconfig
spec:
  features:
    - name: Resiliency
      enabled: true
```

resiliency config
```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
  namespace: default
scopes:
  - aaa
spec:
  policies:
    retries:
      retryForever:
        policy: exponential
        maxInterval: 15s
        maxRetries: -1
  targets:
    apps:
      bbb:
        retry: retryForever
```

aaa deploy
```yaml
kind: Service
apiVersion: v1
metadata:
  name: aaasvc
  labels:
    app: aaa
spec:
  selector:
    app: aaa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaadep
  labels:
    app: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa
  template:
    metadata:
      labels:
        app: aaa
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "aaa"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: featureconfig
    spec:
      containers:
      - name: aaa
        image: aaa
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
```
bbb deploy
```yaml
kind: Service
apiVersion: v1
metadata:
  name: bbbsvc
  labels:
    app: bbb
spec:
  selector:
    app: bbb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbbdep
  labels:
    app: bbb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      labels:
        app: bbb
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "bbb"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: featureconfig
    spec:
      containers:
      - name: bbb
        image: bbb
        ports:
        - containerPort: 8080
        imagePullPolicy: Never

```


send request to aaa
<img width="672" alt="image" src="https://user-images.githubusercontent.com/9897776/204403304-825de9a6-7c99-4faf-9604-4688d2dc7b54.png">


I deleted 1 pod of `bbb` while sending the test requests
there are 34 error logs in `aaa`, show below
<img width="636" alt="image" src="https://user-images.githubusercontent.com/9897776/204403178-d90cc35d-70ef-40ac-8f73-4aaefd553778.png">

**Comment by akhilac1** [comment]
@bookinstock @halspang - I suspect this does not seem like a resiliency retries issue. The retry is being triggered due to the resiliency policy. The name resolution is however always returning the same host - which was shutdown.

@bookinstock - Regarding this statement -
```I expect the retry feature would help me send failed requests to other healthy bff instance, it still retry the same failed instance, then response code 502```

Are you expecting retry policy to perform load balancing and use a healthy instance to send the  request during retry? 
Also, can you confirm which Nameresolution are you using?
Can you please try to use consul with health check enabled? [Link](https://developer.hashicorp.com/consul/tutorials/developer-discovery/service-registration-health-checks)

**Comment by bookinstock** [comment]
@akhilac1 thank your for your reply.  In the example mentioned above, the resiliency retry policy is `retryForever`, if `bbb` not response, `aaa` will keep retry until the request got response from `bbb`. It work fine in the self-hosted mode, but not in the k8s environment. 

Is there anything missing in configuring resiliency in k8s?
Should I add additional annotation to let the sidecar to load the resiliency config
And how to make sure the app `aaa` is use the applied resiliency crd `myresiliency` 

```
annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "aaa"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: featureconfig
```
