### ISSUE TITLE
First simple .Net Dapr app backend call gives 500

### ISSUE THREAD

**Issue by GeofoxCoding** [dapr/dapr#5600]
Hi everyone,

I still try to get a first simple .Net app with blazor server frontend and webapi backend up an running with the basic .net templates.

So far I was able to get my frontend up with docker-compose. Inside FetchData page I call my backend DAPR service:

```
forecasts = await _daprClient.InvokeMethodAsync<IEnumerable<WeatherForecast>>(
            HttpMethod.Get,
            "API",
            "weatherforecast");   
```

But I receive :
Unhandled exception rendering component: An exception occurred while invoking method: 'weatherforecast' on app-id: 'API'
daprtest-dapr.test.frontend-1       |       Dapr.Client.InvocationException: An exception occurred while invoking method: 'weatherforecast' on app-id: 'API'
daprtest-dapr.test.frontend-1       |        ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
daprtest-dapr.test.frontend-1       |          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
daprtest-dapr.test.frontend-1       |          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
daprtest-dapr.test.frontend-1       |          --- End of inner exception stack trace ---
daprtest-dapr.test.frontend-1       |          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
daprtest-dapr.test.frontend-1       |          at DAPR.Test.Frontend.Pages.FetchData.OnInitializedAsync() in /src/DAPR.Test.Frontend/Pages/FetchData.razor:line 49
daprtest-dapr.test.frontend-1       |          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
daprtest-dapr.test.frontend-1       |          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
daprtest-dapr.test.frontend-1       | fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]

My docker-compose.yml:
```
version: '3.4'

services:
  dapr.test.frontend:
    image: ${DOCKER_REGISTRY-}bricksonawhale/dapr-test/frontend:0.0.2
    build:
      context: .
      dockerfile: DAPR.Test.Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=***
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/DAPR.Test.API.pfx
    ports:
      - "51000:50001"
      - "5001:80"
      - "5002:443"
    volumes:
      - ~/.microsoft/usersecrets/:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https/:/root/.aspnet/https/

  dapr.test.frontend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "--app-id", "Frontend", "--app-port", "80", "--app-ssl" ]
    depends_on:
      - dapr.test.frontend
    network_mode: "service:dapr.test.frontend"

  dapr.test.api:
    image: ${DOCKER_REGISTRY-}bricksonawhale/dapr-test/api:0.0.1
    build:
      context: .
      dockerfile: DAPR.Test.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=***
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/DAPR.Test.API.pfx
    ports:
      - "52000:50001"
    volumes:
      - ~/.microsoft/usersecrets/:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https/:/root/.aspnet/https/

  dapr.test.api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "--app-id", "API", "--app-port", "80", "--app-ssl" ]
    depends_on:
      - dapr.test.api
    network_mode: "service:dapr.test.api"
```
    

At the moment I'm unable to get more information because Visual Studio Mac is unable to debug with my Colima Docker Process and needs Docker Desktop ...

Anyway, the API container doesn't show any messages. Can I check that API DAPR service is reachable from inside Frontend container?

For now I will add Logging to probably get some more infos.

Any help is very much appreciated.
