### ISSUE TITLE
Rate Limits not working as specified

### ISSUE THREAD

**Issue by alecor191** [dapr/dapr#5604]
## In what area(s)?

/area runtime

## What version of Dapr?

CLI version: 1.9.1
Runtime version: 1.9.4

## Expected Behavior

Configuring rate limits for app `A` should result in `429` responses being returned when another app (`B`) sends requests at a frequency that exceeds the rate limit.

## Actual Behavior

There are 2 unexpected behaviors:

- When `B` sends requests to `A` at a frequency that exceeds `A`'s configured rate limit, there are no 429; all requests succeed
- When `A` sends requests to `B` (which hasn't _any_ rate limits configured), `A` receives 429 from `B`.

## Steps to Reproduce the Problem

I have 2 apps `A` and `B`. `A` is configured with a rate limit of 1 rps. `B` has no limits configured. Here the relevant yaml snippets:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: default-rate-limit
spec:
  type: middleware.http.ratelimit
  version: v1
  metadata:
    - name: maxRequestsPerSecond
      value: 1

# Config assigned to app A
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: A 
spec:
  ...
  httpPipeline:
    handlers:
    - name: default-rate-limit
      type: middleware.http.ratelimit

# Config assigned to app B
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: B 
spec:
  ...
  # nothing related to rate limits defined
```

The following results show what happened when running a `curl` command from a pod shell connected to either container `A` or `B`. Note that the two requests were sent back-to-back (<1 second apart), so that the second request should have exceeded the configured rate limit of 1 rps.

### Send requests from A -> A

```text
> curl -I -X GET -H "dapr-app-id: a" http://localhost:3500/info
HTTP/1.1 200 OK
...

> curl -I -X GET -H "dapr-app-id: a" http://localhost:3500/info
HTTP/1.1 429 Too Many Requests
...
```

**EXPECTED**: Sending a requests from the container hosting the rate-limited app `A` to itself, works as expected. The second request fails due to >1 rps request frequency.

### Send requests from B -> A

```text
> curl -I -X GET -H "dapr-app-id: a" http://localhost:3500/info
HTTP/1.1 200 OK
...

> curl -I -X GET -H "dapr-app-id: a" http://localhost:3500/info
HTTP/1.1 200 OK
...
```

**UNEXPECTED**: As shown, all requests succeed even though the second one should have failed with 429.

### Send requests from B -> B

```text
> curl -I -X GET -H "dapr-app-id: b" http://localhost:3500/info
HTTP/1.1 200 OK
...

> curl -I -X GET -H "dapr-app-id: b" http://localhost:3500/info
HTTP/1.1 200 OK
...
```

**EXPECTED**: When `B` sends requests with >1 rps to itself, all succeed as there are no rate limits configured for `B`.

### Send requests from A -> B

```text
> curl -I -X GET -H "dapr-app-id: b" http://localhost:3500/info
HTTP/1.1 200 OK
...

> curl -I -X GET -H "dapr-app-id: b" http://localhost:3500/info
HTTP/1.1 429 Too Many Requests
...
```

**UNEXPECTED**: There should be no 429 responses returned by `B`, as there are no rate limits configured for `B`. However, it seems sending requests from `A` to `B` results in 429 responses.
