### ISSUE TITLE
Dapr on K8s doesn't start when Consul container is present

### ISSUE THREAD

**Issue by AfroSpartan** [dapr/dapr#5643]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.9.3

## Expected Behavior

Dapr client container starts successfully when deploying a new container with Dapr and Consul sidecars injected

## Actual Behavior

Dapr starts initializing the operating client then returns fatal log: "context deadline exceeded"

## Steps to Reproduce the Problem

1. Install dapr on K8s
2. Install consul on K8s using helm
3. Create a deployment to inject both sidecars
4. Pod's status should eventually display CrashLoopBackOff

For my current setup I'm using Minikube v1.28.0

Dapr container starts as long as the Consul annotation isn't provided

Example deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickmaths-service
  labels:
    app: quickmaths-service
spec:
  selector:
    matchLabels:
      app: quickmaths-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quickmaths-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "quickmaths-service"
        dapr.io/app-port: "5000"
        dapr.io/config: "tracing"
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-probe-interval: "5"
        dapr.io/app-protocol: "http"
        dapr.io/sidecar-liveness-probe-delay-seconds: "60"
        dapr.io/sidecar-readiness-probe-delay-seconds: "60"
        dapr.io/log-level: "debug"
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name: quickmaths-service
        image: [URL]
        ports:
        - containerPort: 5000
          name: api
      imagePullSecrets:
        - name: regcred
```

Logs:
```
time="2022-12-15T12:39:54.489347682Z" level=info msg="starting Dapr Runtime -- version 1.9.3 -- commit 549b240ea0105feebf0b90b36e5564280eb81066" app_id=quickmaths-service instance=quickmaths-service-f4fc88fdd-br7sw scope=dapr.runtime type=log ver=1.9.3

time="2022-12-15T12:39:54.489380729Z" level=info msg="log level set to: debug" app_id=quickmaths-service instance=quickmaths-service-f4fc88fdd-br7sw scope=dapr.runtime type=log ver=1.9.3

time="2022-12-15T12:39:54.48948637Z" level=info msg="metrics server started on :9090/" app_id=quickmaths-service instance=quickmaths-service-f4fc88fdd-br7sw scope=dapr.metrics type=log ver=1.9.3

time="2022-12-15T12:39:54.489606313Z" level=info msg="Initializing the operator client (config: appconfig)" app_id=quickmaths-service instance=quickmaths-service-f4fc88fdd-br7sw scope=dapr.runtime type=log ver=1.9.3

time="2022-12-15T12:40:24.490756071Z" level=fatal msg="context deadline exceeded" app_id=quickmaths-service instance=quickmaths-service-f4fc88fdd-br7sw scope=dapr.runtime type=log ver=1.9.3
```
