### ISSUE TITLE
Alias the existing state store as KV store

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#5653]
> /area runtime

> /area docs

## Describe the proposal

In anticipation of new specialised State Management building blocks coming online in the future ([Object Store](https://github.com/dapr/proposals/pull/18), [Document Store](https://github.com/dapr/dapr/issues/5146)) there is a general agreement that the existing State Management Building Block should be aliased to something more specific, such as KeyValue Store (or KV Store) in the API surface.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4224880/208268843-c37fd9e3-1076-4ac0-9a50-22ebaaa3784b.png">

## Non-exhaustive list of other work to be considered which doesn't have to be done as part of this ticket
- Introduce new methods in SDK ?
- Update dapr State Management documentation  ?
- Update quickstarts and code samples ?

## Other thoughts....

Should the component `type` be aliased too ? For example `type : kv.postgresql`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: kv.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "<CONNECTION STRING>"
```
