### ISSUE TITLE
Subscription - Format Azure Container App Service

### ISSUE THREAD

**Issue by BC89** [dapr/dapr#5708]
## In what area(s)?

> /area runtime - v1.9

## Ask your question here

I have a azure service bus component configured and a subscription configuration setup and working locally just fine like so but can't seem to figure out how the Subscription should be coded in bicep when pushing to azure container app services: 

SUBSRIPTION:
  ```
apiVersion: dapr.io/v2alpha1
  kind: Subscription
  metadata:
    name: messages-email
  spec:  
    pubsubname: messages
    topic: model
    routes:   
      rules:
        - match: event.type == "com.my.widget"
          path: /widget
      default: /email
  scopes:
    - dotnet-dotnetemail 
```

PUBLISHER:
```
 apiVersion: dapr.io/v1alpha1
 kind: Component
 metadata:
   name: messages
 spec:
   type: pubsub.azure.servicebus
   version: v1
   metadata:
   - name: connectionString
     value: "Endpoint=sb://sbnxnyb...."
```

However, when deploying to Azure via Bicep it's unclear how to configure a Subscriber component. The bicep below runs and does the deploy but leaves my app in a failed state:

PUBLISHER (BICEP):
```
resource serviceBusComponent 'Microsoft.App/managedEnvironments/daprComponents@2022-06-01-preview' = {
  name: 'messages'
  parent: containerEnvironment
  properties: {
    secretStoreComponent: keyVaultComponent.name
    componentType: 'pubsub.azure.servicebus'
    version: 'v1'
    metadata: [
      {
        name: 'connectionString'
        secretRef: 'serviceBusConn'
      }
    ]
    secrets: []
    scopes: []
  }
}
```

**SUBSCRIBER (BICEP):**
```
resource emailSubscriptionComponent 'Microsoft.App/managedEnvironments/daprComponents@2022-06-01-preview' = {
  name: 'messages-email'
  parent: containerEnvironment
  properties: {
    componentType: 'subscription'
    version: 'v1'
    metadata: [
      {
        name: 'pubsubname'
        value: serviceBusComponent.name
      }, {
        name: 'topic'
        value: 'model'
      }, {
        name: 'route'
        value: 'email'
      }
    ]
    scopes: [
      appApiAppName
    ]
  }
}
```

Any help or pointers/leads would be much appreciated.

Thx,
-BC
