### ISSUE TITLE
Resiliency, timeouts, and gRPC proxying streams

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5748]
While performing some tests, I ran into one potential issue that I think may be worth clarifying.

- `client` invokes `server` using gRPC proxying
- Resiliency policy:  
  
  ```yaml
  apiVersion: dapr.io/v1alpha1
  kind: Resiliency
  metadata:
    name: myresiliency
  scopes:
    - client
  spec:
    policies:
      timeouts:
        five: 5s
    targets:
      apps:
        server:
          timeout: five
  ```
- If the method `client` invokes in `server` is a streaming call (e.g. `rpc Pinger(stream Ping) returns (stream Ping) {}`), after 5s the timeout policy kicks in and forcefully terminates the connection

Is this an intended behavior? Which means that users should not set policies with a timeout when they are using streaming calls

- If so, possible downside: there's no way to set a custom timeout, for example to handle connection errors (there's a timeout of 30s for establishing connections, but that may be too long)
