### ISSUE TITLE
dapr-dashboard Deployment (k8s) Crashloopbackoff

### ISSUE THREAD

**Issue by VuiDJi** [dapr/dapr#5763]
/area placement

## What version of Dapr?
1.9.5

## Expected Behavior
dapr-dashboard deployment should works.

## Actual Behavior
dapr-dashboard deployment starts and crashes if I try to load dashboard page.

dapr was deployed using `dapr init -k --enable-ha=true --enable-mtls=false` command at RKE2 k8s v1.24.9 cluster with three nodes.

Everything was working fine, but I noticed that after one of the nodes was drained (I'm not sure if it matters), the dapr-dashboard started to crash with an exception:
```
15/1/2023 14:42:08 | Dapr Dashboard running on http://localhost:8080
15/1/2023 14:42:16 | panic: runtime error: index out of range [0] with length 0
15/1/2023 14:42:16 |  
15/1/2023 14:42:16 | goroutine 57 [running]:
15/1/2023 14:42:16 | github.com/dapr/dashboard/pkg/instances.(*instances).GetControlPlaneStatus.func1({0x17bdb86, 0x15})
15/1/2023 14:42:16 | /home/runner/work/dashboard/dashboard/pkg/instances/instances.go:306 +0x7e5
15/1/2023 14:42:16 | created by github.com/dapr/dashboard/pkg/instances.(*instances).GetControlPlaneStatus
15/1/2023 14:42:16 | /home/runner/work/dashboard/dashboard/pkg/instances/instances.go:288 +0x228
```

## Steps to Reproduce the Problem
Deploy darp using  `dapr init -k --enable-ha=true --enable-mtls=false` command.
Drain node, that was running dapr dashboard (I'm not sure if it matters).
Try to open dashboard web page.

**Comment by VuiDJi** [comment]
Apparently, the application crashed when we had the next resource defined in helm chart:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: donum-lockstore
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: lock.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:26379
  - name: failover
    value: true
  - name: sentinelMasterName
    value: mymaster
  - name: redisType
    value: cluster
```
Perhaps the fact is that lock.redis does not seem to be able to work with redis+sentinel: https://github.com/dapr/components-contrib/issues/2442
