### ISSUE TITLE
dapr sidecar crashes when using redis lock with sentinel

### ISSUE THREAD

**Issue by VuiDJi** [dapr/dapr#5764]
## In what area(s)?
/area runtime

## What version of Dapr?
1.9.5

## Expected Behavior
We've deployed redis with sentinel with 3 nodes.

According to the following documentation https://docs.dapr.io/reference/components-reference/supported-locks/redis-lock/ it's expected that it is possible to use a failover redis with sentinel for lock component.

## Actual Behavior
However, dapr sidecar crashes several times until it starts with the following error:
`time="2023-01-15T15:13:33.408791532Z" level=fatal msg="process component donum-lockstore error: [INIT_COMPONENT_FAILURE]: initialization error occurred for donum-lockstore (lock.redis/v1): [standaloneRedisLock]: InitLockStore error. Replication is not supported" app_id=donum-staging-donum-proxyinput instance=donum-proxyinput-5bffbfcd4b-szx57 scope=dapr.runtime type=log ver=1.9.5`

## Steps to Reproduce the Problem

Deploy redis+sentinels with 3 nodes:
```
helm upgrade redis bitnami/redis \
--install \
--namespace $DONUMNAMESPACE --create-namespace \
--set "architecture=replication" \
--set "sentinel.enabled=true" \
--set "sentinel.redisShutdownWaitFailover=false" \
--set "auth.enabled=false" \
--set "auth.sentinel=false" \
--set "pdb.create=true" \
--set "pdb.minAvailable=2" \
--wait
```

Apply state.redis component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: donum-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:26379
  - name: failover
    value: true
  - name: sentinelMasterName
    value: mymaster
  - name: redisType
    value: cluster
```

Try to deploy some ASP.NET Core app with dapr sidecar:
```
    metadata:
      annotations:
        dapr.io/app-id: some-app-name
        dapr.io/app-port: "80"
        dapr.io/config: dapr-config
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1024"
        dapr.io/sidecar-readiness-probe-threshold: "20"
```
