### ISSUE TITLE
Have an ingress template for the dashboard helm chart

### ISSUE THREAD

**Issue by cmoulliard** [dapr/dapr#5778]
## In what area(s)?

> /area helm-packaging

## Describe the feature

Create an ingress template part of the Dashboard chart in oder to expose the dashboard on the k8s cluster withut the need to use `dapr dashboard -k`

Example of ingress yaml to be converted to a ingress helm template file
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr
  namespace: dapr-system <-- Convert to var that we can customize as helm value
spec:
  ingressClassName: nginx <-- Convert to var that we can customize as helm value
  rules:
  - host: dapr.192.168.1.90.nip.io <-- Convert to var that we can customize as helm value
    http:
      paths:
      - backend:
          service:
            name: dapr-dashboard
            port:
              number: 8080
        path: /
        pathType: Prefix
```

## Release Note

RELEASE NOTE:
