### ISSUE TITLE
Use Dapr oAuth-Middleware in a .Net App with Keycloak

### ISSUE THREAD

**Issue by GeofoxCoding** [dapr/dapr#5785]
## In what area(s)?
/area docs

## Ask your question here

Hello,

I'm new to Dapr and we are starting to develop an .Net app. I was following the beginner guide provided here:
https://learn.microsoft.com/de-de/dotnet/architecture/dapr-for-net-developers/getting-started

We are starting with a frontend Blazor server app with Dapr sidecar and a Keycloak all defined in a docker-compose for development purpose.

I have added two Dapr configurations to my components folder:

Keycloak_Component.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
  namespace: default
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: "my_app_id"
  - name: clientSecret
    value: "my_secret"
  - name: scopes
    value: "openid profile roles"
  - name: authURL
    value: "https://localhost:30200/auth/realms/my_realm/protocol/openid-connect/auth"
  - name: tokenURL
    value: "https://localhost:30200/auth/realms/my_realm/protocol/openid-connect/token"
  - name: redirectURL
    value: "https://localhost:54956/"
  - name: authHeaderName
    value: "authorization"
  - name: forceHTTPS
    value: "true"
```

Keycloak_Pipeline.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
  namespace: default
spec:
  httpPipeline:
    handlers:
    - name: oauth2
      type: middleware.http.oauth2
```

Now I have two questions:
1. If I have my frontend application and I have a "login" button or something like that, how can I initiate the login flow to Keycloak via dapr. Do I really have to create a secured REST endpoint and make a Dapr call to it?
2. How does Dapr understand that a special endpoint is secured?

Thank you very much for your help!
