### ISSUE TITLE
Proposal: protected topics for pub/sub

### ISSUE THREAD

**Issue by ralf-vogel** [dapr/dapr#5843]
## In what areas?

> /area runtime

## Proposal

In #1296, @yaron2 has introduced the scopes for pub/sub. As described in [the docs](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-scopes/), one can limit the scopes like this:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
  - name: allowedTopics
    value: "A,B"
  - name: publishingScopes
    value: "app1=A"
  - name: subscriptionScopes
    value: "app1=;app2=A"
```
so that `app1` can only publish to topic `A`, but subscribe to no topic, because it is explicitly forbidden to subscribe to any topic in `subscriptionScopes`.

Futhermore, `app3` is not listed in any of the scopes an can do whatever it wants with the allowed topics:
| subscribe to: | A | B | C |
| --- | --- | --- | --- |
| app1 | | | |
| app2 | X | | |
| app3 | X | X | |

If the data published on one of the topics is sensitive, every new app has to be explicitly listed in `subscriptionScopes` to prevent it from subscribing to that topic. This makes it impossible to protect a topic.

So I suggest adding a new field to the metadata:
```yaml
  - name: protectedTopics
    value: "A"
```
when this is added to the configuration above, `app3` would not be allowed to subscribe to topic `A` any more, because it is not explicitly allowed in the `subscriptionScopes` (but `app2` is):
| subscribe to: | A | B | C |
| --- | --- | --- | --- |
| app1 | | | |
| app2 | X | | |
| app3 | | X | |

---

### Note
This would leave the publishing permissions untouched:
| publish to: | A | B | C |
| --- | --- | --- | --- |
| app1 | X | | |
| app2 | X | X | |
| app3 | X | X | |
