### ISSUE TITLE
Register a pluggable component in k8s failed

### ISSUE THREAD

**Issue by Bryce-huang** [dapr/dapr#5846]
## Ask your question here

After see the [How-To: Register a pluggable component](https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-registration/)

I make the  yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-queue
  labels:
    app: dapr-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-queue
  template:
    metadata:
      labels:
        app: dapr-queue
      annotations:
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets"
        dapr.io/app-id: "dapr-queue"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dapr.io/env: "TZ=Asia/Shanghai"
    spec:
      volumes:
        - name: dapr-unix-domain-socket
          emptyDir: {}
      containers:
        - name: component
          volumeMounts:
            - name: dapr-unix-domain-socket
              mountPath: /tmp/dapr-components-sockets
          image: docker.io/cnapp/queue:v5
          imagePullPolicy: Always
          env:
           - name: TZ
             value: Asia/Shanghai
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue
scopes:
  - publish
  - subscribe
spec:
  type: pubsub.queue
  version: v1
  metadata: [] 
```                                                                                                                                                                                                                                                               

The pod of deployment always  crashLoopBackOff,and I see the logs of daprd:
```
time="2023-01-29T21:24:25.721706602+08:00" level=info msg="app id: dapr-queue" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.721967282+08:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.727662255+08:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=0.000100)" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.727697982+08:00" level=info msg="Initialized name resolution to kubernetes" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.727718069+08:00" level=debug msg="loading pluggable components under path /tmp/dapr-components-sockets" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=pluggable-components-grpc-connector type=log ver=1.9.5
time="2023-01-29T21:24:25.727769997+08:00" level=debug msg="found -1 pluggable component services" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=pluggable-components-grpc-connector type=log ver=1.9.5
time="2023-01-29T21:24:25.727834027+08:00" level=debug msg="loading component. name: kubernetes, type: secretstores.kubernetes/v1" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.756111686+08:00" level=debug msg="found component. name: queue, type: pubsub.queue/v1" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.756152252+08:00" level=info msg="waiting for all outstanding components to be processed" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.756170447+08:00" level=info msg="all outstanding components processed" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.756181036+08:00" level=info msg="gRPC proxy enabled" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime type=log ver=1.9.5
time="2023-01-29T21:24:25.756265264+08:00" level=warning msg="Failed to listen on [::1]:50001 with error: listen tcp [::1]:50001: bind: cannot assign requested address" app_id=dapr-queue instance=dapr-queue-6b7d7b86b9-crzpp scope=dapr.runtime.grpc.api type=log ver=1.9.5
```
After kill the pod :

`time="2023-01-29T20:55:58.829934486+08:00" level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=dapr-queue instance=dapr-queue-77b6798cb5-rp2gt scope=dapr.runtime type=log ver=1.9.5`



In my Dapr cluster,i close the mTLS.

I am try to use the pluggable faeture with java.
My pluggable component sample from https://github.com/dapr-sandbox/components-java-sdk

Thanks for all the help!!


dapr version: 1.9.5 
k8s version: 1.20.0
