### ISSUE TITLE
Does Dapr support CSI secret store in EKS ? 

### ISSUE THREAD

**Issue by krab-skunk** [dapr/dapr#5884]
Hi Team, 

We are using CSI secret store drivers to wire our EKS to Secret manager, and while deploying Dapr, especially at the stage of creating a statestore such as 

``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key:$PASSWORD
```

This password is stored in aws secret manager but i don't quite know how to call it using the csi drivers here. 

For a pod, i would generally create an IRSA and simply mount the secret into the pod, but in that case for example, i'm quite unsure  how to do it ? Does anyone made it to work already ?

I saw that dapr seems to have his own way of connecting with aws secret manager https://docs.dapr.io/reference/components-reference/supported-secret-stores/aws-secret-manager/ but i would ideally stick to our current setup using this csi driver.

Thanks a lot
