### ISSUE TITLE
kafka pubsub always use app-max-concurrency = 1

### ISSUE THREAD

**Issue by VuiDJi** [dapr/dapr#5946]
/area runtime

## What version of Dapr?
1.9.5

Hi all!
Could you please tell me if kafka can be used for parallel event processing?
We did not set the dapr.io/app-max-concurrency: "1" annotation, however, faced the fact that the application does not start processing a new event while it does not complete the processing of the previous one.

## Expected Behavior
Application should start processing a new event even if it does not complete the processing of the previous one.

## Actual Behavior
Application does not start processing a new event while it does not complete the processing of the previous one.

## Steps to Reproduce the Problem
Our pubsub yaml file:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: donum-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers 
      value: "kafka:9092"
    - name: authType
      value: none
    - name: initialOffset
      value: "oldest"
```
