### ISSUE TITLE
Generic Perf tests for pub-sub components

### ISSUE THREAD

**Issue by ASHIQUEMD** [dapr/dapr#5989]
## In what area(s)?

> /area test-and-release

## Describe the proposal

We have been writing perf tests for different building blocks of Dapr using one of the componentsAPR. However, we would like to have performance tests for different components of building blocks. More often it seems only the component and their configuration are different while writing performance test of components in a building block, but and the rest of the code remains the same. So, it would be better to have a generic perf test written for a building block which could be extended to test other components of the same building block just by adding required configuration.

As part of this project, we will be focusing on Pub/Sub building block perf tests to make it generic for stable components like Kafka, RabbitMQ etc.

**GOALS AND OBJECTIVES**
Intent behind this idea is to reduce the additional work required by developer to write similar performance tests for a new component.

**REQUIREMENTS**
Currently, for any building block that DAPR has, developer writes new perf test cases with one component. But if we write perf tests for each component, then there will be duplicate codes for perf tests. For example, if we look at Kafka and RabbitMQ perf test, code remains same with only configuration values being changed.
So, we need to define a template for perf- test where configuration will be parametrized, and tests will run for all components with configuration defined in the config file.

**SOLUTION ARCHITECTURE**

_APPROACHES FOR SETTING THE CONFIGURATION_

> USING YAML CONFIG FILE

1.	There will be single image of test app, which will have multiple instance running with different pubsub configuration. 
2.	A single test of a building block will be invoked from make file. In the go test file, configuration of different component of building blocks will be read from a config yaml file and it will be iterated through to run the same test for all listed components in the config file.
a.	When a test is running, it will create the app by assigning the environment variables to each running app, which will be read by the app at runtime to talk to dapr component.

> BY SETTING ALL THE CONFIG FILES IN MAKE FILE

1.	For each component we can run a loop in makefile (dapr_tests.mk), and set the configuration variable for each test. With this approach, the existing test will have no changes and we will be reading all the config values from env variable and pass on to test apps for each component test.

**FINAL APPROACH**

We are inclining towards first approach to have to configuration of each component, where a config file will have specific configuration mentioned. 
Reason for selecting the first approach is that config file changes are cleaner and easy for developer to add the configuration in future for newly onboarded components in DAPR. It also looks cleaner, as configuration is maintained in a config file whose sole purpose is to have the component’s details. Makefile’s job seems to be of running the tests and not really worry about the configuration for each test.

**HIGH-LEVEL DESCRIPTION OF THE SOLUTION ARCHITECTURE**

_TEST APP_

We will have test application instances running with different components, for example, one instance of application with Kafka Pub/Sub component, one with RabbitMQ component and so on. There will be single application which will be parametrized to run with different Pub/Sub components.
Apps which will use the DAPR component to perform required operations. For example, an app will subscribe to Kafka component to receive message from publisher using DAPR. 
Perf test app folder name example: Pubsub_subscribe_http

_COMPONENT CONFIG_

There will be one config file for all the components for one building block, where new component config will be appended whenever they are introduced.
Component config will have specification of DAPR components like Kafka, RabbitMQ.
Component config file name example: pubsub_component.yaml

_TEST FILES AND TEST CONFIG FILE_

We will have one test file for one building block which will different tests added to it. These tests will run for each component individually. Now, to invoke these tests multiple time for different components we will test config file for each component to be tested.
One test config file will be introduced which will contain component related configs to be read in go test file.
Go Test file name example: pubsub_subscrtibe_test.go
K6 test file name example: test.js
Test Config file name example: pubsub_subscribe_test_config.yaml

_MAKEFILE_

This makefile will invoke the perf test of a building block as it generally does other tests.

### TECHNICAL DETAILS

**DETAILED TECHNICAL SPECIFICATIONS OF THE SOLUTION.**

_TEST APP_

Create an application which will use a DAPR building block like Pub/Sub, bindings etc. In this app, we will make component name configurable, which will be read from environment variable/ config file. It will have normal implementation of app like Order-Processor which will use the underlying DAPR component to complete its operation.

> EXAMPLE OF READING PUB/SUB NAME FOR DIFFERENT COMPONENTS WHILE RUNNING THE TESTS

```
var pubSubName string
  var topic string
  var route string
  
  func main() {
      errMsg := readPubsubEnvVar()
      if errMsg != nil {
          return
      }
  }

  func readPubsubEnvVar() error {
    pubSubName, ok := os.LookupEnv("PUB_SUB_COMPONENT_NAME")

    if !validateEnvVar("PUB_SUB_COMPONENT_NAME", pubSubName, ok) {
        return errors.New("Invalid PUB_SUB_COMPONENT_NAME")
    }

    return nil
  }


func validateEnvVar(key string, value string, ok bool) bool {
    if !ok {
        log.Printf("error: Env variable %s is not set", key)
        return false
    }

    if value == "" {
        log.Printf("error: Env variable %s is set to empty", key)
        return false
    }

    log.Printf("Env variable %s is set to %s", key, value)


    return true
}
```

> MAIN METHOD WITH HANDLER FOR DAPR ENDPOINTS

```
func main() {
    errMsg := readPubsubEnvVar()

    go notify(messagesCh, notifyCh)

    http.HandleFunc("/dapr/subscribe", subscribeHandler)
    http.HandleFunc("/"+route+"-bulk", bulkMessageHandler)
    http.HandleFunc("/"+route, messageHandler)
    http.HandleFunc("/test", testHandler)
    log.Fatal(http.ListenAndServe(":3000", nil))
}
```

_COMPONENT CONFIGURATION_

> PUB_SUB_COMPONENT.YAML

 – This file will contain component specific configuration which will be applied to Kubernetes for component creation in the cluster. We will keep all the components of a building block in a single file.
Example of RabbitMQ and Kafka component for Pub/Sub building block. 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-messagebus
spec:
  type: pubsub.kafka
  initTimeout: 1m
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: dapr-kafka:9092
  - name: authRequired
    value: "false"
  - name: initialOffset
    value: oldest

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-messagebus
spec:
  type: pubsub.rabbitmq
  initTimeout: 1m
  version: v1
  metadata:
  # rabbitmq broker connection setting
  - name: host
    value: "amqp://user:q7kwe3F0JPmllo2E@rabbitmq.dapr-tests.svc.cluster.local:5672"
```

> PUBSUB_PERF_TEST_CONFIG.YAML 

This file will be having component specific details, where any new component perf test related config should be added. This file will be read in go test file and same set of tests will run for all the components.

```
name: pubsub performance test
components:
  - name: kafka-messagebus
    topic: kafka-perf-test
    route: kafka-perf-test
    numHealthChecks: 60
    testAppName: kafka-test-app
    testLabel: pubsub_subscribe_kafka
    defaultSubscribeHttpThresholdMs: 500
    imageName: perf-pubsub_subscribe_app
  - name: rabbitmq-messagebus //add new component details
```

_WRITING TEST CASES_

There will be 2 test files, one test file will be in golang to invoke the K6 test.js file, which will generate the load and hit the applications. Another would be test.js file, which will be invoked by K6 engine with configured load such as number of virtual users and number of requests per second.

_SETTING UP GO TEST FILE_

Setting up Test App and their configuration in a generic way by reading the config yaml file.

```
func TestMain(m *testing.M) {
    utils.SetupLogs(testLabel)

    //Read the config file for individual components
    data, err := ioutil.ReadFile("testConfig.yaml")
    if err != nil {
        t.Log("error reading testConfig.yaml: %s", err)
        return
    }

    var config PubsubComponentConfig

    err = yaml.Unmarshal(data, &config)

    //set the configuration as environment variables for the test app.
    var testApps []kube.AppDescription

    for _, component = range config.Components {
        appDescription := kube.AppDescription{
            AppName:           component.TestAppName,
            DaprEnabled:       true,
            ImageName:         component.ImageName,
            Replicas:          1,
            IngressEnabled:    true,
            MetricsEnabled:    true,
            AppPort:           3000,
            AppProtocol:       "http",
            DaprCPULimit:      "4.0",
            DaprCPURequest:    "0.1",
            DaprMemoryLimit:   "512Mi",
            DaprMemoryRequest: "250Mi",
            AppCPULimit:       "4.0",
            AppCPURequest:     "0.1",
            AppMemoryLimit:    "800Mi",
            AppMemoryRequest:  "2500Mi",
            Labels: map[string]string{
                "daprtest": component.TestLabel,
            },
            AppEnv: map[string]string{
                "PUB_SUB_COMPONENT_NAME": component.PubsubName,
                "PUB_SUB_TOPIC_NAME":     component.Topic,
                "PUB_SUB_ROUTE_NAME":     Component.Route,
            },
        }

        testApps = append(testApps, appDescription)
    }

    tr = runner.NewTestRunner(testLabel, testApps, nil, nil)
    os.Exit(tr.Start(m))
}

func TestMe(t *testing.T) {
    for _, component := range configs.Components {
        t.Run(component.Name, func(t *testing.T) {
            // Get the ingress external url of test app
            testAppURL := tr.Platform.AcquireAppExternalURL(component.TestAppName)
            require.NotEmpty(t, testAppURL, "test app external URL must not be empty")

            // Check if test app endpoint is available
            t.Logf("test app url: %s", testAppURL+"/health")
            _, err := utils.HTTPGetNTimes(testAppURL+"/health", numHealthChecks)
            require.NoError(t, err)

            threshold := os.Getenv("DAPR_PERF_PUBSUB_SUBSCRIBE_HTTP_THRESHOLD")
            if threshold == "" {
                threshold = strconv.Itoa(defaultSubscribeHttpThresholdMs)
            }
            runTest(t, testAppURL, threshold, component.PubsubName)
        })
    }
}

```

_SETTING UP K6 ENV VARIABLES IN TEST_

```
func TestPubsubSubscribeHttp(t *testing.T) {
    //setup urls etc here

    //Load k6 with required env variable
    k6Test := loadtest.NewK6("./test.js",
        loadtest.WithParallelism(1),
        // loadtest.EnableLog(), // uncomment this to enable k6 logs, this however breaks reporting, only for debugging.
        loadtest.WithRunnerEnvVar("TARGET_URL", testAppURL),
        loadtest.WithRunnerEnvVar("PUB_SUB_COMPONENT_NAME", pubsubName),
        loadtest.WithRunnerEnvVar("PUBLISH_TYPE", publishType),
        loadtest.WithRunnerEnvVar("SUBSCRIBE_TYPE", subscribeType),
        loadtest.WithRunnerEnvVar("HTTP_REQ_DURATION_THRESHOLD", httpReqDurationThresholdMs))
    defer k6Test.Dispose()
}

```

_SETTING K6 TEST.JS FILE_

There will be no change to this file, as all the app related configuration are read at runtime.

_SETTING UP MAKEFILE_

SETTING UP PERF TEST APP
	A single image of the app will be created and it will be deployed individually for each component. For example, pub/sub test app will have single image and it will have multiple instances running with each pub/sub component.

**CHANGES REQUIRED BY CONTRIBUTORS FOR A NEW COMPONENT PERF TEST**

> Adding helm install command for the test

```
# install kafka to the cluster
setup-test-env-kafka:
	$(HELM) upgrade --install dapr-kafka bitnami/kafka -f ./tests/config/kafka_override.yaml --namespace $(DAPR_TEST_NAMESPACE) --timeout 10m0s
```

> Adding component config

New component should be appended to this file for pubsub perf test
 
```
#kafka pubsub component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-messagebus
spec:
  type: pubsub.kafka
  initTimeout: 1m
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: dapr-kafka:9092
  - name: authRequired
    value: "false"
  - name: initialOffset
    value: oldest
```

> Adding test config

For new components append the components list as shown below
 
```
name: pubsub performance test
components:
  - name: kafka-messagebus
    topic: kafka-perf-test
    route: kafka-perf-test
    numHealthChecks: 60
    testAppName: kafka-test-app
    testLabel: pubsub_subscribe_kafka
    subscribeHttpThresholdMs: 1500
    bulkSubscribeHttpThresholdMs: 500
    imageName: perf-pubsub_subscribe_app
    operations: [bulk, normal]
```
