### ISSUE TITLE
Bulk pubsub subscriber panics when tracing is disabled

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6099]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.10.x
> master

## Description

Using bulk pubsub to subscribe to a topic, Daprd panics if tracing is disabled.

The bug is in these lines (and in another similar spot in the same file):

https://github.com/dapr/dapr/blob/585da2feb90d5ddbc5a94efca5ba0702a9e43808/pkg/runtime/bulk_subscriber.go#L587-L588

When tracing is disabled, `diag.StartInternalCallbackSpan` returns `nil` for `span`, so the next line panics.

## Release Note

RELEASE NOTE: **FIX** Bulk pubsub subscriber panics when tracing is disabled

**Comment by mukundansundar** [comment]
I am not able to repro this when I set 
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "0"
```
samplingRate as `0`
