### ISSUE TITLE
argo workflow , dapr-sidecar-injector include "service account  system:serviceaccount:argo:argo not on the list of allowed controller accounts"

### ISSUE THREAD

**Issue by gongshen** [dapr/dapr#6126]
## /area runtime
/area runtime

## What version of Dapr?

v1.10.4

## Expected Behavior

Sidecar should be created.

## Actual Behavior

Sidecar not created, and dapr-sidecar-injector pod say  "service account 'system:serviceaccount:argo:argo' not on the list of allowed controller accounts"

## Ask your question here
i need help!!!!!
I encountered a problem with Kubernetes. I added an annotation to start Dapr in a pod launched by an Argo Workflow.
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    dapr.io/app-id: watermelon
    dapr.io/enabled: "true"
    dapr.io/log-level: error
```
the Argo Workflow runs in the `argo` namespace, serviceaccount is `argo`
the dapr-sidecar-injector runs in the dapr namespace, serviceaccount is `dapr-injector`

but the sidecar not created, and dapr-sidecar-injector pod say:
```
time="2023-03-23T12:52:57.123117756Z" level=error msg="Admission succeeded, but pod was not patched. No sidecar injected for 'watermelon'" instance=dapr-sidecar-injector-775f9c476c-sddgw scope=dapr.injector type=log ver=1.10.4
time="2023-03-23T12:53:07.164119156Z" level=error msg="service account 'system:serviceaccount:argo:argo' not on the list of allowed controller accounts" instance=dapr-sidecar-injector-775f9c476c-sddgw scope=dapr.injector type=log ver=1.10.4
```

I followed some troubleshooting steps,  create clusterrolebinding and rolebinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dapr-injector
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
```
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dapr-injector
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
```
