### ISSUE TITLE
exec: "C:\\Users\\myuser\\.dapr\\bin\\daprd.exe": file does not exist

### ISSUE THREAD

**Issue by eliassal** [dapr/dapr#6133]
I have setup Dapr on a remote linux machine and it is up and running. Created a .Net console, added the dapt package
dotnet add package Dapr.Client

I updated code according to MS learn and added a config file statestore.yml as follows

```
apiVersion: dapr.io/v1alpha1 
kind: Component 
metadata: 
  name: statestore 
spec:
  type: state.redis 
  version:  v1 
  metadata: 
  - name: redisHost 
    value: 192.168.100.36:6379 
  - name: redisPassword 
    value: ""   
  - name: actorStateStore 
    value: "true"
```

Whe I run the application using
`dapr run --app-id DaprCounter --components-path Dapr\Components dotnet run`

I get the following error

> Starting Dapr with id DaprCounter. HTTP Port: 35186. gRPC Port: 35187
> exec: "C:\\Users\\myuser\\.dapr\\bin\\daprd.exe": file does not exist

## Ask your question here

Is this a correct path to work or should I install Dapr/or anything else on the dev box on the dev box as well?
