### ISSUE TITLE
All sidecars failed since new binding installed

### ISSUE THREAD

**Issue by steve-heslouin** [dapr/dapr#6155]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.1.x

## Expected Behavior

I created an SQS Bindings as follow :

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqs-bindings
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: side-scanner-queue
  - name: region
    value: us-east-1
```

And now , all the dapr side car that are attached to a pod having a service account pointing to a Iam Role Service Account (IRSA)
are failing with this error:
```
time="2023-03-29T17:09:40.856142471Z" level=fatal msg="process component sqs-bindings error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sqs-bindings (bindings.aws.sqs/v1): AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.\n\tstatus code: 400, request id: a3f5d554-2763-53e2-ae64-89ca546cb6ab" app_id=scans-uploader instance=scans-uploader-d7f66bd4f-cn2c2 scope=dapr.runtime type=log ver=1.9.5
```

I really don't get what is the connection between those 2 events, but to make it work, i need to delete my binding, deploy my app, and reapply my binding
