### ISSUE TITLE
415 Unsupported Media Type when trying to get messages from Azure Servicebus Topic

### ISSUE THREAD

**Issue by TheElectricCo** [dapr/dapr#6184]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

hi,

I'm tyring to get Dapr to work with a pubsub component connecting an aspnet.core application with a topic in Azure servicebus. Unfortunately, I'm getting 415 errors from Dapr when trying to add items to the queue

Dapr V1.10.4 
Nuget package Dapr.AspNetCore 1.10.0

`2023-04-04T12:01:11.539Z  time="2023-04-04T12:01:11.538914318Z" level=error msg="App handler returned an error for message 66f95f4676864842a2c89033b2ab14c8 on topic d365-uat-events-egress: retriable error returned from app while processing pub/sub event 100, topic: , body: {\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.13\",\"title\":\"Unsupported Media Type\",\"status\":415,\"traceId\":\"00-73f7288121a6846e10184ee50c8c7436-89b7c69bf52ad9c3-00\"}. status code returned: 415" app_id=beacon component="sar-uat-d365-integration (pubsub.azure.servicebus/v1)" instance=beacon-9f957b5bf-w86xt scope=dapr.contrib type=log ver=1.10.4`

my aspnet core configuration : 
```
[Topic("sar-uat-d365-integration", "d365-uat-events-egress")]
[HttpPost("")]
public async Task<IActionResult> GetBusinessEvents([FromBody] dynamic notification)
{
   //Do stuff here
   return Ok();
}
```

my dapr yml component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sar-uat-d365-integration
  namespace: lighthouse
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  - name: connectionString # Required when not using Azure Authentication.
    value: "Endpoint=sb://sar-d365-integration.servicebus.windows.net/;SharedAccessKeyName=Dapper;SharedAccessKey={OMMITED};EntityPath=d365-uat-events-egress"
```

the message I'm trying to send is simple:
```
{
   "id" : "100"
}

```

When trying to post the same message via a simple HTTPost message this seems to work fine, but every message on the messagebus falls directly to the deadletter queue after 10 failed attempts

can anyone point me to what I'm doing wrong? Thanks!
Regards,
Lens
