### ISSUE TITLE
Dapr sidecar container can not injected in Pod

### ISSUE THREAD

**Issue by mgyboom** [dapr/dapr#6263]
## In what area(s)?

 /area operator

 /area sidecar injector

## What version of Dapr?

1.10.4

## Expected Behavior

When I create a Pod object in kubernetes, the sidecar injection should happen in the pod in question.

## Actual Behavior

Sidecar injection does not happen if the kind is Pod and hence we can not communicate with any of the services from within the created Pod.

## Release Note

environments:
```
docker: 19.03.8
kubernetes: 1.19.5
helm: 3.0.1
dapr: 1.10.4
```

deploy:
```
helm upgrade --install dapr dapr.tar.gz \
--version=1.10.4 \
--namespace dapr-system \
--create-namespace \
--set dapr_sidecar_injector.hostNetwork=true \
--set dapr_operator.watchInterval=30s \
--wait
```

configuration:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  annotations:
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.10.4
    app.kubesphere.io/instance: dapr
  name: daprsystem
  namespace: dapr-system
spec:
  metric:
    enabled: true
  metrics:
    enabled: true
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
```

component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  annotations:
    kubesphere.io/creator: admin
  name: pubsub-pulsar
  namespace: mgy-project
scopes:
  - orderprocessing
  - checkout
spec:
  metadata:
    - name: host
      value: 'pulsar-standalone.mgy-project:6650'
    - name: enableTLS
      value: 'false'
    - name: tenant
      value: public
    - name: namespace
      value: default
    - name: persistent
      value: 'true'
    - name: disableBatching
      value: 'true'
  type: pubsub.pulsar
  version: v1
```

subscription:
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order
  namespace: mgy-project
scopes:
  - orderprocessing
  - checkout
spec:
  bulkSubscribe:
    enabled: false
  pubsubname: pubsub-pulsar
  route: /checkout
  topic: orders
```

deployment:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-dapr-sub
  namespace: mgy-project
  labels:
    app: demo-dapr-sub
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dapr-sub
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-dapr-sub
      annotations:
        dapr.io/app-id: checkout
        dapr.io/app-port: '8066'
        dapr.io/enabled: 'true'
        kubesphere.io/restartedAt: '2023-04-18T07:35:51.977Z'
    spec:
      containers:
        - name: sub
          image: 'demo-dapr-sub:latest'
          ports:
            - name: http-8066
              containerPort: 8066
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: 10.58.14.24
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

deployment:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-dapr-pub
  namespace: mgy-project
  labels:
    app: demo-dapr-pub
  annotations:
    deployment.kubernetes.io/revision: '10'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dapr-pub
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-dapr-pub
      annotations:
        dapr.io/app-id: orderprocessing
        dapr.io/app-port: '8066'
        dapr.io/enable-debug: 'true'
        dapr.io/enabled: 'true'
        dapr.io/log-as-json: 'true'
        dapr.io/sidecar-liveness-probe-delay-seconds: '10'
        dapr.io/sidecar-readiness-probe-delay-seconds: '10'
        kubesphere.io/restartedAt: '2023-04-19T05:59:59.831Z'
    spec:
      containers:
        - name: pub
          image: demo-dapr-pub
          ports:
            - name: http-8066
              containerPort: 8066
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: 10.58.14.24
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

operator.log:
```
E0419 09:54:21.529945       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.Pod: unknown (get pods)

 time="2023-04-19T09:54:30.527700274Z" level=info msg="DaprWatchdog started checking pods" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:54:30.531354695Z" level=warning msg="Pod mgy-project/demo-dapr-sub-67b5cdf4c-s2mt7 does not have the Dapr sidecar and will be deleted" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:54:30.538506289Z" level=info msg="Deleted pod mgy-project/demo-dapr-sub-67b5cdf4c-s2mt7" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:54:30.538585133Z" level=warning msg="Pod mgy-project/demo-dapr-pub-cbf96d5b6-ddzgn does not have the Dapr sidecar and will be deleted" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:54:30.543214141Z" level=info msg="Deleted pod mgy-project/demo-dapr-pub-cbf96d5b6-ddzgn" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:54:33.538897627Z" level=info msg="DaprWatchdog completed checking pods" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 E0419 09:54:58.324484       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.Pod: unknown (get pods)

 time="2023-04-19T09:55:00.52712563Z" level=info msg="DaprWatchdog started checking pods" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:55:00.53107921Z" level=warning msg="Pod mgy-project/demo-dapr-sub-67b5cdf4c-pl8hk does not have the Dapr sidecar and will be deleted" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:55:00.537204666Z" level=info msg="Deleted pod mgy-project/demo-dapr-sub-67b5cdf4c-pl8hk" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:55:00.537369051Z" level=warning msg="Pod mgy-project/demo-dapr-pub-cbf96d5b6-4fhpv does not have the Dapr sidecar and will be deleted" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:55:00.542983296Z" level=info msg="Deleted pod mgy-project/demo-dapr-pub-cbf96d5b6-4fhpv" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4

 time="2023-04-19T09:55:03.537475665Z" level=info msg="DaprWatchdog completed checking pods" instance=dapr-operator-6dcdf99f5-c72cg scope=dapr.operator type=log ver=1.10.4
```

sidecar-injector.log
```
time="2023-04-19T06:08:36.086309798Z" level=info msg="log level set to: info" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.086880606Z" level=info msg="metrics server started on :9090/" instance=zhibang-test-d-010058014022.hz.td scope=dapr.metrics type=log ver=1.10.4

 time="2023-04-19T06:08:36.087122005Z" level=info msg="starting Dapr Sidecar Injector -- version 1.10.4 -- commit 42964736b1e99c9c03595c80c61fbe77912391c8" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.091412768Z" level=info msg="Healthz server is listening on :8080" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176829578Z" level=warning msg="Unable to get SA kube-system:replicaset-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176864406Z" level=warning msg="Unable to get SA kube-system:deployment-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176878483Z" level=warning msg="Unable to get SA kube-system:cronjob-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176891077Z" level=warning msg="Unable to get SA kube-system:job-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176903009Z" level=warning msg="Unable to get SA kube-system:statefulset-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176914684Z" level=warning msg="Unable to get SA kube-system:daemon-set-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.176933436Z" level=warning msg="Unable to get SA tekton-pipelines:tekton-pipelines-controller UID" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4

 time="2023-04-19T06:08:36.1770889Z" level=info msg="Sidecar injector is listening on :4000, patching Dapr-enabled pods" instance=zhibang-test-d-010058014022.hz.td scope=dapr.injector type=log ver=1.10.4
```

I can not find dapr sidecar injected in pod:
```
$ kubectl get deploy demo-dapr-sub -n mgy-project -o wide
NAME            READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                 SELECTOR
demo-dapr-sub   1/1     1            1           26h   sub          demo-dapr-sub:latest   app=demo-dapr-sub
```

I'm not sure if it's caused by "Unable to get SA".

RELEASE NOTE:
FIX Dapr sidecar NOT injected in Pod.
