### ISSUE TITLE
Ingress resource not reachable when installed with dapr 

### ISSUE THREAD

**Issue by prashanth-nagaraj1** [dapr/dapr#6267]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

## What version of Dapr?

> 1.10.5

## Expected Behavior

I have created a new aks cluster with kubernetes version 1.26.3. I have installed a dapr version 1.10.5 and then nginx ingress with dapr annotations. I'm not able to access the ingress resource. I tried with load balancer ip and also with host.

However, the same steps works well with a different cluster with kubernetes version 1.23.15

**Steps followed**

- Install dapr
```
helm upgrade --install dapr dapr/dapr --version=1.10.5 --namespace dapr-system --create-namespace --wait
```
- Install nginx ingress controller
```
helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx -f dapr-annotations.yaml --create-namespace --namespace nginx
```
```
# dapr-annotations.yaml
controller:
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nginx-ingress"
    dapr.io/sidecar-listen-addresses: "0.0.0.0"
    dapr.io/app-port: "80"
```
After this I tried to access http://{{LOAD_BALANCER_IP}}, but I cannot reach default nginx NOT FOUND page.

The url http://{{LOAD_BALANCER_IP}} should load nginx NOT FOUND page

## Actual Behavior

The url http://{{LOAD_BALANCER_IP}} is not accessible. 

## Steps to Reproduce the Problem

- Install dapr in the k8s cluster with version 1.26.3
- Install nginx controller 
```
helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx -f dapr-annotations.yaml --create-namespace --namespace nginx
```
- Access the ingress with load balancer ip
