### ISSUE TITLE
Support for multiple state stores on the same cluster

### ISSUE THREAD

**Issue by aminebizid** [dapr/dapr#636]
It will be great if we can deploy many instances of dapr and components on the same cluster.
```
annotations:
        dapr.io/dapr_id: "staging"
        dapr.io/enabled: "true"
        dapr.io/id: "bindings-pythonapp"
```
```
annotations:
        dapr.io/dapr_id: "production"
        dapr.io/enabled: "true"
        dapr.io/id: "bindings-pythonapp"
```
