### ISSUE TITLE
Azure Event Hub component debugging?

### ISSUE THREAD

**Issue by rsirny** [dapr/dapr#6396]
## In what area(s)?

/area runtime

## Ask your question here

We are using dapr 1.10.7 as a side car in our Kubernetes workload. One of the use cases we have is a service that consumes messages from Azure Event Hub using pubsub component and subscription. See sample config below. We faced an issue with messages not being processed by our service. The dapr side car would start with logs indicating that the pubsub component was loaded and subscription successfully created on the pubsub. There were several issues like no consumer group with name `my-app` or connection string that did not have listen permissions. Side car logs, even with debug log level, did not indicate any issue. Is there a good way of debugging these kind of issues?

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventhubs-pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
    - name: connectionString
      value: "Endpoint=sb://{EventHubNamespace}.servicebus.windows.net/;SharedAccessKeyName={PolicyName};SharedAccessKey={Key};EntityPath=myentitypath"
    - name: storageAccountName
      value: "myeventhubstorage"
    - name: storageAccountKey
      value: "***"
    - name: storageContainerName
      value: "myeventhubstoragecontainer"
scopes:
- my-app
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: my-sub
scopes:
- my-app
spec:
  pubsubname: eventhubs-pubsub
  routes:
    default: /myroute
  topic: myentitypath
```
