### ISSUE TITLE
Enable Secret Support in DAPR sidecar configuration

### ISSUE THREAD

**Issue by bb-avi** [dapr/dapr#6426]
## In what area(s)?

/area runtime

## Describe the feature
The documentation to trace to New Relic (https://docs.dapr.io/operations/monitoring/tracing/newrelic/) in Dapr configuration embeds a License Key (secret) in the URI.  There currently isn't a way to retrieve the URI or Key from a secret store.

And once we can use secrets in configuration files, it would also be helpful to be able to specify custom headers and/or query-string parameters.  In this case, New Relic supports both headers and query-string parameters.  So something like the following would be ideal, as it ensures we don't have to store the entire URI as a secret:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "https://trace-api.newrelic.com/trace/v1"
      queryParams:
      - name: Data-Format
        value: zipkin
      - name: Data-Format-Version
        value: 2
      headers:
      - name: api-key
        secretKeyRef: 
           name: NewRelicApiKey
           value: NewRelicApiKey
auth:
  secretStore: <SECRET_STORE_NAME>
```

RELEASE NOTE:  **ADD** ability to use secret stores in Dapr configuration and **ADD** ability to use secrets on query-string and header values.

## Alternative
If using a secret store is not possible, would using environment variables be possible?
