### ISSUE TITLE
Specify explicit direction for bindings

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#6449]
A spinoff from #6328, after discussions with @artursouza and @mukundansundar.

For bindings, I suggest we make directions explicit in the specification, ie. bring it to the component level (this will not require any change to components, existing or new).

### Example

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: queueName
    value: queue1
  - name: direction
    value:  input, output
```
This is fully backwards compatible. If a direction isn't specified, the same logic as today is executed, meaning that Dapr will try to discover the endpoint for input bindings and automatically assume it's an output binding if the type supports it.

I recommend that we don't deprecate the current mechanism.
