### ISSUE TITLE
Dapr Sidecar Pod CrashLoopBackOff Error

### ISSUE THREAD

**Issue by 3rk1n** [dapr/dapr#6483]
/area test-and-release

I want to close "Kubernetes Clusters Should Disable Automounting API Credentials" issue with "automountServiceAccountToken: false" value in Kubernetes deployment YAML, I follow these steps but DAPR sidecar has a CrashLoopBackOff error

I checked this reference links:
https://docs.dapr.io/operations/troubleshooting/common_issues/
https://docs.dapr.io/operations/components/component-secrets/
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Create a service accont**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <service-account-name>
automountServiceAccountToken: false
```

**Create a secret for service account**

```
apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
  annotations:
    kubernetes.io/service-account.name: <service-account-name>
type: kubernetes.io/service-account-token
```

**Give a role and role base permission for service account**

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <role-name>
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <role-binding-name>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <role-name>
subjects:
- kind: ServiceAccount
  name: <service-account-name>
  namespace: <namespace-name>
```

**Deloyment  YAML File**

```
apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  replicas: 
  strategy:
  selector:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: <deployment-name>
        dapr.io/app-port: "<port-number>"
        dapr.io/config: "dapr-config"
      labels:
    spec:
      automountServiceAccountToken: false
      serviceAccountName: <service-account-name>
```

**DAPR Config YAML**

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: <namespace-name>
spec:
  global:
    automountServiceAccountToken: false
```

**DAPR Sidecard Error**

```
level=info msg="starting Dapr Runtime -- version 1.9.5 -- commit =******" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="log level set to: info" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="metrics server started on :9090/" app_id=****** instance=****** scope=dapr.metrics type=log ver=1.9.5
level=info msg="Initializing the operator client (config: dapr-config)" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="kubernetes mode configured" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="app id: ******" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Initialized name resolution to kubernetes" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="loading components" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=warning msg="error processing component, daprd process will exit gracefully" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="dapr shutting down." app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Stopping PubSub subscribers and input bindings" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Stopping Dapr APIs" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Waiting 5s to finish outstanding operations" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=info msg="Shutting down all remaining components" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
level=fatal msg="process component kubernetes error: [INIT_COMPONENT_FAILURE]: initialization error occurred for kubernetes (secretstores.kubernetes/v1): stat /.kube/config: no such file or directory" app_id=****** instance=****** scope=dapr.runtime type=log ver=1.9.5
```
