### ISSUE TITLE
Encountered a transient exception during the rolling update process

### ISSUE THREAD

**Issue by Hsuwen** [dapr/dapr#6631]
My environment:
Server: AWS EKS version 1.27
Dapr CLI: 1.11
Dapr Runtime: 1.11
Dapr SDK: dot-net 1.11
Dapr Components: redis(statestore), rabbitmq(pubsub)
Other: zipkin, middleware.http.ratelimit, middleware.http.routeralias

All of this runs smoothly. However, when scrolling updates (such as kubectl replace/set image/rollback restart), exceptions from dapr sdk are encountered. The process of reporting errors is brief until the rolling update is completed. 
For example:
```
{
	"Type": "Dapr.Client.InvocationException",
	"Message": "An exception occurred while invoking method: \u0027path1/path2\u0027 on app-id: \u0027my-app-abc\u0027",
	"TargetSite": "Dapr.Client.dll.MoveNext",
	"Source": "Dapr.Client",
	"Inner": {
		"Type": "System.Net.Http.HttpRequestException",
		"Message": "Response status code does not indicate success: 500 (Internal Server Error).",
		"TargetSite": "System.Net.Http.dll.EnsureSuccessStatusCode",
		"Source": "System.Net.Http",
		"StackTrace": []
	},
	"StackTrace": [{
		"Method": "MoveNext",
		"File": "MyClass.cs",
		"Line": 328,
		"Column": 5
	}]
}
```

I suspect this may be due to the temporary unavailability of the service during the update process; Alternatively, service registration and discovery did not remove service instances on pods that were in the process of being "terminating" as early as possible.
Pod deployment yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-abc
  namespace: my-ns
  labels:
    app: my-app-abc
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: my-app-abc
  minReadySeconds: 5
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: my-app-abc
        version: "v1.0.1"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "my-app-abc"
        dapr.io/app-port: "80"
        dapr.io/app-protocol: "http"
        dapr.io/api-token-secret: ""
        dapr.io/log-level: "warn"
        dapr.io/log-as-json: "true"
        dapr.io/config: "common"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-delay-seconds: "10"
        dapr.io/sidecar-cpu-limit: "300m"
        dapr.io/sidecar-memory-limit: "512M"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "128M"
    spec:
      containers:
        - name: my-app-abc
          image: my-app-abc:v1.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 300m
              memory: 512M
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
              httpHeaders:
              - name: Health-Check
                value: Internal
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: my-key
```

I found that "[app health check](https://github.com/dapr/dapr/pull/4990)" has been added in version 1.11, and I am not sure if these annotations must be specified. I did not find any relevant cases in the examples in the [samples](https://github.com/dapr/samples) repository.

May I ask how to elegantly set up DAPR in a production environment to support rolling updates and avoid interrupting traffic during the update process.

Thanks.
