### ISSUE TITLE
Couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" 

### ISSUE THREAD

**Issue by Itchimonji** [dapr/dapr#6634]
## In what area(s)?

> /area operator
> /area sidecar
> /area sentry

## What version of Dapr?

> Docker image version: 1.11.1
> Helm Chart Version: 1.11.1

## Expected Behavior

Working dapr pod sidecar without restarting dapr sentry and dapr sidecar.

## Actual Behavior

After changing a Configuration, the main pod and its dapr sidecar are broken.

Here are the error logs from the dapr-sidecar:

```
time="2023-07-09T19:06:01.595999728Z" level=fatal msg="couldn't find trust anchors in environment variable DAPR_TRUST_ANCHORS" app_id=app-123 instance=app-123 scope=dapr.runtime type=log ver=1.11.1
```

I deployed dapr with Helm and here are my configuration of the sidecar:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: test-tracing
  namespace: test
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
```

The following env variables of the sidecar have no values. I think there is something wrong in my configuration:
```
env:
  - name: DAPR_TRUST_ANCHORS
  - name: DAPR_CERT_CHAIN 
  - name: DAPR_CERT_KEY
  - name: SENTRY_LOCAL_IDENTITY
    value: test:app-123
```

## Steps to Reproduce the Problem

1. Deploy Dapr via Helm
2. Create a configuration file for a specific namespace (see above)
3. Add the following pod annotations to a pod that needs to be observed:

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/api/metrics"
  dapr.io/enabled: "true"
  dapr.io/app-id: "app-123"
  dapr.io/app-port: "8080"
  dapr.io/enable-metrics: "true"
  dapr.io/metrics-port: "9090"
  dapr.io/config: "test-tracing"
```

4. Redeploy the pod
5. Change the Configuration file like that:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: test-tracing
  namespace: test
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://jaeger-collector.jaeger.svc.cluster.local:14250"
      isSecure: false
      protocol: grpc
```
6. Redeploy the pod

## Workaround
After redeploy of dapr sentry and dapr sidecar the pod gets a valid `DAPR_TRUST_ANCHORS` with value and is starting normally.

Am I doing something wrong or does anyone else have a similar problem?

Thanks for help 💪
