### ISSUE TITLE
Apply two resiliency files against the same component will mess up the policy 

### ISSUE THREAD

**Issue by iamzhaoxu** [dapr/dapr#6708]
## In what area(s)?
Resiliency 
/area runtime

## What version of Dapr?
1.1.2

## Expected Behavior

When applying these 2 Resiliency yaml files one after another to k8s, I should expect the policy will be either applied to both or the last one override the previous one.
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: slotting-pubsub-retry-policy
  namespace: apps
spec:
  policies:
    # Retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 3
  targets:
    components:
      slotting.pubsub:
        outbound:
          retry: pubsubRetry
        inbound: # inbound only applies to delivery from sidecar to app
          retry: pubsubRetry
```
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: slotting-pubsub-timeout-policy
  namespace: apps
spec:
  policies:
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s
  targets:
    components:
      slotting.pubsub:
        outbound:
          retry: general
        inbound: # inbound only applies to delivery from sidecar to app
          retry: general
```

## Actual Behavior

The policy looks like being messed up in Daprd logs. The policy `general` should be the timeout policy name but somehow it has been applied to Retry.
![image](https://github.com/dapr/dapr/assets/1594894/f068ea2d-891b-4939-ae15-2e0c5ce4ac0c)

## Steps to Reproduce the Problem
I tried to use this bash script to apply the yamls against the local minikube cluster
```
#!/bin/bash

# Get the current directory
current_dir=$(pwd)/..
# Loop through all the YAML files in the current directory
for file in $current_dir/*.yaml; do

  # Apply the YAML file to Kubernetes
  kubectl delete -f $file

done

# Loop through all the YAML files in the current directory
for file in $current_dir/*.yaml; do

  # Apply the YAML file to Kubernetes
  kubectl apply -f $file

done
```
