### ISSUE TITLE
How to configure the HttpEndpoint via the http pipeline directly

### ISSUE THREAD

**Issue by danvic712** [dapr/dapr#6794]
## In what area(s)?

/area runtime

## Ask your question here

In our scenario, we want to use the shared dapr runtime to comunication, and deploy a single instance of a service via docker compose, and then go ahead and build it into the full system

So we need to use the same configuration and components for all services, and we create a folder to store the configuration and component files that we use

I know we can specify the value of HttpEndpoint in the code by using the SDK, just wondering if exist a way can let us specify it in the dapr configuration file directly, like the following

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  httpPipeline:
    handlers:
      - name: dapr-instance
        type: "http"
        version: "v1"
        settings:
          baseURL: "http://<remote-dapr-instance>:<port>"
```
