### ISSUE TITLE
Support multiple actor state stores for a single actor type/service

### ISSUE THREAD

**Issue by KrylixZA** [dapr/dapr#6866]
## Describe the feature
It would be nice to be able to use multiple actor state stores for a single actor type/service. 

We have a service that uses Cosmos DB as the underlying actor state store. We are also processing very large volumes of data (at peak times, more than 5000 events per second). This has resulted in us setting our Cosmos container to autoscale at 400,000 RU/s peak. From the times I've observed the system, we often peak well above 350K RU/s. To that end, this is only for one of our customers. And not even our biggest customer. We have 10s of customers with this kind of scale. While Cosmos (by default) only allows us up to 1,000,000 RU/s as a maximum. We'll breach through that on our 3rd customer...

When the following decision record was recorded, it was made clear that multiple state stores is supported, but not actor state stores: https://github.com/dapr/dapr/blob/master/docs/decision_records/api/API-008-multi-state-store-api-design.md
<img width="1016" alt="image" src="https://github.com/dapr/components-contrib/assets/16819506/e6a9ae69-3762-41e9-bfd6-7fc508d482f5">

To work around this problem, we'd need quite a complex arrangement of Pub/Sub components, namespaces and Cosmos containers. In a perfect world, I'd love to simply define multiple actor state YAML configurations with names unique to each customer, and these components would each point to a single Cosmos container set with enough RU/s. For example:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customer-actor-state-1 # where 1 is an internal unique identifier for the customer
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://some-cosmos-db-in-azure.com/
  - name: database
    value: actor-state-db
  - name: collection
    value: customer-container-1
```
And
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customer-actor-state-2 # where 2 is an internal unique identifier for the customer
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://some-cosmos-db-in-azure.com/
  - name: database
    value: actor-state-db
  - name: collection
    value: customer-container-2
```

## Release Note

RELEASE NOTE:
