### ISSUE TITLE
redisDB not working

### ISSUE THREAD

**Issue by topfunet** [dapr/dapr#6875]
According to this page https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/，there's a redisDB means "Database selected after connecting to redis.".But it's not working.
this is my statestore.yaml:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "1"
```
But when i call SaveStateAsync, data always write to db0.
## What version of Dapr?

> 1.11.0

## Expected Behavior

Data write to db1.

## Actual Behavior

Data always write to db0 no matter what value i set to redisDB.
