### ISSUE TITLE
[Proposal] Distributed outbound rate-limiting backed by state store

### ISSUE THREAD

**Issue by sujitdmello** [dapr/dapr#6935]
### Dapr Maintainer Comment / Description

We should explore the creation of a distributed outbound rate limiter that can be backed by any state store. While the original request received was specific to the HTTP Binding - this could likely be done as HTTP middleware such that it can be used in other scenarios such as external service invocation as well.

### Original Description 
In a recent DAPR project, we implemented a distributed rate-limiting feature using DAPR state to throttle calls made by the HTTP binding to internal services, so as to honor service limits and budgets. This proved really key in the message processing scenario as it prevented these existing services from  being overwhelmed by numerous API calls. The project was implemented in Java using the token-bucket library Bucket4j.

It seemed like this may be a useful addition to the HTTP Binding itself, so we did some spikes and created a sample approach and design proposal for integrating a distributed token bucket into DAPR using DAPR State. An existing rate limiting library in Golang was forked and a sample created. You can find it [here](https://github.com/sujitdmello/go-limiter/tree/main/daprsample) along with a potential proposal for the HTTP binding (summarized below).

- maxCallsPerPeriod - the maximum number of calls allowed per period
- period - the period of time in which the maximum number of calls is allowed
- rateLimitStore - the name of the DAPR state store to use for the rate-limiting

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-person-service
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://localhost:8089/participant
    - name: maxCallsPerPeriod
      value: "10"
    - name: period
      value: "1s"
    - name: rateLimitStore
      value: "redis-rate-limit"
```

**Comment by berndverst** [comment]
cc @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
This should be implemented with an internal actor. We're already considering using internal actors for other things such as middlewares (rate-limiting and OAuth2).

**Comment by sujitdmello** [comment]
> This should be implemented with an internal actor. We're already considering using internal actors for other things such as middlewares (rate-limiting and OAuth2).

FWIW, in our original Java implementation, we used the DAPR Actor framework to process messages and the Actor method was grabbing a token from the distributed bucket before making the HTTP binding call. That approached worked really well.

**Comment by ItalyPaleAle** [comment]
Nice! Thanks for sharing @sujitdmello 

Yes, that's the idea. As long as you can tolerate that the current rate-limiter state can be lost at any time (generally that is fine), you don't even need to persist the actor state's in the actor state store, and keeping the state in-memory is enough.

**Comment by sujitdmello** [comment]
@stuartleeks and myself are planning to pick up this effort and do some analysis/design around it. Will share when available.

**Comment by stuartleeks** [comment]
@ItalyPaleAle  I just wanted to check in with some assumptions/questions....

Firstly, from this thread it seems that the intention is to implement this using internal actors.

Secondly, should this just apply to the HTTP binding and service invocation, or more bindings more generally?
I'm trying to work out whether the expectation is that this would add `maxCallsPerPeriod` and `period` properties to bindings: 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-person-service
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://localhost:8089/participant
    - name: maxCallsPerPeriod
      value: "10"
    - name: period
      value: "1s"
```

... or be a new component type that can be applied to bindings via config:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ratelimit
spec:
  type: middleware.binding.ratelimit
  version: v1
  metadata:
    - name: maxCallsPerPeriod
      value: 10
    - name: period
      value: "1s"
```
