### ISSUE TITLE
unexpected resiliency policy behavior with v1.12

### ISSUE THREAD

**Issue by sicoyle** [dapr/dapr#6997]
## In what area(s)?
> /area runtime

## What version of Dapr?

1.12 rc 5

## Expected Behavior

When I set a resiliency policy for my caller appid with the yaml manifest (omitting metadata for brevity):
```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
scopes:
- ignore-me
spec:
  policies:
    circuitBreakers:
      DefaultAppCircuitBreakerPolicy:
        interval: 0s
        maxRequests: 1
        timeout: 60s
        trip: consecutiveFailures > 5
    retries:
      DefaultAppRetryPolicy:
        duration: 5s
        maxInterval: 60s
        maxRetries: -1
        policy: constant
    timeouts:
      DefaultAppTimeoutPolicy: 10s
  targets: {}
```
I expect no issue performing service invocation.

## Actual Behavior

Then my caller sidecar gives me logs (some things omitted with ...):
```
"app_id":"sam-invokerrr","error_message":"{\"errorCode\":\"ERR_DIRECT_INVOKE\",\"message\":\"failed to invoke, id: ignore-me, err: context canceled\"}","execution_time":"180.883958ms","instance":"...","level":"info" ... "method":"GET /v1.0/invoke/ignore-me/method/todos","msg":"Inbound App ID call received (http)",...,"protocol":"http","scope":....,"start_time":"2023-10-05T16:12:55.509103626Z","status":"500","time":"2023-10-05T16:12:55.690156084Z","type":"request",...}
```

However, if I update my resiliency yaml from:
```
  targets: {}

```
to 👇 
```
  targets:
    apps: {}
```

THEN it works 🎉 .

Looking at the resiliency structs, there is an omitempty json tag on apps:
```
	Apps       map[string]EndpointPolicyNames  `json:"apps,omitempty" yaml:"apps,omitempty"`
```

That I do not think we should have. Otherwise, there is other weirdness going on in the underlying resiliency logic causing my sidecar to _immediately_ give me the context cancel error.

### Other weirdness

Furthermore, if I update my invocation URL from `https://jsonplaceholder.typicode.com/todos` to `https://jsonplaceholder.typicode.com/todos/1`, THEN it also works. But, it does not work for `https://jsonplaceholder.typicode.com/todos`, showing the context cancel error. I use this URL as it easily allows me to do basic crud operations without me doing any underlying logic just to test the resiliency :) Again, the context cancel is given almost immediately irrespective of my specified timeout.

## Steps to Reproduce the Problem

1. Create 2 appids using invoker resiliency policy listed above.
2. Perform service invocation. NOTE: you will see an okay status code; however, if you check the caller sidecar logs, then you see a status 500 with the context cancel error.
