### ISSUE TITLE
Proposal: Alternate backends for Dapr Workflow

### ISSUE THREAD

**Issue by cgillum** [dapr/dapr#7127]
## In what area(s)?

> /area runtime

## Describe the proposal

This is a proposal for allowing users to configure alternate backend implementations for Dapr Workflow, beyond the default Actors backend.

## Background

Dapr Workflow relies on the Durable Task Framework for Go (a.k.a. [durabletask-go](https://github.com/microsoft/durabletask-go)) as the core engine for executing workflows. This engine is designed to support multiple backend implementations. For example, the durabletask-go repo includes a SQLite implementation and the Dapr repo includes an Actors implementation. For Dapr Workflow users today, the Actors implementation is the only option.

The backend implementation is largely decoupled from the core engine or the programming model that developers see. Rather, the backend primarily impacts how workflow state is stored and how workflows execution is coordinated across replicas. In that sense, it is similar to Dapr's state store abstraction, except designed specifically for workflow. All APIs and programming model features are the same regardless of which backend is used.

## Proposal

This proposal is about opening up the possibility of using alternate `durabletask-go` *backend* implementations for Dapr Workflow. For example, the [existing (POC) SQLite implementation](https://github.com/microsoft/durabletask-go/tree/main/backend/sqlite) could be used for local development and testing, or a custom, vendor-specific implementation could be used for specialized scenarios. Dapr Workflow would continue to use the Actors implementation by default, and there is currently no desire to change this.

To be clear, this proposal does *not* propose making the Dapr Workflow backend into a full-fledged building block. Rather, it would be limited to backends that are either compiled into the `durabletask-go` project or into the Dapr runtime, like how the Actors backend is today. This is a scoping decision designed to keep the proposal simple and focused, but could be revisited if there's sufficient interest in community-contributed workflow backends.

Also, this is *not* a proposal to make the APIs for Dapr Workflow pluggable like we did in the start of the project - e.g., with a Temporal API implementation. The workflow management APIs would continue to target only the built-in Dapr Workflow implementation (and would not need to be updated to support alternate backends).

Lastly, this proposal doesn't recommend any specific alternate implementations. SQLite is mentioned as a practical example that could be made available for all Dapr users since a (POC) implementation already exists. But there are other possibilities, such as a Postgres implementation, or even a gRPC-based implementation that could target a highly customized remote workflow backend implementation.

### Configuration options

There are currently two options we're considering for configuring the backend implementation. We're seeking community feedback to see whether one option is preferred over the other, or if there are other options we should consider.

1. Use a **Dapr Workflow configuration setting specify** the backend implementation and configuration settings. This option would build upon the proposed work to introduce workflow configuration settings in https://github.com/dapr/dapr/issues/7089. For example, add `backendType` and `backendConfiguration` properties for selecting the alternative backend type and configuring it with backend-specific settings, as show in the following example for SQLite:

    ```yaml
    apiVersion: dapr.io/v1alpha1
    kind: Configuration
    metadata:
      name: daprConfig
    spec:
      workflow:
        # ...
        backendType: "sqlite"
        backendConfiguration:
          connectionString: "file::memory:" # use in-memory SQLite
    ```

    These would be optional settings, with the default being to use the Actors backend as it exists today.

2. Use **component config YAML files** to specify the backend implementation and configuration settings. For example, a user could place a `sqlite.yaml` file in the `components` directory with the following contents:

    ```yaml
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: sqlite
    spec:
      type: workflow.dapr.sqlite
      metadata:
      - name: connectionString
        value: "file::memory:" # use in-memory SQLite
    ```

    This option would be similar to how Dapr building blocks work today. The `type` property would be used to select the backend implementation, and the `metadata` property would be used to configure it. This option would also be optional, with the default being to use the Actors backend as it exists today.

    One potential point of confusion with this option is that users might mistakenly think that this can be used to swap out the workflow engine implementation itself. For example, a user might try to use this option to swap out `durabletask-go` with a different workflow engine. This is not the case. The workflow engine itself is not configurable in this proposal, only the backend implementation.
