### ISSUE TITLE
fail to run make setup-test-components due to crd version conversion not work

### ISSUE THREAD

**Issue by lucus-sun** [dapr/dapr#7180]
## In what area(s)?

 /area docs

 /area test-and-release

## Ask your question here

When setup the e2e environment following [this doc](https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md) by executing the command:

```
make setup-test-components
```

It reports error:

```
kubectl apply -f ./tests/config/app_topic_subscription_pluggable_pubsub.yaml --namespace dapr-tests
Error from server: error when creating "./tests/config/app_topic_subscription_pluggable_pubsub.yaml": conversion webhook for dapr.io/v1alpha1, Kind=Subscription failed: Post "https://dapr-webhook.replaceme.svc:443/convert?timeout=30s": service "dapr-webhook" not found
```

It seems we're using the v1alpha1 subscription in `./tests/config/app_topic_subscription_pluggable_pubsub.yaml`:

```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: pluggable-c-topic-subscription
spec:
  pubsubname: pluggable-messagebus
  topic: pubsub-c-topic-http
  route: /pubsub-c-topic-http
scopes:
  - pubsub-subscriber-pluggable
```

It needs version conversion but we don't have the dapr service installed yet in the e2e environment preparation.
