### ISSUE TITLE
Rabbit pubsub giving 404's since dapr 1.12 upgrade

### ISSUE THREAD

**Issue by kayvonkhosrowpour** [dapr/dapr#7224]
## In what area(s)?
- On latest Dapr runtime in Kubernetes: `Dapr v1.12`
- On latest Dapr Go SDK `v1.9.0`
- We use **pubsub component specs**, specifically for RabbitMQ
- We have a number of annotations set on the pod to control the dapr sidecar

Snippets of our config & relevant logs are included at the end of the thread for clarity.

## Description of Issue
Since upgrade to the latest Go SDK/Dapr runtime, we see the below errors from the dapr sidecar:
```
> rabbitmq pub/sub error: handling message from topic '<TOPIC NAME>', RETRY status returned from app while processing pub/sub event <UUID>: retriable error occurred
> rabbitmq pub/sub error: handling message from topic '<TOPIC NAME>', RETRY status returned from app while processing pub/sub event <UUID>: retriable error occurred
> rabbitmq pub/sub error: handling message from topic '<TOPIC NAME>', RETRY status returned from app while processing pub/sub event <UUID>: retriable error occurred
> Failed to listen for gRPC server on TCP address :50002 with error: listen tcp :50002: bind: address already in use
> non-retriable error returned from app while processing pub/sub event <UUID>: 404 page not found
. status code returned: 404
```

We never received this error prior to Dapr v1.12 (previously we were on `v1.8`). However, now we receive these errors consistently when our pods roll out initially. It seems that deleting the pods and redeploying seems to fix the errors, but it's unclear to me how to resolve these issues.

## Ask your question here
My questions:
1. What is the cause of these 404 errors?
2. How can we configure the dapr sidecar/application to retry the connection if there is a 404?

## Snippets of our setup
Annotations on our pod that received this error:
```yaml
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "handler"
    dapr.io/app-port: "8081"
    dapr.io/log-as-json: "true"
    dapr.io/sidecar-liveness-probe-delay-seconds: "30" # wait 30 seconds between probing
    dapr.io/sidecar-liveness-probe-timeout-seconds: "10" # timeout after 10s to the service
    dapr.io/sidecar-liveness-probe-period-seconds: "6" # retry every 6 seconds
    dapr.io/sidecar-liveness-probe-threshold: "5" # retry 5 times before failing
    dapr.io/sidecar-readiness-probe-delay-seconds: "30" # wait 30 seconds between probing
    dapr.io/sidecar-readiness-probe-timeout-seconds: "10" # timeout after 10s to the service
    dapr.io/sidecar-readiness-probe-period-seconds: "6" # retry every 6 seconds
    dapr.io/sidecar-readiness-probe-threshold: "5" # retry 5 times before failing
    dapr.io/config: "evs-enable-resiliency"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.pubsub.name }}
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqp://{{ <<fetch connection string>> }}
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2
  - name: prefetchCount
    value: 1
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: false
  - name: enableDeadLetter
    value: true
  - name: exchangeKind
    value: topic
```
