### ISSUE TITLE
[Proposal] Start Dapr Workflow instance via PubSub subscription

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#7226]
## In what area(s)?

/area runtime

## Describe the feature

**Start Dapr Workflow instance via PubSub subscription**

If an app has registered a Workflow, It should be possible to auto-start a workflow instance of a particular Workflow Type via receiving a message from a Dapr PubSub Topic.

### Benefits

- This would reduce the boiler plate code to zero to schedule a workflow from a pubsub message, and would be a great showcase for how composable Dapr components can be with zero code.
- Allows other Apps on the network to start Workflows, which is currently not easy to achieve.
   - Could also extend the operation beyond `start` to `terminate` `raise-event` `pause` `resume` but that is beyond the scope of this proposal. Let's assume the default operation is `start` for this proposal.
- The app wouldn't even need to run an App channel / webserver, which is great for a minimal example.

### Design

We could extend the existing `Subscription` CRD or create a new CRD specifically for workflows, `Subscription-workflow` for example. I'm less opinionated about this, so for simplicity sake, I'll just present an example of what it could like to extend the existing `Subscription` CRD

I propose adding a new attribute to the `routes` section called `defaultworkflow`

The `defaultworkflow` attribute would be **mutually exclusive** with the existing `default` route option for existing HTTP subscribers. Specifying both would cause an error on dapr init.

```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-pub-sub
spec:
  topic: orders
  routes: 
    defaultworkflow: MyWorkflowType
  pubsubname: order-pub-sub
scopes:
- checkout
```

---

The default behaviour would use the `cloudevent.id` as the Workflow Instance Id.

This could be overridden, with a few different kind of dynamic strategies
- `{cloudevent.id}` this would be the default
- `{cloudevent.my-custom-field-name}`
- `{cloudevent.type}-{cloudevent.id}`
- `some-constant-prefix-{cloudevent.id}`
- `{uuid}`

```yaml
spec:
  topic: orders
  routes: 
    defaultworkflow: MyWorkflowType
    workflowid: some-constant-{cloudevent.id}
  pubsubname: order-pub-sub
```
---

Due to at least once delivery guarantee of Dapr PubSub (and other scenarios where a user provides the instance id specifically via custom cloud event field), there needs to be a hint provided to the workflow runtime on how to handle the starting of the workflow instance (just incase it is already running from a previous delivery attempt).

Fortunately, there are [Workflow Id reuse strategies](https://github.com/dapr/dapr/issues/7101) already planned for Dapr Workflows, and I hypothesise that these can be re-used for the above purpose.

The current planned reuse policies are 
* `TerminateIfExists` 
    * Terminates any existing workflows with the same instance ID and then schedules a new instance as one atomic action, similar to on-demand 
    * **This is a destructive operation, but should be allowed.**
    * **Should return the equivalent of a  `SUCCESS` status code to dapr.**
* `SkipIfExists`
   * If there is an existing workflow already scheduled, then the scheduler does nothing. 
   * **IMO this should be the default as it is the least destructive option**
   * **Should return the equivalent of a `SUCCESS` status code to dapr.**
* `ThrowIfExists` 
   * If there is an existing workflow then the scheduler throws an exception (this is the current behaviour).
   * **I don't see that there is any value in exposing this option, but we can include it for completeness (or prevent it)**
   * **Should return the equivalent of a `SUCCESS` status code to dapr.**

```yaml
spec:
  topic: orders
  routes: 
    defaultworkflow: MyWorkflowType
    workflowid: some-constant-{cloudevent.id}
    workflowidreusepolicy: SkipIfExists
  pubsubname: order-pub-sub
```
---

The payload of the message should be used as the `input` to the dapr workflow instance.
 
It may be necessary to hint to dapr if it should attempt to deliver the message payload as-is, or just the `cloudevent.data` field

* `{cloudevent.data}` 
   * **IMO this should be the default**
* `as-is`
   

```yaml
spec:
  topic: orders
  routes: 
    defaultworkflow: MyWorkflowType
    workflowid: some-constant-{cloudevent.id}
    workflowidreusepolicy: SkipIfExists
    payload: as-is
  pubsubname: order-pub-sub
```

---

## Release Note

RELEASE NOTE:
