### ISSUE TITLE
App exit results in Rabbit pubsub "context canceled", and resiliency spec is not respected

### ISSUE THREAD

**Issue by kayvonkhosrowpour** [dapr/dapr#7258]
## In what area(s)?
- On latest Dapr runtime in Kubernetes: `Dapr v1.12`
- On latest Dapr Go SDK `v1.9.0`
- We use **pubsub component specs**, specifically for RabbitMQ
- We have a resiliency spec defined to retry 3 times, exponentially
- We have a number of annotations set on the pod to control the dapr sidecar

Snippets of our config & relevant logs are included at the end of the thread for clarity.

## Expected Behavior
When our application shuts down to perform a deployment, the application has a rabbit event in-process that is successfully sent to the application. The application is processing the event, performing a long-running operation.

When the application is shutting down, the request context from Dapr to the application is canceled. We expect that if the event is in-process and fails to complete (i.e., does not give a 200 to Dapr), that Dapr would treat it as a regular failure and the event would be retried when the application comes back up. 

## Actual Behavior
However, the actual behavior is that Dapr logs the "context canceled" error and the event is sent immediately to the dead letter queue.

## Steps to Reproduce the Problem
It is possible to reproduce if you have a long-running operation that holds the context in the pubsub handler on the application, and you delete the pod as the operation is completing. For example:
1. Handle event from application
2. Event handler in application has long-running task
3. Explicitly kill the pods with `k pod delete ....`
4. Application gets context canceled from Dapr request when pods shut down
5. Event is sent to DLQ immediately and is not retried

### Example golang handler
Here is an example golang handler that could be used to test the context canceled
```go
func ContextCanceledError() common.TopicEventHandler {
	zap.L().Info("init context canceled error handler")

	return func(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
		logger := zap.L()
		logger.Info(
			"event received",
			zap.String("pubsub", e.PubsubName),
			zap.String("topic", e.Topic),
			zap.String("event_id", e.ID),
			zap.Any("data", e.Data),
		)

		// some long-running task that uses the `ctx`.
		err := api.CallAPI(ctx)

		// err != nil when the context is canceled.
		// if we return `true, err` we would expect a retry to be issued, or if dapr does not get the response, then the event is requeued.
		return (err != nil), err
	}
}
```

###  Config
Rabbit pubsub:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ << pubsub name >> }}
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqp://{{ << connection string >> }}
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2
  - name: prefetchCount
    value: 1
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: false
  - name: enableDeadLetter
    value: true
  - name: exchangeKind
    value: topic
```

Resiliency:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: {{ << pubsub name >> }}-resiliency
spec:
  policies:
    retries:
      exponentialLimitedRetry:
        policy: exponential
        maxRetries: 3
  targets:
    components:
      {{ <<pubsub name>> }}:
        inbound:
          retry: exponentialLimitedRetry
        outbound:
          retry: exponentialLimitedRetry
```

Resiliency enabled:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Values.pubsub.evsPubSubName }}-enable-resiliency
spec:
  tracing:
    samplingRate: "0"
  features:
    - name: Resiliency
      enabled: true
    - name: ServiceInvocation.NoDefaultContentType
      enabled: true
```

We also have the necessary annotations on the pod to bind the config:
```yaml
dapr.io/config: "evs-enable-resiliency"
```

## Release Note
RELEASE NOTE: up for discussion
