### ISSUE TITLE
State management - Incorrect key in redis when key-prefix-strategy is namespace

### ISSUE THREAD

**Issue by q1a0mu** [dapr/dapr#7267]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.12.0

## Expected Behavior

I set the key-prefix-strategy to namespace and namespace is production
the redis key should be production.myApp||name

## Actual Behavior

redis key：myApp||name

## Steps to Reproduce the Problem

https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-share-state/

1. Create a statestore.yaml in the resources folder
``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: production
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: namespace
```
2. Run dapr
```
dapr run --app-id myApp --dapr-http-port 3500 --resources-path resources
```
3. Save state
```
curl -X POST http://localhost:3500/v1.0/state/statestore \
  -H "Content-Type: application/json"
  -d '[{ "key": "name", "value": "Bruce Wayne"}]'
```

## Release Note

RELEASE NOTE:  **FIX**  incorrect key when key-prefix-strategy is namespace
