### ISSUE TITLE
GraphQL Binding returning GraphQL Error: decoding response: invalid character '\u003c'

### ISSUE THREAD

**Issue by MarekLani** [dapr/dapr#7269]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.12.2

## Expected Behavior
When I invoke the GraphQL Binding with valid payload according to documentation, I'd expect request to be executed and ricted to my graphql endpoint

## Actual Behavior
I am getting following error: {"errorCode":"ERR_INVOKE_OUTPUT_BINDING","message":"error invoking output binding apimgraphql: GraphQL Error: decoding response: invalid character '\u003c' looking for beginning of value"}

## Steps to Reproduce the Problem
I have my working graphql endpoint deployment on Azure API Management, nevertheless the target endpoint should be irelevant. 

This is my binding definition:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: apimgraphql
spec:
  type: bindings.graphql
  version: v1
  metadata:
    - name: endpoint
      value: "https://<myapimendpoint>.azure-api.net/mygraphql"
    - name: header:Ocp-Apim-Subscription-Key
      value: "mySubscriptionKey"
    - name: header:Cache-Control
      value: "no-cache"
    - name: header:Content-Type
      value: "application/json"
```
Invocation of binding with valid grapql query: 
`curl -X POST http://localhost:3500/v1.0/bindings/apimgraphql -H "Content-Type: application/json" -d '{ "metadata": {"query":"query {getProduct {description price}}"},"operation": "query"}'`

When invoking the binding I am getting error stated above. I believe binding is well configured as well as the query is valid.

## Release Note

RELEASE NOTE:
