### ISSUE TITLE
The subscriber received message but it's not in the redis stream (For redis stream as pubsub)

### ISSUE THREAD

**Issue by zhangcz828** [dapr/dapr#7291]
Hello, I have a publisher and subscriber, and the component is redis stream. 

Within the publisher, I have below code to send messages with a loop 
```
	// Publish a single event
	for i := 0; i < 10000; i++ {
		if err := p.daprClient.PublishEvent(ctx, pubsubName, topicName, publishEventData); err != nil {
			fmt.Println("publish the", i, " message with err: ", err)
			return nil, err
		}
	}
```

And I start to do `sentinel failover mymaster` when I trigger the event send. So this simulate the redis keep doing failover when receiving messages. 

And then by checking the message in redis by using XLEN and the message in the subscriber, I found that some messages appears in the log of subscriber but not in the topic of redis stream. 

Notes that the publisher send 10, 000 messages, and the subscriber received about 2500 and the XLEN in redis stream with 1800. But the publisher does not report any errors. 

the component yaml in publisher
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: rfs-redis-cluster.redis-cluster.svc.cluster.local:26379
  - name: redisPassword
    value: ""
  - name: failover
    value: true
  - name: sentinelMasterName
    value: mymaster # default of bitnami/redis-sentinel
  - name: redisMaxRetries
    value: 5
  - name: redisMinRetryInterval
    value: 8ms
  - name: redisMaxRetryInterval
    value: 5s
```

I'm wondering why this would happen and is there any potential bug?
