### ISSUE TITLE
High cardinality metrics: most rules in a metrics config for the label "path" aren't applied

### ISSUE THREAD

**Issue by opticoder** [dapr/dapr#7309]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.12.2

## Expected Behavior
All specified in the config metrics rules were applied

## Actual Behavior
For verifying metrics regex rules for an app deployed with Dapr in k8s I run 
> kubectl port-forward svc/app1-dapr 9090:9090
and then open http://localhost:9090 in a browser.

I see that numbers (IDs for my app) in metrics were replaced according the rules in my config with "\<int\>" for the metrics:
- dapr_runtime_service_invocation_req_sent_total
- dapr_runtime_service_invocation_req_recv_total
- dapr_runtime_service_invocation_res_sent_total
- dapr_runtime_service_invocation_res_recv_total
- dapr_runtime_service_invocation_res_recv_latency_ms
- dapr_http_client_completed_count

And weren't replaced for the metrics:
- dapr_http_client_roundtrip_latency_bucket
- dapr_http_client_roundtrip_latency_sum
- dapr_http_client_roundtrip_latency_count
- dapr_http_client_sent_bytes_bucket
- dapr_http_client_sent_bytes_sum
- dapr_http_client_sent_bytes_count

Therefore all the rules for the metrics with the label "path" except `dapr_http_client_completed_count` weren't applied

## Steps to Reproduce the Problem
Simplified config:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myapps_config
spec:
  metric:
    enabled: true
    rules:
    - name: dapr_runtime_service_invocation_req_sent_total
      labels:
      - name: method
        regex:
          "/<int>": "/\\d+"
    - name: dapr_runtime_service_invocation_req_recv_total
      labels:
      - name: method
        regex:
          "/<int>": "/\\d+"

    - name: dapr_runtime_service_invocation_res_sent_total
      labels:
      - name: method
        regex:
          "/<int>": "/\\d+"
    - name: dapr_runtime_service_invocation_res_recv_total
      labels:
      - name: method
        regex:
          "/<int>": "/\\d+"
    - name: dapr_runtime_service_invocation_res_recv_latency_ms
      labels:
      - name: method
        regex:
          "/<int>": "/\\d+"

    - name: dapr_http_client_completed_count
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"

    - name: dapr_http_client_roundtrip_latency_bucket
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"
    - name: dapr_http_client_roundtrip_latency_sum
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"
    - name: dapr_http_client_roundtrip_latency_count
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"

    - name: dapr_http_client_sent_bytes_bucket
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"
    - name: dapr_http_client_sent_bytes_sum
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"
    - name: dapr_http_client_sent_bytes_count
      labels:
      - name: path
        regex:
          "/<int>": "/\\d+"
```
## Release Note

RELEASE NOTE: **FIX** applying metrics rules for some metrics
