### ISSUE TITLE
Automatic state encryption fails in Dapr 1.12

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/dapr#7512]
## In what area(s)?

 /area runtime

## What version of Dapr?
1.12.4 

## Expected Behavior

Automatic state encryption should work [as documented](https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-encrypt-state/#enabling-automatic-encryption) it does in Dapr 1.11.6.

## Actual Behavior

Running Dapr with a state store and automatic encryption enabled saves the state value correctly but does not append the encryption key to the record. This is problematic for decryption as Dapr expects the state store value to be in the format of `<encrypted-value>||<encryption-key>`. Thus, when trying to access the state store values, you get the error "could not decrypt data for state store statestore: encryption key name not found on record".

Note I tried this same sample and it worked with Dapr 1.11.6 and it worked, but failed in Dapr 1.12.4 with both local redis and Azure blob storage using the dotnet 1.12 Dapr sdk.

Eg. dotnet sdk:
![image](https://github.com/dapr/dapr/assets/14792988/1458f5f8-608c-4f27-a390-a52142842cff)

## Steps to Reproduce the Problem

1. Run the Dapr dotnet state sample with redis locally with Dapr runtime 1.12.4. Use the following component:
``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: primaryEncryptionKey
    secretKeyRef:
      name: encryption-key
      key: encryption-key
auth:
    secretStore: local-secret-store
```
2. Create a local secretstore with the following component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "your/path/to/secrets.json"
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"
```
4.  Add a secrets.json file with the following:

``` json
{
  "encryption-key": "<YOUR_KEY>"
}
```
5. Run the sample to save a value in the state store. Notice that that the value is saved in Redis with two pipe characters at the end. For instance:

![image](https://github.com/dapr/dapr/assets/14792988/7e8659ed-f86b-4dde-a113-4a824a648a34)

6. Running the sample to retrieve the value from the state store throws the following error:

``` text
== APP == fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
== APP ==       An unhandled exception has occurred while executing the request.
== APP ==       Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==        ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to get local from state store statestore: could not decrypt data for state store statestore: encryption key name not found on record")
== APP ==          at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          --- End of inner exception stack trace ---
== APP ==          at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          at Program.<>c__DisplayClass0_0.<<<Main>$>b__1>d.MoveNext() in /Users/alicegibbons/repos/pubsub-svc-example/csharp-service/Program.cs:line 64
== APP ==       --- End of stack trace from previous location ---
== APP ==          at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
== APP ==          at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass46_3.<<HandleRequestBodyAndCompileRequestDelegate>b__2>d.MoveNext()
== APP ==       --- End of stack trace from previous location ---
== APP ==          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
== APP ==          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Release Note

RELEASE NOTE: **FIX** Bug in automatic state encryption.
