### ISSUE TITLE
Scope of component not working

### ISSUE THREAD

**Issue by MatteoRigoni** [dapr/dapr#7564]
I, i've several microservices in .NET 8 that i run with docker compose.
I've a Dapr component using binding "cron". I use it to schedule periodic operations on different microservices. I need that each one is managed only by the right microservice.

**Docker compose:**
```
_micro-1-dapr:
  command: ["./daprd",
    "-app-id", "micro-1",
    "-app-port", "80",
    "-components-path", "/components"
    ]
  volumes:
    - ./Dapr/components:/components
micro-2-dapr:
  command: ["./daprd",
    "-app-id", "micro-2",
    "-app-port", "80",
    "-components-path", "/components"
    ]
  volumes:
    - ./Dapr/components:/components_
```

**Component:**
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cleanup-database
spec:
  type: bindings.cron
  version: v1
  metadata:
- name: schedule
    value: "@every 30m"
scope:
- micro-1

```
If i implement an HTTP endpoint "/cleanup-database" both on micro-1 and micro-2, the call is made to all. What am i missing?
How can i prevent that also micro-2 is call every 30 minutes?

Thanks 
Bye
