### ISSUE TITLE
Incomplete Downloads of Large Files (>10GB) in AKS 

### ISSUE THREAD

**Issue by silverwrath** [dapr/dapr#7589]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.12.1

## Expected Behavior

Given the network speed is adequate, I expect the complete file download to succeed within the specified 600-second duration as outlined by the resiliency policies.

## Actual Behavior

While attempting to download large files (around 10GB or larger) from my application running in an AKS pod via the Dapr sidecar endpoint `[http://localhost:3500/v1.0/invoke/pds-app/method/api/v1.0/large-file-download/`](http://localhost:3500/v1.0/invoke/pds-app/method/api/v1.0/large-file-download/), the request terminates prematurely (roughly between 3 minutes 20 seconds to 3 minutes 40 seconds), resulting in an incomplete file download. The downloaded file size ranges from 7-8 GB, varying with network speed.

To address this issue, I have configured resiliency policies aiming to ensure successful downloads within a 600-second time frame, as shown below:

```yaml
apiVersion: [dapr.io/v1alpha1](http://dapr.io/v1alpha1)
kind: Resiliency
metadata:
  name: noretrypolicy
scopes:
  - data-management-app
  - pds-app
spec:
  policies:
    retries:
      retryNever:
        policy: constant
        duration: 600s
        maxRetries: 0
    timeouts:
      general: 60s
      important: 600s
      largeResponse: 100s
      # Global Timeout Policy
      DefaultTimeoutPolicy: 600s
  targets:
    apps:
      data-management-app:
        timeout: important
        retry: retryNever
```
When I add resiliency policies as given below, the download gets over immediately after sending the request. There are no logs in daprd either.
```
dapr.io/http-max-request-size: "100000"
dapr.io/http-read-buffer-size: "16"
```
we are using the above values for our DAPR app. So http-max-request-size is sufficient enough

Also, when I make the request directly to my pod using the endpoint 'http://10.244.2.24:8000/api/v1.0/large-file-download/' the request always completes successfully and downloads the complete file. 

This "large-file-download" API exists behind a Django server and will be sending a **streaming** response for the 10 GB file.

## Steps to Reproduce the Problem

1. Deploy Dapr version 1.12.1 within an AKS environment.
2. Initiate a file download request from one pod (e.g., `data-management-app`) to another (e.g., `pds-app`) utilizing the endpoint `[http://localhost:3500/v1.0/invoke/pds-app/method/api/v1.0/large-file-download/`](http://localhost:3500/v1.0/invoke/pds-app/method/api/v1.0/large-file-download/).
3. Observe the premature termination of the download request and the incomplete file download.

## Environment Details
- Dapr Version: 1.12.1
- Kubernetes (AKS) Environment
- Size of the file attempted to download: >10GB

I kindly request guidance on whether there might be additional configurations required or if there's a potential issue with Dapr handling large file downloads in conjunction with the specified resiliency policies. Any insights or recommendations to ensure the completion of large file downloads within the desired time frame would be greatly appreciated.

## Release Note

RELEASE NOTE:
