### ISSUE TITLE
Redis NOAUTH Authentication required

### ISSUE THREAD

**Issue by dennymao** [dapr/dapr#7627]
My yaml file:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: MSession
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 192.168.0.79:6379
  - name: redisPassword
    value: "123456"
    name: redisDB
    value: "3" 
```

Because I have configured the redisDB node. So the following error occurred：
 
`time="2024-03-14T16:45:55.7878517+08:00" level=fatal msg="Fatal error from runtime: process component MSession error: [INIT_COMPONENT_FAILURE]: initialization error occurred for MSession (state.redis/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for MSession (state.redis/v1): redis store: error connecting to redis at 192.168.0.79:6379: NOAUTH Authentication required." app_id=Coyotebrass-Bell instance=TF-Laptop scope=dapr.runtime type=log ver=1.12.5`
If the redisDB node is removed. Running normally

I made a mistake. The configuration node is missing "-"
