### ISSUE TITLE
Troubleshooting pub/sub with Redis in a .NET Aspire solution

### ISSUE THREAD

**Issue by ngruson** [dapr/dapr#7638]
I'm running my .NET 8 solution locally with .NET Aspire.
The solution contains a Blazor application and a Redis instance.
I want to use Dapr for pub/sub.

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddContainer("redis", "redis")
    .WithEndpoint(containerPort: 6379, hostPort: 6379);

builder.AddProject<Projects.UI_Blazor>("frontend")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "frontendDapr",
        AppPort = 5001,
        ResourcesPaths = ImmutableHashSet.Create("./components")
    })
```

The Dapr sidecars start correctly and are showing up in the Aspire dashboard.

My `pubsub.yaml` file in the components folder looks like this:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bookingPubSub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```

When I start my solution, Redis is running on localhost:6379.

The Blazor application publishes an integration event to the Dapr sidecar:

```csharp
await this.daprClient.PublishEventAsync(
    PubSubNames.BookingPubSub,
    TopicNames.AddBookingTopic,
    request.@event,
    cancellationToken);
```
This code doesn't throw an exception.

The problem is that my subscribing application doesn't receive the message.
I implemented the subscriber following the samples.

```csharp
app.MapSubscribeHandler();

app.MapPost("/booking", [Topic(PubSubNames.BookingPubSub, TopicNames.AddBookingTopic)]
    async (AddBookingIntegrationEvent @event) =>
{
    return Results.Ok();
});
```

I'd like to confirm that the publishing part is going ok, but I can't find any evidence of that.

The log file of the Dapr sidecar doesn't show any logging of the event being published.

![image](https://github.com/dapr/dapr/assets/3188323/eae36abe-5c02-4ea6-b797-b14a976da151)

Also, the Redis logs don't show any activity.

![image](https://github.com/dapr/dapr/assets/3188323/38d5b679-94e4-4345-900e-e6c7694977f0)

Should the publishing of a message show up in the sidecar logs?
Any other suggestions?
