### ISSUE TITLE
blocked-duration-in-seconds does not seem to work

### ISSUE THREAD

**Issue by virgilp** [dapr/dapr#7653]
## In what area(s)?

 /area runtime

## What version of Dapr?

> 1.13.0

## Expected Behavior

When I restart the deployment while a message is actively being processed, I am expecting daprd to block shutdown for the specified period & keep on processing the active message. 

## Actual Behavior

While shutdown sequence is indeed blocked (and I can e.g. still send messages using the sidecar), the currently-processed message is imediatelly/unilaterally cancelled.  This is a bug, since it leads to duplicate "full" processing of the same message (if my app, attempting to do graceful shutdown, actually finishes the processing of the message before shutting down). 
This is how the sidecar logs look like:

```
{"app_id":"my-app","instance":"my-app-6b94bcfbdc-bbxdm","level":"info","msg":"Received signal 'terminated'; beginning shutdown","scope":"dapr.signals","time":"2024-03-27T10:57:23.821429774Z","type":"log","ver":"1.13.0"}
{"app_id":"my-app","instance":"my-app-6b94bcfbdc-bbxdm","level":"info","msg":"Blocking graceful shutdown for 1h1m40s or until app reports unhealthy...","scope":"dapr.runtime","time":"2024-03-27T10:57:23.821530477Z","type":"log","ver":"1.13.0"}
{"app_id":"my-app","instance":"my-app-6b94bcfbdc-bbxdm","level":"warning","msg":"encountered a retriable error while publishing a subscribed message to topic my-topic, err: Post \"http://127.0.0.1:7187/internalApi/myTopic/myTopicRequest\": context canceled","scope":"dapr.runtime.processor.pubsub","time":"2024-03-27T10:57:23.821942387Z","type":"log","ver":"1.13.0"}
```

Daprd should not cancel the active message handler, it defeats the purpose of the "graceful shutdown"/ "block shutdown". 

## Steps to Reproduce the Problem
It's described above - just try to restart a deployment while a message is being processed, notice the sidecar immediately giving up on it.  See also discussion in https://discord.com/channels/778680217417809931/901141467840524289/threads/1222501189829263491

My setup is:
- C# / .NET8 app processing messages. ServiceBus Topics configured as pubsub component, maxActiveMessages 1, maxConcurrentHandlers 1. Generous (1day) handlerTimeoutInSec & defaultMessageTimeToLiveInSec

Pod annotations/ configuration:
```
Labels:
                           dapr.io/app-id=my-app
                           dapr.io/metrics-enabled=true
                           dapr.io/sidecar-injected=true
Annotations:
                           dapr.io/app-health-check-path: /api/status
                           dapr.io/app-health-probe-interval: 1
                           dapr.io/app-health-threshold: 1
                           dapr.io/app-id: my-app
                           dapr.io/app-port: 7187
                           dapr.io/block-shutdown-duration: 3700s
                           dapr.io/config: my-app-config
                           dapr.io/disable-builtin-k8s-secret-store: true
                           dapr.io/enable-app-health-check: true
                           dapr.io/enabled: true
                           dapr.io/graceful-shutdown-seconds: 30
                           dapr.io/log-as-json: true
                           dapr.io/sidecar-cpu-limit: 300m
                           dapr.io/sidecar-cpu-request: 100m
                           dapr.io/sidecar-memory-limit: 1000Mi
                           dapr.io/sidecar-memory-request: 100Mi
Termination Grace Period:  3700s
SeccompProfile:            RuntimeDefault
```
daprd sidecar container - arguments:
```
 /daprd
      --dapr-http-port
      3500
      --dapr-grpc-port
      50001
      --dapr-internal-grpc-port
      50002
      --dapr-listen-addresses
      [::1],127.0.0.1
      --dapr-public-port
      3501
      --app-id
      dbt-execution
      --app-protocol
      http
      --log-level
      info
      --dapr-graceful-shutdown-seconds
      30
      --mode
      kubernetes
      --control-plane-address
      dapr-api.dapr-system.svc.cluster.local:443
      --sentry-address
      dapr-sentry.dapr-system.svc.cluster.local:443
      --app-port
      7187
      --enable-metrics
      --metrics-port
      9090
      --config
      my-app-config
      --placement-host-address
      dapr-placement-server.dapr-system.svc.cluster.local:50005
      --disable-builtin-k8s-secret-store
      --enable-app-health-check
      --app-health-check-path
      /api/status
      --app-health-probe-interval
      1
      --app-health-probe-timeout
      500
      --app-health-threshold
      1
      --log-as-json
      --enable-mtls
      --dapr-block-shutdown-duration
      3700s
```

### Additional observations.
`blocked-duration-in-seconds` is designed to be an upper bound - the if the app healthchecks start failing, it will immediately unblock. This is all nice and well, except that Kestrel (and any reasonable web server, one would argue) stops receiving new requests after SIGTERM. This includes the "health check" requests, which by default will immediately start failing.

I solved this with a `preStop` hook in Kubernetes (basically, my container is not getting the SIGTERM at all during the shutdown procedure - but I can't configure a hook on `daprd` so I can't prevent it from getting the SIGTERM). However, this mechanism is not nice at all - IMO, `daprd` should not poll for app health in this situation, it should be pinged by the app to continue shutdown.  The whole reason to have the setting is in order to get an app-controlled, graceful shutdown. You can trust the app to report when it's done with shutdown (if it can't do that, shutdown probably isn't graceful after all)

## Release Note

RELEASE NOTE: **FIX** Daprd graceful pubsub shutdown.
