### ISSUE TITLE
Update the holopin.yaml to use the runtime badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/dapr#7684]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqh1xny39170fl75cawk0h5) for this repo:

```yaml
organization: dapr
defaultSticker: clrqh1xny39170fl75cawk0h5
stickers:
  -
    id: clrqh1xny39170fl75cawk0h5
    alias: runtime-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.
