### ISSUE TITLE
How could I know about redis state store's state, I don't know my redis state store is or not good 

### ISSUE THREAD

**Issue by yhyddr** [dapr/dapr#769]
## Ask your question here

I `kubectl apply -f` this yaml and didn't know if it was successful. And my application can't persist state.
I wonder if my host value set error.Maybe in my Kubernetes, it's not redis-master:6379

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    value: 123456
```

![image](https://user-images.githubusercontent.com/32089134/68530143-9de45a80-0340-11ea-9bfe-4f315f90d5f3.png)
