### ISSUE TITLE
process component sentinel error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1)

### ISSUE THREAD

**Issue by bunengxiu** [dapr/dapr#7714]
An error occurred following the [documentation tutorial](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-sentinel/), deploy context is [nodeapp.txt](https://github.com/dapr/dapr/files/15192595/nodeapp.txt)

error log:
process component sentinel error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1): [CREATE_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1): process component sentinel error: error creating HTTP middleware middleware.http.sentinel/v1: error to init sentinel with config '{\"Version\":\"v1\",\"Sentinel\":{\"App\":{\"Name

Dapr 
  Runtime -- version 1.13.2
kubectl
  Client Version: v1.28.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.2

**Comment by berndverst** [comment]
Are you saying the component yaml file you used is **exactly** the one from the docs?

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sentinel
spec:
  type: middleware.http.sentinel
  version: v1
  metadata:
  - name: appName
    value: "nodeapp"
  - name: logDir
    value: "/var/tmp"
  - name: flowRules
    value: >-
      [
        {
          "resource": "POST:/v1.0/invoke/nodeapp/method/neworder",
          "threshold": 10,
          "tokenCalculateStrategy": 0,
          "controlBehavior": 0
        }
      ]  
```
