### ISSUE TITLE
Subscription stops working when having 5 routing keys defined

### ISSUE THREAD

**Issue by byteAbit0101** [dapr/dapr#7739]
## In what area(s)?

runtime

## What version of Dapr?

1.12.4

## Expected Behavior

- 5 routing keys are supported.
- Documentation: 
    - stating what is the maximum amount of routingKeys
    - stating whether routingKeys have any kind of limits/constraints

## Actual Behavior

When defining 5 routing keys the subscription stops working, no messages are getting pushed by Dapr to the defined route

## Steps to Reproduce the Problem

- RabbitMQ: 
    - Version: 3.12.2
    - Exchange 'topica'>> durable - NO
- Dapr
   - Version: 1.12.4
   - configuration:
       - pubsub.yaml
          ```
          apiVersion: dapr.io/v1alpha1
          kind: Component
          metadata:
            name: pubsub-a
          spec:
            type: pubsub.rabbitmq
            version: v1
            metadata:
            - name: consumerID
              value: "test-api"
            - name: connectionString
              value: {RABBIT-MQ-CONNECTION-STRING}
            - name: durable
              value: false
            - name: deletedWhenUnused
              value: false
            - name: autoAck
              value: false
            - name: deliveryMode
              value: 0
            - name: requeueInFailure
              value: false
            - name: prefetchCount
              value: 0
            - name: reconnectWait
              value: 5
            - name: concurrencyMode
              value: parallel
            - name: enableDeadLetter 
              value: false
            - name: exchangeKind
              value: topic
            ```
       - subscription.yaml
          ```
          apiVersion: dapr.io/v2alpha1
          kind: Subscription
          metadata:
            name: event-user-receiver
          spec:
            topic: topica
            routes: 
              default: /api/events/user
            pubsubname: pubsub-a
            metadata:
              routingKey: SYS.*.event.User.UserCreated.#, SYS.*.event.User.UserUpdated.#, SYS.*.event.User.UserDeleted.#, SYS.*.event.User.UserDeactivated.#, SYS.*.event.User.UserActivated.#
          scopes:
          - test-api
          ```

## Release Note

RELEASE NOTE: **FIX** Supported routing key count -->
