### ISSUE TITLE
Proposal: Circuit Breaking

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#777]
## Proposal Overview

This proposal builds on #767 to allow circuit breaker policies to be enabled on a per service (`daprID`) basis.
The benefits of Circuit Breaking are well known and implemented in various L7/L4 networking services such as Linkerd 1.x and Istio.

However, different from the type of circuit breakers you'd typically find in service meshes, Dapr can utilize circuit breaking on a per service basis (as source), and apply the breaker not only to other services within the cluster but also to Dapr's various building blocks such as Pub/Sub and State Management.

The motivation behind applying circuit breaking to various building blocks is to allow the underlying implementations to recover gracefully from failures, upgrades or load.
For example, consider 3 applications in a cluster publishing events to a NATS server. Eventually the NATS server cannot handle the load and starts rejecting messages, but cannot be given ample time to recover because the applications have no idea of an open circuit, meaning, they continue to send messages.

A circuit breaker applied to a Dapr component can allow any type of component to recover while the circuit is open.
Another benefit of applying circuit breakers individually to a given service is to allow a priority based delivery.

Building on the  Pub/Sub example above, lets assume we have 2 services (A and B) which we can tolerate sending delayed messages, whereas service C carries heavier weight in terms of delivery, meaning it should try to send as many messages as possible.

If we apply the circuit breaker to services A and B, but not to C, in a situation where the Pub/Sub server is under load, A and B will transition from a closed circuit (healthy) to open circuit (out of play) under certain conditions, thus reducing the load their respective services carry, giving service C the ability maintain regular throughput and better meeting its SLA.

The circuit breaker can also be applied to Dapr bindings which may refer to external cloud services which reside outside the cluster.

## Architecture

Components will see the addition of a new component type, `policies`.

Under policies, different types such as `circuitbreaker` and `retry` can register to provide different capabilities that are implemented through the Dapr middleware.
Because this is implemented in the Dapr middleware, we ensure almost zero-cost integration with distributed tracing, which will allow for near zero-cost tracing of circuit breaking behaviors. (For example, tracing consecutive failures  from service A calling method X on service B).

Because circuit breakers are a component, they are automatically treated as any other component by Dapr, and no special changes are required in Dapr modes (Kubernetes, Standalone etc.). The same Dapr mechanisms for updating, adding and removing components are at work for policies.

## Component Spec

The following examples shows a `circuitbreaker` policy:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myCB
spec:
  type: policies.circuitbreaker
  metadata:
  - name: maxRequests
    value: 1
  - name: interval
    value: 5s
  - name: timeout
    value: 60s
  - name: rule.latency
    value: "> 500ms"
  - name: rule.failures
    value: 10
  - name: rule.threshold
    value: 5
  - name: appliesTo
    value: bindings.http.myFunction, orderService
  - name: consumedBy
    value: "*"
```

* maxRequests: The number of requests allowed to pass to the destination while in `half-open` state
* interval: The interval in which the circuit will clear trip counts when in a `closed` state
* timeout: The time to wait before the circuit becomes `half-open` when in `open` state
* rule.latency: Takes an expression that defines latency behaviors of a given target to trip the circuit
* rule.failures: A number of consecutive failures to trip the circuit
* rule.threshold: The threshold for any given `rule.latency` or `rule.failures` to be met to transition the circuit to an `open` state
* appliesTo: A comma delimited string of destinations to apply this rule to.
* consumedBy: By default, "*" will apply this to any service in the cluster. A comma delimited string can allow this rule to apply only for given services, for example: `value: serviceA, serviceB`.
