### ISSUE TITLE
[pubsub] topic name does not match queue name with RabbitMQ

### ISSUE THREAD

**Issue by kylelmh** [dapr/dapr#7852]
## In what area(s)?

/area runtime

> /area operator

> /area placement

/area docs

> /area test-and-release

## What version of Dapr?

1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

I have a DAPR-subscriber and a non-DAPR publisher with RabbitMQ.
I have set the subscriber to subscribe to "test_queue". Then I have the publisher produce to "test_queue" with a direct implementation of RabbitMQ. 

I expect the DAPR-subscriber would be able to receive such a message.

## Actual Behavior

The DAPR-subscriber instead subscribes to "appname-test_queue" when I look on the RabbitMQ management UI. Setting the producer to produce to "appname-test_queue" is my current workaround

Having to add the app name in front of the queue on the publisher side is confusing. I couldn't find this behavior documented anywhere in the docs. 

## Steps to Reproduce the Problem
Using a `pubsub.yaml`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: worker-pub-sub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://rabbitmq:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "true"
  - name: reconnectWait
    value: "1"
  - name: concurrency
    value: parallel
scopes:
  - appname
```

Next, following the official document to subscribe to raw events
https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/#publishing-raw-messages

I implemented a grpc subscriber in Python as follows

```python
from dapr.ext.grpc import App

app = App()


@app.subscribe(pubsub_name="worker-pub-sub", topic="test_queue")
def on_msg(*args):
  print("OK")

app.run(6002)
```

Then publishing a message to the same queue name via an external Python script: e.g.

```python
import pika

with pika.BlockingConnection(pika.ConnectionParameters(host=RABBITMQ_HOST)) as conn:
  ch = conn.channel()
  ch.queue_declare("test_queue")
  ch.basic_publish("", "test_queue", "test")
```

## Release Note

RELEASE NOTE:
