### ISSUE TITLE
[Proposal] Chained token credentials for component authentication

### ISSUE THREAD

**Issue by WhitWaldo** [dapr/dapr#7860]
## In what area(s)?
/area runtime

## Describe the proposal
Today, Dapr supports the capability to authenticate to Azure using any of a collection of authentication measures:
- Client Credentials
- Certificates
- Managed Identities
- Workload Identity (AKS)
- Azure CLI

This is more than fine when the deployment is going to a single known environment, but it makes things sticker when trying to minimizing having multiple sets of files for different environments when the values you use don't change between the two or even create artifacts that are fully permissioned in Azure but intended only for development purposes and not intended to be distributed.

In the effort to minimize creating additional artifacts that can be misplaced (like client credentials or certificates), Azure provides Managed Identities, which are passwordless and great.. so long as your application is running in Azure, which is probably isn't if you're developing locally. If you're running locally, you can just pass in a certificate.. except that that probably shouldn't be a part of the repo for obvious security implications. Same goes for the client credentials in that they shouldn't be saved locally necessarily. Ah, but that's why we have environment variables, right? Just provide the credentials separately to each developer and have them install to their environment. That's nice until you have to roll the secret because an employee resigned and now everyone gets to reinstall.

Rather, to simplify .NET development, Visual Studio implements a local auth service that is represented by a [VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocredential?view=azure-dotnet) or a [VisualStudioCodeCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocodecredential?view=azure-dotnet) depending on your preferred IDE. This is great because now you're authenticating directly through Entra and if a user's credentials are revoked, they immediately lose all related access to Azure without rotating secrets or swapping certificates.

But this is really only a development time problem as your secrets are presumably safely maintained in a Key Vault and accessible via Managed Identity, so that's trivially handled.. how can we reconcile the two to make development easy locally, but functional remotely without having to modify any code or configurations between the two?

In the `Azure.Identity` package for .NET (and presumably for other languages), there exists a class that I've found invaluable called (ChainedTokenCredential)[https://learn.microsoft.com/en-us/dotnet/api/azure.identity.chainedtokencredential?view=azure-dotnet]. It does precisely what it sounds like. Where one can typically authenticate by providing a single credential to Azure services, a `ChainedTokenCredential` allows one to pass in multiple credential types and it will essentially failover between each (in the order provided) until one works.

To look at how easily this is set up (in C#), let me share how I handle this in my various non-Dapr microservices via dependency injection registration (so the credentials are readily available to other Azure resources):
```cs
builder.Services.AddSingleton(_ => {
  var managedIdentityCredential = new ManagedIdentityCredential("<clientId>");
  var visualStudioCredential = new VisualStudioCredential();

  return new ChainedTokenCredential(managedIdentityCredential, visualStudioCredential);
});
```

With nothing but the above, I have a fully functional instance I can pass into any Azure resource that accepts a `TokenCredential` and I don't have to change anything between local and development deployments. I place the managed identity credential first in the list because a brief timeout delay is acceptable for local development where it would have negative implications in production, but this is a detail that can be explained in the documentation.

I would like to propose something similar be implemented in Dapr. This is likely a pretty small addition as it's just repurposing everything already there and chaining it, but rather than provide a single set of metadata fields to authenticate to Entra (or whatever else other cloud providers are using), I propose some changes to the approach used today. My approach doesn't deprecate the existing approach and instead leaves it as something that can be discouraged (not mentioned in the documentation) and marked as obsolete down the road. Today, the approach looks like the following, allowing only a single authentication approach to be attempted (and which one depends on which properties are provided, here the last three options in the metadata values): 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "[your_keyvault_name]"
  - name: azureTenantId
    value: "[your_tenant_id]"
  - name: azureClientId
    value: "[your_client_id]"
  - name: azureClientSecret
    value : "[your_client_secret]"
```

When referencing a secret that's intended to be accessed via this Entra-based approach, there was a new type created called `SecretKeyRef`. I propose a new resource should be introduced called `Credential` with a format similar to the following (included all available token providers, but also added VS). This type should allow the desired identity providers to be passed in (meaning that if there's a duplicate type provided, it's fully legal and processed in the order provided):

```yaml
apiVersion: dapr.io/v2alpha1
kind: Credential
metadata:
  name: <REPLACE-WITH-NAME>
spec:
  providers:
    - type: VisualStudioCredentialProvider
    - type: AzureClientCredentialProvider
      clientId: <REPLACE-WITH-CLIENT-ID>
      tenantId: <REPLACE-WITH-TENANT-ID>
      clientSecret: <REPLACE-WITH-CLIENT-SECRET>
    - type: AzureCertificateCredentialProvider
      clientId: <REPLACE-WITH-CLIENT-ID>
      tenantId: <REPLACE-WITH-TENANT-ID>
      certificate: '<REPLACE-WITH-CERTIFICATE-IN-PFX/PKCS#12-FORMAT>'
      certificateFile: <REPLACE-WITH-PATH-TO-CERTIFICATE>
      certificatePassword: <REPLACE-WITH-CERTIFICATE-PASSWORD>
    - type: AzureManagedIdentityCredentialProvider
      clientId: <REPLACE-WITH-CLIENT-ID>
    - type: AzureWorkloadIdentityCredentialProvider
    - type: AzureCliCredentialProvider
scopes:
  - <REPLACE-WITH-SCOPED-APPIDS>
```

Nothing needs to be changed about how the `secretKeyRef` works in component specifications. 

The secret store component should be updated to add a new key/value pair at the bottom, as in the following:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: [your_keyvault_name]
  - name: azureEnvironment # Optional, defaults to AZUREPUBLICCLOUD
    value: "AZUREPUBLICCLOUD"
  - name: azureTenantId
    value: "[your_service_principal_tenant_id]"
  - name: azureClientId
    value: "[your_service_principal_app_id]"
  - name: azureCertificateFile
    value : "[pfx_certificate_file_fully_qualified_local_path]"
identity:
  credential: <REPLACE-WITH-NAME-OF-CREDENTIAL-PROVIDER-COMPONENT-ABOVE>
```

From there, Dapr will attempt to secure credentials in the order provided in the specified component until it receives a non-default credential and then use it like it would today to authenticate to the component it's trying to access.

A couple of follow-up thoughts on the approach:
- Names don't assume Azure usage and instead clarify who the credential provider is associated with so this can be extended to support in other cloud providers as part of a future effort
- Nothing about the implementation in the secret stores needs to change as the fail-over behavior should be managed entirely within Dapr
- The way the authentication values are passed in today needn't change. Rather, as a matter of documentation, it should be introduced ASAP that there's a new preferred approach and that either one or the other needs to be implemented (emphasis on the new approach). Existing approaches will continue to work either indefinitely without chaining support or until the component spec gets an upgrade, so plenty of time to migrate and give notice.

Especially paired with users learning about Dapr from its recent integration with Aspire, implementing low-effort functionality like this will only simplify their adoption and lessen authentication overhead while encouraging richer development-time security.

Thank you for the consideration.

## Release Note
RELEASE NOTE:
**ADD** Support for chained authentication enabling a fail-over style approach across different credential providers
