### ISSUE TITLE
rabbitmq component, cannot enable deletedWhenUnused and enableDeadLetter at the same time

### ISSUE THREAD

**Issue by Cherrs** [dapr/dapr#7899]
## What version of Dapr?
1.13.4

log:
level=error msg="rabbitmq pub/sub: prepareSubscription for topic/queue 'orders/dlq-event-test-orders' failed in channel.QueueDeclare: Exception (406) Reason: \"PRECONDITION_FAILED - invalid arg 'x-queue-mode' for queue 'dlq-event-test-orders' in vhost 'open' of queue type rabbit_quorum_queue\"" app_id=event-test component="order-pubsub (pubsub.rabbitmq/v1)" instance=event-test-5db89b5c9-2ksqv scope=dapr.contrib type=log

RabbitMQ Version:
3.13.2

Component:
apiVersion: dapr.io/v1alpha1
kind: Component
```yaml
metadata:
  name: order-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "***"
    - name: prefetchCount
      value: 2
    - name: deletedWhenUnused
      value: false
    - name: enableDeadLetter # Optional enable dead Letter or not
      value: true
```
