### ISSUE TITLE
Inbound Binding is not triggering the event named in the outbound binding

### ISSUE THREAD

**Issue by jocko-wowza** [dapr/dapr#794]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 0.1.x

## Expected Behavior

Outbound binding call for `create-transcoder` should trigger the `/create-transcoder` endpoint in my server that is handling the inbound bindings.

## Actual Behavior

An Outbound binding call for `create-transcoder` is triggering the `/stop-transcoder` or `/delete-transcoder` seemingly randomly based on the deploy.

## Steps to Reproduce the Problem

1. Deploy DAPR to my K8s cluster/namespace
2. Deploy my Helm chart with the Binding component configurations set to access my bindings API server.
3. Trigger the `create-transcoder` outbound binding using CURL inside the event API sever.
    `curl -X POST http://localhost:3500/v1.0/bindings/transcoder-start -d '{ "data": { "message": "Hi!" } }'`
4. Logs in the Event API server show that a different endpoint is being called:

```
I, [2019-11-14T17:43:10.543034 #10]  INFO -- : Event Received: {"message":"Hi!"}]
I, [2019-11-14T17:43:10.543127 #10]  INFO -- : EVENT: transcoder-delete received | payload: [{}]
127.0.0.1 - - [14/Nov/2019:17:43:10 +0000] "POST /transcoder-delete HTTP/1.1" 200 20 0.0005
127.0.0.1 - - [14/Nov/2019:17:43:10 UTC] "POST /transcoder-delete HTTP/1.1" 200 20
```

----

Binding Component declarations in the Helm Chart:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "transcoder-start"
spec:
  type: bindings.aws.sqs
  metadata:
  - name: region
    value: us-west-1
  - name: queueName
    value: [OMITTED]
  - name: accessKey
    value: [OMITTED]
  - name: secretKey
    value: [OMITTED]
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "transcoder-create"
spec:
  type: bindings.aws.sqs
  metadata:
  - name: region
    value: us-west-1
  - name: queueName
    value: [OMITTED]
  - name: accessKey
    value: [OMITTED]
  - name: secretKey
    value: [OMITTED]
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "transcoder-stop"
spec:
  type: bindings.aws.sqs
  metadata:
  - name: region
    value: us-west-1
  - name: queueName
    value: [OMITTED]
  - name: accessKey
    value: [OMITTED]
  - name: secretKey
    value: [OMITTED]
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "transcoder-delete"
spec:
  type: bindings.aws.sqs
  metadata:
  - name: region
    value: us-west-1
  - name: queueName
    value: [OMITTED]
  - name: accessKey
    value: [OMITTED]
  - name: secretKey
    value: [OMITTED]
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: [OMITTED]
```

----

DAPRD Startup Logs:

```
time="2019-11-14T16:00:59Z" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
time="2019-11-14T16:00:59Z" level=info msg="log level set to: info"
time="2019-11-14T16:00:59Z" level=info msg="kubernetes mode configured"
time="2019-11-14T16:00:59Z" level=info msg="dapr id: dapr-event-handler"
time="2019-11-14T16:00:59Z" level=info msg="loaded component transcoder-stop (bindings.aws.sqs)"
time="2019-11-14T16:00:59Z" level=info msg="loaded component statestore (state.redis)"
time="2019-11-14T16:00:59Z" level=info msg="loaded component transcoder-start (bindings.aws.sqs)"
time="2019-11-14T16:00:59Z" level=info msg="loaded component transcoder-create (bindings.aws.sqs)"
time="2019-11-14T16:00:59Z" level=info msg="loaded component transcoder-delete (bindings.aws.sqs)"
time="2019-11-14T16:00:59Z" level=info msg="application protocol: http. waiting on port 4242"
time="2019-11-14T16:00:59Z" level=info msg="application discovered on port 4242"
2019/11/14 16:00:59 redis: connecting to [OMITTED]
2019/11/14 16:00:59 redis: connected to [OMITTED]
time="2019-11-14T16:00:59Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
time="2019-11-14T16:00:59Z" level=info msg="actors: starting connection attempt to placement service at dapr-placement.dapr-demo.svc.cluster.local:80"
time="2019-11-14T16:00:59Z" level=info msg="http server is running on port 3500"
time="2019-11-14T16:00:59Z" level=info msg="gRPC server is running on port 50001"
time="2019-11-14T16:00:59Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 459.10249ms"
time="2019-11-14T16:00:59Z" level=info msg="actors: established connection to placement service at dapr-placement.dapr-demo.svc.cluster.local:80"
time="2019-11-14T16:00:59Z" level=info msg="actors: placement order received: lock"
time="2019-11-14T16:00:59Z" level=info msg="actors: placement order received: update"
time="2019-11-14T16:00:59Z" level=info msg="actors: placement tables updated"
time="2019-11-14T16:00:59Z" level=info msg="actors: placement order received: unlock"
```

----

Event API Server Initial Logs:

```
== Sinatra (v2.0.7) has taken the stage on 4242 for development with backup from WEBrick
[2019-11-14 17:52:43] INFO  WEBrick::HTTPServer#start: pid=10 port=4242
127.0.0.1 - - [14/Nov/2019:17:52:43 +0000] "GET /dapr/config HTTP/1.1" 200 2 0.0048
127.0.0.1 - - [14/Nov/2019:17:52:43 UTC] "GET /dapr/config HTTP/1.1" 200 2
- -> /dapr/config
127.0.0.1 - - [14/Nov/2019:17:52:43 +0000] "OPTIONS /transcoder-create HTTP/1.1" 200 15 0.0004
127.0.0.1 - - [14/Nov/2019:17:52:43 UTC] "OPTIONS /transcoder-create HTTP/1.1" 200 15
- -> /transcoder-create
127.0.0.1 - - [14/Nov/2019:17:52:43 +0000] "OPTIONS /transcoder-delete HTTP/1.1" 200 15 0.0003
127.0.0.1 - - [14/Nov/2019:17:52:43 UTC] "OPTIONS /transcoder-delete HTTP/1.1" 200 15
- -> /transcoder-delete
127.0.0.1 - - [14/Nov/2019:17:52:43 +0000] "OPTIONS /transcoder-start HTTP/1.1" 200 15 0.0003
127.0.0.1 - - [14/Nov/2019:17:52:43 UTC] "OPTIONS /transcoder-start HTTP/1.1" 200 15
- -> /transcoder-start
127.0.0.1 - - [14/Nov/2019:17:52:43 +0000] "OPTIONS /transcoder-stop HTTP/1.1" 200 15 0.0003
127.0.0.1 - - [14/Nov/2019:17:52:43 UTC] "OPTIONS /transcoder-stop HTTP/1.1" 200 15
- -> /transcoder-stop
I, [2019-11-14T17:53:05.913721 #10]  INFO -- : Running.
1
```

**Comment by yaron2** [comment]
Hey @jocko-wowza, this is actually the intended behavior, let me explain why:

Input bindings bind an event handler in your code to an external system, in your case, AWS SQS.
That means every binding you have for AWS SQS should get triggered when an event comes in to SQS.

An event might come in from invoking an output binding, or it might be triggered when you manually send a message to SQS without Dapr at all.

If you want to use different event handlers in your code, you can use different queues within SQS, for example, a queue for `transcoder-stop` and `transcoder-start`.

Another way is to have a single input binding, and then inspect the message to understand the context of the operation (stop, delete, start).

**Comment by yaron2** [comment]
Just to illustrate technically:

You have two input bindings listening to queue A from SQS.
You then invoke two output bindings, both sending a message to queue A.

As SQS is a queue based message, a message will be pulled from either bindings, and then execute your code with it.
This is because of the queue based nature of SQS.

**Comment by jocko-wowza** [comment]
@yaron2 -- Okay ... so I thought that when I hit the `/bindings/1.0/bindings/[event-name]` was sending a message to a queue, and then by setting the components like:

In my specific example:
`/bindings/1.0/bindings/transcoder-create`

Then my component declaration is telling my DAPR configuration to direct messages in the `transcoder-create` queue to the `localhost:4242/transcoder-create` endpoint.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "transcoder-stop"
spec:
  type: bindings.aws.sqs
  metadata:
  - name: region
    value: us-west-1
  - name: queueName
    value: [OMITTED]
  - name: accessKey
    value: [OMITTED]
  - name: secretKey
    value: [OMITTED]

```

Please tell me specifically what I'm missing in MY configuration.
