### ISSUE TITLE
dapr.runtime.scheduler transport: Error while dialing: dial tcp: address localhost: missing port in address 

### ISSUE THREAD

**Issue by calvin2021y** [dapr/dapr#7993]
## In what area(s)?

> /area runtime

## What version of Dapr?

1.14.0

## Expected Behavior

expect no error report

## Actual Behavior

get this from dapr cli

```sh
ERRO[0700] failed to watch scheduler jobs, retrying: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address localhost: missing port in address"  app_id=core instance=dapr scope=dapr.runtime.scheduler type=log ver=1.14.0
```

## Steps to Reproduce the Problem

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: testAppConfig
spec:
  metric:
    enabled: false
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "consul:8500"
      selfRegister: true
      checks:
        - name: "Dapr Health Status"
          checkID: "daprHealth:${APP_ID}"
          interval: "19s"
          http: "http://127.0.0.1:3503/v1.0/healthz"
      tags:
        - "dapr"
        - "v1"
      daprPortMetaKey: "DAPR_PORT"
      queryOptions:
        useCache: true
```

```sh
dapr run -c config.yaml -a core --log-level info -P grpc -H 3500 -p 8019 -G 50001  app_path
```
