### ISSUE TITLE
Resiliency in k8s must restart service

### ISSUE THREAD

**Issue by maqueisaprogrammer** [dapr/dapr#8120]
I am using Dapr in K8s，but when i applied resiliency spec in k8s，i must restart my app service otherwise it won't work.
below is what i do to make the resilency spec work.
1. resilency.yaml in namespace tenent1

```
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-ns1
  namespace: tenent1

scopes:
  - refactor-test-app1

spec:
  policies:
    timeouts:
      general: 2s
      important: 30s
      largeResponse: 30s

  targets:
    apps:
      refactor-test-order: 
        timeout: general
```

2.  kubectl apply -f resiliency.yaml
3.  restart  refactor-test-app1 Service

I have two questions about this 
1. is there any solution that can make the resiliency work without restart service 
3. in my k8s, i may put my service to many namespaces, can i make the resilency spec work in all namespaces，from the example above, the resiliency.yaml is targeted to tenent1 namespace，if i have a namespace tenent2, i have to make a new resilency.yaml file and change the namespace to tenent2

can anyone help me, thanks!

**Comment by scosta-kar** [comment]
Did you try the hot reloading feature?
https://docs.dapr.io/operations/components/component-updates/#hot-reloading-preview-feature

**Comment by maqueisaprogrammer** [comment]
> Did you try the hot reloading feature? https://docs.dapr.io/operations/components/component-updates/#hot-reloading-preview-feature

@scosta-kar  thanks , but i tried , the hot reloading feature does not work for me

i do the following steps,
1. modify configuration.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: tenent1
spec:
  features:
    - name: "Component Hot Reloading"
      enabled: true
    - name: "Subscription Hot Reloading"
      enabled: true
```
run command `kubectl apply -f configuration.yaml`

2. restart apps
3. modify resiliency.yaml, timeout.general from 2s to 10s
4. test call AND the daprd logs as belows
time="2024-09-23T10:36:13.369886491Z" level=warning msg="Error processing operation endpoint[refactor-test-order, refactor-test-order:items/100]. Retrying in 2s…" app_id=refactor-test-app1 instance=refactor-test-app1-6895cc7b57-n7qv2 scope=dapr.runtime type=log ver=1.14.2

it seems the timeout value is still 2s NOT 10s, in fact my service will return in 5s, if the resiliency works, the daprd pod should not trigger timeout policy.
