### ISSUE TITLE
Not able to see dapr workflow state in MongoDB

### ISSUE THREAD

**Issue by TonyPythoneer** [dapr/dapr#8129]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

I'm using MongoDB as my actor state store to put my Dapr Workflow there.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-actorstatestore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: connectionString
    value: "..."
  - name: actorStateStore
    value: "true"
```

I tried to see what the records look like, but it shows "Invalid UTF-8 string in BSON document" there.
I wonder if this is an issue or not.

<img width="861" alt="Screenshot 2024-09-20 at 1 49 45 PM" src="https://github.com/user-attachments/assets/1eca067a-ecf8-42c2-a5cb-56e9790dd2ad">
