### ISSUE TITLE
Service Invocation: Provide access lists for inter-service invocation

### ISSUE THREAD

**Issue by amanbha** [dapr/dapr#813]
Service Invocation: Provide allowlists for inter-service invocation

In enterprise environment (think of a non-hostile multi tenant environment), allowlists are needed to allow service invocation from only selected services.

eg. Lets say SvcA, SvcB, SvcC & SvcD are running in a cluster. Currently all services can invoke each other. With an allowlist feature Svc can specify tht I only accept calls from SvcA & SvcB, then SvcD will nto be able to invoke SvcC.

**Comment by yaron2** [comment]
# Design Proposal

## Features

The access control feature will allows developers to:

1. Specify, for a given app, an allowed list of applications that can invoke it. for both HTTP and gRPC enabled apps.
2. Specify, for a given app, which methods may be invoked by the different applications. for both HTTP and gRPC enabled apps.
3. Enable this feature for both Kubernetes and Self-Hosted modes

## Design

The leading design principle here is to keep the design as simple and clear as possible while providing enough flexibility for both protocols.

### Option 1

A new CRD for access control will be created. By default, traffic from all apps in the cluster is allowed. once an `AccessControl` instance is created for an app, the rules defined act as an allowed access list.

#### HTTP

```yaml
apiVersion: dapr.io/v1alpha1
kind: AccessControl
metadata:
  name: app1
spec:
  rules:
  - app: app2
    methods:
    - name: /orders
      httpVerb: GET
    - name: /products/*
      httpVerb: "*"
    trustDomain: default
```

The `AccessControl` instance above declared a set of rules that apply to application with id of `app1`. In this case, one rule is defined. that rule specifies that only `app2` can call `app1`, and specifically allows the invocation of two methods: `/orders` with the `GET` verb, and `/products/*` with all methods.

The `trustDomain` refers to a logical group of trusted applications. On Kubernetes, this stands for the namespace.
If `"*"` is specified as the value, it means applications with the ID of `app2` from all namespaces are allowed.

#### gRPC

```yaml
apiVersion: dapr.io/v1alpha1
kind: AccessControl
metadata:
  name: app1
spec:
  rules:
  - app: app2
    methods:
    - name: Orders
    - name: Products
    trustDomain: default
```

The `AccessControl` instance above declared a set of rules that apply to application with id of `app1`. In this case, one rule is defined. that rule specifies that only `app2` can call `app1`, and specifically allows the invocation of two methods: `Orders` and `Products`.

The `trustDomain` refers to a logical group of trusted applications. On Kubernetes, this stands for the namespace.

protocol specific fields like `httpVerb` from the `HTTP` example will be ignored when used on an app that has its protocol set to gRPC.

### Option 2

Instead of creating a new CRD, the rules will be added to the existing `Configuration` object.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  accessControl:
    rules:
    - app: app2
      methods:
      - name: /orders
        httpVerb: GET
      - name: /products/*
        httpVerb: "*"
      trustDomain: *
```

### Modes

#### Kubernetes

On Kubernetes, the `AccessControl` CRD will be applied to a cluster and configured in every sidecar from the operator, just like components and configurations.

If we choose to add the access control specs to the `Configuration` object, there is no change in behavior.

#### Self-Hosted

In this mode, the file will be read from the components directory along with all other components.

If we choose to add the access control specs to the `Configuration` object, there is no change in behavior.

### Identification

The [SPIFFE](https://spiffe.io/) spec, a CNCF project, defines a specification for generating an ID for an application. this is called a [SPIFFE ID](https://spiffe.io/docs/latest/spiffe/concepts/#spiffe-id), and it determines a well formatted URI format:

```
spiffe://trust domain/workload identifier
``` 

In the case of Dapr, a SPIFFE ID for a Dapr app would look like this:

```
spiffe://default/app1
```

SPIFFE IDs are carried inside a x509 certificate known as an SVID (SPIFFE Verifiable Identity Document).
Dapr's workload certificates mostly match the requirement for [SPIFFE leaf certificates](https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md#31-leaf-certificates), and will be made X509-SVID compatible.

The certificates will then contain the SPIFFE ID, and a server side verification will occur in a post-handshake step to verify the identity of the caller IF access control rules have been applied to the called app.

The reason why verification is made in the server side and not client side is to prevent attacks from malicious actors that are sending requests from inside the cluster and not from or through a Dapr sidecar.

#### Kubernetes

In the example above, `default` is the Kubernetes namespace that acts as the trust domain. In terms of relation to the universal namespace feature, the following is also a valid SPIFFE ID: 

```
spiffe://cluster1/default/app1
``` 

In this example, `cluster1` specifies the external cluster/environment name.

#### Self Hosted

Dapr today supports setting a namespace on the process level. In Kubernetes, a namespace is set automatically. On self hosted mode, it is empty unless set.

It's recommended that we keep parity between the two implementations and fill a default namespace value for self-hosted mode.
The recommended value for a default namespace here is to use the hostname.
