### ISSUE TITLE
Daprd Env Variables from Secrets

### ISSUE THREAD

**Issue by antontroshin** [dapr/dapr#8180]
## In what area(s)?

/area runtime

> /area test-and-release
### Issue:
Today the only Env variables that can be injected into the sidecar pod, are the plain key value (see [here](https://docs.dapr.io/reference/arguments-annotations-overview/#:~:text=not%20supported-,dapr.io/env,-List%20of%20environment)).
Some applications or libraries require the environment variables to include secret values, such as Auth tokens, headers, etc.
This is a suggestion to solve this issue and discuss potential implementation and possible problems with it.

### Solution
Similar to the `dapr.io/env` annotation, add `dapr.io/env-from-secret` annotation.
The values of this annotation are formatted like so:
Single key value secret: `<ENV_VAR_NAME>=<SECRET_NAME>` 
Multi key value secret: `<ENV_VAR_NAME>=<SECRET_NAME>:<SECRET_KEY>`
Since the k8s annotations are limited in size, supporting multi key-value secrets might be considered as optional.
This annotation then will be injected via dapr-injector into the daprd container manifest like so.
```yaml
...
spec:
  containers:
  - name: daprd
    image: docker.io/daprio/daprd:1.13.5
    env:
    - name: <ENV_VAR_NAME>
      valueFrom:
        secretKeyRef:
          name: <SECRET_NAME>
          key: <<SECRET_KEY>
```

Then Env variable can be consumed by Dapr sidecar, component or configuration.

**Comment by antontroshin** [comment]
Due to the restriction of the `secretKeyRef`, `name` field is required (read more [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables), in section "env.valueFrom.secretKeyRef.name"), this makes the single key value secret requires us to have both `name` and `key`. 
Example:
Annotation: `dapr.io/env-from-secret: "HEADERS=auth-headers-secret"`
Will be injected as:
```yaml
    env:
    - name: HEADERS
      valueFrom:
        secretKeyRef:
          name: auth-headers-secret
          key: auth-headers-secret
```
This will require the Secret to have both a name and a key as "auth-headers-secret"
Example secret (for demo purposes only, don't leave secrets in plain text)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-headers-secret
type: Opaque
stringData:
  auth-headers-secret: "AUTH=mykey"
```
