### ISSUE TITLE
Scheduler fails to start when started according to docker compose example in the docs

### ISSUE THREAD

**Issue by thedmi** [dapr/dapr#8207]
## In what area(s)?

/area runtime

## What version of Dapr?

1.14.4

## Expected Behavior

Scheduler service starts sucessfully

## Actual Behavior

Scheduler fails to start with error 

> {"level":"panic","ts":"2024-10-17T14:42:16.805372Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"data/default-dapr-scheduler-server-0/member/snap/db","error":"write data/default-dapr-scheduler-server-0/member/snap/db: no space left on device","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.13/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.13/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.13/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.13/etcdserver/backend.go:76"}

## Steps to Reproduce the Problem

Docker compose:

```yaml
services:
  scheduler:
    image: "daprio/dapr:1.14.4"
    command: ["./scheduler", "--port", "50007"]
    ports:
      - "50007:50007"
    # WARNING - This is a tmpfs volume, your state will not be persisted across restarts
    volumes:
    - type: tmpfs
      target: /data
      tmpfs:
        size: "10000"
```

The above is a snippet from the [official docs](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-using-docker-compose). I copied the sample from there, removed everything but the scheduler and pinned the image version.

With the compose shown above, run `docker compose up scheduler` to reproduce the problem.

## Release Note

RELEASE NOTE:
