### ISSUE TITLE
The message processing speed when using the outbox pattern

### ISSUE THREAD

**Issue by maximus9802** [dapr/dapr#8233]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.14.1

> edge: output of `git describe --dirty`

## Expected Behavior

Improving the message processing speed when using the outbox pattern.

## Actual Behavior

The message processing speed when using the outbox pattern is nearly 1 second per message.
I checked the source code of Dapr and found a 1-second delay when Dapr processes these events. It occurs in the file [outbox.go](https://github.com/dapr/dapr/blob/master/pkg/runtime/pubsub/outbox.go) at line 273.

## Steps to Reproduce the Problem
Step 1: Setup pubsub.yaml and statestore.yaml

pubsub.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: localhost:9092
  - name: authType
    value: none

```

statestore.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: replication-master-data-user-service
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      value: "host=localhost user=postgres password=postgres port=5432 database=outbox"
    - name: outboxPublishPubsub
      value: orderpubsub
    - name: outboxPublishTopic
      value: user-service
```

Step 2: Use a loop to call function executeStateTransaction  of DaprClient in Java SDK.

Here my function use executeStateTransaction of Java SDK

```
  public <T> void publishEventWithOutbox(String daprStore, T object, String id) {
    try {
      ExecuteStateTransactionRequest request = new ExecuteStateTransactionRequest(daprStore);
      State<T> state = new State<>(id, object, null);
      TransactionalStateOperation<T> transactionalStateOperation = new TransactionalStateOperation<>(
          OperationType.UPSERT, state);
      request.setOperations(List.of(transactionalStateOperation));
      client.executeStateTransaction(request).block();
      LogUtil.info("Executed state transaction for object with id: {}", id);
    } catch (Exception e) {
      LogUtil.error("Failed to execute state transaction for object with id: {}", id, e);
      throw e;
    }
  }
```

I use a loop to call my function approximately 1000 times.

```
    messages.forEach(categoryMappingMessage -> {
      try {
        categoryMappingMessage.setReplicationId(uid);
        categoryMappingMessage.setLastUpdated(timestamp);
        daprUtil.publishEventWithOutbox(prefix + service, categoryMappingMessage,
            UUID.randomUUID().toString());
      } catch (Exception e) {
        handlePublishMessageFail(importResult, categoryMappingMessage);
        LogUtil.warn("Publish message to service " + prefix + service + " fail!");
      }
    });
```

Step 3: Check the logs to observe the event processing speed.

After checking the logs, the processing speed is only 1 message per second. Look at the attached image.

![log_outbox](https://github.com/user-attachments/assets/ccb9cb72-2a49-4e9d-93a7-1409dd7247d7)

## Release Note

RELEASE NOTE:

Runtime error when using the Transactional Outbox Pattern
