### ISSUE TITLE
Pods remain idle and fail to join Kafka consumer group during scaling and rebalancing

### ISSUE THREAD

**Issue by anneum** [dapr/dapr#8248]
## In what area(s)?

/area runtime

## What version of Dapr?

1.14.4

## Expected Behavior
When using KEDA to automatically scale a Dapr app on a Kubernetes cluster to subscribe to Apache Kafka, all pods - both new and existing - should join the Kafka consumer group during scaling and rebalancing, and actively participate in consuming messages.

## Actual Behavior

When scaling up the deployment, both new and existing pods sometimes fail to join or rejoin the Kafka consumer group during rebalancing. As a result, some pods (e.g., 2 out of 5) remain idle and do not process any messages. There are no error messages or warnings in the daprd sidecar logs to explain this behavior.

```bash
NAME                                   READY   STATUS    RESTARTS   AGE    IP              NODE  NOMINATED NODE   READINESS GATES
consumer-7669445bff-6gvgf              2/2     Running   0          54m    10.233.67.74    w01   <none>           <none>
consumer-7669445bff-7r7bg              2/2     Running   0          54m    10.233.71.50    w02   <none>           <none>
consumer-7669445bff-9rmsk              2/2     Running   0          54m    10.233.67.83    w01   <none>           <none>
consumer-7669445bff-nj8gg              2/2     Running   0          54m    10.233.79.241   w03   <none>           <none>
consumer-7669445bff-rhqkb              2/2     Running   0          54m    10.233.79.198   w03   <none>           <none>
```

```bash
~$ kubectl -n kafka exec -it kafka-0 -- ./bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group consumer --describe
GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                 HOST            CLIENT-ID
consumer        tests1          1          810094          815770          5676            sarama-3d8c2edf-28c9-4f6f-86c7-574b7057b984 /10.233.71.50   sarama
consumer        tests1          0          15499017        15499017        0               sarama-3d8c2edf-28c9-4f6f-86c7-574b7057b984 /10.233.71.50   sarama
consumer        tests1          3          810583          816315          5732            sarama-3d8c2edf-28c9-4f6f-86c7-574b7057b984 /10.233.71.50   sarama
consumer        tests1          2          815650          815650          0               sarama-3d8c2edf-28c9-4f6f-86c7-574b7057b984 /10.233.71.50   sarama
consumer        tests1          7          814626          816542          1916            sarama-9050d6cf-e8d3-4d27-b6f0-387aad75f999 /10.233.67.74   sarama
consumer        tests1          9          815537          815537          0               sarama-9050d6cf-e8d3-4d27-b6f0-387aad75f999 /10.233.67.74   sarama
consumer        tests1          8          812852          814762          1910            sarama-9050d6cf-e8d3-4d27-b6f0-387aad75f999 /10.233.67.74   sarama
consumer        tests1          5          816473          816473          0               sarama-4bdbe62b-b48b-47f6-bf78-8e21212f3855 /10.233.79.241  sarama
consumer        tests1          4          815806          815807          1               sarama-4bdbe62b-b48b-47f6-bf78-8e21212f3855 /10.233.79.241  sarama
consumer        tests1          6          815878          815878          0               sarama-4bdbe62b-b48b-47f6-bf78-8e21212f3855 /10.233.79.241  sarama
```

## Steps to Reproduce the Problem
1. Set up a Kubernetes cluster running Dapr, with Kafka 3.8 managed by Strimzi.
2. Deploy a Dapr-enabled Kafka subscriber, using the following configurations:

Dapr Kafka Component:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: pipeline
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka-bootstrap.kafka:9092"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "oldest"
  - name: consumeRetryEnabled
    value: true
  - name: maxRetries
    value: "10"
  - name: consumeRetryInterval
    value: "100ms"
```
Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: pipeline
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "consumer"
        dapr.io/app-port: "50051"
        dapr.io/app-protocol: "grpc"
        dapr.io/graceful-shutdown-seconds: "15"
    spec:
      containers:
      - name: consumer
        image: <image_path>
        imagePullPolicy: Always
```

3. Configure KEDA to scale the consumer deployment based on Kafka pub/sub lag.
KEDA ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
  namespace: pipeline
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 15
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 300
  triggers:
  - type: kafka
    metadata:
      topic: tweets
      bootstrapServers: kafka-bootstrap.kafka:9092
      consumerGroup: consumer
      lagThreshold: "60"
```

4. Observe that during scaling and rebalancing, some pods (e.g., 2 out of 5) fail to join or rejoin the Kafka consumer group and remain idle without processing any messages. The daprd sidecar logs contain no errors related to this issue.

## Release Note
RELEASE NOTE: FIX Issue with Kafka consumers remaining idle and not joining the consumer group on scaling and rebalancing.
