### ISSUE TITLE
Adding additional labels for service monitor prometheus or adding to dapr service in automatic sidecar injection 

### ISSUE THREAD

**Issue by aytemuryakup** [dapr/dapr#8275]
Hi,

To monitor Dapr sidecar metrics with the help of prometheus Service Monitor, we use the Selector Labels field.

For Example,

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-dapr-sidecars-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      dapr.io/enabled: 'true'
  endpoints:
    - port: dapr-metrics
      interval: 30s
      path: /
  namespaceSelector:
    matchNames:
      - demo-apps
```
When metrics are opened for more than one service and we want to monitor only specific services, the labels definition must be unique.
But in k8s service that occurs after dapr sidecar injection, it assigns only one label as below.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-service-dapr
  namespace: demo-apps
  labels:
    dapr.io/enabled: 'true'
  annotations:
    dapr.io/app-id: demo-service
    prometheus.io/path: /
    prometheus.io/port: '9090'
    prometheus.io/probe: 'true'
    prometheus.io/scrape: 'true'
```
Can the automatic value assignment with annotations value also be done to the sidecar service-dapr?

**_dapr.io/app-id: demo-service_**
