### ISSUE TITLE
failed to retrieve the initial identity certificate

### ISSUE THREAD

**Issue by nguyentriloi** [dapr/dapr#8320]
## In what area(s)?

when I run kubectl apply -f app.yaml, my dapr container got an error : Fatal error from runtime: failed to retrieve the initial identity certificate: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = failed to get configuration
## What version of Dapr?

1.14.1
## My deployment config: 
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp"
        dapr.io/app-port: "8081"
        dapr.io/config: ""

RELEASE NOTE:

**Comment by Sarthak-Biswas** [comment]
Getting the same error on minikube Dapr deployment.

**Comment by ISAF87** [comment]
Any update regarding this issue?
I am running dapr on a local kubernetes cluster (docker desktop)
After deploying 2 api's using aspire.net I get the following:

kubectl logs checkout-7cdd565b5-fh7ck -c daprd -n dapr-test

```
time="2025-03-18T10:37:06.265214554Z" level=info msg="Starting Dapr Runtime -- version 1.15.3 -- commit c3687714f9592def48b14b8300bf5170fe8a1bff" app_id=checkout-api instance=checkout-7cdd565b5-fh7ck scope=dapr.runtime type=log ver=1.15.3
time="2025-03-18T10:37:06.265277858Z" level=info msg="Log level set to: info" app_id=checkout-api instance=checkout-7cdd565b5-fh7ck scope=dapr.runtime type=log ver=1.15.3
time="2025-03-18T10:37:06.265848989Z" level=info msg="Fetching initial identity certificate" app_id=checkout-api instance=checkout-7cdd565b5-fh7ck scope=dapr.runtime.security type=log ver=1.15.3
time="2025-03-18T10:37:06.279520628Z" level=fatal msg="Fatal error from runtime: failed to retrieve the initial identity certificate: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = failed to get configuration\nno SVID available" app_id=checkout-api instance=checkout-7cdd565b5-fh7ck scope=dapr.runtime type=log ver=1.15.3
```

**Comment by henrikrexed** [comment]
I'm getting the same issue with daps 1.15.4 in gke.
here are the log software the sidecar daprd : 
```
time="2025-04-08T07:29:00.743210982Z" level=info msg="Starting Dapr Runtime -- version 1.15.4 -- commit eb94584f0e14b9fb61d2d139277c2962c1567064" app_id=cart instance=cart-6c5898b856-wwpbs scope=dapr.runtime type=log ver=1.15.4
time="2025-04-08T07:29:00.743241542Z" level=info msg="Log level set to: info" app_id=cart instance=cart-6c5898b856-wwpbs scope=dapr.runtime type=log ver=1.15.4
time="2025-04-08T07:29:00.743763552Z" level=info msg="Fetching initial identity certificate" app_id=cart instance=cart-6c5898b856-wwpbs scope=dapr.runtime.security type=log ver=1.15.4
time="2025-04-08T07:29:00.772980658Z" level=fatal msg="Fatal error from runtime: failed to retrieve the initial identity certificate: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = failed to get configuration\nno SVID available" app_id=cart instance=cart-6c5898b856-wwpbs scope=dapr.runtime type=log ver=1.15.4
```

I have created the following config: 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cart-state-store
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: dedededed
```
and my workload has the right annotation : 
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:

    opentelemetry.io/name: cart
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: cart
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: opentelemetry-demo
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "cart"
    dapr.io/app-port: "8080"
    dapr.io/enable-api-logging: "true"
    dapr.io/config: "cart-state-store"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:

      opentelemetry.io/name: cart
  template:
    metadata:
      labels:

        opentelemetry.io/name: cart
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: cart
        app.kubernetes.io/name: cart

      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "cart"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "cart-state-store"
```
Is it an issue or did I miss something?
