### ISSUE TITLE
Dapr Fails to Initialize AWS Components with LocalStack Due to UnrecognizedClientException

### ISSUE THREAD

**Issue by renatodinizc** [dapr/dapr#8356]
## In what area(s)?

> /area runtime

## What version of Dapr?

CLI version: 1.14.1
Runtime version: 1.14.4

## Expected Behavior

Dapr should authenticate successfully with LocalStack's AWS Parameter Store using the provided dummy credentials (accessKey, secretKey, and sessionToken) and initialize the parameterstore secret store component without errors.

## Actual Behavior

Dapr fails to initialize the parameterstore component and exits with the following error:

```
Fatal error from runtime: process component parameterstore error: [INIT_COMPONENT_FAILURE]: initialization error occurred for parameterstore (secretstores.aws.parameterstore/v1): error validating access to the aws.parameterstore secret store: UnrecognizedClientException: The security token included in the request is invalid.
status code: 400, request id: 4933096e-457b-4268-99b7-6dc844d3faf1
```

This error suggests that Dapr is passing an invalid or incorrectly formatted session token to LocalStack, leading to a failure during the authentication process. This occurs despite valid dummy credentials being used (test, test, dummy-session-token) and the same credentials working without issue via awslocal or the AWS CLI.

## Steps to Reproduce the Problem

1. **Set Up LocalStack**:
   - Start LocalStack with the `ssm` service enabled.
   ```yaml
   services:
     localstack:
       image: localstack/localstack
       ports:
         - "4566:4566"
       environment:
         - SERVICES=ssm
   ```

2. **Add a Secret to LocalStack**:
   - Add a test parameter to LocalStack’s AWS Parameter Store using `awslocal`:
   ```bash
   awslocal ssm put-parameter --name "fruit" --value "banana" --type String
   ```

3. **Create a Dapr Component**:
   - Add the following YAML configuration for the `parameterstore` component:
   ```yaml
   apiVersion: dapr.io/v1alpha1
   kind: Component
   metadata:
     name: parameterstore
     namespace: default
   spec:
     type: secretstores.aws.parameterstore
     version: v1
     metadata:
     - name: region
       value: us-east-1
     - name: accessKey
       value: test
     - name: secretKey
       value: test
     - name: sessionToken
       value: dummy-session-token
     - name: endpoint
       value: http://localstack-main:4566 # tried with localhost, docker-internal and other variations as well
   auth:
     secretStore: ""
   ```

4. **Run Dapr**:
   - Start Dapr with the component configuration:
   ```bash
   dapr run --app-id myapp --resources-path ./components --log-level debug
   ```

5. **Observe the Error**:
   - The Dapr runtime fails to initialize the `parameterstore` component, exiting with the following error:
   ```
   [INIT_COMPONENT_FAILURE]: initialization error occurred for parameterstore (secretstores.aws.parameterstore/v1): error validating access to the aws.parameterstore secret store: UnrecognizedClientException: The security token included in the request is invalid.
   ```

6. **Test Credentials Outside Dapr**:
   - Using the same credentials, test the `ssm` service directly with `awslocal` to confirm that they work:
   ```bash
   AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_SESSION_TOKEN=dummy-session-token \
   awslocal ssm get-parameter --name "fruit"
   ```

   - This command works without issues, returning the parameter successfully.
