### ISSUE TITLE
Connect to google managed kafka from dapr running in GKE 

### ISSUE THREAD

**Issue by Naresh-cwx** [dapr/dapr#8357]
- I have a GKE cluster running and and have installed dapr-crds and dapr
- Have created the dapr component and dapr config 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "<actual-bootstrap-url>"
  - name: authRequired
    value: "true"
  - name: authType
    value: "oidc"
  - name: saslMechanism
    value: "OAUTHBEARER"
  - name: saslLoginCallbackHandlerClass
    value: "com.google.cloud.hosted.kafka.auth.GcpLoginCallbackHandler"
  - name: saslJaasConfig
    value: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;"
  - name: authType
    value: "oidc"
  - name: clientId
    value: "<service-account-clientid>"
  - name: tokenEndpoint
    value: "https://oauth2.googleapis.com/token"
```

I have a service account created with `kafka.admin`
- I have used the official dapr documentation to generate a sample app and create it's deployment with following annotations 
```
annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "myservice"
```
    
Also implemented KSA for same
Still unable to get the sidecar injector for dapr into the application pod ( using above deployment )

- The use-case is to connect to kafka cluster using Dapr in GCP

**Comment by FirePing32** [comment]
Does your pod have these annotations?
```yaml
dapr.io/enabled: "true"
dapr.io/app-id: "my-app"   # This app ID should be in the allowed scopes in the Subscription component
dapr.io/app-port: "3001"
```
App port should be the port your main application is listening on.

**Comment by Naresh-cwx** [comment]
> Does your pod have these annotations?
> 
> ```yaml
> dapr.io/enabled: "true"
> dapr.io/app-id: "my-app"   # This app ID should be present in the allowed scopes in the Subscription component
> dapr.io/app-port: "3001"
> ```
> 
> App port should be the port your main application is listening on.

Yes, passing the `dapr.io/app-port` help me get the `daprd` but getting some error in daprd

`Fatal error from runtime: process component kafka-pubsub error: [INIT_COMPONENT_FAILURE]: initialization error occurred for kafka-pubsub (pubsub.kafka/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for kafka-pubsub (pubsub.kafka/v1): kafka: client has run out of available brokers to talk to: kafka server: SASL Authentication failed: Authentication failed: credentials for user could not be verified\nfailed to load declarative subscriptions: rpc error: code = Canceled desc = context canceled" app_id=kafka-app instance=kafka-app-6995596cdd-hq5tg scope=dapr.runtime type=log ver=1.14.4`

The updated component file is 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "<google managed kafka bootstrap url>"
    - name: authRequired
      value: "true"
    - name: authType
      value: "password"
    - name: saslMechanism
      value: "PLAINTEXT" # also tried "SHA-512"
    - name: saslUsername
      value: "<iam-service-account-email>"
    - name: saslPassword
      secretKeyRef:
        name: kafka-auth # k8s secrets
        key: password # key containing base64 encoded json for iam service account
```

The iam service account used in above configuration have `roles/managedkafka.admin`

Didn't the the context for subscription component, not sure if that's creating this issue
