### ISSUE TITLE
How to use Dead Letter Topics with Redis and a multi app setup

### ISSUE THREAD

**Issue by richaswr** [dapr/dapr#8368]
Hi all, I have an app suite containing a dotnet API and a Python application. We use Dapr of course and this works nicely for the most part. Locally we use Redis.

We want to start using dead letter topics, however, when I change my programmatic declaration to include a dead letter topic name like so:

```
@app.get("/dapr/subscribe")
def read_items():
    items = [
        {
            "pubsubname": settings.PUBSUB_NAME,
            "topic": settings.PUBSUB_TOPIC,
            "deadLetterTopic": settings.PUBSUB_DEADLETTER_TOPIC,
            "routes": {
                "rules": [
                    {
                        "match": 'event.type == "MessageValidatedEvent"',
                        "path": "/api/v1/processEvent",
                    }
                ]
            }
        }
    ]
    return items
```

The redis component is set up as follows:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redeliverInterval
    value: "0"
```

Once an initial event comes in, it immediately goes into the dead letter topic, or at least, my handler for the dead letter topic in the dotnet app is called upon. What's strange is that there are no errors that I can see and the regular application flow continues successfully. Here is my handler, which is in an ASP Core controller:
```
[Route("api")]
[ApiController]
public class FailureController() : ControllerBase
{
    [HttpPost]
    [Route("failure/handle")]
    [AuthorizeInternal]
    [Topic(PubsubConsts.Name, PubsubConsts.DeadLetterTopic)]
    public async Task<Result> HandleFailureAsync(JsonDocument @event)
    {
           // code omitted        
           return Result.Success();
    }
}
```
I'm very confused at why this is happening. I thought it might be Redis, but I also tried RabbitMQ and got the same behaviour. It's as if there's an exception somewhere that is swallowed, or perhaps a message that isn't acknowledged, causing Dapr to fire the message off to the dead letter topic. I have extended logging in the dotnet side but have seen nothing of note.

Has anyone experienced this before or have some suggestions?
