### ISSUE TITLE
Helm chart validation fails due to missing dependencies in `Chart.yaml`

### ISSUE THREAD

**Issue by stucki-stuck** [dapr/dapr#8420]
## In what area(s)?

> /area runtime

> /area operator

> /area placement

## What version of Dapr?

latest helm chart

## Expected Behavior

When running `helm lint dapr`, the command should pass without errors or missing dependencies. All required sub-charts and metadata should be properly included in the Helm chart

## Actual Behavior

Running `helm lint dapr` produces the following error message:

```bash
==> Linting dapr
[INFO] Chart.yaml: icon is recommended
[ERROR] /home/stucki/stucki/tests-perso/helm/dapr/dapr: chart metadata is missing these dependencies: dapr_placement,dapr_rbac,dapr_scheduler,dapr_sentry,dapr_sidecar_injector,dapr_config,dapr_operator
```

## Steps to Reproduce the Problem

Fetch the Dapr Helm chart:

```bash
helm fetch dapr/dapr --untar
```

Run Helm lint:

```bash
helm lint dapr
```

## Modifications to Apply

Currently, in the `Chart.yaml` file, the content is:

```yaml
apiVersion: v1
appVersion: 1.14.4
description: A Helm chart for Dapr on Kubernetes
name: dapr
version: 1.14.4
```
It should be replaced with:
```yaml
apiVersion: v2
appVersion: 1.14.4
description: A Helm chart for Dapr on Kubernetes
name: dapr
version: 1.14.4
dependencies:
  - name: dapr_config
    version: 1.14.4
  - name: dapr_operator
    version: 1.14.4
  - name: dapr_placement
    version: 1.14.4
  - name: dapr_rbac
    version: 1.14.4
  - name: dapr_scheduler
    version: 1.14.4
  - name: dapr_sentry
    version: 1.14.4
  - name: dapr_sidecar_injector
    version: 1.14.4
```

### Explanation
The `apiVersion` must be updated to `v2` because `Helm 3` is being used. Reference: [Helm Documentation on API Version](https://helm.sh/docs/topics/charts/#the-apiversion-field).
The list of `dependencies` must be added to the `Chart.yaml` file to ensure all required sub-charts are included.
With these two modifications, the output of helm lint becomes:

```bash
==> Linting dapr
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```
(And, it might also be helpful to include a link to the Dapr icon)

I’m not entirely sure where to modify the chart and the GitHub Actions to submit a PR with these changes. If you have any suggestions to help me patch this, I’d greatly appreciate it!

## Why is it important to patch this?
The issue lies in the fact that helm lint is used by multiple tools to validate user-provided values.yaml files against the chart’s JSON schema. This includes tools like Helmfile and Terraform, as highlighted in this Stack Overflow discussion: [Helm chart metadata dependency issue with Dapr](https://stackoverflow.com/questions/76641343/helm-chart-metadata-dependency-issue-with-dapr).

Without these fixes, users (and I) relying on such tools may encounter validation errors, making it harder to integrate and manage the Dapr Helm chart in automated workflows
