### ISSUE TITLE
Dapr Runtime Not Emitting Traces

### ISSUE THREAD

**Issue by sleom** [dapr/dapr#8467]
## In what area(s)?

 /area runtime

## What version of Dapr?

 1.14.x

## Expected Behavior

Traces should be emitted for any operation performed by the Dapr runtime. For example, traces should be generated when using pubsub to send/receive messages from a queue.

## Actual Behavior

 No traces are being emitted for operations performed by the Dapr runtime.

## Steps to Reproduce the Problem

1. Configure Dapr runtime with tracing enabled.
2. Perform operations such as sending/receiving messages using pubsub.
3. Observe that no traces are emitted.

### Configuration:

Dapr version: 1.14.X
Environment: Kubernetes, Docker Compose. 
Tracing configuration:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://zipkin:9411/api/v2/spans
```

## Additional Context:

- Versions 1.13.X work as expected, indicating that the issue might be introduced in later versions.
- Both Zipkin and OpenTelemetry tracing exhibit the same behavior.

## Release Note

RELEASE NOTE: **FIX** Bug in runtime.
