### ISSUE TITLE
Setting CloudEvent metadata in BulkPublish does not work

### ISSUE THREAD

**Issue by fvanzee** [dapr/dapr#8523]
## In what area(s)?

runtime

## What version of Dapr?

Seen on both:
- 1.14.4
- 1.15.0-rc16 

## Expected Behavior

When providing metadata on the `publish/bulk` API, I expect all the messages published to the topic to apply this metadata. Especially for the `cloudevent.*` keys. 

## Actual Behavior

Metadata doesn't seems to be applied and cloudevent transformations do not work.

## Steps to Reproduce the Problem

Slight changes to docker-compose.yml for the `hello-docker-compose` sample
- Map port `3500` on `pythonapp` container to expose dapr sidecar API on localhost.
- Using `redis-stack` container to easily debug published messages using RedisInsight on `localhost:8001` 

```yaml
version: '3'
services:
  nodeapp:
    build: ./node
    ports:
      - "50002:50002"
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
  nodeapp-dapr:
    image: "daprio/daprd:1.15.0-rc.16"
    command: ["./daprd",
     "-app-id", "nodeapp",
     "-app-port", "3000",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp"
  pythonapp:
    build: ./python
    depends_on:
      - redis
      - placement
    ports:
      - "3500:3500"
    networks:
      - hello-dapr
  pythonapp-dapr:
    image: "daprio/daprd:1.15.0-rc.16"
    command: ["./daprd",
    "-app-id", "pythonapp",
    "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - pythonapp
    network_mode: "service:pythonapp"
  placement:
    image: "daprio/dapr:1.15.0-rc.16"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    environment:
    - DEBUG=ioredis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - hello-dapr
networks:
    hello-dapr:
```

Using the following `.http` file
```http
@host = http://localhost:3500
###

POST {{ host }}/v1.0-alpha1/publish/bulk/pubsub/test-events?metadata.cloudevent.type=testevent
Content-Type: application/json'

[
  {
      "entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002",
      "event":  "first text message",
      "contentType": "text/plain"
  },
  {
      "entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002",
      "event":  {
          "message": "second JSON message"   
      },
      "contentType": "application/json"
  }
]
```
1. Run `docker compose` and execute the request from the `http` file.
2. Note the event's `type` field is still set to `com.dapr.event.sent`

## Release Note

RELEASE NOTE: **FIX** Apply metadata to events when using bulk publish
