### ISSUE TITLE
Mongodb state store with azure cosmos mongodb mode

### ISSUE THREAD

**Issue by FWorren** [dapr/dapr#8535]
We have configured a state.mongodb state store in dapr like this:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: namespace
  name: mongodb
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      secretKeyRef:
        name: mongodb-url
        key: mongodb-url
    - name: username
      secretKeyRef:
        name: mongodb-username
        key: mongodb-username
    - name: password
      secretKeyRef:
        name: mongodb-key
        key: mongodb-key
    - name: databaseName
      value: "mongodb"
    - name: collectionName
      value: "mongodb"
    - name: operationTimeout
      value: "60s"
auth:
  secretStore: keyvault
scopes:
  - mongodb
```
The mongodb is a cosmos db in azure. The dapr sidecar is now crashing with the following exception:
```json
{"app_id":"mongodb","instance":"mongodb-7b47dd5f6d-kstfz","level":"fatal","msg":"Fatal error from runtime: process component mongodb error: [INIT_COMPONENT_FAILURE]: initialization error occurred for mongodb (state.mongodb/v1): init timeout for component mongodb (state.mongodb/v1) exceeded after 5s\nfailed to load declarative subscriptions: rpc error: code = Canceled desc = context canceled","scope":"dapr.runtime","time":"2025-02-27T08:14:32.614011732Z","type":"log","ver":"1.14.4"}
```
Are we missing some configuration to get this to work?
What does the error message failed to load declarative subscription mean?
Also the operationtimeout has no effect, it still timeout after the default value 5 s.
