### ISSUE TITLE
Duplicated property `actorstatestore` is not detected

### ISSUE THREAD

**Issue by AlbertoVPersonal** [dapr/dapr#8540]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.13.4

## Expected Behavior

`dapr` should not start the sidecar.

## Actual Behavior

`dapr` starts the process and you think it is running but it is not.

## Steps to Reproduce the Problem

1. Create a file called `state.in-memory.yaml`.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state.in-memory
spec:
  type: state.in-memory
  version: v1
  metadata: 
  - name: actorStateStore
    value: "true"
```

2. Create a file called `state.mongodb.yaml`.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state.mongodb
spec:
  type: state.in-memory
  version: v1
  metadata: 
  - name: actorStateStore
    value: "true"
```

3. Start a process using `dapr run` including these files in the command line.

## Release Note

RELEASE NOTE: **FIX** Bug in runtime with the duplicated property `actorstatestore`.
