### ISSUE TITLE
Unable to connect to local Azure Table Storage emulator

### ISSUE THREAD

**Issue by atrauzzi** [dapr/dapr#8554]
Running an emulator locally, when I try to point to it with the following configuration:

```yaml
apiVersion: "dapr.io/v1alpha1"
kind: "Component"
metadata:
  name: "blablablabla"
spec:
  type: "state.azure.tablestorage"
  version: "v1"
  metadata:
    - name: "serviceURL"
      value: "http://localhost:10002"
    - name: "accountName"
      value: "devstoreaccount1"
    - name: "tableName"
      value: "blablabla"
```

I end up seeing this in my logs:

```
authenticated requests are not permitted for non TLS protected (https) endpoints
```

Normally when configuring storage, there's a connection string and some ability to provide `UseDevelopmentStorage=true`.  But I don't see how I can do this correctly with the Azure Table Storage state binding.

**Comment by mtaghavi2005** [comment]
Please check the following configuration. It is working properly on my machine.

CLI version: 1.15.0 
Runtime version: 1.15.2

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-table-store
spec:
  type: state.azure.tablestorage
  metadata:
    - name: accountName
      value: devstoreaccount1
    - name: accountKey
      value: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    - name: serviceURL
      value: http://127.0.0.1:10002/devstoreaccount1
    - name: tableName
      value: Table1
```

You can find more information here:

[Connect to the Emulator Account](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-shortcut)
