### ISSUE TITLE
Azure Storage Queues with private endpoints does not work

### ISSUE THREAD

**Issue by rpaiAveva** [dapr/dapr#8579]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
1.14.2

## Expected Behavior
Dapr component to Azure storage account queue should allow to queue and dequeue messages. 
Azure storage account has public network access disabled and is setup with a private endpoint for the queue. 
Workload identity is used for authentication. 

Dapr component to Azure storage account queue works with workload identity when Azure storage account has public network access enabled.

``` 
daprResources:
  - component:
     apiVersion: dapr.io/v1alpha1
     name: "TestStorageQueueInputBinding"
     spec:
       type: bindings.azure.storagequeues
       version: v1
       metadata:
         - name: accountName           
           value: "storageAccountName"                  
         - name: azureClientId
           value: "Client Id of Managed  Identity"         
         - name: queueName
           value: "storageAccountQueueName"
         - name: direction 
           value: "output"
         - name: decodeBase64
           value: "true"
         - name: ttlInSeconds
           value: "600"
     scopes:
       - daprIdOfPodsSidecar

```
## Actual Behavior

The above binding causes dapr sidecar to go into crashloopbackoff with error 

"level=error msg="Failed to init component TestStorageQueueInputBinding(bindings.azure.storagequeues/v1): init timeout for component TestStorageQueueInputBinding(bindings.azure.storagequeues/v1) exceeded after 5s" app_id=daprIdOfPodsSidecar instance=... scope=dapr.runtime.processor type=log ver=1.14.2                

level=warning msg="Error processing component, daprd will exit gracefully: process component TestStorageQueueInputBinding error: [INIT_COMPONENT_FAILURE]: initialization error occurred for TestStorageQueueInputBinding (bindings.azure.storagequeues/v1): init timeout for component TestStorageQueueInputBinding (bindings.azure.storagequeues/v1) exceeded after 5s" app_id=  daprIdOfPodsSidecar  instance=... scope=dapr.runtime.processor type=log ver=1.14.2"       

## Steps to Reproduce the Problem
Disable public network access on the Azure storage account and create Private Endpoint Connection with Queue as target sub-resource and Network policy for private endpoints(disabled)
