### ISSUE TITLE
Message Outbox doesn't work with Cosmos

### ISSUE THREAD

**Issue by amolenk** [dapr/dapr#8587]
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.15.3

## Expected Behavior

I’ve tested message outbox with CosmosDB using an example that @yaron2 posted in https://github.com/dapr/samples/issues/221:

```javascript
import express from 'express';
import bodyParser from 'body-parser';

const APP_PORT = process.env.APP_PORT ?? '3000';

const app = express();
app.use(bodyParser.json({ type: 'application/*+json' }));

app.get('/dapr/subscribe', (_req, res) => {
    res.json([
        {
            pubsubname: "orderpubsub",
            topic: "orders",
            route: "orders"
        }
    ]);
});

app.post('/orders', (req, res) => {
    console.log("order received:", req.body.data);
    res.sendStatus(200);
});

app.listen(APP_PORT);
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: keyPrefix
    value: none
  - name: url
    value: https://.......documents.azure.com:443/
  - name: masterKey
    value: "........"
  - name: database
    value: admitto
  - name: collection
    value: core
  - name: outboxPublishPubsub
    value: "orderpubsub"
  - name: outboxPublishTopic
    value: "orders"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
spec:
  type: pubsub.in-memory
  version: v1
  metadata: []
```

I run the app with a Dapr sidecar:
```
dapr run --app-id ordersapp --dapr-http-port 3500 --app-port 3000 --resources-path ./components --log-level debug -- node app.js
```

And then add an item to the state store
```
POST http://localhost:3500/v1.0/state/statestore/transaction?metadata.partitionKey=foo

{
  "operations": [
    {
      "operation": "upsert",
      "request": {
        "key": "order1",
        "value": {
            "orderId": "7hf8374s",
            "type": "book",
            "name": "assasin's apprentice"
        }
    }
    }
  ]
}
```

I expect the app to receive the order via the outbox mechanism and write it to the log:

```
== APP == order received:...
```

## Actual Behavior

When I send the request, I don’t receive the event. The only logging I get is:

```
DEBU[0005] #operations=2,partitionkey=foo                app_id=ordersapp component="cosmos (state.azure.cosmosdb/v1)" instance=SANDERM01.localdomain scope=dapr.contrib type=log ver=1.15.3
DEBU[0005] Operation 0 completed with status code 201    app_id=ordersapp component="cosmos (state.azure.cosmosdb/v1)" instance=SANDERM01.localdomain scope=dapr.contrib type=log ver=1.15.3
DEBU[0005] Operation 1 completed with status code 201    app_id=ordersapp component="cosmos (state.azure.cosmosdb/v1)" instance=SANDERM01.localdomain scope=dapr.contrib type=log ver=1.15.3
```

### Using another state store

I also tested using SQLite:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.sqlite
  version: v1
  metadata:
  - name: connectionString
    value: "data.db"
  - name: outboxPublishPubsub
    value: "orderpubsub"
  - name: outboxPublishTopic
    value: "orders"
```

In this case, I do receive the order via pub/sub 🎉:

```
== APP == order received: map[name:assasin's apprentice orderId:7hf8374s type:book]
DEBU[0004] skipping status check due to error parsing result from pub/sub event outbox-c8b3de7f-6e19-43b0-a044-247b4a10a001: invalid character 'O' looking for beginning of value  app_id=ordersapp instance=SANDERM01.localdomain scope=dapr.runtime.processor.pubsub.subscription type=log ver=1.15.3
```

However, there’s also a parse result ‘error’ in the debug log. Also, when I send the request a second time, I don’t get any response. The HTTP request simply hangs without the sidecar responding 😕. Any idea what’s going on here?

## Release Note

RELEASE NOTE:
