### ISSUE TITLE
dapr gprc connection lost when pod rolling update in kubernetes

### ISSUE THREAD

**Issue by cataglyphis** [dapr/dapr#8602]
dapr version: 1.13.5

Below picture is the topology of our services in Kubernetes. When we update `Pod B`, `Pod A` has lots of error message like below, seems like `Pod A` still use grpc connection to `Pod B`.

`Pod B` dapr sidecar has annotation `graceful-shutdown-seconds`, and container b has `preStop` probe.

```
dapr.io/graceful-shutdown-seconds: "25"

...

lifecycle:
  preStop:
    exec:
      command:
      - sh
      - -c
      - sleep 16

...

terminationGracePeriodSeconds: 30
```

```
rpc client unary retry. Err:rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing: dial tcp 10.110.0.2:50002: connect: connection refused" retry:2
```

Our question is how to avoid such problem when deployment rolling update?

![Image](https://github.com/user-attachments/assets/509cda80-8bc3-4841-a284-2b6e9e03ae2e)
