### ISSUE TITLE
Not able to run the `scheduler` container image with Docker locally

### ISSUE THREAD

**Issue by mathieu-benoit** [dapr/dapr#8604]
I'm following this guide https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-using-docker-compose to run the `scheduler`, but the container is not starting, with this errors in the logs:
```none
level=fatal msg="Fatal error running scheduler: failed to create data dir: mkdir data/default-dapr-scheduler-server-0: permission denied\nfailed to serve: grpc: the server has been stopped" instance=7e97385035a1 scope=dapr.scheduler type=log ver=1.15.3
```

Here is what I do:
```yaml
name: test
services:
    scheduler:
        command:
            - ./scheduler
            - --port
            - "50007"
        image: daprio/dapr
        ports:
            - target: 50007
              published: "50007"
        volumes:
            - type: tmpfs
              target: /data
              tmpfs:
                size: "128"
```

```bash
$ docker inspect 7e97385035a1 --format '{{ json .Mounts }}'
[{"Type":"tmpfs","Source":"","Destination":"/data","Mode":"","RW":true,"Propagation":""}]
```

What am I missing?

Notes:
- I also tried with the `daprio/scheduler` container image, same error.
- Running this from GitHub Codespace: `Linux codespaces-cee837 6.8.0-1021-azure #25~22.04.1-Ubuntu SMP Thu Jan 16 21:37:09 UTC 2025 x86_64 GNU/Linux`
- All the other containers are running successfully: my own workloads, `placement`, `daprd`.

**Comment by mathieu-benoit** [comment]
JFYI, I also tried:
```
name: test
services:
    scheduler:
        command:
            - ./scheduler
            - --port
            - "50007"
        image: daprio/dapr
        ports:
            - target: 50007
              published: "50007"
        volumes:
            - type: tmpfs
              target: /data
              tmpfs:
                size: "1024"
                mode: 0177
```
Note: `uid` is not supported apparently, even if documented [here](https://docs.docker.com/engine/storage/tmpfs/#options-for---tmpfs)...

And my actual error is:
```
{"level":"panic","ts":"2025-03-21T20:27:02.073781Z","caller":"backend/backend.go:201","msg":"failed to open database","path":"data/default-dapr-scheduler-server-0/dapr-0.1/member/snap/db","error":"write data/default-dapr-scheduler-server-0/dapr-0.1/member/snap/db: no space left on device","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:201\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:165\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:76"}
time="2025-03-21T20:27:02.073784465Z" level=info msg="Running gRPC server on port 50007" instance=4a973255539b scope=dapr.scheduler.server type=log ver=1.15.3
panic: failed to open database

goroutine 128 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x0?, {0x0?, 0x0?, 0xc000487a60?})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0006bc1a0, {0xc0000fab00, 0x2, 0x2})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
go.uber.org/zap.(*Logger).Panic(0xc0003f25c0?, {0x21e75d9?, 0x180?}, {0xc0000fab00, 0x2, 0x2})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x51
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0003f25c0, 0x3c}, 0x2faf080, 0x1388, {0x21c85e0, 0x7}, 0x8c717661c6f40000, 0xc0004bf780, 0x0, 0x0, ...})
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:201 +0x334
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:165
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x21e560b, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc000464bd0, 0x1, 0x1}, {0xc000464ea0, ...}, ...}, ...)
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:55 +0x378
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:76 +0x58
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend in goroutine 155
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:75 +0x15a
```

I also tried this with `volume` instead of `tmpfs`:
```
name: test
services:
    scheduler:
        command:
            - ./scheduler
            - --port
            - "50007"
        image: daprio/dapr
        ports:
            - target: 50007
              published: "50007"
        volumes:
            - type: volume
              source: scheduler-data
              target: /data
volumes:
    scheduler-data:
        name: scheduler-data
        driver: local
```

But getting this error:
```
time="2025-03-21T20:28:06.499147586Z" level=fatal msg="Fatal error running scheduler: failed to create data dir: mkdir data/default-dapr-scheduler-server-0: permission denied" instance=4b0de4ebef50 scope=dapr.scheduler type=log ver=1.15.3
```

**Comment by mathieu-benoit** [comment]
Just tried with:
```yaml
name: test
services:
    scheduler:
        command:
            - ./scheduler
            - --port
            - "50007"
            - --etcd-data-dir
            - /data
        image: ghcr.io/dapr/scheduler:latest
        ports:
            - target: 50007
              published: "50007"
        user: root
        volumes:
            - type: tmpfs
              target: /data
              tmpfs:
                size: "1024"
```
But still `panic: failed to open database` error:
```
time="2025-03-25T15:29:37.304784507Z" level=info msg="Data dir contents removed: /data/default-dapr-scheduler-server-0/dapr-0.1" instance=2c86e9115f31 scope=dapr.scheduler.server.etcd type=log ver=1.15.3
{"level":"info","ts":"2025-03-25T15:29:37.304971Z","caller":"embed/etcd.go:128","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
{"level":"info","ts":"2025-03-25T15:29:37.306251Z","caller":"embed/etcd.go:136","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2379"]}
{"level":"info","ts":"2025-03-25T15:29:37.306331Z","caller":"embed/etcd.go:311","msg":"starting an etcd server","etcd-version":"3.5.16","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.23.6","go-os":"linux","go-arch":"amd64","max-cpu-set":2,"max-cpu-available":2,"member-initialized":false,"name":"dapr-scheduler-server-0","data-dir":"/data/default-dapr-scheduler-server-0/dapr-0.1","wal-dir":"","wal-dir-dedicated":"","member-dir":"/data/default-dapr-scheduler-server-0/dapr-0.1/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":false,"snapshot-count":10000,"max-wals":10,"max-snapshots":10,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://127.0.0.1:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"dapr-scheduler-server-0=http://localhost:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-backend-bytes":9200000000000000000,"max-request-bytes":2147483647,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"periodic","auto-compaction-retention":"10m0s","auto-compaction-interval":"10m0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"warn","ts":"2025-03-25T15:29:37.306383Z","caller":"etcdserver/server.go:344","msg":"exceeded recommended request limit","max-request-bytes":2147483647,"max-request-size":"2.1 GB","recommended-request-bytes":10485760,"recommended-request-size":"10 MB"}
{"level":"info","ts":"2025-03-25T15:29:37.306744Z","caller":"etcdserver/backend.go:38","msg":"setting backend batch limit","batch limit":5000}
{"level":"info","ts":"2025-03-25T15:29:37.307130Z","caller":"etcdserver/backend.go:44","msg":"setting backend batch interval","batch interval":"50ms"}
{"level":"panic","ts":"2025-03-25T15:29:37.307201Z","caller":"backend/backend.go:201","msg":"failed to open database","path":"/data/default-dapr-scheduler-server-0/dapr-0.1/member/snap/db","error":"write /data/default-dapr-scheduler-server-0/dapr-0.1/member/snap/db: no space left on device","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:201\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:165\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\t/home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:76"}
panic: failed to open database

goroutine 155 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x0?, {0x0?, 0x0?, 0xc00057c1a0?})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000489860, {0xc000413680, 0x2, 0x2})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
go.uber.org/zap.(*Logger).Panic(0xc0002befc0?, {0x21e75d9?, 0x180?}, {0xc000413680, 0x2, 0x2})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x51
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0002befc0, 0x3d}, 0x2faf080, 0x1388, {0x21c85e0, 0x7}, 0x8c717661c6f40000, 0xc000413280, 0x0, 0x0, ...})
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:201 +0x334
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/mvcc/backend/backend.go:165
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x21e560b, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc0000b0a20, 0x1, 0x1}, {0xc0000b0cf0, ...}, ...}, ...)
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:55 +0x378
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:76 +0x58
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend in goroutine 149
        /home/runner/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.16/etcdserver/backend.go:75 +0x15a
```

**Comment by JoshVanL** [comment]
@mathieu-benoit please try the following

```yaml
name: test
services:
  scheduler:
    command:
      - ./scheduler
      - --port
      - "50007"
      - --etcd-data-dir
      - /data
    image: ghcr.io/dapr/scheduler:latest
    ports:
      - target: 50007
        published: "50007"
    user: root
    volumes:
    - "./dapr-etcd-data/:/data"
```
