### ISSUE TITLE
Add support for ServiceAccount annotations in dapr_rbac chart to enable IRSA on EKS

### ISSUE THREAD

**Issue by osouzaelias** [dapr/dapr#8614]
## In what area(s)?

> /area operator  
> /area placement  
> /area test-and-release  

## Describe the feature

When deploying Dapr on **Amazon EKS** using the official Helm chart, it's currently **not possible** to specify custom annotations on the Kubernetes `ServiceAccount` resources created by the `dapr_rbac` subchart. This limitation prevents the use of **IAM Roles for Service Accounts (IRSA)** — the standard mechanism on EKS to assign AWS IAM permissions to pods.

This annotation is required to bind an IAM Role to a pod using IRSA.

### Proposed Solution

Allow annotations for each component’s `ServiceAccount` to be configured via `values.yaml`, like so:

```yaml
serviceAccount:
  operator:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/operator-role
  injector:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/injector-role
  placement:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/placement-role
  scheduler:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/scheduler-role
  sentry:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/sentry-role
```

The following templates in `dapr_rbac` should be updated:

- `templates/operator.yaml`
- `templates/injector.yaml`
- `templates/placement.yaml`
- `templates/scheduler.yaml`
- `templates/sentry.yaml`

Each template should read annotations like this:

```yaml
metadata:
  annotations:
    {{- with .Values.serviceAccount.<component>.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
```

## Business Value

This allows a native and secure way to run Dapr components on EKS with granular IAM permissions per component, using IRSA. It removes the need for workarounds like `kube2iam` or external patching of the `ServiceAccount`s after installation.

## Release Note

RELEASE NOTE: **ADD** Support for configuring ServiceAccount annotations in Helm chart (`dapr_rbac`) to enable IRSA usage on Amazon EKS.
