### ISSUE TITLE
Configuration CRD mtls required fields

### ISSUE THREAD

**Issue by artyom-p** [dapr/dapr#8716]
## In what area(s)?

/area operator

## What version of Dapr?

> 1.15.4

## Expected Behavior

Our DAPR installation is configured not to use mtls:

dapr helm chart values:

```yaml
mtls:
  enabled: false
```

Dapr configuration CRD also has the same flag:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: my-dapr-config
spec:
  mtls:
    enabled: false
```

Expected - no mtls configuration.

## Actual Behavior

After upgrading to 1.15 I see that CRD definition for Configuration changed, and now two more fields are defined as required.

```yaml
 mtls:
  description: MTLSSpec defines mTLS configuration.
  properties:
    allowedClockSkew:
      type: string
    controlPlaneTrustDomain:
      type: string
    enabled:
      type: boolean
    sentryAddress:
      type: string
    ...
    workloadCertTTL:
      type: string
  required:
  - controlPlaneTrustDomain
  - enabled
  - sentryAddress
  type: object
```

We are not able to create configuration without specifying those required fields:

```
dry-run failed (Invalid): Configuration.dapr.io "notification-geta-api-config" is invalid: [spec.mtls.controlPlaneTrustDomain: Required value, spec.mtls.sentryAddress: Required value]
```

Is it by design that sentryAddress and controlPlaneTrustDomain need to be specified even if mtls is set to false?
