### ISSUE TITLE
HTTP Path matching metrics: match substring of path not entire path

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/dapr#8745]
## In what area(s)?

> /area runtime

## What version of Dapr?

1.15+

## Expected Behavior

Today when users have an API routes that contain a subset of characters that are in the Dapr API route delimiter, path matching does not work unless the entire route is specified. Ie. the last characters will not be path matched but only the full path.

For example if you are using service invocation to invoke an app `order-app` with method: `/api/v1.0/order/route/{ID}`, the only way to path match this is to add the full route including dapr invoke keywords. Otherwise only the metric on the invokee app will be matched. For example, to ensure matching works correctly the following needs to be added for both invoker and invokee apps:

``` yaml
pathMatching:
- /v1.0/invoke/order-app/method/api/v1.0/order/route/{ID} #invoker app metric
- /api/v1.0/order/route/{ID} #invokee app metric
```

## Actual Behavior

Only one path should have to be added since its the back half of the metric, as follows.

``` yaml
pathMatching:
- /api/v1.0/order/route/{ID} #invokee app metric
```

## Steps to Reproduce the Problem

Do service invocation between two apps and add the invoker app path into the path-matching logic.
Check metrics and see that only the invokee metrics are grouped not invoker app.

## Release Note

RELEASE NOTE: **FIX** HTTP Patch matching metrics bug.

**Comment by ananyapahwa** [comment]
can I work on this issue?

**Comment by alicejgibbons** [comment]
Yes - if you comment /assign it should work @ananyapahwa

**Comment by aabhas-sao** [comment]
hey @alicejgibbons ,

I was going through all docs to re-create this issue locally.

I have two app running using multi app run.
dapr version: 
CLI version: 1.15.1
Runtime version: 1.15.5

macos arm64

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  metrics:
    enabled: true
    http:
      increasedCardinality: true
      pathMatching:
      - /orders/route/{ID}
```

I have the config as above. I'm observing below results


![Image](https://github.com/user-attachments/assets/c2fe47ff-92bf-43cd-8486-c112596f9e97)
cc: order-processor app

![Image](https://github.com/user-attachments/assets/be02b794-ca99-4b60-b6e4-38989e86bc29)
cc: checkout app


so is this issue with `api/v1.0` keyword or general issue. as I'm not able to group invoker metric by adding invokee metric
