### ISSUE TITLE
Bug Report: Secret Store Component Initialization Failure

### ISSUE THREAD

**Issue by ujala-singh** [dapr/dapr#8786]
## Expected Behavior
The postgres-secretstore (HashiCorp Vault) component should successfully initialize by retrieving the vault token from the local-secret-store component using secretKeyRef.

## Actual Behavior
The Vault secret store component fails to initialize with the following errors:

Error getting secret: secret local-secret-store not found
[INIT_COMPONENT_FAILURE]: initialization error occurred for postgres-secretstore (secretstores.hashicorp.vault/v1): token mount path and token not set

## Steps to Reproduce

- Create a local file secret store component
- Create a HashiCorp Vault secret store component that references the local secret store via secretKeyRef
- Mount these to the pod where dapr is running as process
- Start the Dapr process
- Observe the initialization failure in logs

## Environment

Dapr version: 1.14.4
OS: Linux (Container)
Deployment method: Kubernetes Pod but running Dapr as a process:

```
# Use dapr in standalone mode without requiring system-level initialization
log "Dapr is running in standalone mode."

log "Starting Dapr..."
dapr run \
  --app-id app \
  --app-port "${DAPR_APP_PORT}" \
  --dapr-http-port "${DAPR_HTTP_PORT}" \
  --dapr-grpc-port "${DAPR_GRPC_PORT}" \
  --metrics-port "${DAPR_METRICS_PORT}" \
  --dapr-http-max-request-size 1024 \
  --resources-path /app/components \
  --log-level info &
DAPR_PID=$!
```

## Configuration Files
**local-secretstore.yaml**
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: postgres-app
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /home/appuser/runtime/secrets.json
    - name: nestedSeparator
      value: ":"
```
**secretstore.yaml**
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-secretstore
  namespace: postgres-app
spec:
  metadata:
  - name: vaultAddr
    value: http://vault-active.vault.svc.cluster.local:8200
  - name: vaultToken
    secretKeyRef:
      name: local-secret-store
      key: VAULT_TOKEN
  type: secretstores.hashicorp.vault
  version: v1
auth:
  secretStore: local-secret-store
```

**secrets.json (Content Verified)**
```
{
  "VAULT_TOKEN": "s.*****",
  "...": "other secrets"
}
```
**Logs**
```
time="2025-06-12T07:02:08.335030508Z" level=info msg="Component loaded: local-secret-store (secretstores.local.file/v1)" app_id=app instance=postgres1-8557fc9844-5txp2 scope=dapr.runtime.processor type=log ver=1.14.4

time="2025-06-12T07:02:08.335054051Z" level=error msg="Error getting secret: secret local-secret-store not found" app_id=app instance=postgres1-8557fc9844-5txp2 scope=dapr.runtime.processor.secret type=log ver=1.14.4

time="2025-06-12T07:02:08.3350932Z" level=error msg="Failed to init component postgres-secretstore (secretstores.hashicorp.vault/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for postgres-secretstore (secretstores.hashicorp.vault/v1): token mount path and token not set" app_id=app instance=postgres1-8557fc9844-5txp2 scope=dapr.runtime.processor type=log ver=1.14.4
```
## Analysis

The local-secret-store component loads successfully
The secrets file exists and contains the required VAULT_TOKEN
However, when postgres-secretstore tries to reference local-secret-store via secretKeyRef, it fails with "secret local-secret-store not found"
This suggests a potential issue with:

Component initialization order
Cross-component secret resolution within the same namespace
Secret store reference resolution timing

## Possible Root Causes

- Initialization Race Condition: The Vault component may be initializing before the local secret store is fully available for cross-references
- Namespace Resolution: Despite both components being in the same namespace, the reference may not be resolving correctly
- Component Reference Validation: The secret store cross-referencing mechanism may have a bug

## Workaround
Directly specifying the vault token in the component configuration works:
```
- name: vaultToken
  value: "s.****"
```
